force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/APT_Product__c.field-meta.xml
<CustomField>
    <fullName>APT_Product__c</fullName>
    <description>Field Created for Ariba mapping purposes</description>
    <inlineHelpText>Ariba migrated field</inlineHelpText>
    <label>Product</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus_CMDSign__DocuSignEnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMDSign__DocuSignEnvelopeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Apttus - DocuSign envelope Id to which this agreement is associated to.</description>
    <inlineHelpText>The Apttus - DocuSign envelope Id to which this agreement is associated to.</inlineHelpText>
    <label>DocuSign Envelope Id</label>
    <referenceTo>Apttus_DocuApi__DocuSignEnvelope__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_DocuApi__DocuSignEnvelope__c/Apttus_DocuApi__DocuSignEnvelope__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_DocuApi__DocuSignEnvelope__c/fields/Apttus_DocuApi__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_DocuApi__Status__c</fullName>
    <description>Envelope status from DocuSign</description>
    <inlineHelpText>Envelope status from DocuSign</inlineHelpText>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ContentVersion/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Contract/fields/APT_Product__c.field-meta.xml
<CustomField>
    <fullName>APT_Product__c</fullName>
    <description>Field Created for Ariba mapping purposes</description>
    <inlineHelpText>Ariba migrated field</inlineHelpText>
    <label>Product</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Parent_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Parent_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main lookup field that links the parent contract and the child clone sf contract</description>
    <label>Original Agreement</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Salesforce Contract</relationshipLabel>
    <relationshipName>SFCon_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APT_ContractFileShareSchedulerTest.cls
/*
@Description        : Test class for APT_ContractFileShareScheduler and APT_ContractFilesQueueClass 
                      which links the apttus contract file/s to the related sf contract when an apttus 
                      contract is activated or a file is added under apttus contract.
================================ Modification Log =============================== 
Developer Name  Date            Comments
Ramtej          15/05/2019      Created
*/
@isTest
public class APT_ContractFileShareSchedulerTest {
    
    // Test variable declaration
    public static final string MSA_RECORTYPE = 'MSA & Service Schedule';
    public static final string INAUTHOR_STATUS_CATEGORY = 'In Authoring';
    public static final string AUTHORCONTRACT_STATUS = 'Author Contract';
    
    @testSetup static void setup() {
        // Create test organisation
        Account accVar = APT_TestUtil2.createOrganisation();
        insert accVar;

        // Create test contact
        Contact conVar = APT_TestUtil2.createContact();
        conVar.AccountId = accVar.Id;
        insert conVar;

        // Create test opportunity
        Opportunity oppVar = APT_TestUtil2.createOpportunity(accVar);
        
        //Create Docusign Envelope Record
        Apttus_DocuApi__DocuSignEnvelope__c docuEnv = new Apttus_DocuApi__DocuSignEnvelope__c();
        docuEnv.Apttus_DocuApi__Status__c = 'completed';
        insert docuEnv;
        // Create test agreement
        Apttus__APTS_Agreement__c aptContract = APT_TestUtil2.createAgreement(accVar,
                                                                              conVar,
                                                                              oppVar,
                                                                              new Apttus_Proposal__Proposal__c(),
                                                                              AUTHORCONTRACT_STATUS,
                                                                              INAUTHOR_STATUS_CATEGORY,
                                                                              MSA_RECORTYPE);

        aptContract.APT_Product__c = 'eParcel';
        aptContract.Apttus_CMDSign__DocuSignEnvelopeId__c = docuEnv.id;
        insert aptContract;
                 

    }
    
    static testMethod void testLinkingFiles(){        
        test.startTest();        
        Apttus__APTS_Agreement__c aptContract = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        Account accVar = [SELECT Id FROM Account LIMIT 1];                                
        //Apttus__APTS_Agreement__c agreement = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        
        //create sf contract under apttus contract
        Contract con = new Contract(Parent_Agreement__c = aptContract.Id, AccountId = accVar.id);
        insert con;
        // Create test content documents more than 5 to test APT_ShareFilesQueueClass
        List<ContentVersion> ContentVersionList = new List<ContentVersion>();
        ContentVersion contentVersion0 = APT_TestUtil2.createContentVersion();
        ContentVersionList.add(contentVersion0);
        ContentVersion contentVersion1 = APT_TestUtil2.createContentVersion();
        ContentVersionList.add(contentVersion1);
        ContentVersion contentVersion2 = APT_TestUtil2.createContentVersion();
        ContentVersionList.add(contentVersion2);
        contentVersion2.title = 'Test__signed';
        ContentVersion contentVersion3 = APT_TestUtil2.createContentVersion();
        ContentVersionList.add(contentVersion3);
        ContentVersion contentVersion4 = APT_TestUtil2.createContentVersion();
        //ContentVersionList.add(contentVersion4);
        ContentVersion contentVersion5 = APT_TestUtil2.createContentVersion();
        //ContentVersionList.add(contentVersion5);
        ContentVersion contentVersion6 = APT_TestUtil2.createContentVersion();
        
        //ContentVersionList.add(contentVersion6);
        insert ContentVersionList;
        
        List<Id> contentversionIds = new List<Id>();
        for(ContentVersion cv :ContentVersionList){
            contentversionIds.add(cv.Id);            
        }

        // Create ContentDocumentLink  records
        List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
        for(ContentVersion cv  :[SELECT Id, contentdocumentId FROM ContentVersion WHERE Id IN :contentversionIds]){
            cdlList.add(APT_TestUtil2.createContentDocumentLink (aptContract.id, cv.contentdocumentId));
        } 
        insert cdlList;
        //schedule class to link files
        APT_ContractFileShareScheduler schedulerClass = new APT_ContractFileShareScheduler();
        schedulerClass.contractList = new List<Contract>{con};
        schedulerClass.linkFiles();        
        test.stopTest();
        //test the number of files under sf contract
        system.assertEquals(4, [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :con.Id].size());
    }
}