force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/APT_Generated_Doc_Ids__c.field-meta.xml
<CustomField>
    <fullName>APT_Generated_Doc_Ids__c</fullName>
    <label>Generated Doc Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/APT_Merge_Documents__c.field-meta.xml
<CustomField>
    <fullName>APT_Merge_Documents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Merge Documents?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Template__c/Apttus__APTS_Template__c.object-meta.xml
<CustomObject>
    <description>Contract language templates available in the system. These templates specify guidance, language, local setitngs, and include Word attachment templates representing the bulk of actual contracts that can be used when creating a first draft . Templates can include standard and non-standard language.</description>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Template__c/fields/Apttus__Agreement_Types__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Agreement_Types__c</fullName>
    <description>Note: If you add a new agreement record type, the type must also be manually added to this set of picklist values to keep record types in sync between agreements and templates.</description>
    <label>Agreement Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Amendment Quote</fullName>
            </value>
            <value>
                <fullName>Renewal Quote</fullName>
            </value>
            <value>
                <fullName>Post Billpay Contract</fullName>
            </value>
            <value>
                <fullName>Letter of Intent</fullName>
            </value>
            <value>
                <fullName>SecurePay Online Payments</fullName>
            </value>
            <value>
                <fullName>MSA &amp; Service Schedule</fullName>
            </value>
            <value>
                <fullName>Rebate Contract</fullName>
            </value>
            <value>
                <fullName>Community Update Pack</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Template__c/fields/Apttus__Category__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Category__c</fullName>
    <description>Specifies the class of template or clauses into a high level category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Template__c/fields/Apttus__Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Subcategory__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apttus__Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Template__c/fields/Apttus__Type__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Type__c</fullName>
    <description>Specifies the contract template type which can be either a template or clause type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
                <default>true</default>
                <label>Agreement</label>
            </value>
            <value>
                <fullName>Clause</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Supporting Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__AllowPDFSelectionOverride__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AllowPDFSelectionOverride__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the pdf selection is allowed to be overridden by the user. Only applicable when pdf is auto enabled for final documents.</description>
    <inlineHelpText>Indicates whether the pdf selection is allowed to be overridden by the user. Only applicable when pdf is auto enabled for final documents.</inlineHelpText>
    <label>Allow PDF Selection Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__AllowPrivateSelectionOverride__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AllowPrivateSelectionOverride__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the private document selection is allowed to be overridden by the user. Only applicable when private indicator is auto enabled for documents</description>
    <inlineHelpText>Indicates whether the private document selection is allowed to be overridden by the user. Only applicable when private indicator is auto enabled for documents</inlineHelpText>
    <label>Allow Private Selection Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__AllowReconcileSelectionOverride__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AllowReconcileSelectionOverride__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the reconcile selection is allowed to be overridden by the user. Only applicable when reconciliation is auto enabled for documents.</description>
    <inlineHelpText>Indicates whether the reconcile selection is allowed to be overridden by the user. Only applicable when reconciliation is auto enabled for documents.</inlineHelpText>
    <label>Allow Reconcile Selection Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__AutoEnablePDFForFinalDocs__c.field-meta.xml
<CustomField>
    <fullName>Apttus__AutoEnablePDFForFinalDocs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether PDF format is auto enabled for final documents</description>
    <inlineHelpText>Indicates whether PDF format is auto enabled for final documents</inlineHelpText>
    <label>Auto Enable PDF For Final Docs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__BypassSharing__c.field-meta.xml
<CustomField>
    <fullName>Apttus__BypassSharing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether apex code can bypass record sharing</description>
    <label>Bypass Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__DocumentStructureFX2ForImportedDocs__c.field-meta.xml
<CustomField>
    <fullName>Apttus__DocumentStructureFX2ForImportedDocs__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Applies FX2 framework to CM actions Create, Import Offline Documents, else Pre-FX2. Not for X-Author actions</description>
    <inlineHelpText>Applies FX2 framework to CM actions Create, Import Offline Documents, else Pre-FX2. Not for X-Author actions</inlineHelpText>
    <label>Document Structure FX2 For Imported Docs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__EnableClauseApprovals__c.field-meta.xml
<CustomField>
    <fullName>Apttus__EnableClauseApprovals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether clause approvals are enabled</description>
    <inlineHelpText>Indicates whether clause approvals are enabled</inlineHelpText>
    <label>Enable Clause Approvals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__EnableDocumentVersioning__c.field-meta.xml
<CustomField>
    <fullName>Apttus__EnableDocumentVersioning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables document versioning. Make sure EnableVersionControl is set to true.</description>
    <inlineHelpText>Enables document versioning. Make sure EnableVersionControl is set to true.</inlineHelpText>
    <label>Enable Document Versioning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__EnableSubmitMergeCall__c.field-meta.xml
<CustomField>
    <fullName>Apttus__EnableSubmitMergeCall__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether merge calls may be submitted for processing. If enabled, a Submit button is displayed during document generation.</description>
    <inlineHelpText>Indicates whether merge calls may be submitted for processing. If enabled, a Submit button is displayed during document generation.</inlineHelpText>
    <label>Enable Submit Merge Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__InstanceUrl__c.field-meta.xml
<CustomField>
    <fullName>Apttus__InstanceUrl__c</fullName>
    <description>The Salesforce instance url for redirecting to custom pages</description>
    <label>Instance Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus__MergeWebserviceEndpoint__c.field-meta.xml
<CustomField>
    <fullName>Apttus__MergeWebserviceEndpoint__c</fullName>
    <description>The Apttus merge web service endpoint</description>
    <label>Merge Webservice Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus_CMDSign__AutoSelectAttachment__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMDSign__AutoSelectAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the most recent attachment is auto selected</description>
    <inlineHelpText>Indicates whether the most recent attachment is auto selected</inlineHelpText>
    <label>Auto Select Attachment ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus_CMDSign__AutoSelectMultipleRecipients__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMDSign__AutoSelectMultipleRecipients__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows projects to specify a list of recipients that will be defaulted for the eSignature. 
To use this option, projects will add &quot;DocuSign Default Recipients&quot; related list on the Agreement and user will specify the list for each Agreement</description>
    <inlineHelpText>Allows projects to specify a list of recipients that will be defaulted for the eSignature. 
To use this option, projects will add &quot;DocuSign Default Recipients&quot; related list on the Agreement and user will specify the list for each Agreement</inlineHelpText>
    <label>Auto-Select multiple recipients?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__ComplySystemProperties__c/fields/Apttus_CMDSign__EnableDocumentPreviewInDocuSign__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CMDSign__EnableDocumentPreviewInDocuSign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable document preview in DocuSign Application ?</description>
    <inlineHelpText>Enable document preview in DocuSign Application ?</inlineHelpText>
    <label>Enable Document Preview in DocuSign App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/APT_AsyncMergeCallTriggerHandlerTest.cls
/**
 * This apex class is test class for apex class - APT_AsyncMergeCallTriggerHandler
 * Created By - Akshay Mewada
 * Created Date - 28th June, 2016
 */ 
 @isTest
private class APT_AsyncMergeCallTriggerHandlerTest {

    /*
        Test Method to Test Functionality and Generate data
    */
    public static testMethod void test_DML()
    {
        Apttus__ComplySystemProperties__c custSettings = new Apttus__ComplySystemProperties__c();
        custSettings.Name = 'System Properties';
        custSettings.Apttus__AllowPDFSelectionOverride__c = true;
        custSettings.Apttus__AllowPrivateSelectionOverride__c = true;
        custSettings.Apttus__AllowReconcileSelectionOverride__c = true;
        custSettings.Apttus__AutoEnablePDFForFinalDocs__c = true;
        custSettings.Apttus__BypassSharing__c = true;
        custSettings.Apttus__DefaultOpportunityAgreementOwner__c = 'Current User';
        custSettings.Apttus__EnableClauseApprovals__c = true;
        custSettings.Apttus__EnableSubmitMergeCall__c = true;
        custSettings.Apttus_CMDSign__AutoSelectAttachment__c = true;
        custSettings.Apttus_CMDSign__AutoSelectMultipleRecipients__c = true;
        custSettings.Apttus_CMDSign__EnableDocumentPreviewInDocuSign__c = true;
        custSettings.Apttus__DocumentStructureFX2ForImportedDocs__c = true;
        custSettings.Apttus__EnableDocumentVersioning__c = true;
        custSettings.Apttus__InstanceUrl__c = 'https://auspost--devr2t.cs5.my.salesforce.com';
        custSettings.Apttus__MergeWebserviceEndpoint__c = 'https://mergews.apttus.net/cgi-bin/4.2.1.2/MergeServer/Bin/MMCGI.exe';
        custSettings.Apttus__MergeCallTimeoutMillis__c = 120;
        insert custSettings;

        Apttus__APTS_Agreement__c agrObj = new Apttus__APTS_Agreement__c();
        agrObj.APT_Merge_Documents__c = true;
        agrObj.recordtypeid = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        insert agrObj;

        Attachment attachmentObj = new Attachment();
        attachmentObj.body = Blob.valueOf('Temp');
        attachmentObj.parentId = agrObj.ID;
        attachmentObj.Name = 'Temp attachment';
        insert attachmentObj;

        agrObj.APT_Generated_Doc_Ids__c = attachmentObj.Id;
        update agrObj;

        Apttus__APTS_Template__c templateObj = new Apttus__APTS_Template__c();
        templateObj.Name = 'Temp template';
        templateObj.Apttus__Type__c = APT_Constants.TYPE_AGR;
        templateObj.Apttus__Agreement_Types__c = APT_Constants.AGR_TYPE_MSA_SERVICE;
        templateObj.Apttus__Category__c = APT_Constants.CATG_SUBMIT;
        templateObj.Apttus__Subcategory__c = APT_Constants.SUBCATG_DEFAULT;
        templateObj.Apttus__Language__c = APT_Constants.LANG_ENG;
        templateObj.Apttus__Locale__c = APT_Constants.LOCALE_ENG;
        templateObj.Apttus__IsActive__c = true;
        insert templateObj;
        
        Test.startTest();
        Apttus__AsyncMergeCall__c asyncMergeObj = new Apttus__AsyncMergeCall__c();
        asyncMergeObj.Apttus__Agreement__c = agrObj.Id;
        asyncMergeObj.Apttus__Template__c = templateObj.Id;
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_FAILED;
        asyncMergeObj.Apttus__Action__c = APT_Constants.ASYNC_ACTION_GENERATE;
        asyncMergeObj.Apttus__StartTime__c = Datetime.now();
        asyncMergeObj.Apttus__EndTime__c = Datetime.now().addMinutes(10);
        asyncMergeObj.Apttus__CallType__c = APT_Constants.ASYNC_CALL_TYPE;
        asyncMergeObj.Apttus__DocumentFormat__c = APT_Constants.ASYNC_DOC_TYPE_PDF;
        asyncMergeObj.Apttus__ProtectionLevel__c = APT_Constants.ASYNC_PROTE_LEVEL_COMMENT_AND_TRACK_CHANGE;
        insert asyncMergeObj;

        asyncMergeObj = [SELECT ID, Apttus__Result__c, Apttus__Status__c FROM Apttus__AsyncMergeCall__c WHERE ID = :asyncMergeObj.Id];
        asyncMergeObj.Apttus__Result__c = attachmentObj.Id;
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_CATEGORY;
        update asyncMergeObj;
        Test.stopTest();
    }
     public static testMethod void test_DML1()
    {
        Account tempacct = APT_TestUtils.createOrganisation();
        insert tempacct;
        
        Opportunity opp = APT_TestUtils.createOpportunity(tempacct.id);
        insert opp;
        Apttus_Config2__PriceList__c priceList = APT_TestUtils.createPriceList();
        insert priceList;
        Apttus_Proposal__Proposal__c Proposal= APT_TestUtils.getQuoteProposal(tempacct.ID,opp.ID,'Proposal','Quote', priceList.ID);
             proposal.APT_Create_Proposal_Batch_Id__c = '';
             proposal.Expected_Revenue_Start_Date__c = System.Today() - 20;
             //proposal.APT_Method_of_Payment__c = 'Charge Account';
             insert Proposal;
        Apttus__ComplySystemProperties__c custSettings = new Apttus__ComplySystemProperties__c();
        custSettings.Name = 'System Properties';
        custSettings.Apttus__AllowPDFSelectionOverride__c = true;
        custSettings.Apttus__AllowPrivateSelectionOverride__c = true;
        custSettings.Apttus__AllowReconcileSelectionOverride__c = true;
        custSettings.Apttus__AutoEnablePDFForFinalDocs__c = true;
        custSettings.Apttus__BypassSharing__c = true;
        custSettings.Apttus__DefaultOpportunityAgreementOwner__c = 'Current User';
        custSettings.Apttus__EnableClauseApprovals__c = true;
        custSettings.Apttus__EnableSubmitMergeCall__c = true;
        custSettings.Apttus_CMDSign__AutoSelectAttachment__c = true;
        custSettings.Apttus_CMDSign__AutoSelectMultipleRecipients__c = true;
        custSettings.Apttus_CMDSign__EnableDocumentPreviewInDocuSign__c = true;
        custSettings.Apttus__DocumentStructureFX2ForImportedDocs__c = true;
        custSettings.Apttus__EnableDocumentVersioning__c = true;
        custSettings.Apttus__InstanceUrl__c = 'https://auspost--devr2t.cs5.my.salesforce.com';
        custSettings.Apttus__MergeWebserviceEndpoint__c = 'https://mergews.apttus.net/cgi-bin/4.2.1.2/MergeServer/Bin/MMCGI.exe';
        custSettings.Apttus__MergeCallTimeoutMillis__c = 120;
        insert custSettings;

        Apttus__APTS_Agreement__c agrObj = new Apttus__APTS_Agreement__c();
        agrObj.APT_Merge_Documents__c = true;
        agrObj.recordtypeid = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        insert agrObj;

        Attachment attachmentObj = new Attachment();
        attachmentObj.body = Blob.valueOf('Temp');
        attachmentObj.parentId = Proposal.ID;
        attachmentObj.Name = 'Temp attachment';
        insert attachmentObj;

        agrObj.APT_Generated_Doc_Ids__c = attachmentObj.Id;
        update agrObj;

        Apttus__APTS_Template__c templateObj = new Apttus__APTS_Template__c();
        templateObj.Name = 'Temp template';
        templateObj.Apttus__Type__c = 'Proposal';
        templateObj.Apttus__Agreement_Types__c = APT_Constants.AGR_TYPE_MSA_SERVICE;
        templateObj.Apttus__Category__c = APT_Constants.CATG_SUBMIT;
        templateObj.Apttus__Subcategory__c = APT_Constants.SUBCATG_DEFAULT;
        templateObj.Apttus__Language__c = APT_Constants.LANG_ENG;
        templateObj.Apttus__Locale__c = APT_Constants.LOCALE_ENG;
        templateObj.Apttus__IsActive__c = true;
        insert templateObj;
        
             
        Test.startTest();
        Apttus__AsyncMergeCall__c asyncMergeObj = new Apttus__AsyncMergeCall__c();
        //asyncMergeObj.Apttus__Agreement__c = agrObj.Id;
        asyncMergeObj.Apttus__Template__c = templateObj.Id;
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_FAILED;
        asyncMergeObj.Apttus__Action__c = APT_Constants.ASYNC_ACTION_GENERATE;
        asyncMergeObj.Apttus__StartTime__c = Datetime.now();
        asyncMergeObj.Apttus__EndTime__c = Datetime.now().addMinutes(10);
        asyncMergeObj.Apttus__CallType__c = APT_Constants.ASYNC_CALL_TYPE;
        asyncMergeObj.Apttus__DocumentFormat__c = APT_Constants.ASYNC_DOC_TYPE_PDF;
        asyncMergeObj.Apttus__ProtectionLevel__c = APT_Constants.ASYNC_PROTE_LEVEL_COMMENT_AND_TRACK_CHANGE;
        asyncMergeObj.Apttus_Proposal__QuoteProposalId__c = Proposal.ID;
        insert asyncMergeObj;

        asyncMergeObj = [SELECT ID, Apttus__Result__c, Apttus__Status__c FROM Apttus__AsyncMergeCall__c WHERE ID = :asyncMergeObj.Id];
        asyncMergeObj.Apttus__Result__c = attachmentObj.Id;
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_CATEGORY;
        try
        {
            update asyncMergeObj;
        }
        catch(Exception ex)
        {
            System.Debug(ex);
        }
        Test.stopTest();
    }

    /*
        Test Method to Test Functionality
    */
    public static testMethod void test_Catch()
    {
        Apttus__APTS_Agreement__c agrObj = new Apttus__APTS_Agreement__c();
        agrObj.recordtypeid = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        insert agrObj;
        Test.startTest();
        Apttus__AsyncMergeCall__c asyncMergeObj = new Apttus__AsyncMergeCall__c();
        //asyncMergeObj.Apttus__Agreement__c = agrObj.Id;
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_FAILED;
        asyncMergeObj.Apttus__Result__c = 'Temp result';
        insert asyncMergeObj;
        
        asyncMergeObj.Apttus__Status__c = APT_Constants.STATUS_CATEGORY;
        update asyncMergeObj;
        Test.stopTest();
    }

}