force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/APT_Submit_to_Contract_Consulting_Team__c.field-meta.xml
<CustomField>
    <fullName>APT_Submit_to_Contract_Consulting_Team__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in Process Builder to create case for contract consulting team</description>
    <inlineHelpText>NOTE: System will automatically uncheck this checkbox after it is checked. 
This is mainly for DOV Purposes.
New Case will be created and assigned to Contract Consulting Team. Please provide details in &apos;Details for Contract Consulting/Legal&apos; field.</inlineHelpText>
    <label>Submit To Contract Consulting Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The link to the account record to identify the external party to this agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N50000001Xl0UEAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Agreement_Category__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Agreement_Category__c</fullName>
    <description>Used to categorize agreement types.  When setting up a new agreement type make sure to seect approrpiate values for that agreement type and to set the right default</description>
    <inlineHelpText>Standard - no changes to Contract
Customised - 3rd Party paper, or requested changes in Terms and Conditions</inlineHelpText>
    <label>Agreement Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Customised</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Contract_End_Date__c</fullName>
    <description>The end date for this agreement</description>
    <inlineHelpText>If contract is Open Ended this field represents Contract Anniversary Date

If Contract is Fixed Term this field represents Contract End Date (Expiration Date)</inlineHelpText>
    <label>Agreement End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Other_Party_Signed_By__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Other_Party_Signed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to contact record to identify external signatory</description>
    <label>Other Party Signed By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N50000001Xl0MEAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Agreements (Primary Contact)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Status__c</fullName>
    <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apttus__Status_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Request Approval</fullName>
            </value>
            <value>
                <fullName>Submitted Request</fullName>
            </value>
            <value>
                <fullName>Approved Request</fullName>
            </value>
            <value>
                <fullName>Cancelled Request</fullName>
            </value>
            <value>
                <fullName>In Amendment</fullName>
            </value>
            <value>
                <fullName>Author Contract</fullName>
            </value>
            <value>
                <fullName>Language Approval</fullName>
            </value>
            <value>
                <fullName>Language Approved</fullName>
            </value>
            <value>
                <fullName>Internal Signatures</fullName>
            </value>
            <value>
                <fullName>Other Party Signatures</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Being Amended</fullName>
            </value>
            <value>
                <fullName>Being Renewed</fullName>
            </value>
            <value>
                <fullName>In Renewal</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Being Terminated</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>In Reconciliation</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
            <value>
                <fullName>Other Party Review</fullName>
            </value>
            <value>
                <fullName>Signature Declined</fullName>
            </value>
            <value>
                <fullName>Ready for Signatures</fullName>
            </value>
            <value>
                <fullName>Fully Signed</fullName>
            </value>
            <value>
                <fullName>Signed by Customer Only</fullName>
            </value>
            <value>
                <fullName>Returned to Requestor</fullName>
            </value>
            <value>
                <fullName>SFDC Case Created</fullName>
                <label>SFDC DSR Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Status_Category__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Status_Category__c</fullName>
    <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
    <label>Status Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
                <default>true</default>
                <label>Request</label>
            </value>
            <value>
                <fullName>In Authoring</fullName>
            </value>
            <value>
                <fullName>In Signatures</fullName>
            </value>
            <value>
                <fullName>In Filing</fullName>
            </value>
            <value>
                <fullName>In Effect</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Inactive - **Data Integrity Only**</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Termination_Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Termination_Notice_Period__c</fullName>
    <inlineHelpText>Termination Notice Period - change in notice period may require approval</inlineHelpText>
    <label>Termination Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_Method_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>APT_Method_of_Payment__c</fullName>
    <description>.</description>
    <label>New Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Charge Account</fullName>
            </value>
            <value>
                <fullName>Charge Account + Sub Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <inlineHelpText>This indicates the status of your proposal record</inlineHelpText>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Accepted without proposal document</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/APT_Submit_to_Contract_Consulting_Team__c.field-meta.xml
<CustomField>
    <fullName>APT_Submit_to_Contract_Consulting_Team__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in Process Builder to create case for contract consulting team</description>
    <inlineHelpText>NOTE: System will automatically uncheck this checkbox after it is checked. 
This is mainly for DOV Purposes.
New Case will be created and assigned to Contract Consulting Team. Please provide details in &apos;Details for Contract Consulting/Legal&apos; field.</inlineHelpText>
    <label>Submit To Contract Consulting Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Termination_Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Termination_Notice_Period__c</fullName>
    <inlineHelpText>Termination Notice Period - change in notice period may require approval</inlineHelpText>
    <label>Termination Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APT_ImportControllerTest.cls
/*
    Version history
    24/10/2018 - kalpita - updated the code to have test data creation and actual test run in seperate scopes to avoid governor limits 
    
*/

@isTest
private with sharing class APT_ImportControllerTest {

    public static testmethod void testAPT_ImportController(){
        Test.startTest();
        
        Account acc = new Account();
        acc.NAME = 'test acc';
        insert acc;
        
        Id rtID = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        Apttus__APTS_Agreement__c agmt = new Apttus__APTS_Agreement__c();
        agmt.Name = 'Apttus Test';
        agmt.Apttus__Status_Category__c = 'In Signatures';
        agmt.Apttus__Status__c = 'Other Party Signatures';
        agmt.Apttus__Account__c = acc.ID;
        if(rtID != null)
        agmt.RecordTypeId = rtID;
        insert agmt;
        
        ApexPages.StandardController stdImp = new ApexPages.StandardController(agmt);
        APT_ImportController objAPTSImportCtrl = new APT_ImportController(stdImp);
        
        system.assertEquals(objAPTSImportCtrl.agreementId==agmt.Id,true);
        
        PageReference pageRef =  objAPTSImportCtrl.doThirdParty();
        system.assertEquals(pageRef!=null,true);
        
        pageRef =  objAPTSImportCtrl.doPartiallySigned();
        //system.assertEquals(pageRef!=null,true);
        
        pageRef =  objAPTSImportCtrl.doFullySigned();
        //system.assertEquals(pageRef!=null,true);
        
        objAPTSImportCtrl.doCancel();
        PageReference pagRf = new PageReference('/'+objAPTSImportCtrl.agreementId);
        //system.assertEquals(pageRef.getUrl()==pagRf.getURl(),true);
         
        Test.stopTest();
         
    }
    public static testmethod void testAPT_ImportController1(){
        
        
        Account acc1 = new Account();
        acc1.NAME = 'test acc';
        insert acc1;
        
        Id rtID1 = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        Apttus__APTS_Agreement__c agmt1 = new Apttus__APTS_Agreement__c();
        agmt1.Name = 'Apttus Test1';
        agmt1.Apttus__Status_Category__c = 'Request';
        agmt1.Apttus__Status__c = 'Signature Declined';
        //agmt1.APT_Submit_to_Contract_Consulting_Team__c = false;
        agmt1.Apttus__Account__c = acc1.ID;
        agmt1.Apttus__Contract_End_Date__c = System.Today() + 100;
        if(rtID1 != null)
        agmt1.RecordTypeId = rtID1;
        insert agmt1;
        
        ApexPages.StandardController stdImp1 = new ApexPages.StandardController(agmt1);
        APT_ImportController objAPTSImportCtrl1 = new APT_ImportController(stdImp1);
        Test.startTest();
        objAPTSImportCtrl1.doFullySigned();
        PageReference pageRef =  objAPTSImportCtrl1.doThirdParty();
        agmt1.Apttus__Status_Category__c = 'Request';
        update agmt1;
        pageRef =  objAPTSImportCtrl1.doLegacy();
        
        ID agreeId = objAPTSImportCtrl1.agreementId;
        Apttus__APTS_Agreement__c agreement = [Select Apttus__Status_Category__c, Apttus__Status__c From Apttus__APTS_Agreement__c Where Id = :agreeId];
        system.assertEquals(agreement.Apttus__Status__c ,'Author Contract');
        
        Test.stopTest();
    }
    public static testmethod void testAPT_ImportController2(){
        Account acc = new Account();
        acc.NAME = 'test acc';
        insert acc;
        
        Opportunity opp = APT_TestUtils.createOpportunity(acc.id);
        insert opp;
        
        Contact con = APT_TestUtils.createContact();
        insert con;
        
        //Create PriceList
        Apttus_Config2__PriceList__c priceList = APT_TestUtils.createPriceList();
        insert priceList;
        
        //Create Proposal
        Apttus_Proposal__Proposal__c Proposal1= APT_TestUtils.getQuoteProposal(acc.id,opp.id,'Proposal','Quote', priceList.id);
        Proposal1.Apttus_Proposal__Approval_Stage__c='Accepted';
        //Proposal1.APT_Method_of_Payment__c = 'None';
        insert Proposal1;
        
        Id rtID = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('MSA & Service Schedule').getRecordTypeId();
        Apttus__APTS_Agreement__c agmt = new Apttus__APTS_Agreement__c();
        agmt.Name = 'Apttus Test';
        agmt.ownerid = userinfo.getUserid();
        agmt.Apttus__Primary_Contact__c = con.id;
        agmt.Apttus__Agreement_Category__c = 'Standard';
        agmt.Apttus__Status_Category__c = 'In Signatures';
        agmt.Apttus__Status__c = 'Other Party Signatures';
        agmt.Apttus__Other_Party_Signed_By__c = con.id;
        agmt.Termination_Notice_Period__c = '30';
        agmt.Included_Product_Lines__c = 'eParcels Domestic';
        agmt.APT_Pricing_Category__c = 'Standard';
        agmt.Apttus__Subtype__c = 'Short Form';
        agmt.Term__c = 'Fixed Term';
        agmt.APT_Contract_Type__c = 'New Contract';
        agmt.Apttus__Contract_Start_Date__c = date.Today();
        agmt.APT_Contracting_Entity1__c = 'Australian Postal Corporation';
        agmt.Apttus__Related_Opportunity__c = opp.id;
        agmt.Apttus_QPComply__RelatedProposalId__c = Proposal1.Id;
        agmt.APT_Trading_As__c = 'None';
        agmt.Apttus__Account__c = acc.ID;
        if(rtID != null)
        agmt.RecordTypeId = rtID;
        insert agmt;
        
        Test.startTest();
        
            ApexPages.StandardController stdImp = new ApexPages.StandardController(agmt);
            APT_ImportController objAPTSImportCtrl = new APT_ImportController(stdImp);
            
            objAPTSImportCtrl.apiSessionId = '';
            objAPTSImportCtrl.apiServerURL  = '';
            objAPTSImportCtrl.output_text_Value = '';
            
            PageReference pageRef =  objAPTSImportCtrl.doThirdParty();
            pageRef =  objAPTSImportCtrl.doFullySigned();
            pageRef =  objAPTSImportCtrl.doPartiallySigned();
            // Commented out by Adrian Recio, temporary fix to avoid the soql 101 limit
            //pageRef =  objAPTSImportCtrl.doLegacy();
            system.assertEquals(pageRef!=null,true);
            
        test.stopTest();
    }
}