force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/APT_Product_group__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_group__c</fullName>
    <label>Product Group</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/APT_Contract__c.field-meta.xml
<CustomField>
    <fullName>APT_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Apttus Contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/APT_Contract_Owner__c.field-meta.xml
<CustomField>
    <fullName>APT_Contract_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases5JB6_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/APT_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_Group__c</fullName>
    <description>.</description>
    <label>Product Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateofIncident__c.field-meta.xml
<CustomField>
    <fullName>DateofIncident__c</fullName>
    <description>Used for Contact Us Form</description>
    <label>Date of Incident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABN/ACN</fullName>
            </value>
            <value>
                <fullName>Account Info</fullName>
            </value>
            <value>
                <fullName>Addendum/DOV</fullName>
            </value>
            <value>
                <fullName>Add lodgement point</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Agreement Renewal</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>AP Sales Support</fullName>
            </value>
            <value>
                <fullName>Ariba Change Ownership</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Billing Account/Sub Account Entry</fullName>
            </value>
            <value>
                <fullName>Billing Account Link</fullName>
            </value>
            <value>
                <fullName>Bulk Order</fullName>
            </value>
            <value>
                <fullName>Bulk Process</fullName>
            </value>
            <value>
                <fullName>Business Initiatives</fullName>
            </value>
            <value>
                <fullName>Business Led Initiatives</fullName>
            </value>
            <value>
                <fullName>CDMT Only</fullName>
            </value>
            <value>
                <fullName>CDMT Only - API</fullName>
            </value>
            <value>
                <fullName>Change billing account details</fullName>
            </value>
            <value>
                <fullName>Change Default Charge Code</fullName>
            </value>
            <value>
                <fullName>Change of Organisation Details</fullName>
            </value>
            <value>
                <fullName>Close billing account</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contract Creation</fullName>
            </value>
            <value>
                <fullName>Contract Entry</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>Copy of Contract</fullName>
            </value>
            <value>
                <fullName>Copy of Rates</fullName>
            </value>
            <value>
                <fullName>Credit Accounts/Sub Accounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Data_Quality_Management.recordType-meta.xml
<RecordType>
    <fullName>Data_Quality_Management</fullName>
    <active>true</active>
    <businessProcess>Data Quality Management</businessProcess>
    <description>Case for a request to change customer information , resolve Salesforce Revenue / Integration and Data Quality Issues</description>
    <label>Data Quality Management</label>
</RecordType>

force-app/main/default/classes/CaseManagerProcessHelper_Test.cls
/*************************************************************************************************
Description:    Test class to cover CaseManagerProcessHelper functionality
History:
---------------------------------------------------------------------------------------
2016-02-01  kalpita.talwadekar@auspost.com.au  Created
2016-08-31  snigdha.sahu@auspost.com.au  ETA Call APT_TestUtils for Agreement test data.
2018-06-22  TDO-65 rahul.kapoor@coroma.com.au  Refactored comments and indentation,
            added assertEquals and assertNotEquals, tests with all input parameters as true/false.
2019-03-15  nathan.franklin@auspost.com.au Fixed failing test
2020-02-04  seth.p.heang@accenture.com Increase code coverage by including check on APT_Product_Group__c
13/10/2020  seth.p.heang@accenture.com   Decommissioned    This class and the flow 'CaseManagerAllocationFlow' which calls this class,
															the entire functionality of 'Deal Enablement Centre' Case implementation is decommissioned 
															and to be replaced with a new DSR implementation with 'Deal Enablement Centre' record type
**************************************************************************************************/
@isTest
private class CaseManagerProcessHelper_Test {

    /*****************************************************************************************
    *  Scenario:
    *      Setup method to create test data
    ******************************************************************************************/
    /*@testSetup 
    static void testDataCreation() {
        //Create Contact
        Contact testContact = APT_TestUtils.createContact();
        Database.insert(testContact);

        //Call the Apttus Test Utility for creating agreement
        Apttus__APTS_Agreement__c  testAptsAgreement = APT_TestUtils.createAgreement(testContact.Id);
        Database.insert(testAptsAgreement);

        //Create Case
        Case testCase = new Case();
        testCase.RecordTypeId = [SELECT Id
                                 FROM RecordType
                                 WHERE DeveloperName = 'Data_Quality_Management'
                                 AND SobjectType='Case'
                                 LIMIT 1].Id;
        testCase.Type = 'Feedback';
        testCase.Subject = 'Newsdd';
        testCase.Status = 'Network Responded';
        testCase.ProductCategory__c = 'Travel & ID';
        testCase.EnquirySubType__c = 'Product Support';
        testCase.EnquirySubType__c = 'KeyPass';
        testCase.EnquirySubType__c = 'Article carded - no card left';
        testCase.DateofIncident__c = date.today();
        testCase.ReferenceId__c = 'SSSWCase';
        testCase.APT_Contract__c = testAptsAgreement.Id;
        testCase.APT_Contract_Owner__c =userinfo.getuserid();
        insert testCase;

        //Create Attachment for Case
        Attachment testAttachment = Util.createAttachment('test attachment', 'ajgskdjgausgdhagsud', 'image', testCase.Id);
        insert testAttachment;

        //Create CaseComment for case
        CaseComment testCaseComment = new CaseComment(ParentId = testCase.Id,IsPublished = true);
        Database.insert(testCaseComment);
    }*/

    /*****************************************************************************************
    *  Scenario:
    *      Test the flow class setup and function with isInsert as true
    ******************************************************************************************/
    static testMethod void testCaseManagerWithInsertTrue() {
        //Fetch case data
        //Case testCase = [SELECT Id FROM Case LIMIT 1];
    
        //Create test conversion
        CaseManagerProcessHelper aLeadPlugin = new CaseManagerProcessHelper();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        //inputParams.put('Id',testCase.ID);
        inputParams.put('isInsert', true);
        inputParams.put('eparcelStandard', true);
        inputParams.put('newCashAccount', false);
        inputParams.put('newChargeAccount', false);
        inputParams.put('newSubAccount', false);

        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = aLeadPlugin.invoke(request);

        Process.PluginDescribeResult describe = aLeadPlugin.describe();
        /*System.assertNotEquals(null,result,
                'CaseManagerProcessHelper_Test_testCaseManagerWithInsertTrue : Result should be retrieved');*/
        
    }

    /*****************************************************************************************
    *  Scenario:
    *      Test the flow class setup and function with isInsert as false
    ******************************************************************************************/
    /*static testMethod void testCaseManagerWithInsertFalse() {
        //Create case data
        Case testCase = [SELECT Id,Status,Work_Type__c FROM Case LIMIT 1];
        testCase.Status = 'Closed';
        testCase.Work_Type__c = 'New Sub Account';
        update testCase;
        
        //Create test conversion
        CaseManagerProcessHelper aLeadPlugin = new CaseManagerProcessHelper();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();
        Process.PluginDescribeResult descr = aLeadPlugin.describe();
        inputParams.put('Id',testCase.ID);
        inputParams.put('isInsert', false);
        inputParams.put('eparcelStandard', false);
        inputParams.put('newCashAccount', false);
        inputParams.put('newChargeAccount', false);
        inputParams.put('newSubAccount', true);

        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = aLeadPlugin.invoke(request);

        System.assertNotEquals(null,result,
                'CaseManagerProcessHelper_Test_testCaseManagerWithInsertFalse : Result should be retrieved');
    }*/

    /*****************************************************************************************
    *  Scenario:
    *      Test the flow class setup and function with all input parameters as false.
    ******************************************************************************************/
    /*static testMethod void testCaseManagerWithInputParamsFalse() {

        Test.startTest();

        //Fetch case data
        Case testCase = [SELECT Id,Status,Work_Type__c FROM Case LIMIT 1];
        testCase.Status = 'Closed';
        testCase.Work_Type__c = 'New Sub Account';
        update testCase;
        
        //Create test conversion
        CaseManagerProcessHelper aLeadPlugin = new CaseManagerProcessHelper();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();
        Process.PluginDescribeResult descr = aLeadPlugin.describe();
        inputParams.put('Id',testCase.ID);
        inputParams.put('isInsert', false);
        inputParams.put('eparcelStandard', false);
        inputParams.put('newCashAccount', false);
        inputParams.put('newChargeAccount', false);
        inputParams.put('newSubAccount', false);

        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = aLeadPlugin.invoke(request);

        Test.stopTest();

        System.assertNotEquals(null,result,
                'CaseManagerProcessHelper_Test_testCaseManagerWithInputParamsFalse : Result should be retrieved');
    }*/

    /*****************************************************************************************
    *  Scenario:
    *      Test the flow class setup and function with all input parameters as true.
    ******************************************************************************************/
    /*static testMethod void testCaseManagerWithInsertTrueInputParams() {
        //Fetch case data
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        //testCase.APT_Contract_Owner__c='0050l000001Nw12340';
        // add product group
        testCase.APT_Product_Group__c = 'Local Pickup and Delivery Services';
        update testCase;

        //Create test conversion
        CaseManagerProcessHelper aLeadPlugin = new CaseManagerProcessHelper();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('Id',testCase.ID);
        inputParams.put('isInsert', true);
        inputParams.put('eparcelStandard', true);
        inputParams.put('newCashAccount', true);
        inputParams.put('newChargeAccount', true);
        inputParams.put('newSubAccount', true);
        inputParams.put('newSubAccount', true);

        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = aLeadPlugin.invoke(request);

        System.assertNotEquals(null,result,
                'CaseManagerProcessHelper_Test_testCaseManagerWithInsertTrueInputParams : Result should be retrieved');

    }*/
    
}