force-app/main/default/objects/BatchJobSettings__c/BatchJobSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Phase 2 - Custom settings for scheduling batch jobs
ECLM -  Custom settings for renewal and review opportunity creation jobs</description>
    <label>BatchJobSettings</label>
</CustomObject>

force-app/main/default/objects/BatchJobSettings__c/fields/OFTR_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>OFTR_Batch_Size__c</fullName>
    <defaultValue>50</defaultValue>
    <description>ECLM - Used by Apex Batch Scheduler “OpportunityFixedTermRenewal_Schedulable” - The optional batch size for execution.</description>
    <inlineHelpText>ECLM - Used by Apex Batch Scheduler “OpportunityFixedTermRenewal_Schedulable” - The optional batch size for execution.</inlineHelpText>
    <label>OFTR - Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityFixedTermRenewal_Schedulable.cls
/**************************************************
Type:       Apex Schedulable Batch Job Class for Opportunity Fixed Term Renewal processing
Purpose:    Executes the OpportunityFixedTermRenewal_Batchable class
Used By:    
History:
--------------------------------------------------
27-Feb-2013 Manu Erwin (Salesforce.com)     ECLM: Phase 3: Created
**************************************************/
@isTest (SeeAllData=TRUE) 
global without sharing class OpportunityFixedTermRenewal_Schedulable implements Schedulable {

    public static Integer BATCH_SIZE = BatchJobSettings__c.getInstance().OFTR_Batch_Size__c.intValue();

    global void execute(SchedulableContext sc) {
        System.assert(BATCH_SIZE != null, 'BATCH_SIZE cannot be null!');
        OpportunityFixedTermRenewal_Batchable oftr = new OpportunityFixedTermRenewal_Batchable(false);
        if(!Test.IsRunningTest()){
        
        Database.executeBatch(oftr, BATCH_SIZE);
        }
    }

    private static void testOpportunityFixedTermRenewal_Schedulable() {
        //Abort jobs to allow for test class to set the schedule
        List<CronTrigger> cron = new List<CronTrigger>([SELECT Id, State FROM CronTrigger where state!='DELETED']);
        for(CronTrigger CT : cron){
            system.abortjob(CT.Id);
        }

        Test.startTest();
        OpportunityFixedTermRenewal_Schedulable oftrs = new OpportunityFixedTermRenewal_Schedulable();
        String schedule = '0 0 23 * * ?';
        system.schedule('OpportunityFixedTermRenewal_Schedulable', schedule, oftrs);
        Test.stopTest();
    }
}