force-app/main/default/objects/BatchJobSettings__c/BatchJobSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Phase 2 - Custom settings for scheduling batch jobs
ECLM -  Custom settings for renewal and review opportunity creation jobs</description>
    <label>BatchJobSettings</label>
</CustomObject>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Day_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>SCR_Day_Of_Month__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Day Of Month</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Day_Of_Week__c.field-meta.xml
<CustomField>
    <fullName>SCR_Day_Of_Week__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Day Of Week</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Hours__c.field-meta.xml
<CustomField>
    <fullName>SCR_Hours__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Hours</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Minutes__c.field-meta.xml
<CustomField>
    <fullName>SCR_Minutes__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Minutes</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Month__c.field-meta.xml
<CustomField>
    <fullName>SCR_Month__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Month</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Optional_Year__c.field-meta.xml
<CustomField>
    <fullName>SCR_Optional_Year__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Optional Year</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchJobSettings__c/fields/SCR_Seconds__c.field-meta.xml
<CustomField>
    <fullName>SCR_Seconds__c</fullName>
    <description>Phase 2 - Utilised in the Sales Coverage Change Request batch process</description>
    <label>SCR Seconds</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExecuteSegmentationChangeRequestBatch.cls
/**************************************************
Type:       Class for executing Batch Job for Segmentation Change Request
Purpose:    
History:
--------------------------------------------------
06.09.2012    M. Isidro (Cloud Sherpas)         Created
**************************************************/
@isTest
public with sharing class ExecuteSegmentationChangeRequestBatch {
    public static void execSegmentationChangeRequest() {
        String sYear = BatchJobSettings__c.getInstance().SCR_Optional_Year__c;  
        if (sYear == null) sYear = '*';
        String sMonth = BatchJobSettings__c.getInstance().SCR_Month__c;
        if (sMonth == null) sMonth = '*';
        String sDay = BatchJobSettings__c.getInstance().SCR_Day_Of_Month__c;
        if (sDay == null) sDay = '*';
        String sHour = BatchJobSettings__c.getInstance().SCR_Hours__c;
        if (sHour == null) sHour = '*';
        String sMinute = BatchJobSettings__c.getInstance().SCR_Minutes__c;
        if (sMinute == null) sMinute = '0';
        String sSecond = BatchJobSettings__c.getInstance().SCR_Seconds__c;
        if (sSecond == null) sSecond = '0';
        String sDayOfWeek = BatchJobSettings__c.getInstance().SCR_Day_Of_Week__c;
        if (sDayOfWeek == null) sDayOfWeek = '?';
        
        SegmentationChangeRequest scr = new SegmentationChangeRequest();
        //String sch = '0 3 19 26 7 ?';
        String sched = sSecond + ' ' + sMinute + ' ' + sHour + ' ' + sDay + ' ' + sMonth + ' ' + sDayOfWeek + '' + sYear;
        system.debug('***sched: ' + sched);
        system.schedule('SegmentationChangeRequest', sched, scr);       
    }
    
    
    private static testMethod void testExecuteSegmentationChangeRequestBatch() {
        
        //list<CronTrigger> cron = new list<CronTrigger>([SELECT Id, State FROM CronTrigger where state!='DELETED']);
        
        // 26 November 2015 (christopher.henschke@auspost.com.au) updated SOQL to include CronJobDetail.JobType and stop test class from failing
		// using scheduled apex (jobtype 7) and batch job (jobtype 9)
		list<CronTrigger> cron = new list<CronTrigger>([SELECT Id, State, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType FROM CronTrigger where state!='DELETED' AND (CronJobDetail.JobType = '7' OR CronJobDetail.JobType = '9')]);
		
        for(CronTrigger CT : cron){
            system.abortjob(CT.Id);
        }
        
        ExecuteSegmentationChangeRequestBatch.execSegmentationChangeRequest();
    }   
}