force-app/main/default/objects/ProductRelationship__c/ProductRelationship__c.object-meta.xml
<CustomObject>
    <description>Establishes relationships between products</description>
    <label>Product Relationship</label>
    <nameField>
        <displayFormat>PRR-{00000000}</displayFormat>
        <label>Product Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRelationship__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Invalidates the product relationship after the specified date</description>
    <inlineHelpText>Specify a date after which this relationship no longer applies. Leave empty for ongoing relationships.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductRelationship__c/fields/ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentProduct__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent Product</description>
    <inlineHelpText>Choose the Parent Product</inlineHelpText>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>ParentProductRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRelationship__c/fields/RelatedProduct__c.field-meta.xml
<CustomField>
    <fullName>RelatedProduct__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that is related to the parent product</description>
    <inlineHelpText>Choose the product that is related to the parent product.</inlineHelpText>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Products</relationshipLabel>
    <relationshipName>ChildProductRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRelationship__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <description>Describes how the parent product is related to the related product</description>
    <inlineHelpText>Specify how the parent product is related to the related product.</inlineHelpText>
    <label>Relationship</label>
	<complianceGroup>GDPR</complianceGroup>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Replaces</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductRelationshipsSelector.cls
/* @author Ken McGuire
 * @date 2023-05-29
 * @test ProductRelationshipsSelector_Test
 * @description simple selector class for product relationships
 * @changelog
 *  2023-05-29 - Ken McGuire - Created
 */
public virtual inherited sharing class ProductRelationshipsSelector extends ApplicationSelector {
	public enum Options {
		WITH_PRODUCT_RELATIONSHIP
	}

	public static ProductRelationshipsSelector newInstance() {
		return (ProductRelationshipsSelector) Application.Selectors.newInstance(ProductRelationshipsSelector.class);
	}

	public static ProductRelationshipsSelector newInstance(Integer recordLimit) {
		return (ProductRelationshipsSelector) Application.Selectors.newInstance(ProductRelationshipsSelector.class).setLimit(recordLimit);
	}

	public override SObjectType getSObjectType() {
		return ProductRelationship__c.getSObjectType();
	}

	public virtual override Set<SObjectField> getSObjectFieldList() {
		return new Set<SObjectField>{
		ProductRelationship__c.ParentProduct__c, ProductRelationship__c.RelatedProduct__c
		// add more fields as needed
		};
	}

	public List<ProductRelationship__c> selectByRelatedAndParent(Set<Id> relatedProductsToInclude, Set<Id> parentProductsToInclude) {
		return selectByRelatedAndParent(relatedProductsToInclude, parentProductsToInclude, new Set<Object>());
	}

	public List<ProductRelationship__c> selectByRelatedAndParent(Set<Id> relatedProductsToInclude, Set<Id> parentProductsToInclude, Set<Object> selectorOptions) {
		Date todaysDate = Date.today();
		QueryBuilder qb = newQueryBuilder(selectorOptions)
		.addConditions()
		.add(new QueryBuilder.SimpleCondition('RelatedProduct__c in :relatedProductsToInclude'))
		.add(new QueryBuilder.SimpleCondition('ParentProduct__c in :parentProductsToInclude'))
		.add(new QueryBuilder.SimpleCondition('Relationship__c = \'Replaces\''))
		.add(new QueryBuilder.SimpleCondition('(EndDate__c = NULL OR EndDate__c > :todaysDate)'))
		.endConditions();
		return (List<ProductRelationship__c>) Database.query(qb.toSoqlString());
	}
    
  	public List<ProductRelationship__c> selectByParent(Set<Id> parentProductsToInclude) {
		return selectByParent(parentProductsToInclude, new Set<Object>());
	}

	public List<ProductRelationship__c> selectByParent(Set<Id> parentProductsToInclude, Set<Object> selectorOptions) {
		Date todaysDate = Date.today();
		QueryBuilder qb = newQueryBuilder(selectorOptions)
		.addConditions()
		.add(new QueryBuilder.SimpleCondition('ParentProduct__c in :parentProductsToInclude'))
		.add(new QueryBuilder.SimpleCondition('Relationship__c = \'Replaces\''))
		.add(new QueryBuilder.SimpleCondition('(EndDate__c = NULL OR EndDate__c > :todaysDate)'))
		.endConditions();
		return (List<ProductRelationship__c>) Database.query(qb.toSoqlString());
	}

	public virtual override QueryBuilder newQueryBuilder(Set<Object> selectorOptions) {
		QueryBuilder builder = super.newQueryBuilder(selectorOptions);

		if (selectorOptions.contains(Options.WITH_PRODUCT_RELATIONSHIP)) {
			builder.addRelatedFields(ProductsSelector.newInstance().newQueryBuilder(), 'ProductRelationship__c');
		}

		return builder;
	}
}