force-app/main/default/objects/Case/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <description>Primary Address which consists of street, suburb, state, country</description>
    <label>Sender Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Country__c.field-meta.xml
<CustomField>
    <fullName>Address1Country__c</fullName>
    <description>SSSW</description>
    <label>Sender Address Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1DPID__c.field-meta.xml
<CustomField>
    <fullName>Address1DPID__c</fullName>
    <description>2014-07 CCU</description>
    <label>Sender Address DPID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1line2__c.field-meta.xml
<CustomField>
    <fullName>Address1line2__c</fullName>
    <description>Address line 2, SSSW</description>
    <label>Sender Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Postcode__c.field-meta.xml
<CustomField>
    <fullName>Address1Postcode__c</fullName>
    <description>SSSW</description>
    <label>Sender Address Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1State__c.field-meta.xml
<CustomField>
    <fullName>Address1State__c</fullName>
    <description>SSSW</description>
    <label>Sender Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Suburb__c.field-meta.xml
<CustomField>
    <fullName>Address1Suburb__c</fullName>
    <description>SSSW</description>
    <label>Sender Address Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <description>Secondary address which consists of street, suburb, state and country</description>
    <label>Addressee Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Country__c.field-meta.xml
<CustomField>
    <fullName>Address2Country__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2DPID__c.field-meta.xml
<CustomField>
    <fullName>Address2DPID__c</fullName>
    <description>2014-07 CCU</description>
    <label>Addressee Address DPID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2line2__c.field-meta.xml
<CustomField>
    <fullName>Address2line2__c</fullName>
    <description>Line 2 of secondary Address, SSSW</description>
    <label>Addressee Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Postcode__c.field-meta.xml
<CustomField>
    <fullName>Address2Postcode__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2State__c.field-meta.xml
<CustomField>
    <fullName>Address2State__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Suburb__c.field-meta.xml
<CustomField>
    <fullName>Address2Suburb__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseOriginator__c.field-meta.xml
<CustomField>
    <fullName>CaseOriginator__c</fullName>
    <description>SSSW</description>
    <label>Case Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Sender</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Addressee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Other_Party__c.field-meta.xml
<CustomField>
    <fullName>Other_Party__c</fullName>
    <description>SSSW - Used for Decipha Load</description>
    <label>Other Party</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Name__c</fullName>
    <description>SSSW</description>
    <label>Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PrimaryContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactFirstName__c</fullName>
    <description>Used for Contact Us Form.</description>
    <label>Primary Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PrimaryContactLastName__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactLastName__c</fullName>
    <description>Contact Us.</description>
    <label>Primary Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Secondary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact__c</fullName>
    <description>SSSW - Text field for page layouts</description>
    <label>Addressee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SecondaryContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>SecondaryContactFirstName__c</fullName>
    <label>Secondary Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SecondaryContactLastName__c.field-meta.xml
<CustomField>
    <fullName>SecondaryContactLastName__c</fullName>
    <description>Contact Us form</description>
    <label>Secondary Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseMassUploadDeciphaCont.cls
public class CaseMassUploadDeciphaCont 
{
    
    public Blob csvBlob {get; set;}
    
    public Case proxyCase {get; set;}   
    
    public CaseMassUploadDeciphaCont()
    {
        proxyCase = new Case();
        proxyCase.Type = CaseMassUploadManager.DEFAULT_CASE_TYPE;
        proxyCase.OwnerId = CaseMassUploadManager.DefaultOwner != null ? CaseMassUploadManager.DefaultOwner.Id : null;      
        proxyCase.Origin = CaseMassUploadManager.CASE_ORIGIN_DECIPHA;
    }
    
    public PageReference upload() 
    {       
        try 
        {
            System.debug('---csvBlob:' + csvBlob.toString());   
            
            List<Case> cases = CaseMassUploadManager.createCases(proxyCase, csvBlob.toString());
            if (cases.size() > 0)
            {
                List<CaseComment> caseComments = new List<CaseComment>();
                for(Case c:cases) 
                {
                    if((c.CaseOriginator__c!= NULL && c.CaseOriginator__c.toLowerCase() == 'addressee') || 
                       (c.Other_Party__c != NULL && c.Other_Party__c.toLowerCase() == 'sender')) 
                    {
                        String temp = '';
                        
                        temp = c.Address1__c;
                        c.Address1__c = c.Address2__c;
                        c.Address2__c = temp;
                        
                        temp = c.Address1line2__c;
                        c.Address1line2__c = c.Address2line2__c;
                        c.Address2line2__c = temp;
                        
                        temp = c.Address1Country__c;
                        c.Address1Country__c = c.Address2Country__c;
                        c.Address2Country__c = temp;
                        
                        temp = c.Address1DPID__c;
                        c.Address1DPID__c = c.Address2DPID__c;
                        c.Address2DPID__c = temp;
                        
                        temp = c.Address1Postcode__c;
                        c.Address1Postcode__c = c.Address2Postcode__c;
                        c.Address2Postcode__c = temp;
                        
                        temp = c.Address1State__c;
                        c.Address1State__c = c.Address2State__c;
                        c.Address2State__c = temp;
                        
                        temp = c.Address1Suburb__c;
                        c.Address1Suburb__c = c.Address2Suburb__c;
                        c.Address2Suburb__c = temp;
                        
                        temp = c.PrimaryContactFirstName__c;
                        c.PrimaryContactFirstName__c = c.SecondaryContactFirstName__c;
                        c.SecondaryContactFirstName__c = temp;
                        
                        temp = c.PrimaryContactLastName__c;
                        c.PrimaryContactLastName__c = c.SecondaryContactLastName__c;
                        c.SecondaryContactLastName__c = temp;
                    }
                    
                    c.Primary_Name__c =  (c.PrimaryContactFirstName__c!=null?c.PrimaryContactFirstName__c+' ':'') + (c.PrimaryContactLastName__c!=null?c.PrimaryContactLastName__c:'');
                    c.Secondary_Contact__c = (c.SecondaryContactFirstName__c!=null?c.SecondaryContactFirstName__c+' ':'') + (c.SecondaryContactLastName__c!=null?c.SecondaryContactLastName__c:'');
                    
                    CaseComment com = new CaseComment(Ispublished=false, CommentBody = c.Description);
                    c.Description = '';
                    caseComments.add(com);
                }
                system.debug('--Cases**'+cases);
                insert cases;
                for(Integer i=0;i<caseComments.size();i++) 
                {
                    caseComments[i].ParentId=cases[i].Id;                        
                }
                for(Integer i=0;i<caseComments.size();i++) 
                {
                    if(caseComments[i].CommentBody == null || caseComments[i].CommentBody == '') 
                    {
                        CaseComment removed = caseComments.remove(i);
                    }
                }
                insert caseComments;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, cases.size() + ' Cases Created'));
            }  
        }
        catch (Exception e)
        {
            ApexPages.addMessages(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, CaseMassUploadManager.TOO_MANY_ROWS_MESSAGE));
        }
        return null;
    }
    
    public PageReference downloadTemplate()
    {
        return new PageReference('/resource/CSVUploadTemplates/DeciphaUploadTemplate.csv');
    }
}