force-app/main/default/objects/Case/fields/AllocateToQueue__c.field-meta.xml
<CustomField>
    <fullName>AllocateToQueue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SSSW - This Field is used to fire the Workflow to allocate the Case back to the correct Queue.</description>
    <label>Allocate to Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/BypassPreferredAgent__c.field-meta.xml
<CustomField>
    <fullName>BypassPreferredAgent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used by the Routing Engine to bypass the Preferred Agent logic. It will be set to False whenever the owner of the case changes from a Queue to a User.</description>
    <label>Bypass Preferred Agent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <formula>IMAGE( 
CASE(Origin, 
&apos;Email&apos;, &apos;/resource/StarTrackCaseIcons/Email_Origin.png&apos;, 
&apos;Internal&apos;, &apos;/resource/StarTrackCaseIcons/Internal_Origin.png&apos;, 
&apos;System&apos;, &apos;/resource/StarTrackCaseIcons/System_Origin.png&apos;, 
&apos;Phone&apos;, &apos;/resource/StarTrackCaseIcons/Phone_Origin.png&apos;, 
&apos;Social&apos;, &apos;/resource/StarTrackCaseIcons/Social_Origin.png&apos;,
&apos;Chat&apos;, &apos;/resource/StarTrackCaseIcons/Chat_Origin.png&apos;,
&apos;Fax&apos;, &apos;/resource/StarTrackCaseIcons/Fax_Origin.png&apos;, 
&apos;Web&apos;, &apos;/resource/StarTrackCaseIcons/Web_Origin.png&apos;,
&apos;BSP&apos;, &apos;/resource/StarTrackCaseIcons/BSPCaseOrigin.png&apos;,
&apos;Snap It&apos;, &apos;/resource/StarTrackCaseIcons/snap_it.png&apos;,
&apos;/resource/StarTrackCaseIcons/Other_Origin.png&apos;),&apos;Other&apos; 
)</formula>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PreferredAgentExpiry__c.field-meta.xml
<CustomField>
    <fullName>PreferredAgentExpiry__c</fullName>
    <inlineHelpText>This date is used by Omni to determine whether to assign the case to the preferred agent or to other agents</inlineHelpText>
    <label>Preferred Agent Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/SSSWRouting__c.object-meta.xml
<CustomObject>
    <label>SSSW Routing</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>SSSW Routing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSSW Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSSWRouting__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/Match_Rules_On__c.field-meta.xml
<CustomField>
    <fullName>Match_Rules_On__c</fullName>
    <label>Match Rules On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/PreferredAgentExpiry__c.field-meta.xml
<CustomField>
    <fullName>PreferredAgentExpiry__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is used to calculate how long Omni will attempt to assign a case to a preferred agent.</inlineHelpText>
    <label>Preferred Agent Expiry (in hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Queue_ID__c</fullName>
    <description>If the Case is marked to &quot;Reassign to Queue&quot;, this is the ID that will be assigned.</description>
    <inlineHelpText>18 Digit ID of the Queue.</inlineHelpText>
    <label>Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/recordTypes/SSSWRouting.recordType-meta.xml
<RecordType>
    <fullName>SSSWRouting</fullName>
    <active>true</active>
    <label>SSSW Routing</label>
</RecordType>

force-app/main/default/classes/APCaseAgentWorkPreferredAgentModule_Test.cls
/***
 * @author George Nguyen
 * @domain Core
 * @description Test class for APCaseAgentWorkPreferredAgentModule 
 * @changelog
 * 2023-02-16 - George Nguyen - Created
 * 2023-03-18 - Noel Lim - Updated to test routing logic which directly assigns the routed Queue as the Owner.
 */
@IsTest
class APCaseAgentWorkPreferredAgentModule_Test {
   
	@IsTest
	static void processUserResponseForPreferredAgent() {
		
		//User
		List<User> users = ApplicationTestDataFactory.getUsers(1, true);

		Map<Id, Group> queues = new Map<Id, Group>(ApplicationTestDataFactory.getGroups(1, 'Queue', true));	
		
		//Case
		Map<Id, Case> cases = new Map<Id, Case>(ApplicationTestDataFactory.getCases(5, true));
		for(Case csRec : cases.values()){
			csRec.BypassPreferredAgent__c = true;
			csRec.PreferredAgentExpiry__c = Datetime.now();
			csRec.OwnerId = users[0].Id;
			csRec.Origin = 'Email';
		}

		//Routing Rule
		SSSWRouting__c routingRule = new SSSWRouting__c();
		Id routingRuleRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'SSSWRouting__c' AND DeveloperName = 'SSSWRouting'].Id;
		routingRule.RecordTypeId = routingRuleRecordTypeId;
		routingRule.Match_Rules_On__c = 'All';
		routingRule.Origin__c = 'Email';
		routingRule.IsActive__c = true;
		routingRule.Queue_ID__c = queues.values()[0].Id;
		routingRule.Sequence__c = 1;
		Insert routingRule;

		//AgentWork
		List<AgentWork> records = OmniChannelTestDataFactory.getAgentWorks(5, UserInfo.getUserId(), cases.keySet(), true);
		records[0] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(records[0], new Map<String, Object> { 'Status' => 'Opened'});
		records[1] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(records[1], new Map<String, Object> { 'Status' => 'Assigned'});
		records[2] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(records[2], new Map<String, Object> { 'Status' => 'Declined'});
		records[3] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(records[3], new Map<String, Object> { 'Status' => 'Declined', 'PreferredUserId' => users[0].Id });
		records[4] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(records[4], new Map<String, Object> { 'Status' => 'DeclinedOnPushTimeout', 'PreferredUserId' => users[0].Id });

		Set<Id> caseIdsToRoute = new Set<Id>{ records[3].WorkItemId, records[4].WorkItemId};
		List<Case> casesToRoute = new List<Case>{cases.values()[3],cases.values()[4]};

		List<AgentWork> existingRecords = records.deepClone(true, true, true);
		existingRecords[0] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(existingRecords[0], new Map<String, Object> { 'Status' => 'Assigned'});
		existingRecords[1] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(existingRecords[1], new Map<String, Object> { 'Status' => 'Assigned'});
		existingRecords[2] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(existingRecords[2], new Map<String, Object> { 'Status' => 'Assigned'});
		existingRecords[3] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(existingRecords[3], new Map<String, Object> { 'Status' => 'Assigned'});
		existingRecords[4] = (AgentWork)ApplicationTestDataFactory.setUnwritableFields(existingRecords[4], new Map<String, Object> { 'Status' => 'Assigned'});

		// =====================================
		// Stubbing
		// =====================================
		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();
		SSSWCasesSelector mockCaseSelector = (SSSWCasesSelector)MockUtility.mockSelector(SSSWCasesSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(mockCaseSelector.selectById(
				(Set<Id>)fflib_Match.eq(caseIdsToRoute)
		)).thenReturn(new Map<Id, Case>(casesToRoute));

		MockUtility.Mocks.stopStubbing();


		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		APCaseAgentWorkPreferredAgentModule.newInstance().onAfterUpdate(records, new Map<Id, AgentWork>(existingRecords), mockUow);

		((ApplicationUnitOfWork) MockUtility.Mocks.verify(mockUow, 1)).registerDirty(
			(List<Case>) fflib_Match.eq(new List<Case>{
				new Case(Id = records[0].WorkItemId, BypassPreferredAgent__c = false, AllocateToQueue__c = false, PreferredAgentExpiry__c = null),
				new Case(Id = records[3].WorkItemId, OwnerId = queues.values()[0].Id, BypassPreferredAgent__c = true, PreferredAgentExpiry__c = null),
				new Case(Id = records[4].WorkItemId, OwnerId = queues.values()[0].Id, BypassPreferredAgent__c = true, PreferredAgentExpiry__c = null)
			}),
			(List<SObjectField>)fflib_Match.eq(new List<SObjectField>{ Case.OwnerId, Case.BypassPreferredAgent__c, Case.PreferredAgentExpiry__c, Case.AllocateToQueue__c }),
			fflib_Match.eqBoolean(true),
			fflib_Match.eqString(APCaseAgentWorkPreferredAgentModule.class.getName())
		);

		// PMD Warning
		System.assert(true);

		Test.stopTest();
	}
}