force-app/main/default/objects/Case/fields/AllocateToQueue__c.field-meta.xml
<CustomField>
    <fullName>AllocateToQueue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SSSW - This Field is used to fire the Workflow to allocate the Case back to the correct Queue.</description>
    <label>Allocate to Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Bypass_Data_enforcement__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Data_enforcement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SSSW</description>
    <label>Bypass Data enforcement?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Milestones_Violated__c.field-meta.xml
<CustomField>
    <fullName>Customer_Milestones_Violated__c</fullName>
    <label>Customer Milestones Violated</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facility_Milestones_Violated__c.field-meta.xml
<CustomField>
    <fullName>Facility_Milestones_Violated__c</fullName>
    <label>Network Milestones Violated</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facility_Tier_Escalation_Email__c.field-meta.xml
<CustomField>
    <fullName>Facility_Tier_Escalation_Email__c</fullName>
    <label>Network Tier Escalation Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Internal_Milestones_Violated__c.field-meta.xml
<CustomField>
    <fullName>Internal_Milestones_Violated__c</fullName>
    <label>Internal Milestones Violated</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Preferred_Communication_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Communication_Method__c</fullName>
    <label>Preferred Communication Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Entitlement_Status__c/Case_Entitlement_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SSSW  - Used by CaseMilestoneUtil</description>
    <label>Case Entitlement Status</label>
</CustomObject>

force-app/main/default/objects/Case_Entitlement_Status__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Entitlement_Status__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Entitlement_Status__c/fields/Internal__c.field-meta.xml
<CustomField>
    <fullName>Internal__c</fullName>
    <label>Internal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Function_Group__c.field-meta.xml
<CustomField>
    <fullName>Function_Group__c</fullName>
    <description>Phase 1 - List of Function Groups.  Dependent picklist will be Function Group Code</description>
    <inlineHelpText>Used by Marketing to categorise contacts. Select the most appropriate option from the picklist.</inlineHelpText>
    <label>Title Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Account Payable</fullName>
            </value>
            <value>
                <fullName>Admin/Office Manager</fullName>
            </value>
            <value>
                <fullName>Admin/Office Staff</fullName>
            </value>
            <value>
                <fullName>Adver/Prom/PR Mgr</fullName>
            </value>
            <value>
                <fullName>Adver/Prom/PR Staff</fullName>
            </value>
            <value>
                <fullName>AR Contact</fullName>
            </value>
            <value>
                <fullName>Bus/Comm/Dev Manager</fullName>
            </value>
            <value>
                <fullName>Bus/Comm/Dev Staff</fullName>
            </value>
            <value>
                <fullName>Communications Mgr</fullName>
            </value>
            <value>
                <fullName>Communications Staff</fullName>
            </value>
            <value>
                <fullName>Company Secretary</fullName>
            </value>
            <value>
                <fullName>Contact Left Company</fullName>
            </value>
            <value>
                <fullName>Cust Services Manager</fullName>
            </value>
            <value>
                <fullName>Cust Services Staff</fullName>
            </value>
            <value>
                <fullName>Deadmail</fullName>
            </value>
            <value>
                <fullName>Desp/Whse/Mroom Mgr</fullName>
            </value>
            <value>
                <fullName>Desp/Whse Mroom Staff</fullName>
            </value>
            <value>
                <fullName>Direct Marketing Mgr</fullName>
            </value>
            <value>
                <fullName>Direct Marketing Staff</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive Board</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Finance Staff</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>HR Staff</fullName>
            </value>
            <value>
                <fullName>IT Manager</fullName>
            </value>
            <value>
                <fullName>Legal Personnel</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Email_1__c.field-meta.xml
<CustomField>
    <fullName>Email_1__c</fullName>
    <label>Email 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Premium &amp; Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCaseMileStoneUtil.cls
@isTest
private class TestCaseMileStoneUtil {
    //No more Needed as all methods in CaseMileStoneUtil is commented
    // @testSetup static void testDataCreate() {
    //     Group g1 = new Group(Name='SSSW Child Cases', type='Queue');
    //     insert g1;
    //     QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
    //     insert q1;
    // }

    // static testMethod void MethodTestChunk1() {
    //     Id rtId ;
    //     for(Id ssswid : Utility.getRecordTypeIds('Case', 'SSSW')) {
    //         rtId = ssswid;
    //         break;
    //     }

    //     buildCaseEntitlement();

    //     Group g1 = [Select Id, Name from Group where Type = 'Queue' AND Name='SSSW Child Cases' limit 1];
    //     QueueSObject q1 = [select QueueId from QueueSObject where QueueId =: g1.id];

    //     Network__c network = new Network__c(Name='test', Email_1__c='test@test.com');
    //     insert network;

    //     Id contactId = createTestContact().Id;

    //     map<Id, Case> map_newCase = new map<Id, Case>();
    //     map<Id, Case> map_oldCase = new map<Id, Case>();

    //     TestDataProvider.preventTrigger = true;

    //     Case c1 = buildCase('Email', rtId, network.Id, contactId, 'In Progress,Awaiting Information', q1.QueueId, null);
    //     map_oldCase.put(c1.Id, c1);

    //     Case c1_new = c1.clone(true, true);
    //     c1_new.Facility_Milestones_Violated__c = 2;
    //     map_newCase.put(c1_new.Id, c1_new);

    //     Case c2 = buildCase('SMS', rtId, network.Id, contactId, 'Awaiting Network Response', g1.Id, c1.Id);
    //     map_oldCase.put(c2.Id, c2);

    //     Case c2_new = c2.clone(true, true);
    //     c2_new.Customer_Milestones_Violated__c = 2;
    //     map_newCase.put(c2_new.Id, c2_new);
            
    //     List<Case> newCases = map_newCase.values();

    //     Test.startTest();
    //     map_newCase.remove(c1.Id);
    //     CaseChildQueueManagement.updateParentCase(map_newCase);

    //     Test.stopTest();
    //     System.assertEquals(True, c2_new.Bypass_Data_enforcement__c);
    //     System.assertEquals('test@test.com', c1_new.Facility_Tier_Escalation_Email__c);
    // } 

    // static testMethod void MethodTestChunk2() {
    //     Id rtId ;
    //     for(Id ssswid : Utility.getRecordTypeIds('Case', 'SSSW')) {
    //     rtId = ssswid;
    //     break;
    //     }

    //     buildCaseEntitlement();

    //     Group g1 = [Select Id, Name from Group where Type = 'Queue'  AND Name='SSSW Child Cases' limit 1];
    //     QueueSObject q1 = [select QueueId from QueueSObject where QueueId =: g1.id];

    //     Network__c network = new Network__c(Name='test', Email_1__c='test@test.com');
    //     insert network;

    //     Id contactId = createTestContact().Id;

    //     map<Id, Case> map_newCase = new map<Id, Case>();
    //     map<Id, Case> map_oldCase = new map<Id, Case>();

    //     TestDataProvider.preventTrigger = true;

            
    //     Case c3 = buildCase(null, rtId, network.Id, contactId, 'Awaiting Customer Response', q1.queueId, null);  
    //     map_oldCase.put(c3.Id, c3);

    //     Case c3_new = c3.clone(true, true);
    //     c3_new.Internal_Milestones_Violated__c = 2;
    //     map_newCase.put(c3_new.Id, c3_new);

    //     Case c4 = c3.clone(true, true);
    //     c4.Internal_Milestones_Violated__c = null;

    //     List<Case> newCases = map_newCase.values();
    //     newCases.add(c4);

    //     Test.startTest();
            
    //     Test.stopTest();
    //     // System.assertEquals(True, c4.Bypass_Data_enforcement__c);
    //     // System.assertEquals('test@test.com', c3_new.Facility_Tier_Escalation_Email__c);
    // } 

    // public static Case buildCase(String pcm, id rtid, id networkId, id contactId, string status, Id queueId, Id parentId) {
    //     Case c = new Case();
    //     c.Status = status;
    //     c.OwnerId = queueId;
    //     c.ParentId = parentId;
    //     c.AllocateToQueue__c = true;
    //     c.Subject = 'test subject';
    //     c.Description = 'test description';
    //     c.Type = 'Fax';
    //     c.RecordTypeId = rtid;
    //     c.Network__c = networkId;
    //     c.Preferred_Communication_Method__c = pcm;
    //     c.Facility_Milestones_Violated__c = 1;
    //     c.Customer_Milestones_Violated__c = 1;
    //     c.Internal_Milestones_Violated__c = 1;
    //     c.ContactId = contactId;
    //     insert c;
    //     return c;
    // }

    // public static void buildCaseEntitlement() {
    // // Requires population, used in CaseTrigger
    //     list<Case_Entitlement_Status__c> list_ces = [SELECT Id 
    //                             FROM Case_Entitlement_Status__c 
    //                             WHERE Internal__c='In Progress,Awaiting Information'
    //                             OR Facility__c='Awaiting Facility Response'
    //                             OR Customer__c='Awaiting Customer Response'];
    //     if(list_ces != null && list_ces.size() == 0) {
    //         Case_Entitlement_Status__c ces = new Case_Entitlement_Status__c(name='test',
    //                                         Internal__c='In Progress,Awaiting Information',
    //                                         Facility__c='Awaiting Facility Response',
    //                                         Customer__c='Awaiting Customer Response');
    //         insert ces;
    //     }
    // }

    // public static Contact createTestContact() {
    //     Contact con = new Contact(); 
    //     con.LastName = 'dsf';
    //     con.Function_Group__c = 'Accountant';
    //     con.MailingCity = 'de';
    //     con.MailingState = '1';
    //     con.MailingStreet = '21';
    //     con.MailingPostalCode = '32';
    //     con.Email = 'dsf@df.com';
    //     con.FirstName = 's';
    //     insert con;
    //     return con;
    // }  
}