force-app/main/default/objects/Case/fields/CustomerQueueType__c.field-meta.xml
<CustomField>
    <fullName>CustomerQueueType__c</fullName>
    <label>Customer Queue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
                <default>true</default>
                <label>Consumer</label>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>MyPost Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SocialPostTags__c.field-meta.xml
<CustomField>
    <fullName>SocialPostTags__c</fullName>
    <description>Post tags from the social post that originated this case. Only populated when the case is originated by a social network post.</description>
    <inlineHelpText>Post tags present on the Social Post that originated the case.</inlineHelpText>
    <label>Social Post Tags</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/SSSWRouting__c.object-meta.xml
<CustomObject>
    <label>SSSW Routing</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>SSSW Routing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSSW Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SSSWRouting__c/fields/CaseKey__c.field-meta.xml
<CustomField>
    <fullName>CaseKey__c</fullName>
    <externalId>true</externalId>
    <label>Case Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <label>Case Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/CustomerQueueType__c.field-meta.xml
<CustomField>
    <fullName>CustomerQueueType__c</fullName>
    <label>CustomerQueueType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/EnquirySubType__c.field-meta.xml
<CustomField>
    <fullName>EnquirySubType__c</fullName>
    <label>EnquirySubType</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>Product Category</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <label>Product Sub Category</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Queue_ID__c</fullName>
    <description>If the Case is marked to &quot;Reassign to Queue&quot;, this is the ID that will be assigned.</description>
    <inlineHelpText>18 Digit ID of the Queue.</inlineHelpText>
    <label>Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/fields/SocialPostTags__c.field-meta.xml
<CustomField>
    <fullName>SocialPostTags__c</fullName>
    <description>Social Post Tags to match for routing cases originated via social network posts.</description>
    <label>Social Post Tags</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SSSWRouting__c/recordTypes/SSSWRouting.recordType-meta.xml
<RecordType>
    <fullName>SSSWRouting</fullName>
    <active>true</active>
    <label>SSSW Routing</label>
</RecordType>

force-app/main/default/classes/SSSWRoutingController_Test.cls
/**************************************************
Type:       SSSWRoutingController_Test
History:
--------------------------------------------------
Jun-2014:  di.chen@bluewolf.com  Created - Test coverage
Jun-2018:  TDO-215 : hector.huang@coroma.com.au Unit tests re-written with scenario based tests.
Jul-2018:  disha.kariya@auspost.com.au Updated class to adopt to new SSSW Routing table
2020-11-18 - Ranjeewa Silva - Added test method for checking duplicate rules based on post tags
**************************************************/
@isTest
private class SSSWRoutingController_Test {

	@TestSetup
	static void testSetup() {
		// create a new Case for testing getRecordTypeId static method
		Case testCase = TestDataProvider.createTestCase();
		testCase.ReferenceID__c = 'SSSWCase';
		insert testCase;

		// create a new SSSWRouting for testing class methods
		SSSWRouting__c sswrou = new SSSWRouting__c();
		RecordType recordType = [SELECT Id FROM RecordType LIMIT 1];
		sswrou.CaseType__c = 'CRM Query';
		sswrou.ProductCategory__c = 'test';
		sswrou.ProductSubCategory__c = 'sub test';
		sswrou.CustomerQueueType__c = 'norm';
		sswrou.EnquirySubType__c = 'enq';
		sswrou.Queue_ID__c = recordType.Id;
		insert sswrou;
	}

	@isTest
	/**
	 * SCENARIO: Record Type Id of a case with SSSWCase Reference ID is returned
	 **/
	// static void SSSWRoutingController_Test_getRecordTypeId_got() {
	//     Test.startTest();

	//     // verify if any Record Type Id has been return by calling the static method
	//     System.assertEquals(false, String.isBlank(SSSWRoutingController.getRecordTypeId('A', 'B')),
	//             'SSSWRoutingController_Test_getRecordTypeId_got: no record type Id relevant to SSSWCase has been returned');

	//     Test.stopTest();
	// }

	/**
	 * SCENARIO: Group information of a SSSWRoutingController is fetched successfully
	**/
	static void SSSWRoutingController_Test_getQueueIDs_got() {
		Test.startTest();

		// get the SSSWRouting inserted during setup
		SSSWRouting__c routing = [SELECT Id FROM SSSWRouting__c LIMIT 1];
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(routing);
		SSSWRoutingController ext = new SSSWRoutingController(stdCtl);

		// call getQueueIDs and verify the group result
		SelectOption queueID = ext.getQueueIDs().get(0);
		System.assertEquals(true, queueID.getLabel().contains('SSSW'),
				'SSSWRoutingController_Test_getQueueIDs_got: fails to get the group info of the SSSWRoutingController');

		Test.stopTest();
	}

	@isTest
	/**
	 * SCENARIO: Email template of a SSSWRoutingController is fetched successfully
	 **/
	// static void SSSWRoutingController_Test_getTemplateIDs_got() {
	//     Test.startTest();

	//     // get the SSSWRouting inserted during setup
	//     SSSWRouting__c routing = [SELECT Id FROM SSSWRouting__c LIMIT 1];
	//     ApexPages.StandardController stdCtl = new ApexPages.StandardController(routing);
	//     SSSWRoutingController ext = new SSSWRoutingController(stdCtl);

	//     // call getTemplateIDs and verify the Email Template result
	//     SelectOption templateID = ext.getTemplateIDs().get(0);
	//     System.assertEquals(true, templateID.getLabel().contains('SSSW'),
	//             'SSSWRoutingController_Test_getTemplateIDs_got: fails to get the Email Template of the SSSWRoutingController');

	//     Test.stopTest();
	// }

	
	/**
	 * SCENARIO: There's no existing routing and proxy case of a SSSWRoutingController is created successfully by calling checkExisting
	 **/
	static void SSSWRoutingController_Test_checkExisting_notExist() {
		Test.startTest();

		// get the SSSWRouting inserted during setup
		SSSWRouting__c routing = [
				SELECT Id, ProductCategory__c, ProductSubCategory__c, CaseType__c,
						CustomerQueueType__c, EnquirySubType__c, Queue_ID__c
				FROM SSSWRouting__c
				LIMIT 1
		];
		routing.SocialPostTags__c = 'w2423423asdfsadfsa'; // making it unique
		update routing;
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(routing);
		SSSWRoutingController ext = new SSSWRoutingController(stdCtl);

		// link the routing attributes to SSWRoutingController
		ext.productCategory = routing.ProductCategory__c.split(SSSWRoutingController.MULTI_SELECT_DELIM);
		ext.productSubCategory = routing.ProductSubCategory__c.split(SSSWRoutingController.MULTI_SELECT_DELIM);
		ext.customerQueueType = routing.CustomerQueueType__c.split(SSSWRoutingController.MULTI_SELECT_DELIM);
		ext.enquirySubType = routing.EnquirySubType__c.split(SSSWRoutingController.MULTI_SELECT_DELIM);
		ext.queueID = routing.Queue_ID__c;

		ext.checkExisting();

		// get the existing routings after call checkExisting method and verify the result
		List<SSSWRouting__c> routings = ext.existingRoutings;
		System.assertEquals(true, routings.isEmpty(), 'SSSWRouting__c should not exist');

		Test.stopTest();
	}

	@isTest
	/**
	 * SCENARIO: New SSSWRouting is saved and updated successfully
	 **/
	static void SSSWRoutingController_Test_save_success() {
		Test.startTest();

		// get the SSSWRouting inserted during setup
		SSSWRouting__c routing = [
				SELECT Id, ProductCategory__c, ProductSubCategory__c, CaseType__c,
						CustomerQueueType__c, EnquirySubType__c
				FROM SSSWRouting__c
				LIMIT 1
		];
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(routing);
		SSSWRoutingController ext = new SSSWRoutingController(stdCtl);
		//ext.enquirySubType='TestingSave';
		ext.enquirySubType= new List<String>{'TestingSave'};
		ext.changeRecordType();
		ext.save();
		// get new SSSWRouting after save
		SSSWRouting__c newRouting = [SELECT CaseKey__c,EnquirySubType__c FROM SSSWRouting__c LIMIT 1];

		// verify if the updated SSSWRouting has right Case Type, Category, CustomerQueueType, Enquire Type
		System.assertEquals('TestingSave', newRouting.EnquirySubType__c,
				'SSSWRoutingController_Test_save_success: fails to update SSSWRouting');


		Test.stopTest();
	}

	@isTest
	static void testIsSamePostTags() {
		// get the SSSWRouting inserted during setup
		SSSWRouting__c routing = [
				SELECT Id, ProductCategory__c, ProductSubCategory__c, CaseType__c,
						CustomerQueueType__c, EnquirySubType__c
				FROM SSSWRouting__c
				LIMIT 1
		];
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(routing);
		SSSWRoutingController ext = new SSSWRoutingController(stdCtl);

		Test.startTest();
		System.assert(ext.isSamePostTags(null, null), 'Expected to return true if post tags are null');
		System.assert(ext.isSamePostTags('', ''), 'Expected to return true if post tags are blank');
		System.assert(ext.isSamePostTags(' ', ' '), 'Expected to return true if post tags are blank');
		System.assert(ext.isSamePostTags(' ', null), 'Expected to return true if post tags are blank or null');
		System.assert(!ext.isSamePostTags('pt1', null), 'Expected to return false if post tags are specified in new rule but blank on existing rule');
		System.assert(!ext.isSamePostTags(null, 'pt1'), 'Expected to return false if post tags are not specified in new rule but specified in the existing rule');
		System.assert(!ext.isSamePostTags('pt1', 'pt2'), 'Expected to return false when post tags differ');
		System.assert(!ext.isSamePostTags('pt1;pt2', 'pt2'), 'Expected to return false when post tags differ');
		System.assert(ext.isSamePostTags('pt1;pt2', 'pt2;pt1'), 'Expected to return true when post tags match irrespective of the order');
		System.assert(ext.isSamePostTags('pt1;pt2', 'pT1;Pt2'), 'Expected to return true when post tags match irrespective of case');
		Test.stopTest();
	}

}