force-app/main/default/objects/Case/fields/Email_Bypass_Data_enforcement__c.field-meta.xml
<CustomField>
    <fullName>Email_Bypass_Data_enforcement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Bypass Data enforcement?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/PreventStatusChange__c.field-meta.xml
<CustomField>
    <fullName>PreventStatusChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this ticked, the status of the case will not automatically changed by the system. USED BY WFR on CaseComment &amp; EmailMessage</description>
    <label>Prevent Status Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseCommentCustomController.cls
global with sharing class CaseCommentCustomController {
  public Case currentCase {get;set;}
  public List<CaseComment> caseComments {get;set;}

  public Boolean currentUserIsPartOfOmniGroup {
      get {
          return OmniChannelService.currentUserIsPartOfOmniGroup;
      }
  }
  
   public CaseCommentCustomController(ApexPages.StandardController stdController) 
    {      
      currentCase = [select 
                caseNumber,
                ProductCategory__c,
                ProductSubCategory__c,
                Description,Status,RecordType.DeveloperName 
              from Case 
              where id=:stdController.getId() 
              limit 1];
              
      caseComments = [SELECT 
                IsPublished, 
                CommentBody, 
                CreatedBy.Name, 
                CreatedById, 
                CreatedDate 
              FROM CaseComment 
              WHERE ParentId =: currentCase.id 
              ORDER BY CreatedDate DESC];
    }
    
    @RemoteAction 
    global static string addComment(id caseId, string comment, boolean isPublishedIn, boolean preventStatusChange){
      string result = '';
      CaseComment newComment = new CaseComment(ParentId = caseId, CommentBody = comment, isPublished = isPublishedIn);
      try{
        if(preventStatusChange) {
          Case c = [select PreventStatusChange__c from Case where id=:caseId limit 1];
          c.preventStatusChange__c = true;
          c.Email_Bypass_Data_enforcement__c = true;
          update c;
        }
        insert newComment;
      }catch(Exception ex){
        result = 'Error: ' + ex.getMessage();
      }        
        
      return result;
    }   
}