force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OmniSkillsReportController.cls
/**
 * @author Nathan Franklin
 * @date 2023-02-01
 * @description Controller for skills based report data from pending service routing data in omni channel
 * @changelog
*/
public with sharing class OmniSkillsReportController {
	public static final Integer MAX_RECORDS_PER_ITERATION = 1000;

	/**
	 * Grab a list of cases the user wants to drill down into
	 */
	@AuraEnabled(Cacheable=true)
	public static List<Case> getCases(List<Id> caseIds) {
		Set<SObjectField> fieldOverrides = new Set<SObjectField>{
			Case.Id, Case.Status, Case.Priority, Case.CreatedDate, Case.CaseNumber, Case.Type, Case.ProductCategory__c, Case.ProductSubCategory__c, Case.EnquirySubType__c
		};

		return SSSWCasesSelector.newInstance(0, fieldOverrides).selectById(new Set<Id>(caseIds)).values();
	}

	/**
	 * Due to limitations around soql rows this has been created to allow retrieval to happen across multiple transactions
	 * The data is processed and crunched on the client side in the omniSkillsReport lwc component
	 */
	@AuraEnabled
	public static JobOutput fetchReportData(String lastIdRetrieved) {

		// specify a dummy Id to get the process started if one isn't already passed in
		if(String.isEmpty(lastIdRetrieved)) {
			lastIdRetrieved = '0JR000000000000';
		}

		List<PendingServiceRouting> pendingWorkRecords = PendingServiceRoutingSelector.newInstance(MAX_RECORDS_PER_ITERATION, new Map<SObjectType, Set<SObjectField>>{
			PendingServiceRouting.SObjectType => new Set<SObjectField>{PendingServiceRouting.Id, PendingServiceRouting.RoutingPriority, PendingServiceRouting.SecondaryRoutingPriority, PendingServiceRouting.WorkItemId},
			Case.SObjectType => new Set<SObjectField>{Case.Id, Case.CreatedDate},
			SkillRequirement.SObjectType => new Set<SObjectField>{SkillRequirement.Id, SkillRequirement.SkillId},
			Skill.SObjectType => new Set<SObjectField>{Skill.DeveloperName, Skill.MasterLabel}
		}).search(new Map<String, Object>{
			'limitToCaseOnly' => true,
			'limitToSkillWorkOnly' => true,
			'idGreaterThan' => lastIdRetrieved,
			'orderBy' => PendingServiceRouting.Id,
			'sortOrder' => 'asc'
		}, new Set<Object>{
			PendingServiceRoutingSelector.Options.WITH_SKILLREQUIREMENTS, PendingServiceRoutingSelector.Options.WITH_WORKITEM, SkillRequirementSelector.Options.WITH_SKILLS
		}, true);

		JobOutput output = new JobOutput();
		output.records = pendingWorkRecords;
		output.isDone = pendingWorkRecords.size() < MAX_RECORDS_PER_ITERATION;
		output.lastId = (pendingWorkRecords.size() > 0 ? pendingWorkRecords[pendingWorkRecords.size()-1].Id : null);

		return output;
	}

	public class JobOutput {
		@AuraEnabled public List<SObject> records = new List<SObject>();
		@AuraEnabled public String lastId;
		@AuraEnabled public Boolean isDone;
	}

}