force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
            <value>
                <fullName>KeyPass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogACallControllerExtension_Test.cls
/**
*  This test class is for LogACallControllerExtension.
*
@author Frank Chen
@created 2014-06-23
@version 1.0
@since 20.0
*
@changelog
* 2014-06-23 Frank Chen <di.chen@bluewolf.com>
* - Created
* - Test coverage 
* 2021-08-24 - Seth Heang - Uplift SF API Version to 52, the class is pending for decommission in the future date
*/
@isTest
private class LogACallControllerExtension_Test {

    static testMethod void myUnitTest() {
    	
    	Contact con = TestDataProvider.createTestContact();
    	insert con;
    	
 		Case case1 = new Case();
 		case1.ContactId = con.Id;
        case1.Type = 'Feedback';
        case1.Subject = 'Newsdd';
        case1.Status = 'New';
        case1.ProductCategory__c = 'Travel & ID';
        case1.EnquirySubType__c = 'Product Support';
        case1.ProductSubCategory__c = 'KeyPass';
        insert case1;
        
        Test.startTest();
        
        ApexPages.StandardController sc1 = new ApexPages.standardController(case1);  
        LogACallControllerExtension ext = new LogACallControllerExtension(sc1);   
        
        LogACallControllerExtension.createLog(case1.Id, con.Id, 'dsf', 'subject', 'description');  
        
        system.assert(true);
        Test.stopTest();
    }
	static testMethod void myUnitTest2() {
    	
    	Contact con = TestDataProvider.createTestContact();
    	insert con;
    	
 		Case case1 = new Case();
 		case1.ContactId = con.Id;
        case1.Type = 'Feedback';
        case1.Subject = 'Newsdd';
        case1.Status = 'New';
        case1.ProductCategory__c = 'Travel & ID';
        case1.EnquirySubType__c = 'Product Support';
        case1.ProductSubCategory__c = 'KeyPass';
        insert case1;
        
        Test.startTest();
        
        ApexPages.StandardController sc1 = new ApexPages.standardController(case1);  
        LogACallControllerExtension ext = new LogACallControllerExtension(sc1);   
        
        LogACallControllerExtension.createLog(case1.Id, null, 'dsf', 'subject', 'description');  
        
        system.assert(true);
        Test.stopTest();
    }
}