force-app/main/default/objects/Job_Template__c/Job_Template__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <displayFormat>JT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Template__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fit For Duty</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Collection</fullName>
                <default>true</default>
                <label>Delivery &amp; Collection</label>
            </value>
            <value>
                <fullName>Rest Break</fullName>
            </value>
            <value>
                <fullName>Prepare Vehicle</fullName>
            </value>
            <value>
                <fullName>Prepare Trailer</fullName>
            </value>
            <value>
                <fullName>Drop Trailer</fullName>
            </value>
            <value>
                <fullName>Return &amp; Refuel Vehicle</fullName>
            </value>
            <value>
                <fullName>Return Vehicle</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Work As Directed</fullName>
            </value>
            <value>
                <fullName>Clear Posting Box</fullName>
            </value>
            <value>
                <fullName>Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Scheduled Task</fullName>
            </value>
            <value>
                <fullName>Supervisory</fullName>
            </value>
            <value>
                <fullName>Vehicle Servicing</fullName>
            </value>
            <value>
                <fullName>Unscheduled Task</fullName>
            </value>
            <value>
                <fullName>Delivery, Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Unpaid Break</fullName>
            </value>
            <value>
                <fullName>Change Trailer</fullName>
                <isActive>false</isActive>
                <label>Change Trailer</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Collect (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Deliver</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Deliver (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Exchange</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Exchange (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Meal Break Paid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Paid</label>
            </value>
            <value>
                <fullName>Meal Break Unpaid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Unpaid</label>
            </value>
            <value>
                <fullName>Parcel Delivery</fullName>
                <isActive>false</isActive>
                <label>Parcel Delivery</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Collect</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Interim</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Interim</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Route_Template__c.field-meta.xml
<CustomField>
    <fullName>Route_Template__c</fullName>
    <label>Duty Template</label>
    <referenceTo>Route_Template__c</referenceTo>
    <relationshipLabel>Job Templates</relationshipLabel>
    <relationshipName>Job_Templates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>A customer or delivery site where products are collected and delivered, and where trailers may be located.</description>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Route_Template__c/Route_Template__c.object-meta.xml
<CustomObject>
    <label>Duty Template</label>
    <nameField>
        <label>Duty Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duty Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TDF_DutyTemplatePrintControllerYTest.cls
/**
 * @author Emmanuel Yap
 * @date 2021-09-10
 * @description Test class for Print Duty Template Controller
 * @changelog
 * 2021-09-10 - Emmanuel Yap - Created
*/

@isTest
public class TDF_DutyTemplatePrintControllerYTest {

    @testSetup 
    static void setup() {
        // Create common test accounts
        TDF_TestDataFactory objTestDataFactory = new TDF_TestDataFactory();

        OperatingHours objOperatingHours = objTestDataFactory.getOperatingHours('Afternoon Shift');
        insert objOperatingHours;

        ServiceTerritory objServiceTerritory = objTestDataFactory.getServiceTerritory('Dendanong', objOperatingHours.Id);
        insert objServiceTerritory;

        Route_Template__c objRouteTemplate = objTestDataFactory.getDutyTemplate('Test Template', objServiceTerritory.Id);
        insert objRouteTemplate;

        Schema.Location objSiteLocation = new Schema.Location();
        objSiteLocation = objTestDataFactory.getLocation('Dendanong', 'Site');
        insert objSiteLocation;

        Job_Template__c objJobTemplate = objTestDataFactory.getJobTemplate(objRouteTemplate.Id, objSiteLocation.Id);
        objJobTemplate.Activity_Type__c = 'Rest Break';
        insert objJobTemplate;  
        
        Job_Template__c objJobTemplate1 = objTestDataFactory.getJobTemplate(objRouteTemplate.Id, objSiteLocation.Id);
        objJobTemplate1.Activity_Type__c = 'Collection';
        insert objJobTemplate1; 
    }

    @isTest 
    static void validateDutyTemplatePrintControllerXMethodOne(){

    	Test.StartTest(); 

        Route_Template__c objRouteTemplate = [select id, name from Route_Template__c where name = 'Test Template' LIMIT 1];

			PageReference pageRef = Page.TDF_DutyTemplatePrint_New; 
			pageRef.getParameters().put('Id', String.valueOf(objRouteTemplate.Id));
			Test.setCurrentPage(pageRef);
        
        	TDF_DutyTemplatePrintControllerY testDTPrint = new TDF_DutyTemplatePrintControllerY(new ApexPages.StandardController(objRouteTemplate));
            System.assertEquals(objRouteTemplate.Id, testDTPrint.routeTemplate.id ,'Asserted Route Template is existing');
            System.assertNotEquals(0, testDTPrint.jobTemplateList.size(),'Assert Job Templates are populated');

		Test.StopTest();              
    } 

    @isTest 
    static void negativeTest(){

    	Test.StartTest(); 

        	PageReference pageRef = Page.TDF_DutyTemplatePrint_New; 
			pageRef.getParameters().put('Id', null);
			Test.setCurrentPage(pageRef);
            try{
                TDF_DutyTemplatePrintControllerY testDTPrint = new TDF_DutyTemplatePrintControllerY(new ApexPages.StandardController(null));
                System.assertEquals(null, testDTPrint.routeTemplate ,'Asserted Route Template is null');
            } catch(NullPointerException ex){
                System.assertEquals(null,null,'System.NullPointerException: Argument cannot be null');
            }
        
		Test.StopTest();              
    } 

}