force-app/main/default/objects/Job_Template__c/Job_Template__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <displayFormat>JT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Template__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fit For Duty</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Collection</fullName>
                <default>true</default>
                <label>Delivery &amp; Collection</label>
            </value>
            <value>
                <fullName>Rest Break</fullName>
            </value>
            <value>
                <fullName>Prepare Vehicle</fullName>
            </value>
            <value>
                <fullName>Prepare Trailer</fullName>
            </value>
            <value>
                <fullName>Drop Trailer</fullName>
            </value>
            <value>
                <fullName>Return &amp; Refuel Vehicle</fullName>
            </value>
            <value>
                <fullName>Return Vehicle</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Work As Directed</fullName>
            </value>
            <value>
                <fullName>Clear Posting Box</fullName>
            </value>
            <value>
                <fullName>Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Scheduled Task</fullName>
            </value>
            <value>
                <fullName>Supervisory</fullName>
            </value>
            <value>
                <fullName>Vehicle Servicing</fullName>
            </value>
            <value>
                <fullName>Unscheduled Task</fullName>
            </value>
            <value>
                <fullName>Delivery, Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Unpaid Break</fullName>
            </value>
            <value>
                <fullName>Change Trailer</fullName>
                <isActive>false</isActive>
                <label>Change Trailer</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Collect (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Deliver</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Deliver (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Exchange</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Exchange (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Meal Break Paid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Paid</label>
            </value>
            <value>
                <fullName>Meal Break Unpaid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Unpaid</label>
            </value>
            <value>
                <fullName>Parcel Delivery</fullName>
                <isActive>false</isActive>
                <label>Parcel Delivery</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Collect</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Interim</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Interim</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Day_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Day_Start_Time__c</fullName>
    <description>Start Time with Next Day Job to allow sort to list Next Day Jobs at end</description>
    <formula>IF(Next_Day_Job__c, &apos;2&apos;,&apos;1&apos;) + &quot;-&quot; + IF(Len(Start_Time__c)&lt;4,&apos;0&apos; + Start_Time__c,Start_Time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day Start Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Dock_Number__c.field-meta.xml
<CustomField>
    <fullName>Dock_Number__c</fullName>
    <description>Dock number for the Job</description>
    <label>Dock Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The expected duration of the visit in minutes</description>
    <label>Duration (minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <default>true</default>
                <label>15</label>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>125</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Job_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Job_Instructions__c</fullName>
    <label>Job Instructions</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>TDF Enhance: Added lookup filter</description>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Job Templates (Site)</relationshipLabel>
    <relationshipName>Booking_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Location_Details__c.field-meta.xml
<CustomField>
    <fullName>Location_Details__c</fullName>
    <formula>Location__r.Name + BR() + 
Location__r.Street__c  + BR() + 
Location__r.City__c</formula>
    <label>Location Details</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Route_Template__c.field-meta.xml
<CustomField>
    <fullName>Route_Template__c</fullName>
    <label>Duty Template</label>
    <referenceTo>Route_Template__c</referenceTo>
    <relationshipLabel>Job Templates</relationshipLabel>
    <relationshipName>Job_Templates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Arrival time in 24hr clock format</description>
    <label>Start Time</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Site_Instruction_Notes__c.field-meta.xml
<CustomField>
    <fullName>Site_Instruction_Notes__c</fullName>
    <description>Brief searchable notes about the Location. Retrieved and displayed in the Transport mobile collect deliver flow.</description>
    <inlineHelpText>Brief searchable notes about the Location. Retrieved and displayed in the Transport mobile collect deliver flow.</inlineHelpText>
    <label>Site Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location/fields/Site_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Site_Instructions__c</fullName>
    <description>Detailed notes about the Location.  Retrieved and displayed in the Transport mobile collect deliver flow.</description>
    <inlineHelpText>Detailed notes about the Location.  Retrieved and displayed in the Transport mobile collect deliver flow.</inlineHelpText>
    <label>Site Instructions</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Route_Template__c/Route_Template__c.object-meta.xml
<CustomObject>
    <label>Duty Template</label>
    <nameField>
        <label>Duty Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duty Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TDF_DutyTemplatePrintControllerX.cls
public class TDF_DutyTemplatePrintControllerX {
//Controller for page TDF_DutyTemplatePrint
//Created 08-10-18 Andrew Judd
    public String dutyTemplateId{get;set;} 
    public List<Job_Template__c> jobTemplateList{get;set;}

	// Constructor    
    public TDF_DutyTemplatePrintControllerX(ApexPages.standardController sc){
        
        //Get Id
        dutyTemplateId = Apexpages.currentPage().getParameters().get('id');
        
        //Get file name for save default
        String fileName = [SELECT Name FROM Route_Template__c WHERE Id = :dutyTemplateId LIMIT 1].Name;      
        Apexpages.currentPage().getHeaders().put( 'content-disposition', 'inline; filename=' + fileName + '.pdf');            
        
        //Get list of jobs
        String query = ' SELECT Day_Start_Time__c, Start_Time__c, Activity_Type__c, Duration__c, Job_Instructions__c, ' + 
            			' Location__r.Name, Location_Details__c, Dock_Number__c, Route_Template__r.Name, ' + 
            			' Location__r.Site_Instruction_Notes__c, Location__r.Site_Instructions__c ' + 
            			' FROM Job_Template__c WHERE Route_Template__c = \'' + dutyTemplateId + '\'' + 
            			' ORDER BY Day_Start_Time__c ';
        
        jobTemplateList = Database.query(query);

    }
}