force-app/main/default/objects/Job_Template__c/Job_Template__c.object-meta.xml
<CustomObject>
    <label>Job Template</label>
    <nameField>
        <displayFormat>JT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Template__c/fields/Active_Route_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_Route_Days__c</fullName>
    <description>Days of the week the duty applies</description>
    <formula>IF(Route_Template__r.Monday__c,&quot;Mon &quot;,&quot;&quot;)+
IF(Route_Template__r.Tuesday__c,&quot;Tue &quot;,&quot;&quot;) + 
IF(Route_Template__r.Wednesday__c,&quot;Wed &quot;,&quot;&quot;) + 
IF(Route_Template__r.Thursday__c,&quot;Thu &quot;,&quot;&quot;) + 
IF(Route_Template__r.Friday__c,&quot;Fri &quot;,&quot;&quot;) + 
IF(Route_Template__r.Saturday__c,&quot;Sat &quot;,&quot;&quot;) +
IF(Route_Template__r.Sunday__c,&quot;Sun &quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Duty Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fit For Duty</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Collection</fullName>
                <default>true</default>
                <label>Delivery &amp; Collection</label>
            </value>
            <value>
                <fullName>Rest Break</fullName>
            </value>
            <value>
                <fullName>Prepare Vehicle</fullName>
            </value>
            <value>
                <fullName>Prepare Trailer</fullName>
            </value>
            <value>
                <fullName>Drop Trailer</fullName>
            </value>
            <value>
                <fullName>Return &amp; Refuel Vehicle</fullName>
            </value>
            <value>
                <fullName>Return Vehicle</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Work As Directed</fullName>
            </value>
            <value>
                <fullName>Clear Posting Box</fullName>
            </value>
            <value>
                <fullName>Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Scheduled Task</fullName>
            </value>
            <value>
                <fullName>Supervisory</fullName>
            </value>
            <value>
                <fullName>Vehicle Servicing</fullName>
            </value>
            <value>
                <fullName>Unscheduled Task</fullName>
            </value>
            <value>
                <fullName>Delivery, Collection &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Delivery &amp; Clearance</fullName>
            </value>
            <value>
                <fullName>Unpaid Break</fullName>
            </value>
            <value>
                <fullName>Change Trailer</fullName>
                <isActive>false</isActive>
                <label>Change Trailer</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Collect (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Deliver</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Deliver (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Handover Vehicle - Exchange</fullName>
                <isActive>false</isActive>
                <label>Handover Vehicle - Exchange (DO NOT USE)</label>
            </value>
            <value>
                <fullName>Meal Break Paid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Paid</label>
            </value>
            <value>
                <fullName>Meal Break Unpaid</fullName>
                <isActive>false</isActive>
                <label>Meal Break Unpaid</label>
            </value>
            <value>
                <fullName>Parcel Delivery</fullName>
                <isActive>false</isActive>
                <label>Parcel Delivery</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Collect</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Collect</label>
            </value>
            <value>
                <fullName>Prepare Vehicle - Interim</fullName>
                <isActive>false</isActive>
                <label>Prepare Vehicle - Interim</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Dock_Number__c.field-meta.xml
<CustomField>
    <fullName>Dock_Number__c</fullName>
    <description>Dock number for the Job</description>
    <label>Dock Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The expected duration of the visit in minutes</description>
    <label>Duration (minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <default>true</default>
                <label>15</label>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>125</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Job_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Job_Instructions__c</fullName>
    <label>Job Instructions</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>TDF Enhance: Added lookup filter</description>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Job Templates (Site)</relationshipLabel>
    <relationshipName>Booking_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Route_Template__c.field-meta.xml
<CustomField>
    <fullName>Route_Template__c</fullName>
    <label>Duty Template</label>
    <referenceTo>Route_Template__c</referenceTo>
    <relationshipLabel>Job Templates</relationshipLabel>
    <relationshipName>Job_Templates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Template__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Arrival time in 24hr clock format</description>
    <label>Start Time</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Site_Instruction_Notes__c.field-meta.xml
<CustomField>
    <fullName>Site_Instruction_Notes__c</fullName>
    <description>Brief searchable notes about the Location. Retrieved and displayed in the Transport mobile collect deliver flow.</description>
    <inlineHelpText>Brief searchable notes about the Location. Retrieved and displayed in the Transport mobile collect deliver flow.</inlineHelpText>
    <label>Site Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location/fields/Site_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Site_Instructions__c</fullName>
    <description>Detailed notes about the Location.  Retrieved and displayed in the Transport mobile collect deliver flow.</description>
    <inlineHelpText>Detailed notes about the Location.  Retrieved and displayed in the Transport mobile collect deliver flow.</inlineHelpText>
    <label>Site Instructions</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Location/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Route_Template__c/Route_Template__c.object-meta.xml
<CustomObject>
    <label>Duty Template</label>
    <nameField>
        <label>Duty Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duty Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Template__c/fields/Active_Route_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_Route_Days__c</fullName>
    <description>Days of the week the route is performed</description>
    <formula>IF(Monday__c, &quot;Mon &quot;,&quot;&quot;) + 
IF(Tuesday__c, &quot;Tue &quot;,&quot;&quot;) + 
IF(Wednesday__c, &quot;Wed &quot;,&quot;&quot;) + 
IF(Thursday__c, &quot;Thu &quot;,&quot;&quot;) + 
IF(Friday__c, &quot;Fri &quot;,&quot;&quot;) + 
IF(Saturday__c, &quot;Sat &quot;,&quot;&quot;) + 
IF(Sunday__c, &quot;Sun &quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Duty Days</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDF_DutyTemplatePrintControllerY.cls
/**
 * @author Emmanuel Yap
 * @date 2021-09-10
 * @description Controller class for Print Duty Template
 * @changelog
 * 2021-09-10 - Emmanuel Yap - Created
*/

public class TDF_DutyTemplatePrintControllerY {

    private String dutyTemplateId{get;set;} 
    private List<Job_Template__c> jtlist{get;set;}
    public Route_Template__c routeTemplate{get;set;}
    public List<JobTemplateWrapper> jobTemplateList{get;set;}
    public List<BreakWrapper> breakList{get;set;}
    public String startTime{get;set;}
    public String endTime{get;set;}
    
	// Constructor    
    public TDF_DutyTemplatePrintControllerY(ApexPages.standardController sc){
        Boolean startTimeSet = false;
        //Get Id
        startTime = '';
        endTime = '';
        breakList = new List<BreakWrapper>();
        jobTemplateList = new List<JobTemplateWrapper>();
        dutyTemplateId = Apexpages.currentPage().getParameters().get('id').escapeHtml4();
        
        //Get file name for save default
        routeTemplate = TDF_RouteTemplateUtil.getRouteTemplateFromID(dutyTemplateId);
        String fileName = routeTemplate.Name;      
        Apexpages.currentPage().getHeaders().put( 'content-disposition', 'inline; filename=' + fileName + '.pdf');            
        
        jtlist = TDF_RouteTemplateUtil.getJobTemplateFromDutyTemplateId(dutyTemplateId);
        for(Job_Template__c jt : jtlist){
            JobTemplateWrapper wrapper =  new JobTemplateWrapper(jt);
            if(!startTimeSet){
                startTime = wrapper.arrive;
                startTimeSet = true;
            }
            endTime = wrapper.depart;
            jobTemplateList.add(wrapper);
        }
        for(Job_Template__c jt : jtlist){
            if(jt.Activity_Type__c == 'Rest Break'){
                BreakWrapper breakWrapper = new  BreakWrapper(jt);
                breakWrapper.active = breakWrapper.active + ' ' + startTime + ' - ' +endTime;
                breakList.add(breakWrapper);
            }
        }
        
    }

    public class JobTemplateWrapper {
        public Job_Template__c jt {get; set;}
        public String arrive {get; set;}
        public String location {get; set;}
        public String address {get; set;}
        public String activity {get; set;}
        public String docks {get; set;}
        public String depart {get; set;}
        public String jobInstructions {get;set;}
        public String siteInstructionNotes {get;set;}
        public String siteInstructions {get;set;}
        
        //This is the contructor method. When we create a new wrapAccount object we pass a Account that is set to the acc property. We also set the selected value to false
        public JobTemplateWrapper(Job_Template__c a) {
            jt = a;
            arrive = a.Start_Time__c;
            location = a.Location__r.Name;
            address = a.Location__r.Street__c + ' ' + a.Location__r.City__c;
            activity = a.Activity_Type__c;
            docks = a.Dock_Number__c;

            Time departTime = Time.newInstance(
                                Integer.valueOf(a.Start_Time__c.substring(0,2)),
                                Integer.valueOf(a.Start_Time__c.substring(2))
                                ,0,0);

            departTime = departTime.addMinutes(Integer.valueOf(a.Duration__c));

            depart = String.valueOf(departTime).substring(0,2) 
                   + String.valueOf(departTime).substring(3,5);
            jobInstructions = a.Job_Instructions__c;
            siteInstructionNotes = a.Location__r.Site_Instruction_Notes__c;
            siteInstructions = a.Location__r.Site_Instructions__c;
        }
    } 

    public class BreakWrapper {
        public Job_Template__c jt {get; set;}
        public String breakTime {get; set;}
        public String location {get; set;}
        public String active {get; set;}
        public String activity {get; set;}
        
        //This is the contructor method. When we create a new wrapAccount object we pass a Account that is set to the acc property. We also set the selected value to false
        public BreakWrapper(Job_Template__c a) {
            jt = a;
            breakTime = a.Start_Time__c;
            location = a.Location__r.Name;
            active = a.Route_Template__r.Active_Route_Days__c;
            activity = a.Activity_Type__c;
            Time departTime = Time.newInstance(
                                Integer.valueOf(a.Start_Time__c.substring(0,2)),
                                Integer.valueOf(a.Start_Time__c.substring(2))
                                ,0,0);

            departTime = departTime.addMinutes(Integer.valueOf(a.Duration__c));

            breakTime = a.Start_Time__c.substring(0,2) 
                      + ':' + a.Start_Time__c.substring(2) 
                      + ' - ' + String.valueOf(departTime).substring(0,2) 
                      + ':' + String.valueOf(departTime).substring(3,5);
        }
    } 
}