force-app/main/default/objects/BAMExternalOnboardingRequest__c/BAMExternalOnboardingRequest__c.object-meta.xml
<CustomObject>
    <description>This object stores a record of each Merchant Portal onboarding request sent to Camunda and its current status. This provides the ability to view the status of requests.  This data is also used to determine if there have been changes to a Contact Application Role or Linked Entity since the last successfully processed request.</description>
    <label>External Onboarding Request</label>
    <nameField>
        <displayFormat>BEOR-{000000}</displayFormat>
        <label>External Onboarding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Onboarding Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMExternalOnboardingRequest__c/fields/Response_Payload__c.field-meta.xml
<CustomField>
    <fullName>Response_Payload__c</fullName>
    <description>A copy of the response payload returned from Camunda</description>
    <label>Response Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ExternalOnboardingRequestSelector_Test.cls
/**
* @author Nathan Franklin
* @date 2021-01-12
* @group Tests
* @tag Selector
* @tag External Object SObject
* @domain Core
* @description A very simple selector class that sits in the base domain
* @changelog
* 2021-05-12 - Shashwat.Nath@auspost.com.au - Created
*/
@IsTest
public with sharing class ExternalOnboardingRequestSelector_Test{
    /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectString() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();

        ExternalOnboardingRequestSelector selector = ExternalOnboardingRequestSelector.newInstance();
        QueryBuilder qb = selector.newQueryBuilder();
        String soql = qb.toSoqlString();

        System.assertEquals(true, Pattern.compile('(?ism)\\bfrom BAMExternalOnboardingRequest__c\\b').matcher(soql).find(), 'Resulting query does not select from External Onboarding Object');

        Test.stopTest();

    }

    
    /**
     * Executes a query to ensure it returns expected results with actual inserted data
     */
    @IsTest
    public static void testSelectorIntegration() {

        // =====================================
        // Data Preparation
        // =====================================
        MockUtility.disableTriggerExecution();

        BAMExternalOnboardingRequest__c externalOnboardingRecord = ApplicationTestDataFactory.getBAMExternalOnboardingRequests(1,null, null, false)[0];
        insert externalOnboardingRecord; 
        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();
        
        ExternalOnboardingRequestSelector selector = ExternalOnboardingRequestSelector.newInstance(1);
        Map<Id, BAMExternalOnboardingRequest__c > results = selector.selectById(new Set<Id>{externalOnboardingRecord.id});
        System.assertEquals(1, results.size(), 'Result count was wrong');

        Test.stopTest();

    }
    
      /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectStringWithFieldOverrides() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();
        ExternalOnboardingRequestSelector selector1 = ExternalOnboardingRequestSelector.newInstance(0, new Set<SObjectField>{BAMExternalOnboardingRequest__c.Response_Payload__c});

        ExternalOnboardingRequestSelector   selector = ExternalOnboardingRequestSelector.newInstance(0, new Map<SObjectType, Set<SObjectField>>{
                BAMExternalOnboardingRequest__c.SObjectType => new Set<SObjectField>{BAMExternalOnboardingRequest__c.Response_Payload__c}
        });
        QueryBuilder qb = selector.newQueryBuilder();
        String soql = qb.toSoqlString();
        System.assertEquals(true, Pattern.compile('(?ism)Response_Payload__c.*?\\bfrom BAMExternalOnboardingRequest__c\\b').matcher(soql).find(), 'Resulting query does not select payload field: ' + soql);

        Test.stopTest();

    }
}