force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{00000000}</displayFormat>
        <label>Compensation Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/CurrentArticleId__c.field-meta.xml
<CustomField>
    <fullName>CurrentArticleId__c</fullName>
    <description>Stores the article id from Case as static value to track the article that the compensation record was intended for</description>
    <label>Current Article Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Money Order Number</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Contact Customer for Proof of Value</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>EFT Cancelled</fullName>
            </value>
            <value>
                <fullName>Alternate Compensation</fullName>
            </value>
            <value>
                <fullName>EFT Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>Approved Awaiting Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/recordTypes/EFT.recordType-meta.xml
<RecordType>
    <fullName>EFT</fullName>
    <active>true</active>
    <description>Compensation type for Electronic Fund Transfer</description>
    <label>EFT</label>
</RecordType>

force-app/main/default/classes/CompensationService_Test.cls
/***
 * @author Hasantha Liyanage
 * @date 2023-07-25
 * @domain Core
 * @description Test class for CompensationService
 * @changelog
 * 2023-07-25 - Hasantha Liyanage - Created
 */
@IsTest
private class CompensationService_Test {

    @IsTest
    static void updateCurrentArticleInfoOnCompensationRecord() {
        List<Case> cases = ApplicationTestDataFactory.getCases(1, 'REF0001', true);
        String recordTypeId = Schema.SObjectType.Compensation__c.getRecordTypeInfosByName().get('EFT').getRecordTypeId();
        List<Compensation__c> compensations = ApplicationTestDataFactory.getCompensation(1, cases[0].Id, recordTypeId, true);

        CasesSelector mockCasesSelector = (CasesSelector) MockUtility.mockSelector(CasesSelector.class);
        // set up our responses
        MockUtility.Mocks.startStubbing();
        MockUtility.Mocks.when(mockCasesSelector.selectById((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(new Map<Id, Case>{
                cases[0].Id => cases[0]
        });
        MockUtility.Mocks.stopStubbing();

        Test.startTest();
        CompensationService.getInstance().updateCurrentArticleInfoOnCompensationRecord(compensations);
        Test.stopTest();
        System.assertEquals(
                'REF0001',
                compensations[0].CurrentArticleId__c,
                'updateCurrentArticleInfoOnCompensationRecord : Current Article field should be updated'
        );
    }

    @IsTest
    static void approveCompensationRecord() {
        List<Case> cases = ApplicationTestDataFactory.getCases(1, 'REF0001', true);
        String recordTypeId = Schema.SObjectType.Compensation__c.getRecordTypeInfosByName().get('EFT').getRecordTypeId();
        List<Compensation__c> compensations = ApplicationTestDataFactory.getCompensation(1, cases[0].Id, recordTypeId, true);
        Compensation__c compensation = compensations[0];
        compensation.Status__c = 'APPROVED';
        Compensation__c oldCompensation = compensation.clone(true, true, false, false);
        oldCompensation.Status__c = 'PENDING';
        oldCompensation.Approved__c = false;
        Map<Id, Compensation__c> existingRecords = new Map<Id, Compensation__c>{
                oldCompensation.Id => oldCompensation
        };

        Test.startTest();
        CompensationService.getInstance().approveCompensationRecord(compensations, existingRecords);
        Test.stopTest();
        System.assertEquals(
                true,
                compensations[0].Approved__c,
                'approveCompensationRecord : Approved field should be marked true'
        );
    }
}