force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Is_APPC__c.field-meta.xml
<CustomField>
    <fullName>Is_APPC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is APPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Discretionary</fullName>
            </value>
            <value>
                <fullName>Discretionary Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Approval__c/Credit_Approval__c.object-meta.xml
<CustomObject>
    <description>Object used by the Customer Relations Team to summarise credit amounts for product family approvals</description>
    <label>Credit Approval</label>
    <nameField>
        <displayFormat>CA-{0000000000}</displayFormat>
        <label>Credit Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Approval__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Credit Approvals</relationshipLabel>
    <relationshipName>Credit_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Approval__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Credit_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the credit adjustment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval Decision</fullName>
            </value>
            <value>
                <fullName>Pending Approval Signatures</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Approval__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Discretionary</fullName>
            </value>
            <value>
                <fullName>Discretionary Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/Disputed_Item__c.object-meta.xml
<CustomObject>
    <description>Used to disputed items  in a dispute case</description>
    <label>Disputed Item</label>
    <nameField>
        <displayFormat>DI-{0000000000}</displayFormat>
        <label>Disputed Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disputed Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disputed_Item__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Disputed Items</relationshipLabel>
    <relationshipName>Disputed_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Disputed Items</relationshipLabel>
    <relationshipName>Disputed_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/fields/Credit_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Approval</label>
    <referenceTo>Credit_Approval__c</referenceTo>
    <relationshipLabel>Disputed Items</relationshipLabel>
    <relationshipName>Disputed_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/fields/Is_APPC__c.field-meta.xml
<CustomField>
    <fullName>Is_APPC__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Is APPC</label>
	<description>Is this related to an APPC product?</description>
	<inlineHelpText>Is this related to an APPC product?</inlineHelpText>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New = Currently under investigation 

Verified Claim = Customer has provided enough evidence to support claim

Invalid Claim = Customer has not provided enough information to support claim

Rejected = Customers claim does not meet criteria</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Verified Claim</fullName>
            </value>
            <value>
                <fullName>Invalid Claim</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
                <isActive>false</isActive>
                <label>Submitted For Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disputed_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Pick list to distinguish whether the credit is discretionary or not</description>
    <label>Credit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Discretionary</fullName>
            </value>
            <value>
                <fullName>Discretionary Credit</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
                <isActive>false</isActive>
                <label>Adjustment</label>
            </value>
            <value>
                <fullName>Ex Gratia</fullName>
                <isActive>false</isActive>
                <label>Ex Gratia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdjustmentModuleTest.cls
/**
 * @description
 * Test class for Module to handle Adjustment__c object functionality
 * @author Pratyush Chalasani
 * @group Domain
 * @domain Adjustment
 * @changelog
 * 2023-06-28 - Pratyush Chalasani - Created
 *
 */
@isTest
private class AdjustmentModuleTest {
    @isTest
	static void test_AfterInsert() {
		// =====================================
		// Data Preparation
		// =====================================
		Case testCase = ApplicationTestDataFactory.getCases(1, true)[0];

		testCase.AccountId = fflib_IDGenerator.generate(Account.getSObjectType());

		Disputed_Item__c testDI = ApplicationTestDataFactory.getDisputedItems(1, testCase.Id, true)[0];

		testDi.Case__c = testCase.Id;
		testDi.Is_APPC__c = 'Yes';
		testDi.Status__c = 'Verified Claim';
		testDi.Type__c = 'Discretionary Credit';

		Credit_Approval__c testCA = ApplicationTestDataFactory.getCreditApprovals(1, true)[0];

		testCA.Case__c = testCase.Id;
		testCA.Status__c = 'Approved';
		testCA.Type__c = 'Discretionary Credit';

		testCase = (Case)ApplicationTestDataFactory.setChildRelationships(testCase, new Map<String, List<SObject>>{
			'Credit_Adjustments__r' => new List<SObject>{testCA},
			'Disputed_Items__r' => new List<SObject>{testDI}
		});

		Adjustment__c testAdjustment = ApplicationTestDataFactory.getAdjustments(1, testCase.Id, true)[0];

		testAdjustment.Type__c = 'Discretionary Credit';

		// =====================================
		// Stubbing
		// =====================================
		CasesSelector mockCasesSelector = (CasesSelector)MockUtility.mockSelector(CasesSelector.class);

		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockCasesSelector.selectByIdWithCreditAapprovalsAndDisputedItems(new Set<Id>{testCase.Id}, null)).thenReturn(new Map<Id, Case>{testCase.Id => testCase});
		MockUtility.Mocks.when(mockUow.registerDirty((List<SObject>)fflib_Match.anyObject(), (Boolean)fflib_Match.eq(true), (String)fflib_Match.eq(AdjustmentModule.class.getName()))).thenAnswer(new MockUtility.AnswerGenericRegisterUnitOfWorkDML());
		MockUtility.Mocks.stopStubbing();
		
		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		AdjustmentModule module = AdjustmentModule.newInstance();

		module.onAfterInsert(new List<Adjustment__c>{testAdjustment}, mockUow);

		Test.stopTest();
		
		System.assertEquals(3, MockUtility.mockUnitOfWorkDMLs.size());
		
		System.assertEquals(true, ((Adjustment__c)MockUtility.mockUnitOfWorkDMLs[0]).Is_APPC__c, 'Is APPC flag should be carried over from Disputed Item');
		System.assertEquals(testAdjustment.Id, ((Disputed_Item__c)MockUtility.mockUnitOfWorkDMLs[1]).Adjustment__c, 'Disputed Item should be linked to Adjustment');
		System.assertEquals(testAdjustment.Id, ((Credit_Approval__c)MockUtility.mockUnitOfWorkDMLs[2]).Adjustment__c, 'Credit Approval should be linked to Adjustment');
	}

	@isTest
	static void test_AfterUpdate() {
		// =====================================
		// Data Preparation
		// =====================================
		Case testCase = ApplicationTestDataFactory.getCases(1, true)[0];

		testCase.AccountId = fflib_IDGenerator.generate(Account.getSObjectType());

		Disputed_Item__c testDI = ApplicationTestDataFactory.getDisputedItems(1, testCase.Id, true)[0];

		testDi.Case__c = testCase.Id;
		testDi.Is_APPC__c = 'Yes';
		testDi.Status__c = 'Verified Claim';
		testDi.Type__c = 'Discretionary Credit';

		Credit_Approval__c testCA = ApplicationTestDataFactory.getCreditApprovals(1, true)[0];

		testCA.Case__c = testCase.Id;
		testCA.Status__c = 'Approved';
		testCA.Type__c = 'Discretionary Credit';

		testCase = (Case)ApplicationTestDataFactory.setChildRelationships(testCase, new Map<String, List<SObject>>{
			'Credit_Adjustments__r' => new List<SObject>{testCA},
			'Disputed_Items__r' => new List<SObject>{testDI}
		});

		Adjustment__c testAdjustment = ApplicationTestDataFactory.getAdjustments(1, testCase.Id, true)[0];

		testAdjustment.Type__c = 'Discretionary Credit';

		Adjustment__c oldAdjustment = testAdjustment.clone(true, true, true, true);

		oldAdjustment.Case__c = null;

		// =====================================
		// Stubbing
		// =====================================
		CasesSelector mockCasesSelector = (CasesSelector)MockUtility.mockSelector(CasesSelector.class);

		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockCasesSelector.selectByIdWithCreditAapprovalsAndDisputedItems(new Set<Id>{testCase.Id}, null)).thenReturn(new Map<Id, Case>{testCase.Id => testCase});
		MockUtility.Mocks.when(mockUow.registerDirty((List<SObject>)fflib_Match.anyObject(), (Boolean)fflib_Match.eq(true), (String)fflib_Match.eq(AdjustmentModule.class.getName()))).thenAnswer(new MockUtility.AnswerGenericRegisterUnitOfWorkDML());
		MockUtility.Mocks.stopStubbing();
		
		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		AdjustmentModule module = AdjustmentModule.newInstance();

		module.onAfterUpdate(new List<Adjustment__c>{testAdjustment}, new Map<Id, Adjustment__c>{oldAdjustment.Id => oldAdjustment}, mockUow);

		Test.stopTest();
		
		System.assertEquals(3, MockUtility.mockUnitOfWorkDMLs.size());
		
		System.assertEquals(true, ((Adjustment__c)MockUtility.mockUnitOfWorkDMLs[0]).Is_APPC__c, 'Is APPC flag should be carried over from Disputed Item');
		System.assertEquals(testAdjustment.Id, ((Disputed_Item__c)MockUtility.mockUnitOfWorkDMLs[1]).Adjustment__c, 'Disputed Item should be linked to Adjustment');
		System.assertEquals(testAdjustment.Id, ((Credit_Approval__c)MockUtility.mockUnitOfWorkDMLs[2]).Adjustment__c, 'Credit Approval should be linked to Adjustment');
	}
}