force-app/main/default/objects/Callback_Request_Settings__mdt/Callback_Request_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for Callback Request</description>
    <label>Callback Request Settings</label>
    <pluralLabel>Callback Request Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Callback_Request_Settings__mdt/fields/Case_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Queue_Name__c</fullName>
    <description>Queue name from cases will be added to criteria for Callback Request</description>
    <label>Case Queue Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callback_Request_Settings__mdt/fields/CaseStatus__c.field-meta.xml
<CustomField>
    <fullName>CaseStatus__c</fullName>
    <inlineHelpText>Case Status to verify for SLA</inlineHelpText>
    <label>CaseStatus</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callback_Request_Settings__mdt/fields/Enquiry_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Type__c</fullName>
    <inlineHelpText>use comma to add multiple value</inlineHelpText>
    <label>Enquiry Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callback_Request_Settings__mdt/fields/Initial_SLA_in_Hours__c.field-meta.xml
<CustomField>
    <fullName>Initial_SLA_in_Hours__c</fullName>
    <label>Initial SLA in Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Callback_Request_Settings__mdt/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>User comma &quot;,&quot; to add more than once value</inlineHelpText>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <formula>IMAGE( 
CASE(RecordType.Name,
&apos;Transit Warranty Claim&apos;, &apos;/resource/StarTrackCaseIcons/Transit.png&apos;, 
&apos;Sales Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Sales.png&apos;, 
&apos;Pickup Booking Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Pickup.png&apos;,
&apos;Credit Dispute Claim&apos;, &apos;/resource/StarTrackCaseIcons/Credit.png&apos;,
&apos;Delivery Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Delivery.png&apos;,
&apos;General Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/General.png&apos;,
&apos;StarTrack Business Solutions Communications&apos;, &apos;/resource/StarTrackCaseIcons/BSCEmail.png&apos;, &apos;/resource/StarTrackCaseIcons/Other.png&apos;),&apos;No Image&apos; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseOriginator__c.field-meta.xml
<CustomField>
    <fullName>CaseOriginator__c</fullName>
    <description>SSSW</description>
    <label>Case Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Sender</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Addressee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ResolutionCode__c.field-meta.xml
<CustomField>
    <fullName>ResolutionCode__c</fullName>
    <description>SSSW.</description>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acknowledge Feedback</fullName>
            </value>
            <value>
                <fullName>API Issue</fullName>
            </value>
            <value>
                <fullName>Apology</fullName>
            </value>
            <value>
                <fullName>Assistance provided</fullName>
                <default>true</default>
                <label>Assistance provided</label>
            </value>
            <value>
                <fullName>Assistance Provided - Other Team</fullName>
            </value>
            <value>
                <fullName>Basket Size Under $25</fullName>
            </value>
            <value>
                <fullName>BesC</fullName>
            </value>
            <value>
                <fullName>BesS</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled - Duplicate</fullName>
            </value>
            <value>
                <fullName>Cancelled - No Longer Required</fullName>
            </value>
            <value>
                <fullName>Close Account</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Resolved by Advocate</fullName>
            </value>
            <value>
                <fullName>Closed - Resolved by VOC</fullName>
            </value>
            <value>
                <fullName>Closed - Spam</fullName>
            </value>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Education</fullName>
            </value>
            <value>
                <fullName>Customer – no response</fullName>
            </value>
            <value>
                <fullName>Customer – response, no further action</fullName>
            </value>
            <value>
                <fullName>Customer – Self service</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Delay In Receiving</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Exgratia</fullName>
            </value>
            <value>
                <fullName>FCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SLAforCasesTest.cls
@IsTest (IsParallel=true)
public class SLAforCasesTest {

    @TestSetup
    static void setup(){
        
         //.. Get Custom Metadata for Callback Settings.
		Callback_Request_Settings__mdt callbackMdt = [SELECT CaseStatus__c,Case_Queue_Name__c, Initial_SLA_in_Hours__c, Case_Type__c, Enquiry_Sub_Type__c, Product_Category__c
                                                      FROM Callback_Request_Settings__mdt 
                                                      WHERE QualifiedApiName = 'Callback_Request_Settings'];
		
        String sProduct = callbackMdt.Product_Category__c.Split(',')[0];
        /*** Create Case record records. */
        Case cs = new Case();
        cs.RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSSW General Enquiry').getRecordTypeId();
        cs.BusinessHoursId=[SELECT Id FROM BusinessHours WHERE Name='SSSWSydney'].Id;
        cs.Type = callbackMdt.Case_Type__c;
        cs.CaseOriginator__c = 'Sender';
        cs.Origin = SSSWConstants.CASE_ORIGIN;
        cs.ProductCategory__c = sProduct;
        cs.ProductSubCategory__c = callbackMdt.Enquiry_Sub_Type__c;
        cs.Priority = SSSWConstants.CASE_PRIORITY;
        cs.Subject='Testing 5 Days SLA';
        cs.Status= callbackMdt.CaseStatus__c;
        cs.OwnerId = [SELECT Id, QueueId FROM QueueSobject WHERE Queue.Name='SSSW Network Queue'].QueueId;
        cs.ResolutionCode__c = 'Assistance provided';
		cs.EnquirySubType__c = SSSWConstants.CASE_ENQUIRY_SUBTYPE;
        insert cs;
    }

    @IsTest
    public static void SLAforCasesBatchTest(){
		Test.startTest();
        SLAforCases slac = new SLAforCases();
		Database.executeBatch(slac);
        Test.stopTest();
    }
}