force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JN-{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Delivery_Depot__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Depot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Network__c.SSSE_Email__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Only SSSE depots are listed</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Jobs (Delivery Depot)</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Job__c/PUD_Job__c.object-meta.xml
<CustomObject>
    <description>Job sent to the dispatch system</description>
    <label>Job</label>
    <nameField>
        <displayFormat>PJ-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Job__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The network related to the pickup job</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Pickup Booking Jobs</relationshipLabel>
    <relationshipName>Pickup_Booking_Job</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Route__c/PUD_Route__c.object-meta.xml
<CustomObject>
    <description>Route definition for Pickup and Delivery booking system</description>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PUD_AdhocJobsfromListViewControllerX.cls
/**
* @author Dheeraj Mandavilli
* @date 2019-11-28
* @group PUD Project
* @tag Controller
* @tag PUD_Job__c
* @domain Interoperability PUD Project
* @description Controller class to fectch adhoc job records from PUD_Job__c object.
* NOTE: This class is used by PUD_AdhocJobsPrint VF Page upon clicking "Print Adhoc Jobs" from Routes List View Page. 
* 2019-11-28 - Dheeraj Mandavilli - Created
* 2020-05-25 - Dheeraj Mandavilli - Refactored the Logic to Fetch Depot Id from Logged in User
* 2020-06-10 - Dheeraj Mandavilli - Included Time of Print Logic.
 * 2022-07-12 - Kamil Szyc - refactor the controller to use selectors and meet requirements of CUS-72
*/
public with sharing class PUD_AdhocJobsfromListViewControllerX {
	public List<PUD_Route__c> routes {get;set;}
	// Constructor    
	public PUD_AdhocJobsfromListViewControllerX(ApexPages.StandardSetController ssc){
		routes = new List<PUD_Route__c>();
		Set<String> groupNameSet = new Set<String>();

		for(GroupMember objCGM : (List<GroupMember>) GroupMembersSelector.newInstance().getMyGroups(new List<String>(),new Set<Object>{GroupMembersSelector.Options.WITH_GROUP},false)){
			groupNameSet.add(objCGM.Group.Name);
		}

		for(PUD_Route__c route :  PUDRoutesSelector.newInstance(PUD_AdhocJobsPrintfromRouteControllerX.jobPrintFieldOverrides).selectByIdWithJobs(
				new Map<Id, PUD_Route__c>( (PUD_Route__c[])ssc.getSelected()).keySet(),
				new Set<String>{PUDConstants.PUD_BOOKING_RECORD_TYPE_AD_HOC_PICKUP_DELIVERY},
				new Set<Date>{Date.today()
				},
				new Map<Id,Network__c>(NetworksSelector.newInstance().selectByName(groupNameSet)).keySet(),
				new Set<Object>{
						PUDRoutesSelector.Options.WITH_DEPOT, PUDRoutesSelector.Options.LIMIT_TO_MY_GROUPS_ONLY
				})){
			if(!route.Jobs__r.isEmpty()){
				routes.add(route);
			}
		}

	}
}