force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JN-{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Delivery_Depot__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Depot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Network__c.SSSE_Email__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Only SSSE depots are listed</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Jobs (Delivery Depot)</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Integrated_Job_Dispatch_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Integrated_Job_Dispatch_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the network is eligible for integration with dispatch system for PUD Pickup and Delivery Jobs booked via the booking system. If eligible, Pickup and Delivery Jobs serviced by this network are sent to dispatch system via integration.</description>
    <inlineHelpText>Indicates the network is eligible for integration with dispatch system for PUD Pickup and Delivery Jobs booked via the booking system. If eligible, Pickup and Delivery Jobs serviced by this network are sent to dispatch system via integration.</inlineHelpText>
    <label>Integrated Job Dispatch Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/ORG_UNIT_ADDR_2__c.field-meta.xml
<CustomField>
    <fullName>ORG_UNIT_ADDR_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/ORG_UNIT_ADDR_3__c.field-meta.xml
<CustomField>
    <fullName>ORG_UNIT_ADDR_3__c</fullName>
    <externalId>true</externalId>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PUD_Booking__c/PUD_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BK-{000000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Booking__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Depot responsible for the booking</description>
    <inlineHelpText>Business hub responsible for the booking</inlineHelpText>
    <label>Depot</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only a Business Hub or Delivery network can be selected as a depot.</errorMessage>
        <filterItems>
            <field>Network__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Hub_3</value>
        </filterItems>
        <filterItems>
            <field>Network__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Delivery_1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Bookings (Depot)</relationshipLabel>
    <relationshipName>Managed_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Booking__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The network to collect from / deliver to, depending on the booking record type.</description>
    <inlineHelpText>The network to collect from / deliver to, depending on the booking record type.</inlineHelpText>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Booking__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <description>Common address field on Booking. Required for Search. Set via:
-trigger on Booking (update of Booking Location)
-trigger on Booking Location (update of address)
-via API for bookings without location</description>
    <label>Post Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PUD_Booking__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Common address field on Booking. Required for Search. Set via:
-trigger on Booking (update of Booking Location)
-trigger on Booking Location (update of address)
-via API for bookings without location</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PUD_Booking_Location__c/PUD_Booking_Location__c.object-meta.xml
<CustomObject>
    <description>Physical location for a pickup booking</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Booking_Location__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipName>Booking_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Booking_Location__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <label>Post Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PUD_Booking_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PUD_Container__c/PUD_Container__c.object-meta.xml
<CustomObject>
    <description>Object to store container types, expected, actual containers against booking and job. Child containers will be updated by depot supervisor and MobileStar integration.</description>
    <label>Container</label>
    <nameField>
        <displayFormat>CN-{00000}</displayFormat>
        <label>Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Container__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Parent booking for child containers</description>
    <inlineHelpText>Parent booking for child containers</inlineHelpText>
    <label>Booking</label>
    <referenceTo>PUD_Booking__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PUD_Container__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>Condition of container</description>
    <inlineHelpText>Condition of container</inlineHelpText>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Empty</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PUD_Container__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Job associated with containers</description>
    <inlineHelpText>Job associated with containers</inlineHelpText>
    <label>Job</label>
    <referenceTo>PUD_Job__c</referenceTo>
    <relationshipLabel>Containers</relationshipLabel>
    <relationshipName>Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Container__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Specify type of container</description>
    <inlineHelpText>Specify type of container</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aircan</fullName>
            </value>
            <value>
                <fullName>Cage</fullName>
            </value>
            <value>
                <fullName>Cardboard ULD</fullName>
            </value>
            <value>
                <fullName>Colby</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>ULD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PUD_Job__c/PUD_Job__c.object-meta.xml
<CustomObject>
    <description>Job sent to the dispatch system</description>
    <label>Job</label>
    <nameField>
        <displayFormat>PJ-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PUD_Job__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Parent booking job was created from</description>
    <label>Booking</label>
    <referenceTo>PUD_Booking__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PUD_Job__c/fields/Booking_Location__c.field-meta.xml
<CustomField>
    <fullName>Booking_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>PUD_Booking_Location__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Job__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Jobs (Depot)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Job__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The network related to the pickup job</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Pickup Booking Jobs</relationshipLabel>
    <relationshipName>Pickup_Booking_Job</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PUD_Job__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <label>Post Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PUDContainerTypeSyncModule_Test.cls
/**
 * @description Test class for PUDContainerTypeSyncModule
 * @author Dattaraj Deshmukh
 * @date 2022-07-25
 * @group Tests
 * @domain PUD
 * @changelog
 * 2022-07-25 - Dattaraj Deshmukh - Created
  */

@IsTest
private class PUDContainerTypeSyncModule_Test {
	
	
	@IsTest
	public static void testEnsureAfterDeleteContainer() {
		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(PUDContainerTriggerHandler.getUnitOfWorkSObjectTypes());

		List<PUD_Booking__c> pudBookingList = PUDTestDataFactory.getPUDPermanentPickupDeliveryBookings(1, null, null, Date.today(), Date.today().addDays(30), null, true);
		List<PUD_Job__c> jobs = PUDTestDataFactory.getPUDJobs(6, pudBookingList[0].Id, PUDConstants.PUD_JOB_STATUS_NEW, true);
		
		//associate jobs with bookings
		pudBookingList[0] = (PUD_Booking__c)ApplicationTestDataFactory.setChildRelationships(pudBookingList[0], new Map<String, List<SObject>>{'Jobs__r' => jobs});

		//create a booking container
		PUD_Container__c bookingContainer = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Pallets', 'Empty', true )[0];

		//associating containers with bookings.
		pudBookingList[0] = (PUD_Booking__c)ApplicationTestDataFactory.setChildRelationships(pudBookingList[0], new Map<String, List<SObject>>{'Containers__r' => new List<SObject>{bookingContainer}});

		//create a job container and associated it with jobs
		PUD_Container__c jobContainer = PUDTestDataFactory.getPUDJobContainers(1, pudBookingList[0].Id, jobs[0].Id, 'Pallets', 'Empty', true )[0];
		jobs[0] = (PUD_Job__c)ApplicationTestDataFactory.setChildRelationships(jobs[0], new Map<String, List<SObject>>{'Containers__r' => new List<SObject>{jobContainer}});


		// =====================================
		// Stubbing
		// =====================================
		PUDUtility mockPUDUtil = (PUDUtility) MockUtility.mockUtility(PUDUtility.class);
		PUDBookingsSelector mockBookingSelector = (PUDBookingsSelector)MockUtility.mockSelector(PUDBookingsSelector.class);
		PUDJobsSelector mockJobSelector = (PUDJobsSelector)MockUtility.mockSelector(PUDJobsSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(mockBookingSelector.selectById((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(pudBookingList);
		MockUtility.Mocks.when(mockJobSelector.selectByBookingIdStatusAndFromDate((Set<Id>) fflib_Match.anyObject(), fflib_Match.anyDate(), (Set<String>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(jobs);
		
		//mocking PUDUtility method call.
		((PUDUtility)MockUtility.Mocks.doAnswer(new MockUtility.AnswerVoid(), mockPUDUtil)).refreshContainerTypes((Set<Id>)fflib_Match.anyObject(), (ApplicationUnitOfWork)fflib_Match.anyObject());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();
		
		PUDContainerTypeSyncModule module = PUDContainerTypeSyncModule.newInstance();

		module.onAfterDelete(new List<PUD_Container__c>{bookingContainer}, uow);

		Test.stopTest();

		//verify that PUDUtility is called once with expected list of jobs
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes(new Set<Id>{pudBookingList[0].Id}, uow);

		//verify that correct params are being passed to PUDUtility method.
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes((Set<Id>)fflib_Match.eq(new Set<Id>{pudBookingList[0].Id}), (ApplicationUnitOfWork) fflib_Match.eq(uow));

	}
	
	@IsTest
	public static void testEnsureAfterUpdateContainer() {
		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(PUDContainerTriggerHandler.getUnitOfWorkSObjectTypes());

		List<PUD_Booking__c> pudBookingList = PUDTestDataFactory.getPUDPermanentPickupDeliveryBookings(1, null, null, Date.today(), Date.today().addDays(30), null, true);
		List<PUD_Job__c> jobs = PUDTestDataFactory.getPUDJobs(6, pudBookingList[0].Id, PUDConstants.PUD_JOB_STATUS_NEW, true);
		
		//associate jobs with bookings
		pudBookingList[0] = (PUD_Booking__c)ApplicationTestDataFactory.setChildRelationships(pudBookingList[0], new Map<String, List<SObject>>{'Jobs__r' => jobs});

		//create a booking container
		PUD_Container__c bookingContainer = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Pallets', 'Empty', true )[0];

		//associating containers with bookings.
		pudBookingList[0] = (PUD_Booking__c)ApplicationTestDataFactory.setChildRelationships(pudBookingList[0], new Map<String, List<SObject>>{'Containers__r' => new List<SObject>{bookingContainer}});

		//create a job container
		PUD_Container__c jobContainer = PUDTestDataFactory.getPUDJobContainers(1, pudBookingList[0].Id, jobs[0].Id, 'Pallets', 'Empty', true )[0];
		jobs[0] = (PUD_Job__c)ApplicationTestDataFactory.setChildRelationships(jobs[0], new Map<String, List<SObject>>{'Containers__r' => new List<SObject>{jobContainer}});


		// =====================================
		// Stubbing
		// =====================================
		PUDUtility mockPUDUtil = (PUDUtility) MockUtility.mockUtility(PUDUtility.class);
		PUDBookingsSelector mockBookingSelector = (PUDBookingsSelector)MockUtility.mockSelector(PUDBookingsSelector.class);
		PUDJobsSelector mockJobSelector = (PUDJobsSelector)MockUtility.mockSelector(PUDJobsSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(mockBookingSelector.selectById((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(pudBookingList);
		MockUtility.Mocks.when(mockJobSelector.selectByBookingIdStatusAndFromDate((Set<Id>) fflib_Match.anyObject(), fflib_Match.anyDate(), (Set<String>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(jobs);
		//mocking PUDUtility method call.
		((PUDUtility)MockUtility.Mocks.doAnswer(new MockUtility.AnswerVoid(), mockPUDUtil)).refreshContainerTypes((Set<Id>)fflib_Match.anyObject(), (ApplicationUnitOfWork)fflib_Match.anyObject());


		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();
		//updating type for booking container.
		bookingContainer.Type__c = 'Aircan';

		PUDContainerTypeSyncModule module = PUDContainerTypeSyncModule.newInstance();

		module.onAfterUpdate(new List<PUD_Container__c>{bookingContainer}, null, uow);

		Test.stopTest();

		//verify that PUDUtility is called once with expected list of jobs
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes(new Set<Id>{pudBookingList[0].Id}, uow);

		//verify that correct params are being passed to PUDUtility method.
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes((Set<Id>)fflib_Match.eq(new Set<Id>{pudBookingList[0].Id}), (ApplicationUnitOfWork) fflib_Match.eq(uow));

	}

	@IsTest
	public static void testEnsureAfterInsertContainer() {
		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(PUDContainerTriggerHandler.getUnitOfWorkSObjectTypes());

		List<PUD_Booking__c> pudBookingList = PUDTestDataFactory.getPUDPermanentPickupDeliveryBookings(1, null, null, Date.today(), Date.today().addDays(30), null, true);
		List<PUD_Job__c> jobs = PUDTestDataFactory.getPUDJobs(6, pudBookingList[0].Id, PUDConstants.PUD_JOB_STATUS_NEW, true);

		//create a booking container
		PUD_Container__c c1 = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Pallets', 'Empty', true )[0];

		// =====================================
		// Stubbing
		// =====================================
		PUDUtility mockPUDUtil = (PUDUtility) MockUtility.mockUtility(PUDUtility.class);
		PUDBookingsSelector mockBookingSelector = (PUDBookingsSelector)MockUtility.mockSelector(PUDBookingsSelector.class);
		PUDJobsSelector mockJobSelector = (PUDJobsSelector)MockUtility.mockSelector(PUDJobsSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(mockBookingSelector.selectById((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(pudBookingList);
		MockUtility.Mocks.when(mockJobSelector.selectByBookingIdStatusAndFromDate((Set<Id>) fflib_Match.anyObject(), fflib_Match.anyDate(), (Set<String>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())).thenReturn(jobs);
		
		//mocking PUDUtility method call.
		((PUDUtility)MockUtility.Mocks.doAnswer(new MockUtility.AnswerVoid(), mockPUDUtil)).refreshContainerTypes((Set<Id>)fflib_Match.anyObject(), (ApplicationUnitOfWork)fflib_Match.anyObject());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		PUDContainerTypeSyncModule module = PUDContainerTypeSyncModule.newInstance();

		module.onAfterInsert(new List<PUD_Container__c>{c1}, uow);

		Test.stopTest();

		//verify that PUDUtility is called once with expected list of jobs
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes(new Set<Id>{pudBookingList[0].Id}, uow);

		//verify that correct params are being passed to PUDUtility method.
		((PUDUtility) MockUtility.Mocks.verify(mockPUDUtil, MockUtility.Mocks.times(1))).refreshContainerTypes((Set<Id>)fflib_Match.eq(new Set<Id>{pudBookingList[0].Id}), (ApplicationUnitOfWork) fflib_Match.eq(uow));


		
	}

	@IsTest
	static void testEnsureBeforeInsertTriggerContainerDuplicatePrevention() {
		// =====================================
		// Data Preparation
		// =====================================

		List<PUD_Booking__c> pudBookingList = PUDTestDataFactory.getPUDPermanentPickupDeliveryBookings(1, null, null, Date.today(), Date.today().addDays(30), null, true);
		
		PUD_Container__c c1 = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Pallets', 'Empty', true )[0];
		PUD_Container__c c2 = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Aircan', 'Empty', true )[0];

		PUD_Container__c newDuplicateContainer = PUDTestDataFactory.getPUDBookingContainers(1, pudBookingList[0].Id, 'Pallets', 'Empty', true )[0];

		//associating containers with bookings.
		pudBookingList[0] = (PUD_Booking__c)ApplicationTestDataFactory.setChildRelationships(pudBookingList[0], new Map<String, List<SObject>>{'Containers__r' => new List<SObject>{c1, c2}});


		// =====================================
		// Stubbing
		// =====================================
		PUDContainersSelector mockContainerSelector = (PUDContainersSelector)MockUtility.mockSelector(PUDContainersSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockContainerSelector.selectBookingContainersByBookingIds((Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject())).thenReturn(new List<PUD_Container__c>{c1,c2});
		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(PUDContainerTriggerHandler.getUnitOfWorkSObjectTypes());
		PUDContainerTypeSyncModule module = PUDContainerTypeSyncModule.newInstance();


		module.onBeforeInsert(new List<PUD_Container__c>{newDuplicateContainer}, uow);

		// make sure new container creation is prevented under a booking.
		System.assertEquals(true, newDuplicateContainer.hasErrors(), 'Expected validation error duplicated container is being created');

		Test.stopTest();
	}

	
	@IsTest
	static void testEndToEndTriggerIntegrationForInsert() {
		// =====================================
		// Data Preparation
		// =====================================
		Network__c network = ApplicationTestDataFactory.getNetworks(1, false)[0];
		network.recordTypeId = PUDTestDataFactory.businessHubNetworkRecordType;
		network.ORG_UNIT_ADDR_2__c ='1 Main St';
		network.ORG_UNIT_ADDR_3__c ='Melbourne';
		network.State__c  ='VIC';
		network.Post_Code__c ='3121';
		network.Integrated_Job_Dispatch_Enabled__c = true;
		insert(network);

		PUD_Booking_Location__c pudBookingLocation = PUDTestDataFactory.getPUDNetworkBookingLocations(1, network.Id, false)[0];
		insert(pudBookingLocation);

		PUD_Booking__c pudBooking = PUDTestDataFactory.getPUDPermanentPickupDeliveryBookings(1, pudBookingLocation.Id, network.Id, Date.today(), Date.today().addDays(90), null, false)[0];
		insert(pudBooking);

		PUD_Job__c pudJob = PUDTestDataFactory.getPUDJobs(1, pudBooking.Id, PUDConstants.PUD_JOB_STATUS_NEW, false)[0];
		pudJob.Depot__c = network.Id;
		insert(pudJob);

		PUD_Container__c bookingContainer = PUDTestDataFactory.getPUDBookingContainers(1, pudBooking.Id, 'Pallets', 'Empty', false)[0];


		// =====================================
		// Stubbing
		// =====================================
		//NONE

		// =====================================
		// Testing
		// =====================================

		Test.startTest();
		insert(bookingContainer);
		Test.stopTest();


		List<PUD_Container__c> jobContainers = PUDContainersSelector.newInstance().selectByJobIds(new Set<Id>{pudJob.Id}, new Set<Object>());

		System.assertEquals(jobContainers[0].Type__c, bookingContainer.Type__c, 'Expected job containers type to match booking containers type.');
		System.assertEquals(jobContainers[0].Condition__c, bookingContainer.Condition__c, 'Expected job containers type to match booking containers type.');
		System.assertEquals(jobContainers[0].Booking__c, pudBooking.Id, 'Expected job container to be created under same booking where booking container was created.');
		System.assertEquals(jobContainers[0].Job__c, pudJob.Id,'Expected job container is created under a job');
		System.assertEquals(1, jobContainers.size(),' There should be only 1 job container created');
	}
}