force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JN-{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to link the case with the Job</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/is_Allocated__c.field-meta.xml
<CustomField>
    <fullName>is_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the backend field just to rec ord the job has been allocated once or not?</description>
    <inlineHelpText>This is the backend field just to rec ord the job has been allocated once or not?</inlineHelpText>
    <label>is Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <description>Type of Job that requires completing</description>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Security Express</fullName>
            </value>
            <value>
                <fullName>Special Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Stage the in the process that the Job is currently at</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Pickup Arranged</fullName>
            </value>
            <value>
                <fullName>Pick Up Completed</fullName>
            </value>
            <value>
                <fullName>On-Board Trans-Shipment Depot 1</fullName>
            </value>
            <value>
                <fullName>Trans-Shipment Depot 1 - Complete</fullName>
            </value>
            <value>
                <fullName>On-Board Trans-Shipment Depot 2</fullName>
            </value>
            <value>
                <fullName>Trans-Shipment Depot 2 - Complete</fullName>
            </value>
            <value>
                <fullName>Received Into Delivery Depot</fullName>
            </value>
            <value>
                <fullName>On-Board Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobTriggerHandler.cls
/**
* Date            Version          Owner               Desription
* 10-Apr-19       1.0              Anshul Goyal        This is the trigger handler class for the trigger "JobTrigger"
*/

public class JobTriggerHandler {

    /* @created by: Anshul Goyal
     * @description This method handles all the before update operations for the trigger on the custom object job__c
     */
    public static void beforeUpdateTriggerHandler(Map <Id, Job__c> oldMap, List <Job__c> newJobList){
        //set of case Ids
        Set <Id> caseIds= new Set <Id>();
        
        for(Job__c job: newJobList){
            if( (job.Case__c!=null) && (job.Job_Type__c=='Special Services') && (job.Status__c=='Allocated') &&(oldMap.get(job.id).status__c=='New') && (!job.is_Allocated__c)){
                caseIds.add(job.Case__c);
                job.is_Allocated__c = true;
                
            }
        }

        //querying the cases related to the jobs
        if(caseIds.size()>0) {
            List <Case> updatedCasesList = new List <Case>();
            for (Case caseRecord : [SELECT Id,status FROM Case WHERE ID IN:caseIds]) {
                caseRecord.status = 'In Progress';
                updatedCasesList.add(caseRecord);
            }

            if (!updatedCasesList.isEmpty()) {
                update updatedCasesList;
            }
         }
    }
}