force-app/main/default/objects/AuthorisedContacts__c/AuthorisedContacts__c.object-meta.xml
<CustomObject>
    <label>Related Contacts</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Related Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>.</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia Post</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>CSC - Aegis</fullName>
            </value>
            <value>
                <fullName>CSC - Brisbane</fullName>
            </value>
            <value>
                <fullName>CSC - Melbourne</fullName>
            </value>
            <value>
                <fullName>I.T.</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>StarTrack Courier</fullName>
            </value>
            <value>
                <fullName>ECG</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Parcels</fullName>
            </value>
            <value>
                <fullName>Postal Service</fullName>
            </value>
            <value>
                <fullName>Trusted Services</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>StarTrack</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallBackRequired__c.field-meta.xml
<CustomField>
    <fullName>CallBackRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SSSW .</description>
    <inlineHelpText>If this is Checked, the Customer would like to be called about this Case before closure.</inlineHelpText>
    <label>Call Back Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Suggestion</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Adhoc Request</fullName>
            </value>
            <value>
                <fullName>Ongoing Scheduled</fullName>
            </value>
            <value>
                <fullName>Develop New Solution</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Date work is required to be completed</description>
    <inlineHelpText>Date by which work needs to be completed</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nominated_Advocate__c.field-meta.xml
<CustomField>
    <fullName>Nominated_Advocate__c</fullName>
    <label>Nominated Advocate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nominated_Advocate_Email__c.field-meta.xml
<CustomField>
    <fullName>Nominated_Advocate_Email__c</fullName>
    <label>Nominated Advocate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_Open_VOC_Incidents__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Open_VOC_Incidents__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Open VOC Incidents</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_VOC_Incidents__c.field-meta.xml
<CustomField>
    <fullName>Number_of_VOC_Incidents__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of VOC Incidents</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Parent_Status__c.field-meta.xml
<CustomField>
    <fullName>Parent_Status__c</fullName>
    <label>Parent Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recent_Caller_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Recent_Caller_First_Name__c</fullName>
    <description>capture recent caller first name information</description>
    <label>Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recent_Caller_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Recent_Caller_Last_Name__c</fullName>
    <description>Capture recent caller last name information</description>
    <label>Contact Last Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ResolutionCode__c.field-meta.xml
<CustomField>
    <fullName>ResolutionCode__c</fullName>
    <description>SSSW.</description>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acknowledge Feedback</fullName>
            </value>
            <value>
                <fullName>API Issue</fullName>
            </value>
            <value>
                <fullName>Apology</fullName>
            </value>
            <value>
                <fullName>Assistance provided</fullName>
                <default>true</default>
                <label>Assistance provided</label>
            </value>
            <value>
                <fullName>Assistance Provided - Other Team</fullName>
            </value>
            <value>
                <fullName>Basket Size Under $25</fullName>
            </value>
            <value>
                <fullName>BesC</fullName>
            </value>
            <value>
                <fullName>BesS</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled - Duplicate</fullName>
            </value>
            <value>
                <fullName>Cancelled - No Longer Required</fullName>
            </value>
            <value>
                <fullName>Close Account</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Resolved by Advocate</fullName>
            </value>
            <value>
                <fullName>Closed - Resolved by VOC</fullName>
            </value>
            <value>
                <fullName>Closed - Spam</fullName>
            </value>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Education</fullName>
            </value>
            <value>
                <fullName>Customer – no response</fullName>
            </value>
            <value>
                <fullName>Customer – response, no further action</fullName>
            </value>
            <value>
                <fullName>Customer – Self service</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Delay In Receiving</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Exgratia</fullName>
            </value>
            <value>
                <fullName>FCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Business unit field is used by SSSW reporting team.</description>
    <label>Business Unit</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/StarTrack_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>StarTrack custom settings</description>
    <label>StarTrack Settings</label>
</CustomObject>

force-app/main/default/objects/StarTrack_Settings__c/fields/Number_of_Business_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Business_Days__c</fullName>
    <label>Number of Business Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Number_of_Hours_per_Business_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hours_per_Business_Days__c</fullName>
    <label>Number of Hours per Business Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/StarTrack_Related_Contact_RecType_Id__c.field-meta.xml
<CustomField>
    <fullName>StarTrack_Related_Contact_RecType_Id__c</fullName>
    <description>This will store startrack related contact record type Id.</description>
    <label>StarTrack Related Contact RecType Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StarTrackVOC_Test.cls
/**
 ** Description: Test Class for StarTrackVOCEnquiryCalculation, StarTrackVOCEnquiryDueDateCalculation, StarTrackVOCIncidentCalculation class
 ** Author: David Catindoy(CloudSherpas)
 ** Date Created: March 7, 2016
 ** History:--------------------------------------------
 **         March 7, 2016 David Catindoy - Created
 **/
@isTest
private class StarTrackVOC_Test {
    @testSetup static void testSetup(){
        StarTrack_Settings__c cs = new StarTrack_Settings__c();
        cs.Number_of_Hours_per_Business_Days__c = 10;
        cs.Number_of_Business_Days__c = 10;
        cs.StarTrack_Related_Contact_RecType_Id__c = Schema.SObjectType.AuthorisedContacts__c.getRecordTypeInfosByName().get('StarTrack Related Contact').getRecordTypeId();
        INSERT cs;
        
        BusinessHours stdBusinessHours = [SELECT Id from BusinessHours WHERE Name = 'Default'];
        
        Network__c testNetwork = TestDataProvider.createNetwork('Test Network', 1)[0];
        INSERT testNetwork;
        
        Case testVOCCase = new Case();
        testVOCCase.Status = 'New';
        testVOCCase.Subject = 'Test VOC Enquiry';
        testVOCCase.Origin = 'Email';
        testVOCCase.Classification__c = 'Complaint';
        testVOCCase.Priority = 'Normal';
        testVOCCase.BusinessHoursId = stdBusinessHours.Id;
        testVOCCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Voice of Customer Enquiry').getRecordTypeId();
        INSERT testVOCCase;
        
        Id incidentRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Voice of Customer Incident').getRecordTypeId();
        List<Case> testVOCIncidentList = new List<Case>();
        testVOCIncidentList.add(new Case(Subject = 'Test VOC 1', Description = 'Sample VOC 1', ParentId = testVOCCase.Id, Recent_Caller_First_Name__c = 'David', Recent_Caller_Last_Name__c = 'Catindoy', Parent_Status__c = 'New', Status = 'New', Business_Unit__c = 'Commercial', Nominated_Advocate_Email__c = 'david.catindoy@cloudsherpas.com', Nominated_Advocate__c = 'David', CallBackRequired__c = true, Network__c = testNetwork.Id, RecordTypeId = incidentRecType, BusinessHoursId = stdBusinessHours.Id));
        testVOCIncidentList.add(new Case(Subject = 'Test VOC 2', Description = 'Sample VOC 2', ParentId = testVOCCase.Id, Recent_Caller_First_Name__c = 'April', Recent_Caller_Last_Name__c = 'Cervantes', Parent_Status__c = 'New', Status = 'Closed', ResolutionCode__c = 'Apology', Business_Unit__c = 'Commercial', Nominated_Advocate_Email__c = 'david.catindoy@cloudsherpas.com', Nominated_Advocate__c = 'Patrick', CallBackRequired__c = true, Network__c = testNetwork.Id, RecordTypeId = incidentRecType, BusinessHoursId = stdBusinessHours.Id));
        INSERT testVOCIncidentList;
    }
    @isTest static void testVOCEnquiry(){
        Case caseRec = [SELECT Id FROM Case WHERE Subject = 'Test VOC Enquiry']; 
        
        Test.startTest();
            StarTrackVOCEnquiryCalculation.VOCEnquiryCalculation(new List<Id>{caseRec.Id});
        Test.stopTest();
        
        caseRec = [SELECT Id, Number_of_Open_VOC_Incidents__c, Number_of_VOC_Incidents__c FROM Case WHERE Id = :caseRec.Id];
        System.assertEquals(1, caseRec.Number_of_Open_VOC_Incidents__c);
        System.assertEquals(2, caseRec.Number_of_VOC_Incidents__c);
    }
    
    @isTest static void testVOCEnquiryDueDate(){
        Case caseRec = [SELECT Id FROM Case WHERE Subject = 'Test VOC Enquiry']; 
        StarTrack_Settings__c cs = StarTrack_Settings__c.getOrgDefaults();
        
        Test.startTest();
            StarTrackVOCEnquiryDueDateCalculation.VOCEnquiryDueDateCalculation(new List<Id>{caseRec.Id});
        Test.stopTest();
        
        caseRec = [SELECT Id, Number_of_Open_VOC_Incidents__c, Number_of_VOC_Incidents__c, BusinessHoursId, Due_Date__c, CreatedDate FROM Case WHERE Id = :caseRec.Id];
        System.assertEquals(Date.valueOf(BusinessHours.add(caseRec.BusinessHoursId, caseRec.CreatedDate, (3600000 * Integer.valueOf(cs.Number_of_Hours_per_Business_Days__c*cs.Number_of_Business_Days__c))).format('yyyy-MM-dd HH:mm:ss')).format(), caseRec.Due_Date__c.format());
        System.assertNotEquals(null, caseRec.BusinessHoursId);
        System.assertNotEquals(null, caseRec.Due_Date__c);
    }
    
    @isTest static void testVOCIncident(){
        Case caseRec = [SELECT Id FROM Case WHERE Status = 'New' LIMIT 1]; 
        StarTrack_Settings__c cs = StarTrack_Settings__c.getOrgDefaults();
        
        Test.startTest();
            StarTrackVOCIncidentCalculation.VOCIncidentCalculation(new List<Id>{caseRec.Id});
            caseRec = [SELECT Id, BusinessHoursId, CreatedDate, Due_Date__c FROM Case WHERE Id = :caseRec.Id];
            System.assertEquals(Date.valueOf(BusinessHours.add(caseRec.BusinessHoursId, caseRec.CreatedDate, (3600000 * Integer.valueOf(cs.Number_of_Hours_per_Business_Days__c*5))).format('yyyy-MM-dd HH:mm:ss')).format(), caseRec.Due_Date__c.format());
            
            caseRec.Priority = 'High';
            update caseRec;
            StarTrackVOCIncidentCalculation.VOCIncidentCalculation(new List<Id>{caseRec.Id});
            caseRec = [SELECT Id, BusinessHoursId, CreatedDate, Due_Date__c FROM Case WHERE Id = :caseRec.Id];
            System.assertEquals(Date.valueOf(BusinessHours.add(caseRec.BusinessHoursId, caseRec.CreatedDate, (3600000 * Integer.valueOf(cs.Number_of_Hours_per_Business_Days__c*3))).format('yyyy-MM-dd HH:mm:ss')).format(), caseRec.Due_Date__c.format());
            
            caseRec.Priority = 'Urgent';
            update caseRec;
            StarTrackVOCIncidentCalculation.VOCIncidentCalculation(new List<Id>{caseRec.Id});
            caseRec = [SELECT Id, BusinessHoursId, CreatedDate, Due_Date__c FROM Case WHERE Id = :caseRec.Id];
            System.assertEquals(Date.valueOf(BusinessHours.add(caseRec.BusinessHoursId, caseRec.CreatedDate, (3600000 * Integer.valueOf(cs.Number_of_Hours_per_Business_Days__c))).format('yyyy-MM-dd HH:mm:ss')).format(), caseRec.Due_Date__c.format());
            
            caseRec.Priority = 'Critical';
            update caseRec;
            StarTrackVOCIncidentCalculation.VOCIncidentCalculation(new List<Id>{caseRec.Id});
        Test.stopTest();
        
        caseRec = [SELECT Id, BusinessHoursId, CreatedDate, Due_Date__c FROM Case WHERE Id = :caseRec.Id];
        System.assertEquals(Date.valueOf(BusinessHours.add(caseRec.BusinessHoursId, caseRec.CreatedDate, (3600000 * Integer.valueOf(cs.Number_of_Hours_per_Business_Days__c))).format('yyyy-MM-dd HH:mm:ss')).format(), caseRec.Due_Date__c.format());
    }
}