force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/ACIC_Request_Approved__c.field-meta.xml
<CustomField>
    <fullName>ACIC_Request_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will be checked whenever ACIC Request Case Status is set to Approved</description>
    <label>ACIC Request Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prospect Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SFDC_520_Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary contact associated with the quote/proposal</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Proposal_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Proposal_Expiration_Date__c</fullName>
    <description>The quote/proposal expiration date</description>
    <inlineHelpText>This date will be system generated, 60 days from the proposal created date. Expired proposals cannot be presented to the customer</inlineHelpText>
    <label>Proposal Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Proposal_Name__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Proposal_Name__c</fullName>
    <label>Proposal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ACIC Request Case will be created against this Proposal</description>
    <label>Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a custom field created for the User Support Case Page Layout</description>
    <inlineHelpText>Select the individual that the query is from</inlineHelpText>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ACICCaseUtility_Test.cls
/**************************************************
Description:    Test Class for ACICCaseUtility
History:
--------------------------------------------------
26.03.2019    gnana.muruganantham@auspost.com.au	Created
**************************************************/
@isTest
private with sharing class ACICCaseUtility_Test {
    
    /******************************************************************************************************
    * @description       This method is to test Proposal Update based on Case Status Update
    * @param             NA
    * @return            Void
    * @throws            NA
    ******************************************************************************************************/
    static testmethod void testUpdateProposalBasedOnACICStatus_success() {
        // Get ACIC Case Record Type Id 
        Id acicRecordTypeId = CaseUtility.getRecordIdWithDevName(Constants.RECORDTYPE_NAME_ACIC_REQUEST);
        
        // Create test Account
        Account testAccount = TestDataProvider.createTestAccount();
        Database.Insert(testAccount);
        
		// Create test Contact
        Contact testContact = TestDataProvider.createTestContact();
        Database.Insert(testContact);        
        
        // Create test Proposal
        Apttus_Proposal__Proposal__c testProposal = new Apttus_Proposal__Proposal__c(Apttus_Proposal__Proposal_Name__c='Test Proposal',Apttus_Proposal__Account__c=testAccount.Id,Apttus_Proposal__Primary_Contact__c=testContact.Id,Apttus_Proposal__Proposal_Expiration_Date__c=date.today()+10);
        Database.Insert(testProposal);
        
        // Create test ACIC Request Case
        Case testCase = new Case();
        testCase.Subject = 'Test ACIC Request Case';
        testCase.Description = 'Test ACIC Request Case';
        testCase.RecordTypeId = acicRecordTypeId;
        testCase.Proposal__c = testProposal.Id;
        testCase.Requestor__c= UserInfo.getUserId();
        
        // Inserting Case record
        test.startTest();
        Database.Insert(testCase);
        testCase.Status=Constants.CASE_STATUS_APPROVED;
        Database.Update(testCase);
        test.stopTest();
        
        // Checking whether Proposal record updated accordingly
        Apttus_Proposal__Proposal__c proposalRec = [SELECT Id, ACIC_Request_Approved__c FROM Apttus_Proposal__Proposal__c WHERE Id =: testProposal.Id];
        System.assertEquals(true, proposalRec.ACIC_Request_Approved__c);
    }
}