force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>R00N70000001yUfDEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APT_ProposalTriggerHelper.cls
/**
 * @description: This is the helper class for Proposal Trigger
 * @author: Mansi Shah
 * @last modified on: 06-10-2021
 * @last modified by: Mansi Shah
 * Modifications Log
 * Ver Date Author Modification
 * 1.0   06-10-2021 Mansi Shah Initial Version
 * Ken McGuire 2023.04.19 Proposal field migration to opportunity
 * Paul Perry	2023-09-14 Decommissioned StarTrek Pricing Matrix logic MW0005472
**/
public with sharing class APT_ProposalTriggerHelper {
	/**
	* @description : This method will set Proposal based on Opportunity driver on Opportunity Object - (Opportunity'owner)
	* @author Mansi Shah | 07-14-2021
	* @param newProposalList
	**/
	public static void updateProposalOwner(list<Apttus_Proposal__Proposal__c> newProposalList)
	{
		if(newProposalList != null && !newProposalList.isEmpty())
		{
			Set<Id> setOfOpportunityIds = new Set<Id>();
			for(Apttus_Proposal__Proposal__c oProposal : newProposalList){
				if(oProposal.Apttus_Proposal__Opportunity__c != null){
					setOfOpportunityIds.add(oProposal.Apttus_Proposal__Opportunity__c);
				}
			}

			if(setOfOpportunityIds != null){
				List<Opportunity> listOfOpportunities = new List<Opportunity>();
				Map<Id,Opportunity> mapOfOpportunities = new Map<Id,Opportunity>();
				listOfOpportunities = [SELECT Id,OwnerID
									  FROM Opportunity
									  WHERE ID IN: setOfOpportunityIds];

				if(listOfOpportunities != null && !listOfOpportunities.isEmpty()){

					for(Opportunity opp : listOfOpportunities){
						mapOfOpportunities.put(opp.Id,opp);
					}

					for(Apttus_Proposal__Proposal__c oProposal : newProposalList){
						if(oProposal.Apttus_Proposal__Opportunity__c != null && mapOfOpportunities != null && mapOfOpportunities.containsKey(oProposal.Apttus_Proposal__Opportunity__c)){
							oProposal.OwnerID = mapOfOpportunities.get(oProposal.Apttus_Proposal__Opportunity__c).OwnerID;
						}
					}
				}
			}
		}
	}
}