force-app/main/default/objects/SSOAttributeMapping__mdt/SSOAttributeMapping__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map attributes from the JIT/Reg handler claims to the correct identifying attribute on the user record.</description>
    <label>SSO Attribute Mapping</label>
    <pluralLabel>SSO Attribute Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSOAttributeMapping__mdt/fields/FederationField__c.field-meta.xml
<CustomField>
    <fullName>FederationField__c</fullName>
    <description>The API name of the field on the User object to match the SSO subject claim to</description>
    <inlineHelpText>The API name of the field on the User object to match the SSO subject claim to</inlineHelpText>
    <label>Federation Field</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSOAttributeMapping__mdt/fields/NetworkId__c.field-meta.xml
<CustomField>
    <fullName>NetworkId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>A reg handler that implements the SSO Attribute Mapping custom metadata type will use this value to map to correct federation identifier field for that particular network. Example: LBP Community will point to LBPFederationIdentifier__c. This really is environment specific, so this potentially should be refactored at some point (or CI/CD to cover environment specific metadata deployment)</description>
    <inlineHelpText>A reg handler that implements the SSO Attribute Mapping custom metadata type will use this value to map to correct federation identifier field for that particular network. Example: LBP Community will point to LBPFederationIdentifier__c</inlineHelpText>
    <label>Network Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SSOAttributeMapping__mdt/fields/SubjectAttribute__c.field-meta.xml
<CustomField>
    <fullName>SubjectAttribute__c</fullName>
    <description>This represents the name of the attribute of the subject to use from the SSO provider. The value thats contained within this attribute will be compared against the value in the field represented in Federation Field field</description>
    <inlineHelpText>This represents the name of the attribute of the subject to use from the SSO provider. The value thats contained within this attribute will be compared against the value in the field represented in Federation Field field</inlineHelpText>
    <label>Subject Attribute</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSOTestDataFactory.cls
/**
* @description Contains all the test data methods for SSO test classes
* @author Nathan Franklin
* @date 2022-05-11
* @changelog
*/
@IsTest
public class SSOTestDataFactory {

	public static List<SSOAttributeMapping__mdt> getSSOAttributeMappings(Integer count, Object networkIdsOrId, Boolean generateIds) {
		return (List<SSOAttributeMapping__mdt>)ApplicationTestDataFactory.maybeGenerateIds(ApplicationTestDataFactory.populateSObjects(SSOAttributeMapping__mdt.SObjectType, new Map<SObjectField, Object> {
			SSOAttributeMapping__mdt.DeveloperName => 'RECORD%count%',
			SSOAttributeMapping__mdt.NetworkId__c => networkIdsOrId,
			SSOAttributeMapping__mdt.FederationField__c => 'FederationIdentifier',
			SSOAttributeMapping__mdt.SubjectAttribute__c => 'email'
		}, count), generateIds);
	}

}