force-app/main/default/objects/Auspost_Vendors_Email_Address__mdt/Auspost_Vendors_Email_Address__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to save Vendors&apos; email address for sandbox vs productions environment.</description>
    <label>Auspost Vendors Email Address</label>
    <pluralLabel>Auspost Vendors Email Address</pluralLabel>
</CustomObject>

force-app/main/default/objects/Auspost_Vendors_Email_Address__mdt/fields/Vendor_Email__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email__c</fullName>
    <description>Vendors email address</description>
    <inlineHelpText>Enter recipient email address</inlineHelpText>
    <label>Vendor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/VendorEmailUtils.cls
/**
 ** Description: 
 * Apex class to retrieve the vendor email address from Auspost_Vendors_Email_Address__mdt
 * This class provides an invocable method for use in flows to fetch vendor email addresses
 * for ABN Change Notification flow.
 **
 * @changelog
 * 2024-03-19 - Deepak Kemidi - Created
 **/
public with sharing class VendorEmailUtils {

	@InvocableMethod(label='Get Vendors Email Address')
	public static List<String> getEmailAddress() {
		List<String> emailAddresses = new List<String>();
		
		//Create an instance of AuspostVendorEmailSelector
		AuspostVendorEmailSelector selector = AuspostVendorEmailSelector.newInstance();
		
		//Call selectAllRecords() method to fetch all records
		List<Auspost_Vendors_Email_Address__mdt> customMetadataRecords = selector.selectAllRecords();
		
		if (!customMetadataRecords.isEmpty()) {
			for(Auspost_Vendors_Email_Address__mdt record : customMetadataRecords) {
				if (record.Vendor_Email__c != null) {
					emailAddresses.add(record.Vendor_Email__c);
				}
			}
		}
		
		String emailAddressesString = String.join(emailAddresses, ',');
		
		List<String> result = new List<String>();
		
		if(!String.isBlank(emailAddressesString)) {
			result.add(emailAddressesString);
		}
		
		return result;
	}
}