force-app/main/default/objects/ICPS__c/ICPS__c.object-meta.xml
<CustomObject>
    <description>This object will store the details of Inward Commercial Parcel System (ICPS) records for all international articles coming into Australia with a value of more than $1000</description>
    <label>ICPS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICPS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ICPS__c/fields/Articles__c.field-meta.xml
<CustomField>
    <fullName>Articles__c</fullName>
    <description>A concatenation of all the article numbers linked to the ICPS record that will be used on the Notices and for searching purposes</description>
    <inlineHelpText>A concatenation of all the article numbers linked to the ICPS record that will be used on the Notices and for searching purposes</inlineHelpText>
    <label>Article/s</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICPSArticle__c/ICPSArticle__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of articles that are associated with an ICPS record</description>
    <label>ICPS Article</label>
    <nameField>
        <label>Article Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICPS Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ICPSArticle__c/fields/ICPS__c.field-meta.xml
<CustomField>
    <fullName>ICPS__c</fullName>
    <description>This is the linking of the ICPS article to the ICPS record.</description>
    <inlineHelpText>This is the linking of the ICPS article to the ICPS record.</inlineHelpText>
    <label>ICPS</label>
    <referenceTo>ICPS__c</referenceTo>
    <relationshipLabel>ICPS Articles</relationshipLabel>
    <relationshipName>ICPS_Articles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ICPSArticleNoticeGenerationModule.cls
/**
 * @description
 * Domain Module to update ICPS related to notice generation
 * Domain Modules should NEVER be called directly. Domain modules should be exposed and called via the corresponding domain class
 *
 * @author Harry Wang
 * @date 2022-06-30
 * @group Domain
 * @domain ICPS
 * @changelog
 * 2022-06-30 - Harry Wang - Created
*/
public inherited sharing class ICPSArticleNoticeGenerationModule extends ApplicationDomain.Module {
	public static ICPSArticleNoticeGenerationModule newInstance() {
		return (ICPSArticleNoticeGenerationModule)Application.Utilities.newInstance(ICPSArticleNoticeGenerationModule.class);
	}

	public ICPSArticleNoticeGenerationModule() {
		getTriggerEvents().enableAfterInsert();
	}

	public override void onAfterInsert(List<SObject> records, ApplicationUnitOfWork uow) {
		try {
			concatICPSArticleNumbers(records, uow);
		} catch (Exception ex) {
			// Error Logged to Exception object for analysis
			UTIL_LoggingService.logHandledException(ex, UserInfo.getUserId(), 'ICPS', ICPSArticleNoticeGenerationModule.class.getName(), 'onAfterInsert', 'ICPSArticleTrigger', LoggingLevel.ERROR);
		}
	}

	/**
	 * This method is used to concatenate article names with comma on the parent ICPS record
	 * @param records list of ICPS records to be updated
	 * @param uow Unit of Work instance
	 */
	@TestVisible
	private void concatICPSArticleNumbers(List<SObject> records, ApplicationUnitOfWork uow) {
		Set<Id> icpsIds = new Set<Id>();
		for (ICPSArticle__c a: (List<ICPSArticle__c>) records) {
			if (String.isNotBlank(a.Name)) {
				icpsIds.add(a.ICPS__c);
			}
		}

		List<ICPS__c> toUpdateICPSList = new List<ICPS__c>();

		if (!icpsIds.isEmpty()) {
			for (ICPS__c icps: ICPSSelector.newInstance().selectById(icpsIds, new Set<Object>{ICPSSelector.Options.WITH_ICPS_ARTICLES})) {
				List<String> names = new List<String>();
				for (ICPSArticle__c a: icps.ICPS_Articles__r) {
					names.add(a.Name);
				}
				// concatenate article names with comma for each ICPS
				String concatNames = String.join(names, ', ');
				if (String.isNotBlank(concatNames)) {
					toUpdateICPSList.add(new ICPS__c(Id = icps.Id, Articles__c = concatNames));
				}
			}
		}
		// Only update ICPS with expected article names
		if (!toUpdateICPSList.isEmpty()) {
			uow.registerDirty(toUpdateICPSList);
		}
	}

	/**
	 * Module instantiation context. This allows us to dynamically instantiate this module within ApplicationModule
	 */
	public class Constructor implements ApplicationDomain.IConstructableModule {
		public ApplicationDomain.Module construct() {
			return (ApplicationDomain.Module) ICPSArticleNoticeGenerationModule.newInstance();
		}
	}
}