force-app/main/default/objects/ICPS__c/ICPS__c.object-meta.xml
<CustomObject>
    <description>This object will store the details of Inward Commercial Parcel System (ICPS) records for all international articles coming into Australia with a value of more than $1000</description>
    <label>ICPS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICPS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ICPSArticle__c/ICPSArticle__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of articles that are associated with an ICPS record</description>
    <label>ICPS Article</label>
    <nameField>
        <label>Article Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICPS Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ICPSArticle__c/fields/ICPS__c.field-meta.xml
<CustomField>
    <fullName>ICPS__c</fullName>
    <description>This is the linking of the ICPS article to the ICPS record.</description>
    <inlineHelpText>This is the linking of the ICPS article to the ICPS record.</inlineHelpText>
    <label>ICPS</label>
    <referenceTo>ICPS__c</referenceTo>
    <relationshipLabel>ICPS Articles</relationshipLabel>
    <relationshipName>ICPS_Articles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ICPSTriggers_Test.cls
/**
 * @author Harry Wang
 * @date 2022-07-19
 * @group Trigger
 * @domain ICPS
 * @description Test class to cover all ICPS triggers
 * @changelog
 * 2022-07-19 - Harry Wang - Created
 */
@IsTest
public with sharing class ICPSTriggers_Test {
	@IsTest
	public static void testTrigger() {
		List<ICPS__c> icps = ICPSTestDataFactory.getICPS(1, false);
		insert icps;
		List<ICPSArticle__c> articleList = ICPSTestDataFactory.getICPSArticles(icps[0].Id, 1, false);
		insert articleList;
	}
}