force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/ArticleID__c.field-meta.xml
<CustomField>
    <fullName>ArticleID__c</fullName>
    <description>Tracking Number of Article</description>
    <externalId>true</externalId>
    <label>Article ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Article__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Billing Account field to capture billing account info</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSSW - Collection of multiple Articles used to track set of Articles</description>
    <label>Consignment</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture network information for an article</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>Field used to support the remediation process for missorted or looping parcels.</description>
    <formula>ArticleID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Field used to support the remediation process for missorted or looping parcels.</inlineHelpText>
    <label>Remediation Article ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Article</label>
</RecordType>

force-app/main/default/objects/Article__c/recordTypes/Consignment.recordType-meta.xml
<RecordType>
    <fullName>Consignment</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Consignment</label>
</RecordType>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &apos;Accounts&apos; in SAP ERP, eg Charge Account, Cash Account, etc.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/CaseInvestigation__c.object-meta.xml
<CustomObject>
    <label>Case Investigation</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Investigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseInvestigation__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Case Investigations</relationshipLabel>
    <relationshipName>Case_Investigations_Art</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Network__c.Contact_Facility__c</field>
            <operation>equals</operation>
            <value>MyNetwork</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Case Investigations</relationshipLabel>
    <relationshipName>Case_Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>The reference id for the case investigation record i.e article number</description>
	<inlineHelpText>This is Article ID</inlineHelpText>
    <externalId>true</externalId>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/STCaseInvestigationArticleModule_Test.cls
/**
 * @description       : Test class for STCaseInvestigationArticleModule
 * @author            : George Nguyen
 * @domain            : Case
 * @changelog
 * 2022-12-05 - George Nguyen - created
 * 2022-12-13 - Mahesh Parvathaneni - Added test methods for beforeInsert events
 **/
@IsTest
private class STCaseInvestigationArticleModule_Test {

	@IsTest
	static void testBeforeInsertCheckDuplicateCaseInvestigationRecords() {

		// =====================================
		// Data Preparation
		// =====================================
		List<Article__c> articles = ApplicationTestDataFactory.getArticles(2, true);
		Case aCase = ApplicationTestDataFactory.getCases(1, true)[0];
		List<Network__c> networks = ApplicationTestDataFactory.getNetworks(1, true);
		List<CaseInvestigation__c> records = ApplicationTestDataFactory.getCaseInvestigations(1, aCase.Id, articles[0], networks[0].Id, true);
		records.addAll(ApplicationTestDataFactory.getCaseInvestigations(1, aCase.Id, articles[1], networks[0].Id, true));
		List<CaseInvestigation__c> existingCaseInvestigations = ApplicationTestDataFactory.getCaseInvestigations(1, aCase.Id, articles[1], networks[0].Id, true);

		// =====================================
		// Stubbing
		// =====================================
		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();
		CaseInvestigationsSelector mockCaseInvestigationsSelector = (CaseInvestigationsSelector)MockUtility.mockSelector(CaseInvestigationsSelector.class);

		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockCaseInvestigationsSelector.selectOpenCaseInvestigationsByCaseArticleNetworkId((Set<Id>)fflib_Match.anyObject(), (Set<String>)fflib_Match.anyObject(), (Set<Id>)fflib_Match.anyObject())).thenReturn(new Map<Id, CaseInvestigation__c>{existingCaseInvestigations[0].Id => existingCaseInvestigations[0]});
		MockUtility.Mocks.stopStubbing();


		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		STCaseInvestigationArticleModule.newInstance().onBeforeInsert(records, mockUow);

		// make sure new case investigation creation is prevented under same case, article reference and network.
		System.assertEquals(true, records[1].hasErrors(), 'Expected validation error duplicated case investigation is being created');

		Test.stopTest();
	}

	
/**
	 * Test:
	 *  When a case is inserted, the before insert will try and match the ReferenceID or ArticleTest field to their corresponding records in Article__c
	 */
	@IsTest
	private static void testEnsureBeforeInsertPopulatesArticleAndReferenceIds() {

		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(CaseTriggerHandler2.getUnitOfWorkSObjectTypes());
		Account account = ApplicationTestDataFactory.getAccounts(1, true)[0];
		Billing_Account__c billingAccount = ApplicationTestDataFactory.getBillingAccounts(1, account.Id, 'SAP ERP', true)[0];
		List<Case> cases = ApplicationTestDataFactory.getCases(3, true);
		Article__c consignment = ApplicationTestDataFactory.getConsignments(1, true)[0];
		List<Article__c> articles = ApplicationTestDataFactory.getArticles(2, consignment.Id, true);

		List<CaseInvestigation__c> caseInvestigations = ApplicationTestDataFactory.getCaseInvestigations(3, new Map<Id, Case>(cases).keySet(), articles[0], null, true);

		// set up billing account on articles
		articles[0].Billing_Account__c = billingAccount.Id;
		articles[1].Billing_Account__c = billingAccount.Id;

		// this is our test data where 1 record has a reference ID and another article has the Id
		caseInvestigations[0].ReferenceID__c = articles[0].ArticleID__c;
		caseInvestigations[1].Article__c = articles[1].Id;

		ApplicationTestDataFactory.setUnwritableFields(articles[0], new Map<String, Object>{'Consignment__r' => consignment});
		ApplicationTestDataFactory.setUnwritableFields(articles[1], new Map<String, Object>{'Consignment__r' => consignment});

		// =====================================
		// Stubbing
		// =====================================
		ArticlesSelector mockArticleSelector = (ArticlesSelector)MockUtility.mockSelector(ArticlesSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockArticleSelector.selectByIdOrTracking((Set<String>)fflib_Match.anyObject(), (Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject(), fflib_Match.anyBoolean())).thenReturn(new Map<Id, Article__c>(articles));
		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		STCaseInvestigationArticleModule module = STCaseInvestigationArticleModule.newInstance();

		module.onBeforeInsert(caseInvestigations, uow);

		// make sure the method behaved
		((ArticlesSelector)MockUtility.Mocks.verify(mockArticleSelector, 1)).selectByIdOrTracking((Set<String>)fflib_Match.anyObject(), (Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject(), fflib_Match.anyBoolean());

		// make sure fields were updated correctly
		System.assertEquals(articles[0].Id, caseInvestigations[0].Article__c, 'Expected Article Id field to be set on case');
		System.assertEquals(articles[1].ArticleID__c, caseInvestigations[1].ReferenceID__c, 'Expected Reference ID field to be set on case');

		// make sure case was not updated
		System.assertEquals(null, caseInvestigations[2].ReferenceID__c, 'Expected Reference Id field to be empty');
		System.assertEquals(null, caseInvestigations[2].Article__c, 'Expected Article Id field to be empty');

		Test.stopTest();
	}


}