force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/ArticleTest__c.field-meta.xml
<CustomField>
    <fullName>ArticleTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeedCommentTrigger_Test.cls
/* 
* @author		: Mahesh Parvathaneni
* @date			: 06/04/2023
* @description	: test class to cover FeedComment Trigger
* @changelog	:
*/

@IsTest
private class FeedCommentTrigger_Test {

	@IsTest
	static void makingSureThatTheDispatchMethodIsCalledFromTheCorrectClass() {
		// =====================================
		// Data Preparation
		// =====================================
		List<Article__c> articles = ApplicationTestDataFactory.getArticles(1, false);
		insert articles;
		List<Case> cases = ApplicationTestDataFactory.getCases(1, false);
		cases[0].ArticleTest__c = articles[0].Id;
		cases[0].RecordTypeId = ApplicationTestDataFactory.caseStarTrackGeneralEnquiryRecordType;
		insert cases;

		List<FeedItem> feedItems = ApplicationTestDataFactory.getChatterFeeds(1, cases[0].Id, false);
		feedItems[0].Body = 'test feed for case';
		insert feedItems;

		

		// =====================================
		// Stubbing
		// =====================================
		FeedCommentTriggerHandler2 mock = (FeedCommentTriggerHandler2)MockUtility.mockUtility(FeedCommentTriggerHandler2.class);

		// =====================================
		// Testing
		// =====================================
		List<FeedComment> feedComments = ApplicationTestDataFactory.getFeedComments(1, cases[0].Id, feedItems[0].Id, false);
		feedComments[0].CommentBody = 'test comment';

		Test.startTest();
		insert feedComments;
		Test.stopTest();

		((FeedCommentTriggerHandler2) MockUtility.Mocks.verify(mock, MockUtility.Mocks.atLeastOnce())).dispatch();

		System.assertNotEquals(null, feedComments[0].id,'FeedComment should be inserted');

	}
}