force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/ArticleID__c.field-meta.xml
<CustomField>
    <fullName>ArticleID__c</fullName>
    <description>Tracking Number of Article</description>
    <externalId>true</externalId>
    <label>Article ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Article__c/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>Field used to support the remediation process for missorted or looping parcels.</description>
    <formula>ArticleID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Field used to support the remediation process for missorted or looping parcels.</inlineHelpText>
    <label>Remediation Article ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchableArticleDeleter.cls
/**************************************************
Type:       |
Purpose:    To delete Articles meeting following criteria,
			- Created 1 Month ago and
			- Not used by any open Cases or Cases closed within 2 months
Used By:             
History:
--------------------------------------------------
09.05.2014  Mohamed.Atheek@bluewolf.com  Created                                               
**************************************************/
global class BatchableArticleDeleter implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator('SELECT Id, ArticleID__c FROM Article__c WHERE CreatedDate < LAST_N_DAYS:30');
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		Set<String> articleIds = new Set<String>();
		for (Article__c a : (List<Article__c>)scope)
		{
			articleIds.add(a.ArticleID__c);
		}
		
		Set<String> undeletableArticles = new Set<String>();
		for (Case c : [SELECT ReferenceID__c FROM Case WHERE ReferenceID__c IN :articleIds AND (ClosedDate = null OR ClosedDate = LAST_N_DAYS:60)]) 
		{
			undeletableArticles.add(c.ReferenceID__c);
		}
		
		List<Article__c> articlesToDelete = new List<Article__c>();
		for (Article__c a : (List<Article__c>)scope)
		{
			if (!undeletableArticles.contains(a.ArticleID__c))
			{
				articlesToDelete.add(a);
			}
		}
		
		if (articlesToDelete.size() > 0)
		{
			delete articlesToDelete;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
	}
}