force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImpactedArticle__c/ImpactedArticle__c.object-meta.xml
<CustomObject>
    <description>Represents an impacted article for situations having single consignment but multiple article incidents on the same case. This object would indicate what all articles (one record per problem article) needs to be investigated as part of the case.</description>
    <label>Impacted Article</label>
    <nameField>
        <label>Impacted Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Impacted Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ImpactedArticle__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies and links to the problem article in a Consignment. This related list should not be on Consignment layout. Use this on Article layout instead.</description>
    <inlineHelpText>Identifies and links to the problem article in a Consignment</inlineHelpText>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Impacted Articles</relationshipLabel>
    <relationshipName>ImpactedArticles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ImpactedArticleTriggerHandlerTest.cls
/***
 * @description Test class for ImpactedArticleTriggerHandler
 * @author Seth Heang
 * @date 2024-09-13
 * @changelog
 * 2024-09-13 - Seth Heang - Created
 */
@IsTest
private class ImpactedArticleTriggerHandlerTest {

	@IsTest
	private static void testImpactedArticleTriggerHandlerMethods() {
		ImpactedArticleTriggerHandler mockModule = (ImpactedArticleTriggerHandler)MockUtility.mockUtility(ImpactedArticleTriggerHandler.class);
		Case caseTest = ApplicationTestDataFactoryCase.getCases(1, false)[0];
		insert caseTest;
		Article__c articleTest = ApplicationTestDataFactory.getArticles(1, false)[0];
		insert articleTest;
		ImpactedArticle__c impactedArticle = ApplicationTestDataFactory.getImpactedArticles(1, caseTest.Id, articleTest.Id, false)[0];
		insert impactedArticle;

		Assert.areEqual(true, Pattern.compile('\\bImpactedArticleTriggerHandler\\b').matcher(mockModule.toString()).find(), 'ImpactedArticleTriggerHandler should get called');
		Assert.areEqual(true, Pattern.compile('\\bArticleSubscriptionModule\\b').matcher(mockModule.toString()).find(), 'ArticleSubscriptionModule should get called');

		ImpactedArticleTriggerHandler handler = new ImpactedArticleTriggerHandler();
		handler.registerModules();

		Assert.areEqual(ImpactedArticle__c.SObjectType, handler.getSObjectType());
		List<SObjectType> sObjectTypes = new List<SObjectType>{
			ImpactedArticle__c.SObjectType,
			Case.SObjectType,
			Article__c.SObjectType
		};
		Assert.areEqual(sObjectTypes, ImpactedArticleTriggerHandler.getUnitOfWorkSObjectTypes(), 'SObjectType should match but instead got: ' + ImpactedArticleTriggerHandler.getUnitOfWorkSObjectTypes());
	}
}