force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/ArticleID__c.field-meta.xml
<CustomField>
    <fullName>ArticleID__c</fullName>
    <description>Tracking Number of Article</description>
    <externalId>true</externalId>
    <label>Article ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Article__c/fields/CID__c.field-meta.xml
<CustomField>
    <fullName>CID__c</fullName>
    <label>CID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>StarTrack Consignment Delivery Date</description>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Freight_Amount__c.field-meta.xml
<CustomField>
    <fullName>Freight_Amount__c</fullName>
    <description>StarTrack - Freight Amount of Consignment. Used in LDC Approvals.</description>
    <label>Freight Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>Field used to support the remediation process for missorted or looping parcels.</description>
    <formula>ArticleID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Field used to support the remediation process for missorted or looping parcels.</inlineHelpText>
    <label>Remediation Article ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Article</label>
</RecordType>

force-app/main/default/objects/Article__c/recordTypes/Consignment.recordType-meta.xml
<RecordType>
    <fullName>Consignment</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Consignment</label>
</RecordType>

force-app/main/default/objects/Case/fields/ArticleTest__c.field-meta.xml
<CustomField>
    <fullName>ArticleTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Call_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Call_Purpose__c</fullName>
    <description>Client&apos;s intent for calling</description>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Track &amp; Trace</fullName>
            </value>
            <value>
                <fullName>Driver ETA</fullName>
            </value>
            <value>
                <fullName>Card Left</fullName>
            </value>
            <value>
                <fullName>Pick up</fullName>
            </value>
            <value>
                <fullName>Request update</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payroll Enquiry</fullName>
            </value>
            <value>
                <fullName>HR Enquiry</fullName>
            </value>
            <value>
                <fullName>New Business Query</fullName>
            </value>
            <value>
                <fullName>Consumable Orders</fullName>
            </value>
            <value>
                <fullName>Special Services Enquiry</fullName>
            </value>
            <value>
                <fullName>Credit Enquiry</fullName>
            </value>
            <value>
                <fullName>I.T. Issue</fullName>
            </value>
            <value>
                <fullName>Account Management Enquiry</fullName>
            </value>
            <value>
                <fullName>Personal Call for Staff Member</fullName>
            </value>
            <value>
                <fullName>Next Flight</fullName>
            </value>
            <value>
                <fullName>Dangerous Goods</fullName>
            </value>
            <value>
                <fullName>StarTrack Branch Enquiry</fullName>
            </value>
            <value>
                <fullName>Voice Of Customer</fullName>
            </value>
            <value>
                <fullName>Business Solutions</fullName>
            </value>
            <value>
                <fullName>Late Delivery</fullName>
            </value>
            <value>
                <fullName>Security Incident</fullName>
            </value>
            <value>
                <fullName>Transit Warranty Enquiry</fullName>
            </value>
            <value>
                <fullName>Quoting/Pricing</fullName>
            </value>
            <value>
                <fullName>Credit Claim</fullName>
            </value>
            <value>
                <fullName>POD</fullName>
            </value>
            <value>
                <fullName>Delivery in Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Controlled Returns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <formula>IMAGE( 
CASE(RecordType.Name,
&apos;Transit Warranty Claim&apos;, &apos;/resource/StarTrackCaseIcons/Transit.png&apos;, 
&apos;Sales Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Sales.png&apos;, 
&apos;Pickup Booking Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Pickup.png&apos;,
&apos;Credit Dispute Claim&apos;, &apos;/resource/StarTrackCaseIcons/Credit.png&apos;,
&apos;Delivery Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/Delivery.png&apos;,
&apos;General Enquiry&apos;, &apos;/resource/StarTrackCaseIcons/General.png&apos;,
&apos;StarTrack Business Solutions Communications&apos;, &apos;/resource/StarTrackCaseIcons/BSCEmail.png&apos;, &apos;/resource/StarTrackCaseIcons/Other.png&apos;),&apos;No Image&apos; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Connote_number__c.field-meta.xml
<CustomField>
    <fullName>Connote_number__c</fullName>
    <description>Temporary field used by StarTrack Business Solutions Tactical Email Solution to allow consultants to document the connote number related to the enquiry</description>
    <label>Connote #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Consignment_Unique_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Consignment_Unique_External_ID__c</fullName>
    <description>StarTrack - Unique External ID for TEAM and Track &amp; Trace Consignment.</description>
    <inlineHelpText>Unique External ID for TEAM and Track &amp; Trace Consignment</inlineHelpText>
    <label>Consignment Unique External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Stream__c.field-meta.xml
<CustomField>
    <fullName>Customer_Stream__c</fullName>
    <formula>IMAGE( 
CASE(Account.StarTrack_Customer_Stream__c, 
&apos;Sapphire&apos;, &apos;/resource/StarTrackCaseIcons/Sapphire.png&apos;, 
&apos;Emerald&apos;, &apos;/resource/StarTrackCaseIcons/Emerald.png&apos;, 
&apos;Ruby&apos;, &apos;/resource/StarTrackCaseIcons/Ruby.png&apos;, 
&apos;&apos;, &apos;/resource/StarTrackCaseIcons/Other.png&apos;,&apos;/resource/StarTrackCaseIcons/Other.png&apos;),&apos;Other&apos; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Stream</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>StarTrack - Delivery Date</description>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Enquiry_Type__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Type__c</fullName>
    <description>StarTrack - Enquiry Type</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Purpose__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2nd Follow up</fullName>
            </value>
            <value>
                <fullName>3rd Follow up</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Aus Post</fullName>
            </value>
            <value>
                <fullName>Billing Dispute</fullName>
            </value>
            <value>
                <fullName>Billing issue</fullName>
            </value>
            <value>
                <fullName>Billing - Verification/Explanation</fullName>
            </value>
            <value>
                <fullName>Book in</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Business Feedback</fullName>
            </value>
            <value>
                <fullName>Call back request</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Casual 2nd Missed</fullName>
            </value>
            <value>
                <fullName>Casual 3rd Missed</fullName>
            </value>
            <value>
                <fullName>Casual 4th+ Missed</fullName>
            </value>
            <value>
                <fullName>CCM Exgratia (Cust Claim Met)</fullName>
            </value>
            <value>
                <fullName>Check Address</fullName>
            </value>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Confirm Rates</fullName>
            </value>
            <value>
                <fullName>Controlled Returns</fullName>
            </value>
            <value>
                <fullName>Copy of Connote</fullName>
            </value>
            <value>
                <fullName>Copy of Document</fullName>
            </value>
            <value>
                <fullName>Copy of Invoice</fullName>
            </value>
            <value>
                <fullName>Copy of POD</fullName>
            </value>
            <value>
                <fullName>Customer Urgency Requested</fullName>
            </value>
            <value>
                <fullName>Customs Held</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Delivery Dispute</fullName>
            </value>
            <value>
                <fullName>Delivery On Track</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Amount_of_Claim__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Claim__c</fullName>
    <description>StarTrack - Total Amount of Claim</description>
    <label>Total Amount of Claim</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/StarTrack_General_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>StarTrack_General_Enquiry</fullName>
    <active>true</active>
    <businessProcess>StarTrack General Enquiry</businessProcess>
    <description>StarTrack General enquiries case</description>
    <label>General Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/StarTrack_PUD_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>StarTrack_PUD_Enquiry</fullName>
    <active>true</active>
    <businessProcess>StarTrack PUD</businessProcess>
    <description>StarTrack CSC - Pickup &amp; Delivery</description>
    <label>Delivery Enquiry</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/StarTrack_Voice_of_Customer.recordType-meta.xml
<RecordType>
    <fullName>StarTrack_Voice_of_Customer</fullName>
    <active>true</active>
    <businessProcess>StartTrack VOC Enquiry</businessProcess>
    <description>Startrack recordtype used to capture voice of the customer enquiries</description>
    <label>Voice of Customer Enquiry</label>
</RecordType>

force-app/main/default/objects/StarTrack_Transfer_Case_Rule__c/StarTrack_Transfer_Case_Rule__c.object-meta.xml
<CustomObject>
    <description>StarTrack Transfer Case rules to determine case assignment based on certain criteria.</description>
    <label>StarTrack Transfer Case Rule</label>
    <nameField>
        <displayFormat>TCR-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StarTrack Transfer Case Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StarTrack_Transfer_Case_Rule__c/fields/Case_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Case_Purpose__c</fullName>
    <description>Captures case purpose value.</description>
    <label>Case Purpose</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Transfer_Case_Rule__c/fields/Case_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Case_RecordType__c</fullName>
    <description>Captures case record type value.</description>
    <label>Case RecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Transfer_Case_Rule__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>Captures case type value.</description>
    <label>Case Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Transfer_Case_Rule__c/fields/Customer_Stream__c.field-meta.xml
<CustomField>
    <fullName>Customer_Stream__c</fullName>
    <description>Captures custom stream value.</description>
    <label>Customer Stream</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StarTrackTrackingIDSearchUtil.cls
/**************************************************
Description:  Utility class for the startrack ID search module, this will hold all the validation and the detail logics for functionality
History:
--------------------------------------------------
2022-11-24 - H Liyanage - Created
2022-12-05 - Prerna Rahangdale Added a new TransferCaseQueuable and added Transfer Case feature.
**************************************************/
public with sharing class StarTrackTrackingIDSearchUtil {

    public static void getTrackingDetails(List<SObject> records) {
        List<Case> selectedCases = new List<Case>();
        for(Case cse:(List<Case>)records) {
            System.debug('StarTrackTrackingIDSearchModule:onAfterUpdate  cse '+cse);
            // if the reference has been changed
            if(cse.ReferenceID__c != null) {
                selectedCases.add(cse);
            }
        }

        System.debug('StarTrackTrackingIDSearchModule:onAfterUpdate selectedCases '+selectedCases.size());

        if(!selectedCases.isEmpty()) {
            System.enqueueJob(new TrackingSearchQueueable(selectedCases[0]));
        }
    }


    private without sharing class TrackingSearchQueueable implements Queueable, Database.AllowsCallouts {
        Case cse;
        //TODO : Hasantha move strings to constants or custom metadata
        Set<Id> caseRecordTypes = new Set<Id>{
                SObjectType.Case.getRecordTypeInfosByDeveloperName().get('StarTrack_PUD_Enquiry').getRecordTypeId()
                , SObjectType.Case.getRecordTypeInfosByDeveloperName().get('StarTrack_General_Enquiry').getRecordTypeId()
                , SObjectType.Case.getRecordTypeInfosByDeveloperName().get('StarTrack_Voice_of_Customer').getRecordTypeId()};

        public TrackingSearchQueueable(Case record) {
            this.cse = record;
        }

        public void execute(QueueableContext context) {
            try {
                System.debug('HASANTHA TEST MODULE 1 IN queable');
                if(this.cse.ArticleTest__c == null && this.cse.ReferenceID__c != null && caseRecordTypes.contains(this.cse.RecordTypeId)) {
                    System.debug('HASANTHA TEST MODULE 2 :this.cse '+this.cse.Id);
                    System.debug('HASANTHA TEST MODULE 3 :this.cse.ReferenceID__c'+ this.cse.ReferenceID__c);
                    StarTrackTrackingIDSearchService cont = StarTrackTrackingIDSearchService.newInstance();
                    cont.dateRange = '1';
                    cont.searchString = this.cse.ReferenceID__c;
                    cont.isConsole = false;
                    cont.map_searchCustomSettings.get(cont.fieldName).Callout_Search_Type__c = 'CONSIGNMENT';
                    cont.searchConsignment();
                    System.debug('HASANTHA TEST MODULE 3 :cont.lst_article[0]'+ cont.lst_article[0]);
                    if(validate(cont.lst_article[0])) {
                        System.debug('HASANTHA TEST MODULE 3 VALIDATED GOOD ');
                        assignAndUpdateCase(cont.lst_article[0],this.cse);
                    }
                }
            } catch (Exception ex) {
                // Error Logged to Exception object for analysis
                UTIL_LoggingService.logHandledException(
                        ex
                        , UserInfo.getOrganizationId()
                        , StarTrack_Constants.STARTRACK
                        , TrackingSearchQueueable.class.getName()
                        , 'TrackingSearchQueueable'
                        , StarTrack_Constants.ASYNC_QUEUEABLE
                        , LoggingLevel.ERROR);
            }
        }
    }

    /**
         * validate and assign the found article details
         * @param article
         * @param cse
         */
    public static void assignAndUpdateCase(Article__c article, Case cse) {
        try {
            case caseToBeUpdated = new Case();
            caseToBeUpdated.Id = cse.Id;
            caseToBeUpdated.ArticleTest__c = article.Id;
            caseToBeUpdated.Consignment_Unique_External_ID__c = article.ArticleID__c ;
            caseToBeUpdated.Connote_number__c  = article.Name ;

            // Only if Case’s Enquiry Type is LDC
            if (StarTrack_Constants.CASE_ENQUIRY_LDC.equalsIgnoreCase(cse.Enquiry_Type__c)) {
                caseToBeUpdated.Total_Amount_of_Claim__c = article.Freight_Amount__c;
            }
            caseToBeUpdated.Delivery_Date__c = String.isNotBlank(article.CID__c) ? Date.valueOf(article.CID__c.left(4) + '-' + article.CID__c.mid(4, 2) + '-' + article.CID__c.right(2)) : null;
            System.debug('HASANTHA TEST MODULE 4  IN queable cse ' + caseToBeUpdated);

            ElevatedSharingContext sharedContext = new ElevatedSharingContext();
            sharedContext.updateRecords(new List<Case>{caseToBeUpdated});
            System.enqueueJob(new TransferCaseQueueable(caseToBeUpdated));
        } catch (Exception e) {
            UTIL_LoggingService.logHandledException(
                    e
                    , UserInfo.getOrganizationId()
                    , StarTrack_Constants.STARTRACK
                    , StarTrackTrackingIDSearchUtil.class.getName()
                    , 'AssignAndUpdateCaseQueueable'
                    , StarTrack_Constants.ASYNC_QUEUEABLE
                    , LoggingLevel.ERROR
            );
        }
    }

    private without sharing class TransferCaseQueueable implements Queueable{
        Case cse;
        Set<Id> caseRecordTypes = new Set<Id>{
                SObjectType.Case.getRecordTypeInfosByDeveloperName().get('StarTrack_PUD_Enquiry').getRecordTypeId()
        };

        public  TransferCaseQueueable(Case record) {
            this.cse = record;
        }

        public void execute(QueueableContext context) {
            try {
                if(this.cse.ArticleTest__c != null && this.cse.ReferenceID__c != null && caseRecordTypes.contains(this.cse.RecordTypeId) && 'Web'.equalsIgnoreCase(this.cse.Origin)) {
                    Case caseToBeUpdated = new Case();
                    caseToBeUpdated.Id = cse.Id;
                    caseToBeUpdated.OwnerId = transferCase(this.cse);
                    ElevatedSharingContext sharedContext = new ElevatedSharingContext();
                    sharedContext.updateRecords(new List<Case>{caseToBeUpdated});
                }

            } catch (Exception ex) {
                // Error Logged to Exception object for analysis
                UTIL_LoggingService.logHandledException(
                        ex
                        , UserInfo.getOrganizationId()
                        , StarTrack_Constants.STARTRACK
                        , TransferCaseQueueable.class.getName()
                        , 'TransferCaseQueueable'
                        , StarTrack_Constants.ASYNC_QUEUEABLE
                        , LoggingLevel.ERROR);
            }
        }

    }

    /**
     * We can add more validations here if required
     * @param article
     *
     * @return
     */
    public static Boolean validate(Article__c article) {
        // TODO multiple consignments check
        return validateAddressFields(article);
    }

    /**
     * Validating nominated address fields to check wheter a value is exists in one of those defined fields in the article record,
     * if a value exists return true as a valid address
     * @param article
     *
     * @return
     */
    public static Boolean validateAddressFields(Article__c article) {
        for(String field: StarTrack_Constants.ARTICLE_ADDRESS_FIELDS) {
            if(article.get(field) != null || String.isNotBlank(String.valueOf(article.get(field)))) {
                return true;
            }
        }
        return false;
    }

    private without sharing class ElevatedSharingContext {

        /**
		 * Insert a list of sObject records in system mode
		 * @param List<sObject>
		*/
        private void updateRecords(List<sObject> recordList) {
            ApplicationDatabase.getInstance().dmlUpdate(recordList);
        }
    }

    /**
   * @description : This method is used to transfer the Startrack Cases created from the form and assign to valid queue
   * as per StarTrack_Transfer_Case_Rule__c.
   * @param Case whose Owner needs to be transferred.
   */
    public static Id transferCase(Case c){
        StartTrackTransferCaseRulesSelector selector = StartTrackTransferCaseRulesSelector.newInstance();
        Boolean ruleSatisfied = false;
        String queueName = null;
        Id ownerId = c.OwnerId;

        List<StarTrack_Transfer_Case_Rule__c> tc_rules = selector.selectAll(new Set<Object>{
                StartTrackTransferCaseRulesSelector.Options.ORDER_BY_ORDERFIELD,ApplicationSelector.Options.WITHOUT_DEFAULT_ORDER});
        try{
            for(StarTrack_Transfer_Case_Rule__c tc_rule : tc_rules){
                if((String.isNotBlank(tc_rule.Case_Purpose__c) ? c.Call_Purpose__c == tc_rule.Case_Purpose__c : true) && (String.isNotBlank(tc_rule.Case_RecordType__c) ? c.RecordType.Name == tc_rule.Case_RecordType__c : true) &&
                        (String.isNotBlank(tc_rule.Case_Type__c) ? c.Enquiry_Type__c == tc_rule.Case_Type__c : true) && (String.isNotBlank(tc_rule.Customer_Stream__c) ? c.Account.StarTrack_Customer_Stream__c == tc_rule.Customer_Stream__c : true) &&
                        (String.isNotBlank(tc_rule.Initial_Caller_Type__c) ? c.Initial_Caller_Type__c == tc_rule.Initial_Caller_Type__c : true) && (String.isNotBlank(tc_rule.Product_Group__c) ? c.ArticleTest__r.Product_Group__c == tc_rule.Product_Group__c : true) &&
                        (tc_rule.Business_Solutions_Customer__c ? c.Business_Solutions_Customer__c == tc_rule.Business_Solutions_Customer__c : true) && tc_rule.Service_Cloud_Rule__c){
                    if(tc_rule.Queue_Name__c == StarTrack_Constants.TRANSFER_QUEUE) {
                        if (!String.isBlank(c.Related_Billing_Account__r.BSC_Calc_Transfer_Queue__c)) {
                            queueName = c.Related_Billing_Account__r.BSC_Calc_Transfer_Queue__c;
                            ruleSatisfied = true;
                            break;
                        }
                    } else if(tc_rule.Queue_Name__c == StarTrack_Constants.ST_NETWORK_CUST_NOTIF && !StarTrack_Constants.CURRENT_USER_CAN_AUTO_CLOSE_CASE_FROM_TASK) {
                        ruleSatisfied = false;
                        continue;
                    } else{
                        // c.OwnerId = queryQueue(tc_rule.Queue_Name__c);
                        queueName = tc_rule.Queue_Name__c;
                        ruleSatisfied = true;
                        break;
                    }
                }
            }

            if(!ruleSatisfied && String.isNotBlank(c.Network__r.OwnerId)){
                ownerId = c.Network__r.OwnerId;
            }

            if(queueName != null) {
                GroupsSelector groupsSelector = GroupsSelector.newInstance();
                Map<Id,Group> queue = groupsSelector.selectByGroupTypeAndName(new Set<String>{'Queue'},new Set<String>{queueName});

                if(queue != null && !queue.isEmpty()){
                    // c.OwnerId = queue.keySet().iterator().next();
                    ownerId = queue.keySet().iterator().next();
                } else{
                    // c.OwnerId = null;
                    ownerId = null;
                    throw new ErrorException(StarTrack_Error_Messages__c.getValues('Queue not found') != null ?
                            StarTrack_Error_Messages__c.getValues('Queue not found').Value__c :
                            'Queue not found. Please make sure to reference the correct queue name.');
                }

            }
        }catch (Exception e) {
            System.debug('Error in transferring the Case'+e.getCause());
            UTIL_LoggingService.logHandledException(e, UserInfo.getOrganizationId(), StarTrack_Constants.STARTRACK, StarTrackTrackingIDSearchModule.class.getName(), 'transferCase', StarTrack_Constants.CASE_TRIGGER, LoggingLevel.ERROR);
            ruleSatisfied = false;
        }
        System.debug('The Owner Id of the case is '+ownerId);
        return ownerId;
    }

    /**
    * Custom Exception
    * */
    class ErrorException extends Exception{}

}