force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture network information for an article</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Receiver_Suburb__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Suburb__c</fullName>
    <description>StarTrack Receiver Suburb will be used store the suburb data of the receiver.</description>
    <label>Receiver Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ReceiverPostcode__c.field-meta.xml
<CustomField>
    <fullName>ReceiverPostcode__c</fullName>
    <label>Receiver Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>StarTrack Service Type will be used to store the service type of a particular article record.</description>
    <label>Delivery Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/STServiceType__c.field-meta.xml
<CustomField>
    <fullName>STServiceType__c</fullName>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ArticleTest__c.field-meta.xml
<CustomField>
    <fullName>ArticleTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>StarTrack Service Type field will be used to store the service type for a particular case record.</description>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Tailgate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Depot_Area__c/Depot_Area__c.object-meta.xml
<CustomObject>
    <description>StarTrack: Capture Depot Area information</description>
    <label>Depot Area</label>
    <nameField>
        <label>Depot Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depot Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot_Area__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <description>StarTrack: capture depot information for depot areas.</description>
    <label>Depot</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Depot Areas</relationshipLabel>
    <relationshipName>Depot_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Depot_Area_User__c/Depot_Area_User__c.object-meta.xml
<CustomObject>
    <description>StarTrack: Capture depot area user</description>
    <label>Depot Area User</label>
    <nameField>
        <label>Depot Area User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depot Area User</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Depot_Area_User__c/fields/Depot_Role__c.field-meta.xml
<CustomField>
    <fullName>Depot_Role__c</fullName>
    <description>StarTrack: Capture depot role for depot role person</description>
    <label>Depot Area</label>
    <referenceTo>Depot_Area__c</referenceTo>
    <relationshipLabel>Depot Area User</relationshipLabel>
    <relationshipName>Depot_Role_Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Depot_Area_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture user information for depot role person</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Depot_Role_Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Network_Manager__c.field-meta.xml
<CustomField>
    <fullName>Network_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner Info - Approval authority to assign new Licences to LPO or update existing Licences</description>
    <inlineHelpText>This user has the authority to approve new Licences to LPO or update existing Licences.</inlineHelpText>
    <label>Network Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Network</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/Parent_Network__c.field-meta.xml
<CustomField>
    <fullName>Parent_Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner Info - LPO belongs to this Parent Network.</description>
    <inlineHelpText>Parent Network authorised to approve changes to LPO.</inlineHelpText>
    <label>Parent Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Sub-ordinates</relationshipLabel>
    <relationshipName>Network</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postcode__c/Postcode__c.object-meta.xml
<CustomObject>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PostcodeMapping__c/PostcodeMapping__c.object-meta.xml
<CustomObject>
    <label>Postcode Mapping</label>
    <nameField>
        <displayFormat>F2P{000000000}</displayFormat>
        <label>Postcode Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postcode Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PostcodeMapping__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Postcode Mappings</relationshipLabel>
    <relationshipName>Postcode_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PostcodeMapping__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <referenceTo>Postcode__c</referenceTo>
    <relationshipLabel>Postcode Mappings</relationshipLabel>
    <relationshipName>Postcode_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PostcodeMapping__c/fields/Run_Dock__c.field-meta.xml
<CustomField>
    <fullName>Run_Dock__c</fullName>
    <description>StarTrack: Capture run dock information</description>
    <label>Run Dock</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrackDefaultValues__c/StarTrackDefaultValues__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will store the default value to be used in StarTrack controllers.</description>
    <label>StarTrack Default Values</label>
</CustomObject>

force-app/main/default/objects/StarTrackDefaultValues__c/fields/LIMIT__c.field-meta.xml
<CustomField>
    <fullName>LIMIT__c</fullName>
    <description>This field will store limit value for SOQL query.</description>
    <label>LIMIT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrackDefaultValues__c/fields/OFFSET__c.field-meta.xml
<CustomField>
    <fullName>OFFSET__c</fullName>
    <description>This field will store default offset value.</description>
    <label>OFFSET</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Search_Settings__c/Task_Search_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>StarTrack: Task search settings</description>
    <label>Task Search Settings</label>
</CustomObject>

force-app/main/default/objects/Task_Search_Settings__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in NetworkUserTriggerUtility to check environment /org</description>
    <label>User -Network Users</label>
</CustomObject>

force-app/main/default/classes/StarTrackTaskRListSidePanel_Cont_Test.cls
/*------------------------------------------------------------
Author:		Jen Karen Tan
Company:	   Accenture
Description:   Test class for StarTrack StarTrackTaskRListSidePanel controller
History
November 10, 2016 - Jen Karen Tan - Created
2024-09-20	Vasu Gorakati - Case Hand-off - Voice call records visibility to classic users
------------------------------------------------------------*/

@isTest
private class StarTrackTaskRListSidePanel_Cont_Test {
	@testSetup static void testSetup(){
		
		User support = new User(
			ProfileId = [SELECT Id FROM Profile WHERE Name = 'StarTrack Support'].Id,
			LastName = 'last',
			Email = 'test@user.com',
			Username = 'test@supportuser123.com',
			CompanyName = 'TEST',
			Title = 'title',
			Alias = 'alias',
			TimeZoneSidKey = 'America/Los_Angeles',
			EmailEncodingKey = 'UTF-8',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US');
		INSERT support;
		
		StarTrackDefaultValues__c sdv = new StarTrackDefaultValues__c();
		sdv.Name = 'Task Search';
		sdv.OFFSET__c = 0;
		sdv.LIMIT__c = 10;
		INSERT sdv;

		Task_Search_Settings__c tssA = new Task_Search_Settings__c();
		tssA.Name = 'My Area Tasks';
		tssA.Default__c = true;
		INSERT tssA;

		Task_Search_Settings__c tssB = new Task_Search_Settings__c();
		tssB.Name = 'Custom';
		INSERT tssB;

		Network__c testNetwork = TestDataProvider.createNetwork('Test Network', 1)[0];
		testNetwork.RecordTypeId = Schema.SObjectType.Network__c.getRecordTypeInfosByName().get('Metro').getRecordTypeId();
		INSERT testNetwork;

		Postcode__c testPostcode = new Postcode__c();
		testPostcode.Name = 'Test Postcode';
		INSERT testPostcode;

		PostcodeMapping__c testPostcodemap = new PostcodeMapping__c();
		testPostcodemap.Postcode__c = testPostcode.Id;
		testPostcodemap.Network__c = testNetwork.Id;
		testPostcodemap.Run_Dock__c = 'Test Post Code';
		INSERT testPostcodemap;

		Depot_Area__c testDepotArea = new Depot_Area__c();
		testDepotArea.Name = 'Test Depot Area';
		testDepotArea.Depot__c = testNetwork.Id;
		INSERT testDepotArea;

		Depot_Area_User__c testDepotAreaUser = new Depot_Area_User__c();
		testDepotAreaUser.Name = 'Test Depot Area User';
		testDepotAreaUser.Depot_Role__c = testDepotArea.Id;
		testDepotAreaUser.User__c = UserInfo.getUserId();
		INSERT testDepotAreaUser;
		
		Article__c testArticle = TestDataProvider.createTestArticle();
		testArticle.Service_Type__c = 'Express';
		testArticle.ReceiverPostcode__c = '1234';
		testArticle.Receiver_Suburb__c = 'TestSuburb';
		testArticle.STServiceType__c = 'Airlock';
		testArticle.Network__c = testNetwork.Id;
		INSERT testArticle;

		Case testCase = new Case();
		testCase.Origin = 'Email';
		testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Delivery Enquiry').getRecordTypeId();
		testCase.ArticleTest__c = testArticle.Id;
		testCase.Network__c = testNetwork.Id;
		INSERT testCase;
		
		CaseShare cs = new CaseShare(CaseAccessLevel = 'Edit', CaseId = testCase.Id, UserOrGroupId = support.Id);
		INSERT cs;
		
		List<Task> taskList = new List<Task>();
		Integer taskSize = 10;
		Id starTrackTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(StarTrack_Constants.TASK_RECTYPE_OPERATION).getRecordTypeId();
		for (Integer i = 0 ; i <= taskSize ; i++) {
			Task testTask = TestDataProvider.createTask(testCase.Id, null, 'StarTrack Task' + i);
			testTask.Depot_Role__c = testDepotArea.Id;
			testTask.Subject = 'Test' + i;
			testTask.Status = StarTrack_Constants.TASK_STATUS_NOTSTARTED;
			testTask.CaseObject__c = testCase.Id;
			testTask.Network__r = testNetwork;
			testTask.OwnerId = support.Id;
			testTask.RecordTypeId = starTrackTaskRecordTypeId;
			taskList.add(testTask);
		}
		
		INSERT taskList;
		
		List<VoiceCall> voiceCalls = ApplicationTestDataFactory.getVoiceCalls(1, false);
		voiceCalls.get(0).RelatedRecordId = testCase.Id;
		voiceCalls.get(0).CallType = 'Inbound';
		voiceCalls.get(0).VendorType = 'ContactCenter';
		voiceCalls.get(0).CallStartDateTime = System.now();
		voiceCalls.get(0).CallEndDateTime = System.now().addMinutes(5);
		voiceCalls.get(0).FromPhoneNumber = '+61 432 077 455';
		voiceCalls.get(0).ToPhoneNumber = 'CS_Test';
		insert voiceCalls;
	}
	
		@isTest static void testTaskRListSidePanel(){
			Integer tasksPerPage = 5;
			Case caseRec = [SELECT Id, Network__c, ArticleTest__c FROM Case LIMIT 1];
			User supportUser = new List<User>([SELECT Id, UserName FROM User WHERE UserName = 'test@supportuser123.com'])[0];	 		 	

			ApexPages.StandardController sc = null;
			StarTrackTaskRListSidePanel_Controller ctrl = null;

			Test.startTest();
				System.runAs(supportUser) {
					sc = new ApexPages.StandardController(caseRec);
					ctrl = new StarTrackTaskRListSidePanel_Controller(sc);
					System.assert(ctrl.getDisablePreviousBtn());
					ctrl.next();
					ctrl.previous();
				}
			Test.stopTest();
			
			System.assert(ctrl.retrievedTasks != null);
			System.assert(ctrl.retrievedTasks.size() > 0);
			System.assertEquals(tasksPerPage, ctrl.taskList.size());
			System.assert(ctrl.voiceCalls.size() > 0);

		}

		
}