force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture network information for an article</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/CaseInvestigation__c.object-meta.xml
<CustomObject>
    <label>Case Investigation</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Case Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Investigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseInvestigation__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Case Investigations</relationshipLabel>
    <relationshipName>Case_Investigations_Art</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <description>Formula to check the case investigation status is closed or not</description>
    <formula>ISPICKVAL( Status__c , &apos;Closed&apos;) ||  ISPICKVAL(Status__c, &apos;Closed - Required More Information&apos;)</formula>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/MilestoneTimeStartDatetime__c.field-meta.xml
<CustomField>
    <fullName>MilestoneTimeStartDatetime__c</fullName>
    <description>Stores the milestone start date time</description>
    <label>MilestoneTime Start Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Network__c.Contact_Facility__c</field>
            <operation>equals</operation>
            <value>MyNetwork</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Case Investigations</relationshipLabel>
    <relationshipName>Case_Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvestigation__c/fields/NetworkMilestoneCurrentTier__c.field-meta.xml
<CustomField>
    <fullName>NetworkMilestoneCurrentTier__c</fullName>
    <description>Stores the network milestone current tier</description>
    <label>Network Milestone Current Tier</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TransportEnquiryEmailMessagesModule_Test.cls
/**
 * @description Test class for TransportEnquiryEmailMessagesModule
 * @author Mahesh Parvathaneni
 * @date 2023-05-30
 * @changelog
*/

@IsTest
private class TransportEnquiryEmailMessagesModule_Test {

	/**
	* Scenario: Testing the after insert trigger event
	* Test to ensure the related cases have been updated with the correct email to address, network etc as per the metadata
	*/
	@IsTest
	static void testAfterInsertUpdateRelatedCases() {

		// =====================================
		// Data Preparation
		// =====================================
		List<Article__c> articles = ApplicationTestDataFactory.getArticles(2, true);
		List<Case> cases = ApplicationTestDataFactory.getCases(2, true);
		List<Network__c> networks = ApplicationTestDataFactory.getNetworks(2, true);
		List<CaseInvestigation__c> records = ApplicationTestDataFactory.getCaseInvestigations(1, cases[0].Id, articles[0], networks[0].Id, true);
		records.addAll(ApplicationTestDataFactory.getCaseInvestigations(1, cases[1].Id, articles[1], networks[1].Id, true));
		records[0].MilestoneTimeStartDatetime__c = Datetime.now();
		records[1].MilestoneTimeStartDatetime__c = Datetime.now();
		records[0].NetworkMilestoneCurrentTier__c = 1;
		records[1].NetworkMilestoneCurrentTier__c = 1;
		records[0] = (CaseInvestigation__c)ApplicationTestDataFactory.setUnwritableFields(records[0], new Map<String, Object>{'IsClosed__c' => false});
		records[1] = (CaseInvestigation__c)ApplicationTestDataFactory.setUnwritableFields(records[1], new Map<String, Object>{'IsClosed__c' => false});

		// =====================================
		// Stubbing
		// =====================================
		MilestoneService mockService = (MilestoneService)MockUtility.mockUtility(MilestoneService.class);
		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();
		ApplicationDatabase vMockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockService.calculateNextViolationDateForCaseInvestigation(new Set<Id>{records[0].Id, records[1].Id}, 
			STCINetworkMilestoneViolationModule.ENTITLEMENT_RULE_CASE_INVESTIGATION, STCINetworkMilestoneViolationModule.MILESTONE_TIER_TYPE_FACILITY))
			.thenReturn(new Map<Id, Datetime>{records[0].Id => Datetime.now().addDays(1), records[1].Id => Datetime.now().addDays(1)});
		MockUtility.Mocks.when(vMockDatabase.dmlUpdate((List<SObject>)fflib_Match.anyObject(), (Boolean)fflib_Match.anyBoolean())).thenAnswer(new MockUtility.AnswerGenericDMLUpdated());
		MockUtility.Mocks.stopStubbing();


		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		TransportEnquiryEmailMessagesModule.newInstance().onAfterInsert(records, mockUow);

		//should have attempted to call the Milestone Service
		((MilestoneService)MockUtility.Mocks.verify(mockService, MockUtility.Mocks.times(1))).calculateNextViolationDateForCaseInvestigation(new Set<Id>{records[0].Id, records[1].Id},
			STCINetworkMilestoneViolationModule.ENTITLEMENT_RULE_CASE_INVESTIGATION, STCINetworkMilestoneViolationModule.MILESTONE_TIER_TYPE_FACILITY);

		// should have attempted to update the case investigations
		((ApplicationDatabase)MockUtility.Mocks.verify(vMockDatabase, MockUtility.Mocks.times(1))).dmlUpdate((List<SObject>)fflib_Match.anyObject(), (Boolean)fflib_Match.eqBoolean(false));

		// PMD warning
		System.assert(true);

		Test.stopTest();
	}
	
}