force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <description>Created on MyNetwork project based on data mapping</description>
    <label>Product ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Article</label>
</RecordType>

force-app/main/default/objects/Case/fields/CaseTransferDate__c.field-meta.xml
<CustomField>
    <fullName>CaseTransferDate__c</fullName>
    <description>Stores the date and time when the case was handed off to classic team</description>
    <inlineHelpText>Stores the date and time when the case was handed off to classic team</inlineHelpText>
    <label>Case Transfer Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseTransferReason__c.field-meta.xml
<CustomField>
    <fullName>CaseTransferReason__c</fullName>
    <description>Reason selected by the agent when the case was handed off to the classic team.</description>
    <inlineHelpText>Reason selected by the agent when the case was handed off to the classic team.</inlineHelpText>
    <label>Case Transfer Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compensation required</fullName>
            </value>
            <value>
                <fullName>Network contact required</fullName>
            </value>
            <value>
                <fullName>Customer Care Specialist</fullName>
            </value>
            <value>
                <fullName>High Priority investigation</fullName>
            </value>
            <value>
                <fullName>Manager escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/SSSWDelivery.recordType-meta.xml
<RecordType>
    <fullName>SSSWDelivery</fullName>
    <active>true</active>
    <businessProcess>SSSW</businessProcess>
    <description>SSSW - Record Type to include &quot;Article&quot; Related Lists</description>
    <label>SSSW Delivery</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/StarTrack_PUD_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>StarTrack_PUD_Enquiry</fullName>
    <active>true</active>
    <businessProcess>StarTrack PUD</businessProcess>
    <description>StarTrack CSC - Pickup &amp; Delivery</description>
    <label>Delivery Enquiry</label>
</RecordType>

force-app/main/default/objects/ImpactedArticle__c/ImpactedArticle__c.object-meta.xml
<CustomObject>
    <description>Represents an impacted article for situations having single consignment but multiple article incidents on the same case. This object would indicate what all articles (one record per problem article) needs to be investigated as part of the case.</description>
    <label>Impacted Article</label>
    <nameField>
        <label>Impacted Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Impacted Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ImpactedArticle__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies and links to the problem article in a Consignment. This related list should not be on Consignment layout. Use this on Article layout instead.</description>
    <inlineHelpText>Identifies and links to the problem article in a Consignment</inlineHelpText>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Impacted Articles</relationshipLabel>
    <relationshipName>ImpactedArticles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/StarTrack_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>StarTrack custom settings</description>
    <label>StarTrack Settings</label>
</CustomObject>

force-app/main/default/objects/StarTrack_Settings__c/fields/EMS_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>EMS_Endpoint__c</fullName>
    <description>StarTrack - EMS Endpoint</description>
    <label>EMS Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Get_All_Consignment_Details__c.field-meta.xml
<CustomField>
    <fullName>Get_All_Consignment_Details__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls the behaviour of Consignment Search request message. If unchecked, then Action in the request body will be set to &quot;Level1&quot;. The response will include only Consignment Details, Article Details, Subdockets and Book-In Notes. if this field is checked, then the response will also include all Scan Events of Consignment and Articles and last 5 POD images.</description>
    <inlineHelpText>Should the Consignment Search Response contain Scan Events and PODs?</inlineHelpText>
    <label>Get All Consignment Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Log_for__c.field-meta.xml
<CustomField>
    <fullName>Log_for__c</fullName>
    <label>Log for</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Logging__c.field-meta.xml
<CustomField>
    <fullName>Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/StarTrack_ConSearch_Authentication_Level__c.field-meta.xml
<CustomField>
    <fullName>StarTrack_ConSearch_Authentication_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Level of Authentication for Consignment Search Interface</description>
    <inlineHelpText>1 - Basic Authentication
2 - Mutual SSL</inlineHelpText>
    <label>StarTrack ConSearch Authentication Level</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/StarTrack_ConSearch_Client_Cert__c.field-meta.xml
<CustomField>
    <fullName>StarTrack_ConSearch_Client_Cert__c</fullName>
    <description>StarTrack - ConSearch Client Cert</description>
    <label>StarTrack ConSearch Client Cert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Sync_Web_Service_Callout_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Sync_Web_Service_Callout_Timeout__c</fullName>
    <label>Sync Web Service Callout Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Use_Continuation_for_Consignment_Search__c.field-meta.xml
<CustomField>
    <fullName>Use_Continuation_for_Consignment_Search__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To use Continuation server for Consignment Search, set this to true.</description>
    <label>Use Continuation for Consignment Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Web_Service_Callout_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Web_Service_Callout_Timeout__c</fullName>
    <defaultValue>30</defaultValue>
    <description>StarTrack - Web Service Callout Timeout</description>
    <label>Async Web Service Callout Timeout</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/XML_Logging__c.field-meta.xml
<CustomField>
    <fullName>XML_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>XML Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnifiedCaseHandOffControllerTest.cls
/**
 * @description Test class for UnifiedCaseHandOffController
 * @author Vasu Gorakati
 * @date 2024-06-18
 * @changelog
 * 2024-06-18 - Vasu Gorakati - Case Hand-off
 * 2024-07-18 - Raghav Ravipati - Added changes to test duplicate consigment scenarios.
 **/
@isTest
public class UnifiedCaseHandOffControllerTest {
	@isTest
	static void testSingleArticleConsignment() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Article__c> articles = ApplicationTestDataFactory.getConsignments(1, true);
		List<Case> cases = ApplicationTestDataFactory.getCases(1, true);
		List<ImpactedArticle__c> impactedArticles = ApplicationTestDataFactory.getImpactedArticles(1, cases[0].Id, articles[0].Id, true);

		// =====================================
		// Stubbing
		// =====================================
		ArticlesSelector mockArticlesSelector = (ArticlesSelector) MockUtility.mockSelector(ArticlesSelector.class);
		CasesSelector mockCasesSelector = (CasesSelector) MockUtility.mockSelector(CasesSelector.class);
		ImpactedArticlesSelector mockImpactedArticlesSelector = (ImpactedArticlesSelector) MockUtility.mockSelector(ImpactedArticlesSelector.class);

		MockUtility.Mocks.startStubbing();

		// set up our responses
		MockUtility.Mocks.when(
				mockArticlesSelector.selectByArticleNames(new Set<String>{ articles[0].Name }, StarTrack_Constants.CON_REC_TYPE, new Set<Object>{ ArticlesSelector.Options.WITH_RECORDTYPE })
			)
			.thenReturn(new List<Article__c>{ articles[0] });
		MockUtility.Mocks.when(mockCasesSelector.selectById(new Set<Id>{ cases[0].Id }, new Set<Object>{ CasesSelector.Options.WITH_CONTACT }))
			.thenReturn(new Map<Id, Case>{ cases[0].Id => cases[0] });
		MockUtility.Mocks.when(mockImpactedArticlesSelector.selectByCaseId(new Set<Id>{ cases[0].Id }, new Set<Object>())).thenReturn(impactedArticles);

		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.when(mockDatabase.dmlUpdate((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLUpdated());
		MockUtility.Mocks.when(mockDatabase.dmlInsert((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLInserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		String businessUnit = CaseHandOffController.getBusinessUnit(articles[0].ProductId__c);

		CaseHandOffController.CaseHandOffWrapper request = new CaseHandOffController.CaseHandOffWrapper();
		request.articleId = '';
		request.businessUnit = businessUnit;
		request.caseId = cases[0].Id;
		request.caseRecordType = 'UnifiedInvestigation';
		request.comment = 'Testing';
		request.contactCenter = 'UnifiedAusPostHandoffTriageQueue';
		request.handoffReason = 'Network contact required';

		CaseHandOffController.handOffCase(request);

		Test.stopTest();

		// =====================================
		// Verification
		// =====================================
		Id caseSSSWDeliveryRecordType = ApplicationTestDataFactory.caseSSSWDeliveryRecordType;
		Id caseSSSWentitlement = CaseHandOffController.getSSSWEntitlementId();
		System.assertNotEquals(null, cases[0].CaseTransferDate__c, 'Case transfer date should be updated');
		System.assertEquals('Network contact required', cases[0].CaseTransferReason__c, 'Case transfer reason should be updated');
		System.assertEquals(caseSSSWentitlement, cases[0].EntitlementId, 'Case Entitlement should be set to Standard Entitlement - SSSW');
		System.assertEquals(caseSSSWDeliveryRecordType, cases[0].RecordTypeId, 'Record type should be set to SSSWDelivery');
	}

	@isTest
	static void testMultiArticleConsignment() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Article__c> articles = ApplicationTestDataFactory.getConsignments(2, true); // Example: 2 articles
		List<Case> cases = ApplicationTestDataFactory.getCases(1, true);
		List<ImpactedArticle__c> impactedArticles = ApplicationTestDataFactory.getImpactedArticles(2, cases[0].Id, articles[0].Id, true); // Example: 2 impacted articles

		// =====================================
		// Stubbing
		// =====================================
		ArticlesSelector mockArticlesSelector = (ArticlesSelector) MockUtility.mockSelector(ArticlesSelector.class);
		CasesSelector mockCasesSelector = (CasesSelector) MockUtility.mockSelector(CasesSelector.class);
		ImpactedArticlesSelector mockImpactedArticlesSelector = (ImpactedArticlesSelector) MockUtility.mockSelector(ImpactedArticlesSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		//set up responses
		MockUtility.Mocks.when(
				mockArticlesSelector.selectByArticleNames(new Set<String>{ articles[0].Name }, StarTrack_Constants.CON_REC_TYPE, new Set<Object>{ ArticlesSelector.Options.WITH_RECORDTYPE })
			)
			.thenReturn(articles);
		MockUtility.Mocks.when(mockCasesSelector.selectById(new Set<Id>{ cases[0].Id }, new Set<Object>{ CasesSelector.Options.WITH_CONTACT }))
			.thenReturn(new Map<Id, Case>{ cases[0].Id => cases[0] });
		MockUtility.Mocks.when(mockImpactedArticlesSelector.selectByCaseId(new Set<Id>{ cases[0].Id }, new Set<Object>())).thenReturn(impactedArticles);

		// Capture database updates and inserts
		MockUtility.Mocks.when(mockDatabase.dmlUpdate((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLUpdated());
		MockUtility.Mocks.when(mockDatabase.dmlInsert((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLInserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================

		Test.startTest();

		// Create wrapper for case handoff
		CaseHandOffController.CaseHandOffWrapper request = new CaseHandOffController.CaseHandOffWrapper();
		request.articleId = '';
		request.businessUnit = 'AustraliaPost';
		request.caseId = cases[0].Id;
		request.caseRecordType = 'UnifiedInvestigation';
		request.comment = 'Testing';
		request.contactCenter = 'UnifiedAusPostHandoffTriageQueue';
		request.handoffReason = 'Network contact required';

		// Call the method under test
		CaseHandOffController.handOffCase(request);

		Test.stopTest();

		// =====================================
		// Verification
		// =====================================
		List<List<sObject>> insertRecs = MockUtility.verifyAndCaptureInsertedDmlRecords(mockDatabase, 2);

		List<Case> insertedChildCases = new List<Case>();
		List<CaseComment> insertedCaseComments = new List<CaseComment>();

		for (List<SObject> insertList : insertRecs) {
			for (SObject record : insertList) {
				if (record instanceof Case) {
					insertedChildCases.add((Case) record);
				} else if (record instanceof CaseComment) {
					insertedCaseComments.add((CaseComment) record);
				}
			}
		}

		System.assertEquals(2, insertedChildCases.size());
		System.assertEquals(1, insertedCaseComments.size(), 'Case comment not inserted');
	}

	@isTest
	static void testStarTrackConsignmentSearch() {
		// =====================================
		// Data Preparation
		// =====================================

		insert new StarTrack_Settings__c(
			SetupOwnerId = UserInfo.getOrganizationId(),
			Get_All_Consignment_Details__c = true,
			EMS_Endpoint__c = 'testendpt',
			Web_Service_Callout_Timeout__c = 10,
			Use_Continuation_for_Consignment_Search__c = true,
			XML_Logging__c = true,
			Logging__c = true,
			Log_For__c = 'ALL USER',
			StarTrack_ConSearch_Authentication_Level__c = 2,
			StarTrack_ConSearch_Client_Cert__c = 'cert',
			Sync_Web_Service_Callout_Timeout__c = 5
		);

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		CaseHandoffController controller = new CaseHandoffController();

		Continuation conti = (Continuation) CaseHandoffController.searchConsignmentStarTrack('2AT71923');

		// Perform mock callout
		HttpResponse response = new HttpResponse();
		response.setBody(StarTrackContinuationCalloutMock.getResponse_singleConsign());

		// Set the fake response for the continuation
		Map<String, HttpRequest> requests = conti.getRequests();
		String requestLabel = requests.keyset().iterator().next();
		Test.setContinuationResponse(requestLabel, response);

		// Invoke callback method
		// note this will call the controller.processSearchRemoteConsignment() instance method
		// the actual continuation call from the remote action calls the static processSearchRemoteConsignment(state) method
		Object result = Test.invokeContinuationMethod(controller, conti);

		Test.stopTest();

		System.assertNotEquals(null, result, 'Result should be set');
	
	}
	/**
	* To test Duplicate consigments that has duplicate records that are less than 6 months old
	*/
	@isTest
	static void testStarTrackSearchWithDuplicatesLessThanSixmonths() {
		// =====================================
		// Data Preparation
		// =====================================

		insert new StarTrack_Settings__c(
			SetupOwnerId = UserInfo.getOrganizationId(),
			Get_All_Consignment_Details__c = true,
			EMS_Endpoint__c = 'testendpt',
			Web_Service_Callout_Timeout__c = 10,
			Use_Continuation_for_Consignment_Search__c = true,
			XML_Logging__c = true,
			Logging__c = true,
			Log_For__c = 'ALL USER',
			StarTrack_ConSearch_Authentication_Level__c = 2,
			StarTrack_ConSearch_Client_Cert__c = 'cert',
			Sync_Web_Service_Callout_Timeout__c = 5
		);

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		CaseHandoffController controller = new CaseHandoffController();

		Continuation conti = (Continuation) CaseHandoffController.searchConsignmentStarTrack('2AT71923');

		// Perform mock callout
		HttpResponse response = new HttpResponse();
		response.setBody(StarTrackContinuationCalloutMock.getResponse_multiConsignWhereAllConsignmentsWithinLast6Months());

		// Set the fake response for the continuation
		Map<String, HttpRequest> requests = conti.getRequests();
		String requestLabel = requests.keyset().iterator().next();
		Test.setContinuationResponse(requestLabel, response);

		// Invoke callback method
		// note this will call the controller.processSearchRemoteConsignment() instance method
		// the actual continuation call from the remote action calls the static processSearchRemoteConsignment(state) method
		Object result = Test.invokeContinuationMethod(controller, conti);
		List<Article__c> articles = (List<Article__c>) result;
		Test.stopTest();
		System.assertNotEquals(null, result, 'Result should be set');
		System.assertEquals(2, articles.size(), 'Multiple articles found whoes date sent is less than 6 months');	
	}
	/**
	* To test Duplicate consigments that has only one record that are less than 6 months old
	*/
	@isTest
	static void testStarTrackSearchWithMultipleRecordsAndOneIsLessThanSixmonths() {
		// =====================================
		// Data Preparation
		// =====================================

		insert new StarTrack_Settings__c(
			SetupOwnerId = UserInfo.getOrganizationId(),
			Get_All_Consignment_Details__c = true,
			EMS_Endpoint__c = 'testendpt',
			Web_Service_Callout_Timeout__c = 10,
			Use_Continuation_for_Consignment_Search__c = true,
			XML_Logging__c = true,
			Logging__c = true,
			Log_For__c = 'ALL USER',
			StarTrack_ConSearch_Authentication_Level__c = 2,
			StarTrack_ConSearch_Client_Cert__c = 'cert',
			Sync_Web_Service_Callout_Timeout__c = 5
		);

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		CaseHandoffController controller = new CaseHandoffController();

		Continuation conti = (Continuation) CaseHandoffController.searchConsignmentStarTrack('2AT71923');

		// Perform mock callout
		HttpResponse response = new HttpResponse();
		response.setBody(StarTrackContinuationCalloutMock.getResponse_multiConsignWithOneConsignmentWithinLast6Months());

		// Set the fake response for the continuation
		Map<String, HttpRequest> requests = conti.getRequests();
		String requestLabel = requests.keyset().iterator().next();
		Test.setContinuationResponse(requestLabel, response);

		// Invoke callback method
		// note this will call the controller.processSearchRemoteConsignment() instance method
		// the actual continuation call from the remote action calls the static processSearchRemoteConsignment(state) method
		Object result = Test.invokeContinuationMethod(controller, conti);
		List<Article__c> articles = (List<Article__c>) result;
		Test.stopTest();

		System.assertNotEquals(null, result, 'Result should be set');		
		System.assertEquals(1, articles.size(), 'got the recent article and it is less than 6 months');
	
	}

	@isTest
	static void testStarTrackScenario() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Article__c> articles = ApplicationTestDataFactory.getConsignments(1, true);
		List<Case> cases = ApplicationTestDataFactory.getCases(1, true);
		List<ImpactedArticle__c> impactedArticles = ApplicationTestDataFactory.getImpactedArticles(1, cases[0].Id, articles[0].Id, true);

		// =====================================
		// Stubbing
		// =====================================
		ArticlesSelector mockArticlesSelector = (ArticlesSelector) MockUtility.mockSelector(ArticlesSelector.class);
		CasesSelector mockCasesSelector = (CasesSelector) MockUtility.mockSelector(CasesSelector.class);
		ImpactedArticlesSelector mockImpactedArticlesSelector = (ImpactedArticlesSelector) MockUtility.mockSelector(ImpactedArticlesSelector.class);

		MockUtility.Mocks.startStubbing();

		//Set up responses
		MockUtility.Mocks.when(
				mockArticlesSelector.selectByArticleNames(new Set<String>{ articles[0].Name }, StarTrack_Constants.CON_REC_TYPE, new Set<Object>{ ArticlesSelector.Options.WITH_RECORDTYPE })
			)
			.thenReturn(new List<Article__c>{ articles[0] });
		MockUtility.Mocks.when(mockCasesSelector.selectById(new Set<Id>{ cases[0].Id }, new Set<Object>{ CasesSelector.Options.WITH_CONTACT }))
			.thenReturn(new Map<Id, Case>{ cases[0].Id => cases[0] });
		MockUtility.Mocks.when(mockImpactedArticlesSelector.selectByCaseId(new Set<Id>{ cases[0].Id }, new Set<Object>())).thenReturn(impactedArticles);

		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();
		MockUtility.Mocks.when(mockDatabase.dmlUpdate((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLUpdated());
		MockUtility.Mocks.when(mockDatabase.dmlInsert((List<SObject>) fflib_Match.anyObject())).thenAnswer(new MockUtility.AnswerGenericDMLInserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		CaseHandOffController.CaseHandOffWrapper request = new CaseHandOffController.CaseHandOffWrapper();
		request.articleId = articles[0].Id;
		request.businessUnit = 'StarTrack';
		request.caseId = cases[0].Id;
		request.caseRecordType = 'UnifiedInvestigation';
		request.comment = 'Testing';
		request.contactCenter = 'UnifiedStarTrackHandoffTriageQueue';
		request.handoffReason = 'Network contact required';

		CaseHandOffController.handOffCase(request);

		Test.stopTest();

		// =====================================
		// Verification
		// =====================================
		Id caseStarTrackDeliveryEnquiryRecordType = ApplicationTestDataFactory.caseStarTrackDeliveryEnquiryRecordType;
		System.assertNotEquals(null, cases[0].CaseTransferDate__c, 'Case transfer date should be updated');
		System.assertEquals('Network contact required', cases[0].CaseTransferReason__c, 'Case transfer reason should be updated');
		System.assertEquals(caseStarTrackDeliveryEnquiryRecordType, cases[0].RecordTypeId, 'Record type should be set to StarTrack_PUD_Enquiry');
	}
}