force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSSW - Collection of multiple Articles used to track set of Articles</description>
    <label>Consignment</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Date_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent__c</fullName>
    <description>StarTrack: Capture date sent information</description>
    <label>Date Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ExpectedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDeliveryDate__c</fullName>
    <description>SSSW</description>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture network information for an article</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>System that generated the consignment record.</description>
    <inlineHelpText>This Consignment record is generated by this system.</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TEAM</fullName>
            </value>
            <value>
                <fullName>TRACK &amp; TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book_In_Note__c/Book_In_Note__c.object-meta.xml
<CustomObject>
    <description>StarTrack consignment book-in notes.</description>
    <label>Book-In Note</label>
    <nameField>
        <label>Book-In Note ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book-In Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_In_Note__c/fields/By__c.field-meta.xml
<CustomField>
    <fullName>By__c</fullName>
    <label>By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_In_Note__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <label>Consignment</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Book-In Notes</relationshipLabel>
    <relationshipName>Book_In_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_In_Note__c/fields/Date_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Entered__c</fullName>
    <label>Date Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Book_In_Note__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ArticleTest__c.field-meta.xml
<CustomField>
    <fullName>ArticleTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>StarTrack - Source System</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Peoplesoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Proof_of_Delivery__c/Proof_of_Delivery__c.object-meta.xml
<CustomObject>
    <label>Proof of Delivery</label>
    <nameField>
        <label>Proof of Delivery ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proof of Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proof_of_Delivery__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Proof of Deliveries</relationshipLabel>
    <relationshipName>Proof_of_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proof_of_Delivery__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <label>Delivery Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proof_of_Delivery__c/fields/POD_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>POD_Received_Date__c</fullName>
    <label>POD Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Proof_of_Delivery__c/fields/QC_Status__c.field-meta.xml
<CustomField>
    <fullName>QC_Status__c</fullName>
    <label>QC Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proof_of_Delivery__c/fields/SignatureXString__c.field-meta.xml
<CustomField>
    <fullName>SignatureXString__c</fullName>
    <description>Text field to be used for signature - StarTrack</description>
    <label>Signature XString</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proof_of_Delivery__c/fields/Signed_by__c.field-meta.xml
<CustomField>
    <fullName>Signed_by__c</fullName>
    <label>Signed by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/StarTrack_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>StarTrack custom settings</description>
    <label>StarTrack Settings</label>
</CustomObject>

force-app/main/default/objects/StarTrack_Settings__c/fields/EMS_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>EMS_Endpoint__c</fullName>
    <description>StarTrack - EMS Endpoint</description>
    <label>EMS Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Get_All_Consignment_Details__c.field-meta.xml
<CustomField>
    <fullName>Get_All_Consignment_Details__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls the behaviour of Consignment Search request message. If unchecked, then Action in the request body will be set to &quot;Level1&quot;. The response will include only Consignment Details, Article Details, Subdockets and Book-In Notes. if this field is checked, then the response will also include all Scan Events of Consignment and Articles and last 5 POD images.</description>
    <inlineHelpText>Should the Consignment Search Response contain Scan Events and PODs?</inlineHelpText>
    <label>Get All Consignment Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Log_for__c.field-meta.xml
<CustomField>
    <fullName>Log_for__c</fullName>
    <label>Log for</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Logging__c.field-meta.xml
<CustomField>
    <fullName>Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/StarTrack_ConSearch_Authentication_Level__c.field-meta.xml
<CustomField>
    <fullName>StarTrack_ConSearch_Authentication_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Level of Authentication for Consignment Search Interface</description>
    <inlineHelpText>1 - Basic Authentication
2 - Mutual SSL</inlineHelpText>
    <label>StarTrack ConSearch Authentication Level</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/StarTrack_ConSearch_Client_Cert__c.field-meta.xml
<CustomField>
    <fullName>StarTrack_ConSearch_Client_Cert__c</fullName>
    <description>StarTrack - ConSearch Client Cert</description>
    <label>StarTrack ConSearch Client Cert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Sync_Web_Service_Callout_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Sync_Web_Service_Callout_Timeout__c</fullName>
    <label>Sync Web Service Callout Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Use_Continuation_for_Consignment_Search__c.field-meta.xml
<CustomField>
    <fullName>Use_Continuation_for_Consignment_Search__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To use Continuation server for Consignment Search, set this to true.</description>
    <label>Use Continuation for Consignment Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/Web_Service_Callout_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Web_Service_Callout_Timeout__c</fullName>
    <defaultValue>30</defaultValue>
    <description>StarTrack - Web Service Callout Timeout</description>
    <label>Async Web Service Callout Timeout</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StarTrack_Settings__c/fields/XML_Logging__c.field-meta.xml
<CustomField>
    <fullName>XML_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>XML Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/Sub_Docket__c.object-meta.xml
<CustomObject>
    <label>Sub-Docket</label>
    <nameField>
        <label>Sub-Docket ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Dockets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Docket__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Sub-Dockets</relationshipLabel>
    <relationshipName>Sub_Dockets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/fields/Date_Registered__c.field-meta.xml
<CustomField>
    <fullName>Date_Registered__c</fullName>
    <label>Date Registered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/fields/Delivery_Depot__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Depot__c</fullName>
    <label>Delivery Depot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <label>Payer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/fields/Payer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payer_Account_Number__c</fullName>
    <label>Payer Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_Docket__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StarTrackConsignmentDetails_Test.cls
/**
 ** Description: Test Class for StarTrackConsignmentDetails_ControllerX class
 ** Author: David Catindoy(CloudSherpas)
 ** Date Created: JAN.7.2016
 ** History:--------------------------------------------
 **         JAN.7.2016 David Catindoy - Created
 **         JAN.7.2016 Patrick James Franco - Added test method for attachPODSignatureToCase
 **/
@isTest
private class StarTrackConsignmentDetails_Test {

    @testSetup static void testSetup(){
        Network__c testNetwork = TestDataProvider.createNetwork('Test Network', 1)[0];
        INSERT testNetwork;

        Article__c testCon = TestDataProvider.createTestArticle();
        testCon.Network__c = testNetwork.Id;
        testCon.Date_Sent__c = System.today();
        testCon.ExpectedDeliveryDate__c = System.today()+1;
        INSERT testCon;

        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Origin = 'Email';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Transit Warranty Claim').getRecordTypeId();
        testCase.Network__c = testNetwork.Id;
        testCase.ArticleTest__c = testCon.Id;
        INSERT testCase;

        Id creditClaim = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Credit Dispute Claim').getRecordTypeId();
        List<Case> newCases = new List<Case>();
        for(Integer i=0; i<5; i++){
            Case newCase = new Case(Subject = 'Test Case ' + i, Origin = 'Phone', RecordTypeId = creditClaim, Network__c = testNetwork.Id, ArticleTest__c = testCon.Id);
            newCases.add(newCase);
        }
        INSERT newCases;

        Book_In_Note__c bookIn = new Book_In_Note__c(Name = 'Sample Book-In', Date_Entered__c = System.now(), By__c = 'David Catindoy', Notes__c = 'Sample Note', Consignment__c = testCon.Id);
        INSERT bookIn;

        Sub_Docket__c subDocket = new Sub_Docket__c(Name = 'Sample Subdocket', Date_Registered__c = System.now(), Delivery_Depot__c = 'Manila', Supervisor__c = 'Wayne Helena', Payer__c = 'Patrick Franco', Payer_Account_Number__c = '9663649086', Consignment__c = testCon.Id);
        INSERT subDocket;

        Proof_of_Delivery__c deliveryProof = new Proof_of_Delivery__c(Name = '93KDH87FH', Signed_by__c = 'David Catindoy', POD_Received_Date__c = System.now(), Delivery_Address__c = 'Sample Delivery Address', QC_Status__c = 'Verified', Consignment__c = testCon.Id);
        INSERT deliveryProof;

        Attachment attach = new Attachment(Name = 'Test Attachment', Body = Blob.valueOf('Unit Test Attachment Body'), ParentId = deliveryProof.Id);
        INSERT attach;
    }

    @isTest static void testRelatedRecords() {
        Case caseRec = [SELECT Id, Network__c, ArticleTest__c, ArticleTest__r.Name, RecordType.Name FROM Case WHERE Subject = 'Test Case'];
        Test.setCurrentPage(Page.StarTrackConsignmentDetails);

        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
            StarTrackConsignmentDetails_ControllerX ctrl = new StarTrackConsignmentDetails_ControllerX(sc);
        Test.stopTest();

        //test related records
        System.assertEquals(5, ctrl.relatedCases.size());
        System.assertEquals(1, ctrl.relatedNotes.size());
        System.assertEquals(1, ctrl.relatedSubdockets.size());
        System.assertEquals(1, ctrl.relatedPODs.size());
    }

    @isTest static void testAttachPODSignatureToCase() {
        Case caseRec = [SELECT Id, ArticleTest__c FROM Case WHERE Subject = 'Test Case'];

        Proof_of_Delivery__c testPOD = new Proof_of_Delivery__c();
        testPOD.Name = 'Test POD';
        testPOD.Consignment__c = caseRec.ArticleTest__c;
        testPOD.Signed_by__c = 'Tester';
        testPOD.SignatureXString__c = 'iVBORw0KGgoAAAANSUhEUgAAAPoAAABkAQMAAACVTr9NAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURQAAAP///6XZn90AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEnSURBVEjH7dMxTgMxEAXQ3CRHyRE4Qs5B5WOk5AgpU1CYG+QAKHJBsVVioUhYizMeZgxCCO3+X0C57lZ66/F8j1eK19NqAQtYwAJ+r8zADoGi2u4JGBsCVn/QgMEDBElbIGBUeIZoxyQgYxDsjAQEFQCa/46BYCB6ZcCirABUSwqCYkFgYDcBQZa+zTxIlYFCQDwqnuoYCQjB68yD1m8agbHXmQfSGwgAZAKql/+cuGlQIgO+uwBw6XUAODPw7B0UAA4M7L2DDMDWQZoHLTrYAOAv8yunSXDT76c7DcRBBaD6LAwAFAcJgMF73ABwtJRuCsBe9fUFga1FsQagxZ9fE0AYqIGAN/0rODNwYuCRgQMDdwS0SIAEAt6VgJGBKwOZgcSA/jv4AFz3QW6D/iIMAAAAAElFTkSuQmCC';
        INSERT testPOD;

        Attachment attach = [SELECT Id FROM Attachment WHERE Name = 'Test Attachment'];
        Test.setCurrentPage(Page.StarTrackConsignmentDetails);
        ApexPages.currentPage().getParameters().put('sPODId', testPOD.Id);
        ApexPages.currentPage().getParameters().put('attachmentId', attach.Id);

        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
            StarTrackConsignmentDetails_ControllerX ctrl = new StarTrackConsignmentDetails_ControllerX(sc);
            ctrl.attachPODSignatureToCase();
            //test if attachment is attached to the Case
            System.assert(![SELECT Id FROM Attachment WHERE ParentId = :caseRec.Id].isEmpty());
        Test.stopTest();

    }

    @isTest static void testAttachPODSignatureToCase_TrackNTrace() {
        Case caseRec = [SELECT Id, ArticleTest__c FROM Case WHERE Subject = 'Test Case'];
        Article__c artRec = [SELECT Id, Source_System__c FROM Article__c WHERE Id =: caseRec.ArticleTest__c];
        artRec.Source_System__c = 'TRACK & TRACE';
        UPDATE artRec;

        Proof_of_Delivery__c testPOD = new Proof_of_Delivery__c();
        testPOD.Name = 'Test POD';
        testPOD.Consignment__c = caseRec.ArticleTest__c;
        testPOD.Signed_by__c = 'Tester';
        testPOD.SignatureXString__c = 'iVBORw0KGgoAAAANSUhEUgAAAPoAAABkAQMAAACVTr9NAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURQAAAP///6XZn90AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEnSURBVEjH7dMxTgMxEAXQ3CRHyRE4Qs5B5WOk5AgpU1CYG+QAKHJBsVVioUhYizMeZgxCCO3+X0C57lZ66/F8j1eK19NqAQtYwAJ+r8zADoGi2u4JGBsCVn/QgMEDBElbIGBUeIZoxyQgYxDsjAQEFQCa/46BYCB6ZcCirABUSwqCYkFgYDcBQZa+zTxIlYFCQDwqnuoYCQjB68yD1m8agbHXmQfSGwgAZAKql/+cuGlQIgO+uwBw6XUAODPw7B0UAA4M7L2DDMDWQZoHLTrYAOAv8yunSXDT76c7DcRBBaD6LAwAFAcJgMF73ABwtJRuCsBe9fUFga1FsQagxZ9fE0AYqIGAN/0rODNwYuCRgQMDdwS0SIAEAt6VgJGBKwOZgcSA/jv4AFz3QW6D/iIMAAAAAElFTkSuQmCC';
        INSERT testPOD;

        Test.setCurrentPage(Page.StarTrackConsignmentDetails);
        ApexPages.currentPage().getParameters().put('sPODId', testPOD.Id);

        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
            StarTrackConsignmentDetails_ControllerX ctrl = new StarTrackConsignmentDetails_ControllerX(sc);
            ctrl.attachPODSignatureToCase();
            //test if attachment is attached to the Case
            System.assert(![SELECT Id FROM Attachment WHERE ParentId = :caseRec.Id].isEmpty());
        Test.stopTest();

    }

    @isTest
    public static void testConsignSearch_singleResponse() {

        INSERT new StarTrack_Settings__c(SetupOwnerId = UserInfo.getOrganizationId(), 
        Get_All_Consignment_Details__c = true,
        EMS_Endpoint__c = 'testendpt',
        Web_Service_Callout_Timeout__c = 10,
        Use_Continuation_for_Consignment_Search__c = true,
        XML_Logging__c = true,
        Logging__c = true,
        Log_For__c = 'ALL USER',
        StarTrack_ConSearch_Authentication_Level__c = 2,
        StarTrack_ConSearch_Client_Cert__c = 'cert',
        Sync_Web_Service_Callout_Timeout__c = 5
        );
        
        Case caseRec = [SELECT Id, Network__c, ArticleTest__c, ArticleTest__r.Name FROM Case WHERE Subject = 'Test Case']; 
        //List<Article__c> testArticle = new List<Article__c>([SELECT Id FROM Article__c WHERE Id =: caseRec.ArticleTest__c]);

        ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
        StarTrackConsignmentDetails_ControllerX cont = new StarTrackConsignmentDetails_ControllerX(sc);

        Test.startTest();        
        // Invoke the continuation by calling the action method
        Continuation conti = cont.searchConsignment();

        // Verify that the continuation has the proper requests
        Map<String, HttpRequest> requests = conti.getRequests();
        System.assertEquals(requests.size(), 1);

        // Perform mock callout 
        HttpResponse response = new HttpResponse();
        response.setBody(StarTrackContinuationCalloutMock.getResponse_singleConsign());

        // Set the fake response for the continuation
        String requestLabel = requests.keyset().iterator().next();
        Test.setContinuationResponse(requestLabel, response);

        // Invoke callback method
        Object result = Test.invokeContinuationMethod(cont, conti);
        System.debug(cont);
        
        cont.logTime();
        Test.stopTest();

        // result is the return value of the callback
        System.assertEquals(null, result);               
    }
}