force-app/main/default/objects/APT_APPC_Definition__c/APT_APPC_Definition__c.object-meta.xml
<CustomObject>
    <description>APPC Zone Mappings object is used to get the destination zone details based on product and price model. This information is used to display destination zone on View RateCard, Proposal and Contract Document for Australia Post Parcel Contract Product.</description>
    <label>APPC Zone Mapping</label>
    <nameField>
        <label>APPC Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APPC Zone Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_APPC_Definition__c/fields/APT_Dest_Zone1__c.field-meta.xml
<CustomField>
    <fullName>APT_Dest_Zone1__c</fullName>
    <description>This field represent the Destination e.g. National, Same State, Near State, Interstate.
This information will be print on ViewRatecard, Proposal and Contract document.</description>
    <label>Dest Zone1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_APPC_Definition__c/fields/APT_Dest_Zone2__c.field-meta.xml
<CustomField>
    <fullName>APT_Dest_Zone2__c</fullName>
    <description>This field represent the Destination Zone e.g. either Capital/Local, Country, Metro, and each State in case of Z60.
This information will be used to map it with Pricing Information to pull what needs to be Print on ViewRatecard, Proposal and Contract document.</description>
    <label>Dest Zone2</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_APPC_Definition__c/fields/APT_Dest_Zone2_In_RateCard__c.field-meta.xml
<CustomField>
    <fullName>APT_Dest_Zone2_In_RateCard__c</fullName>
    <description>This field represent the Destination Zone e.g. either Capital/Local, Country, Metro, and each State in case of Z60.
This information will be used to Print on ViewRatecard, Proposal and Contract document.</description>
    <label>Dest Zone2 In RateCard</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_APPC_Definition__c/fields/APT_Lodgement__c.field-meta.xml
<CustomField>
    <fullName>APT_Lodgement__c</fullName>
    <description>Lodgment values eg Capital, Country, Metro</description>
    <label>Lodgement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APT_APPC_Definition__c/fields/APT_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>APT_Price_Model__c</fullName>
    <description>Price model value for eg Z3, Z6, Z9</description>
    <label>Price Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z003</fullName>
                <label>Z3</label>
            </value>
            <value>
                <fullName>Z006</fullName>
                <label>Z6</label>
            </value>
            <value>
                <fullName>Z009</fullName>
                <label>Z9</label>
            </value>
            <value>
                <fullName>Z060</fullName>
                <label>Z60</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__AllowManualAdjustment__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AllowManualAdjustment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether manual price adjustments are allowed for the line item</description>
    <label>Allow Manual Adjustment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__NetAdjustmentPercent__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__NetAdjustmentPercent__c</fullName>
    <description>The net adjustment percent</description>
    <label>Net Adjustment (%)</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__OptionId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__OptionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected option</description>
    <label>Option</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Option Line Items</relationshipLabel>
    <relationshipName>OptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__PrimaryLineNumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PrimaryLineNumber__c</fullName>
    <description>Represents the unique number for each primary line item</description>
    <label>Primary Line Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/Apttus_Config2__PriceListItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__AllowManualAdjustment__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AllowManualAdjustment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether manual price adjustments are allowed for the product</description>
    <label>Allow Manual Adjustment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductAttributeValue__c/Apttus_Config2__ProductAttributeValue__c.object-meta.xml
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <label>Product Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__ProductAttributeValue__c/fields/APT_Postcode__c.field-meta.xml
<CustomField>
    <fullName>APT_Postcode__c</fullName>
    <label>Lodgement Postcode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductAttributeValue__c/fields/APT_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_Type__c</fullName>
    <formula>IF((APT_Returns_of_Total_Annual_Volume__c) &gt; 0.4, &apos;EPR1&apos;, &apos;EPR2&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__ProductAttributeValue__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CAT1</fullName>
            </value>
            <value>
                <fullName>CAT2</fullName>
            </value>
            <value>
                <fullName>CAT3</fullName>
            </value>
            <value>
                <fullName>CAT4</fullName>
            </value>
            <value>
                <fullName>CAT5</fullName>
            </value>
            <value>
                <fullName>CAT6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Apttus_Product_Classification__c.field-meta.xml
<CustomField>
    <fullName>APT_Apttus_Product_Classification__c</fullName>
    <description>Classifies wheather the product belong to speed, feature or return group</description>
    <label>Apttus Product Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Postal Services</fullName>
            </value>
            <value>
                <fullName>Parcel Services</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Ancillary Fees</fullName>
            </value>
            <value>
                <fullName>Other Fees &amp; Services</fullName>
            </value>
            <value>
                <fullName>APPC</fullName>
            </value>
            <value>
                <fullName>APPC-Standard</fullName>
            </value>
            <value>
                <fullName>APPC-Premium</fullName>
            </value>
            <value>
                <fullName>APPC-Feature</fullName>
            </value>
            <value>
                <fullName>APPC-Surcharge</fullName>
            </value>
            <value>
                <fullName>APPC-Return</fullName>
            </value>
            <value>
                <fullName>APPC-FuelSurcharge</fullName>
            </value>
            <value>
                <fullName>PBP</fullName>
            </value>
			<value>
                <fullName>PBP-Transaction</fullName>
            </value>
			<value>
                <fullName>PBP-PaymentMethod</fullName>
            </value>
			<value>
                <fullName>PBP-Cheque</fullName>
            </value>
			<value>
                <fullName>PBP-CardFees</fullName>
            </value>
			<value>
                <fullName>PBP-SetupFees</fullName>
            </value>
			<value>
                <fullName>PBP-ChangeFees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Product_type__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_type__c</fullName>
    <label>Product type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>eParcels Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>UMS</fullName>
            </value>
            <value>
                <fullName>Post Billpay</fullName>
            </value>
            <value>
                <fullName>Print Post</fullName>
            </value>
            <value>
                <fullName>Community Update</fullName>
            </value>
            <value>
                <fullName>Securepay</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Legacy Products</fullName>
            </value>
            <value>
                <fullName>StarTrack</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>Decipha</fullName>
            </value>
            <value>
                <fullName>Workforce Verification</fullName>
            </value>
            <value>
                <fullName>Priority Product</fullName>
            </value>
            <value>
                <fullName>Local Pickup and Delivery Services</fullName>
            </value>
            <value>
                <fullName>Track Mail</fullName>
            </value>
            <value>
                <fullName>Parcel Contract</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Feature</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Surcharge</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Lodgement_zone__c.field-meta.xml
<CustomField>
    <fullName>Lodgement_zone__c</fullName>
    <description>From parcel contract product, we are maintaining lodgement zone on product level and this field is created, so the product can be picked up by new pricing batch job solution</description>
    <label>Lodgement zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APT_ViewRateCardHandlerTest.cls
/**
 * Created by: Sautul Mehta
 * Description: Test Class for view rate card handler
 * @changelog
 * 2021-10-05 - Sautul Mehta - Class Created as part of CI-8
 */
@istest
public class APT_ViewRateCardHandlerTest {
    
    @testSetup 
    public static void setup() {
        // Create APPC Zone Mappings 
        List<APT_APPC_Definition__c> appcZoneMappings = new List<APT_APPC_Definition__c>();
        appcZoneMappings.add( new APT_APPC_Definition__c(APT_Price_Model__c = 'Z6', APT_Lodgement__c = 'Country', 
                                                         APT_Dest_Zone1__c = 'Same State',  APT_Dest_Zone2_In_RateCard__c = 'Capital/Local', 
                                                         APT_Dest_Zone2__c= 'Local'));
        appcZoneMappings.add(new APT_APPC_Definition__c(APT_Price_Model__c = 'Z6', APT_Lodgement__c = 'Country', 
                                                        APT_Dest_Zone1__c = 'Same State', APT_Dest_Zone2_In_RateCard__c = 'Capital', 
                                                        APT_Dest_Zone2__c= 'Local'));
        insert appcZoneMappings;      
        
        Account acc = APT_TestUtils.createOrganisation();
        insert acc;
        
        //Create Opportunity
        Opportunity opty = APT_TestUtils.createOpportunity(acc.Id);
        insert opty;
        
        //Create PriceList
        Apttus_Config2__PriceList__c priceList = APT_TestUtils.createPriceList();
        insert priceList;

        Product2 bundle1 = APT_TestUtils.createDomesticProduct('APPC','APPC','APPC',null,null);
        bundle1.APT_Product_type__c = 'APPC';
        bundle1.Lodgement_Zone__c = 'Country';
        bundle1.APT_Apttus_Product_Classification__c = 'APPC';
        
        insert bundle1;
        
        //Create Price list Item
        Apttus_Config2__PriceListItem__c pli= APT_TestUtils.createPriceListItem(priceList.ID,bundle1.ID,'C Manufacturing','BAND 2');
        insert pli;
        
        //Create Proposal
        Apttus_Proposal__Proposal__c Proposal= APT_TestUtils.getQuoteProposal(acc.ID,opty.ID,'Proposal','Quote', priceList.ID);
        insert Proposal;
        
        //Create Product Configuration             
        Apttus_Config2__ProductConfiguration__c prodconfig = APT_TestUtils.getProductConfiguration('Product Configuration', 1, 
                                                                                                   proposal.Id, 'Proposal',
                                                                                                   'Ad Hoc',priceList.Id, null,
                                                                                                   'Ready For Finalization',
                                                                                                   null, Datetime.now(), true);
        insert prodconfig;
        
        // Create LineItem
        Apttus_Config2__LineItem__c bundleLine = APT_TestUtils.getConfigLineItem(prodconfig.Id, null, 1, true,//Config Id, grpId, LineNum, isPrimary
                                                                                 1, 'Option', bundle1.Id, true, null,//ItemSeq, lineType, bundleId, customizable, productOptionId
                                                                                 null, null, null, 1, true,//optionId, class Id, class hierarchy, qty, qty Modifiable 
                                                                                 'Each', 1, priceList.Id, pli.Id,//Uom, term, priceList, Pli,
                                                                                 'One Time', 'Per Unit', 'Standard Price', 'One Time',//priceType, priceMethod, chargeType, frequency
                                                                                 true, true, 5500, 5500, 'Per Unit',//allowManualAdj, allocateGroupAdj, listPrice, basePrice, basePriceMethod, 
                                                                                 5225, 0, 5225, 'TestaPTTUS');//baseExtPrice, optionPrice, extendedPrice, lineDesc
        
        bundleLine.Apttus_Config2__AllowManualAdjustment__c = true;
        bundleLine.Apttus_Config2__NetPrice__c = 5225; 
        bundleLine.Apttus_Config2__PrimaryLineNumber__c = 1;
        bundleLine.Apttus_Config2__NetAdjustmentPercent__c = -10;
        bundleLine.Apttus_Config2__OptionId__c = bundle1.Id;
        insert bundleLine;       
        
        //Create product Attribute value                
        Apttus_Config2__ProductAttributeValue__c attribute1 = APT_TestUtils.GetAttributeValue(bundleLine.Id,'Standard',false,false,false,'Yes','B Mining',True,false);
        attribute1.Category__c='CAT1';
        attribute1.APT_Postcode__c = '2000';
        attribute1.APT_AirmailSmallParcelGT2kgAVGWeightKG__c = 3;
        attribute1.APT_Distribution_Type_Printpost__c = 'Local Sort Division;Same State Metro;Other State';
        attribute1.APTS_Price_Structure__c = 'Z6';
        insert attribute1;
        
        Apttus__APTS_Template__c template = new Apttus__APTS_Template__c(Name = 'APPC_RateCard');
        insert template;
    }
    
    @istest
    public static void testProcess(){ 
        Apttus_Config2__ProductConfiguration__c cart = [select Id from Apttus_Config2__ProductConfiguration__c];
        string configLineId = cart.Id; 
        APT_ViewRateCardHandler viewRateCardHandler = new APT_ViewRateCardHandler();
        viewRateCardHandler.process(configLineId);
    }
    
    @istest
    public static void testGenerateDocument(){
        APT_ViewRateCardHandler viewRateCardHandler = new APT_ViewRateCardHandler();
        Apttus_Proposal__Proposal__c proposal = [Select Id from Apttus_Proposal__Proposal__c];
        string proposalId = proposal.Id;
        viewRateCardHandler.generateDocument(proposalId);
    }
    
     @istest 
    public static void createLineItemRateCard(){
        APT_ViewRateCardHandler viewRateCardHandler = new APT_ViewRateCardHandler();
        Apttus_Proposal__Proposal__c proposal = [Select Id from Apttus_Proposal__Proposal__c];
        string proposalId = proposal.Id;
        Apttus_Config2__ProductConfiguration__c config = [Select Id from Apttus_Config2__ProductConfiguration__c];
        string cartId = config.Id;
        viewRateCardHandler.createLineItemRateCard(cartId, proposalId);
    }
}