force-app/main/default/objects/BSB__c/BSB__c.object-meta.xml
<CustomObject>
    <description>This object contains master list of BSB numbers of Australia. It is mastered in SAP.</description>
    <label>BSB</label>
    <nameField>
        <label>BSB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/recordTypes/SSSWDelivery.recordType-meta.xml
<RecordType>
    <fullName>SSSWDelivery</fullName>
    <active>true</active>
    <businessProcess>SSSW</businessProcess>
    <description>SSSW - Record Type to include &quot;Article&quot; Related Lists</description>
    <label>SSSW Delivery</label>
</RecordType>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{00000000}</displayFormat>
        <label>Compensation Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Compensation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Amount__c</fullName>
    <inlineHelpText>Value must be greater than 0</inlineHelpText>
    <label>Value of Contents</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/CostCentreCode__c.field-meta.xml
<CustomField>
    <fullName>CostCentreCode__c</fullName>
    <label>Cost Centre Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Money Order Number</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Contact Customer for Proof of Value</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>EFT Cancelled</fullName>
            </value>
            <value>
                <fullName>Alternate Compensation</fullName>
            </value>
            <value>
                <fullName>EFT Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>Approved Awaiting Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/recordTypes/EFT.recordType-meta.xml
<RecordType>
    <fullName>EFT</fullName>
    <active>true</active>
    <description>Compensation type for Electronic Fund Transfer</description>
    <label>EFT</label>
</RecordType>

force-app/main/default/classes/CompensationGenerateFile_Batchable_Test.cls
/**************************************************
Description :	This class contains unit tests for validating the behavior of Apex class CompensationGenerateFile_Batchable
History:
2018-09-18 dilshan.egodawela@auspost.com.au created
**************************************************/
 
 
@isTest
public class CompensationGenerateFile_Batchable_Test {

	@testSetup static void setup() {
		//create test data
		Case testCase = TestDataProvider.createCase('my subject', 'mydescription', 'SSSWDelivery');
        insert testCase;
        
        Id recordTypeId = [select Id from RecordType where sobjectType = 'Compensation__c' and DeveloperName = 'EFT'].Id;
        
        Compensation__c comp = new Compensation__c(Case__c = testCase.Id ,Batch_ID__c = 1 , Compensation_Amount__c = 50, CostCentreCode__c = 'test', BSB__c = '444333', Account_Number__c = '123234345' , RecordTypeId = recordTypeId);
        Insert comp;
        
        Compensation__c comp2 = new Compensation__c(Case__c = testCase.Id , Batch_ID__c = 2 , Compensation_Amount__c = 50, CostCentreCode__c = 'test', BSB__c = '444333', Account_Number__c = '123234345' , RecordTypeId = recordTypeId);
        Insert comp2;
        
	}
	
	/********************************************
	Scenario:
	Test the method used by the scheduler class. Test batch Id assignment and file creation.
	*********************************************/
    static testMethod void testBatchMethod() {

        Test.startTest();
        //run the batch job
        CompensationGenerateFile_Batchable batch = new  CompensationGenerateFile_Batchable();
        Database.executeBatch(batch, 200);
        
		Test.stopTest();
		//get the compensation records after the batch completion
		List<Compensation__c> processedComps = [select id,Batch_ID__c , Name,Status__c from Compensation__c ];
		
		//both compensation values must be updated to batch 3.
		System.assertEquals(3,processedComps[0].Batch_ID__c,'');
		System.assertEquals(3,processedComps[1].Batch_ID__c,'');
		
		String nowDate = Date.today().format();
		System.Debug([SELECT Id,Name FROM Document WHERE Folder.Name = 'Compensation']);
		//get the workspace ID
		Id contectWorkspaceId = [Select Id, Name from ContentWorkspace where Name = 'Compensation' limit 1].Id;
		//use workspace id to get document id
		Id documentID = [select ContentDocumentId, ContentWorkspaceId from ContentWorkspaceDoc where ContentWorkspaceId =:contectWorkspaceId].ContentDocumentId;
		
		//get document title from contectDocument
		System.assertEquals('Compensation Batch(3) '+nowDate,[SELECT Id,Title FROM ContentDocument WHERE Id =:documentID limit 1].Title);
    }
    
    /********************************************
	Scenario:
	test the method used to run compensations by batch Id. verify only specified batches are run.
	*********************************************/
    static testMethod void testBatchbyNumberMethod() {
        
        Test.startTest();
        //run the batch job
        
        CompensationGenerateFile_Batchable batch = new  CompensationGenerateFile_Batchable(2);
        
        Database.executeBatch(batch, 200);
        
		Test.stopTest();
		
		//get the compensation records after the batch completion
		List<Compensation__c> processedComps = [select id,Batch_ID__c , Name,Status__c from Compensation__c Order by Batch_ID__c];
		//only compensation with batch 2 should be processed.
		//record with batch 1 should retain the same value
		System.assertEquals(1,processedComps[0].Batch_ID__c);
		//record with batch 2 should be updated to batch 3
		System.assertEquals(3,processedComps[1].Batch_ID__c);
    }
    
    /********************************************
	Scenario:
	test the method used email errors
	*********************************************/
    static testMethod void testErrorHandling() {
        
        Test.startTest();
        //send the email
        CompensationGenerateFile_Batchable.sendEmail('Compensation File Save Error','dilshan.egodawela@auspost.com.au');
        
        Integer invocations = Limits.getEmailInvocations();
      	System.assertEquals(1,invocations,'email sent');
        
		Test.stopTest();
    }

	/********************************************
   	Scenario:
   	test scheduling funtionality
   	*********************************************/
	static testMethod void testSchedulale() {

		Test.startTest();
		CompensationGenerateFile_Schedulable schedule = new CompensationGenerateFile_Schedulable();
		schedule.execute(null);
		Test.stopTest();

	}
    
}