force-app/main/default/objects/BSB__c/BSB__c.object-meta.xml
<CustomObject>
    <description>This object contains master list of BSB numbers of Australia. It is mastered in SAP.</description>
    <label>BSB</label>
    <nameField>
        <label>BSB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Address4__c.field-meta.xml
<CustomField>
    <fullName>Address4__c</fullName>
    <label>Receiver Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address4Country__c.field-meta.xml
<CustomField>
    <fullName>Address4Country__c</fullName>
    <label>Receiver Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address4Line2__c.field-meta.xml
<CustomField>
    <fullName>Address4Line2__c</fullName>
    <label>Receiver Address Line2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address4Postcode__c.field-meta.xml
<CustomField>
    <fullName>Address4Postcode__c</fullName>
    <label>Receiver Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address4State__c.field-meta.xml
<CustomField>
    <fullName>Address4State__c</fullName>
    <label>Receiver State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address4Suburb__c.field-meta.xml
<CustomField>
    <fullName>Address4Suburb__c</fullName>
    <label>Receiver Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DescriptionofContents__c.field-meta.xml
<CustomField>
    <fullName>DescriptionofContents__c</fullName>
    <label>Description of Contents</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{00000000}</displayFormat>
        <label>Compensation Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>bank account name</description>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Bank_Detail_Provided_By_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detail_Provided_By_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if bank detail is provided by customer via compensation form</description>
    <inlineHelpText>Check if bank detail is provided by customer via compensation form</inlineHelpText>
    <label>Bank Detail Provided By Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/BSB__c.field-meta.xml
<CustomField>
    <fullName>BSB__c</fullName>
    <label>BSB</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Compensation_Form_Attemps__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Form_Attemps__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Attemps counter for compensation form</description>
    <label>Compensation Form Attemps</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Compensation_Form_Token__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Form_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Compensation Form Token</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Money Order Number</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Contact Customer for Proof of Value</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>EFT Cancelled</fullName>
            </value>
            <value>
                <fullName>Alternate Compensation</fullName>
            </value>
            <value>
                <fullName>EFT Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>Approved Awaiting Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Total_Compensation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Compensation_Amount__c</fullName>
    <formula>Compensation_Amount__c + IF(TEXT(Cover_Type__c) = &quot;Extra Cover&quot;, ExtraCoverPostage__c, Service_Value__c) + Other__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Compensation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CompensationSelector.cls
/**
 * @author Phap Mai
 * @date 2021-07-12
 * @group Selector
 * @tag Selector
 * @tag Compensation
 * @domain Core
 * @description Compensation selector class
 * @changelog
 * 2021-07-12 - Phap Mai - Init
 * 2023-07-25 - Hasantha Liyanage - Modified: added SelectByCaseIds
 * 2023-09-11 - Hasantha Liyanage - Modified: added Compensation__c.RecordTypeId field
 */
public virtual inherited sharing class CompensationSelector extends ApplicationSelector
{
    public enum Options
    {   
        WITH_OVERRIDE_CASE, WITH_OVERRIDE_RECORD_TYPE, WITH_CASE, WITH_RECORD_TYPE
    }
    
    // define fields from parent object of compensation, will be used to override fields in parent selector
    public Map<SObjectType, Set<SObjectField>> moreFields;

    /**
     * Constructor
     */
    public CompensationSelector()
    {
        this.moreFields = new Map<SObjectType, Set<SObjectField>> {
            Case.getSObjectType() => new Set<SObjectField>
            {
                Case.ContactEmail,
                Case.CaseNumber,
                Case.EnquirySubType__c,
                Case.DescriptionofContents__c,
                Case.ContactId,
                Case.Address4__c,
                Case.Address4Line2__c,
                Case.Address4Suburb__c,
                Case.Address4State__c,
                Case.Address4Postcode__c,
                Case.Address4Country__c
            },
            RecordType.getSObjectType() => new Set<SObjectField>
            {
                RecordType.DeveloperName
            }
        };
    }


    public static CompensationSelector newInstance()
    {
		return (CompensationSelector) Application.Selectors.newInstance(CompensationSelector.class);
	}

	public static CompensationSelector newInstance(Integer recordLimit)
    {
		return (CompensationSelector) Application.Selectors.newInstance(CompensationSelector.class).setLimit(recordLimit);
	}

    /**
	 * NOTE: Field overrides should only ever be used when the results are not passed from method to method.
	 * This approach removes data consistency and prevents possible caching of results
	 */
	public static CompensationSelector newInstance(Set<SObjectField> fieldOverrides)
    {
		CompensationSelector selector = (CompensationSelector)Application.Selectors.newInstance(CompensationSelector.class);
		selector.setFieldOverrides(fieldOverrides);
		return selector;
	}

    /**
	 * NOTE: Field overrides should only ever be used when the results are not passed from method to method.
	 * This approach removes data consistency and prevents possible caching of results
	 */
	public static CompensationSelector newInstance(Integer recordLimit, Set<SObjectField> fieldOverrides)
    {
		CompensationSelector selector = (CompensationSelector)Application.Selectors.newInstance(CompensationSelector.class).setLimit(recordLimit);
		selector.setFieldOverrides(fieldOverrides);
		return selector;
	}

    public virtual override SObjectType getSObjectType()
    {
        return Compensation__c.getSObjectType();
    }

    public virtual override Set<SObjectField> getSObjectFieldList()
    {
        return new Set<SObjectField>
        {
            Compensation__c.Id,
            Compensation__c.Name,
            Compensation__c.Compensation_Form_Attemps__c,
            Compensation__c.Case__c,
            Compensation__c.Total_Compensation_Amount__c,
            Compensation__c.Status__c,
            Compensation__c.Account_Name__c,
            Compensation__c.Account_Number__c,
            Compensation__c.BSB__c,
            Compensation__c.Bank_Detail_Provided_By_Customer__c,
            Compensation__c.RecordTypeId
        };
	}

    public virtual override QueryBuilder newQueryBuilder() {
		return newQueryBuilder(new Set<Object>());
	}

    public virtual override QueryBuilder newQueryBuilder(Set<Object> selectorOptions)
    {
        QueryBuilder builder = super.newQueryBuilder(selectorOptions);

        if (selectorOptions.contains(Options.WITH_OVERRIDE_CASE))
            builder.addRelatedFields(CasesSelector.newInstance().setFieldOverrides(this.moreFields).newQueryBuilder(), 'Case__r');
        
        if (selectorOptions.contains(Options.WITH_OVERRIDE_RECORD_TYPE))
            builder.addRelatedFields(RecordTypesSelector.newInstance().setFieldOverrides(this.moreFields).newQueryBuilder(), 'RecordType');

        if (selectorOptions.contains(Options.WITH_CASE))
            builder.addRelatedFields(CasesSelector.newInstance().newQueryBuilder(), 'Case__r');

        if (selectorOptions.contains(Options.WITH_RECORD_TYPE))
            builder.addRelatedFields(CasesSelector.newInstance().newQueryBuilder(), 'RecordType');

        return builder;
    }

    public virtual List<Compensation__c> selectByCaseIds(Set<Id> ids, Set<Object> selectorOptions) {
        QueryBuilder qb = newQueryBuilder(selectorOptions).addConditions().add(new QueryBuilder.SimpleCondition(Compensation__c.Case__c + ' in :ids')).endConditions();
        return (List<Compensation__c>)Database.query(qb.toSoqlString());
    }

    public virtual List<Compensation__c> getByToken(String token, Set<Object> selectorOptions)
    {
        QueryBuilder qb = this.newQueryBuilder(selectorOptions).addConditions().add(new QueryBuilder.SimpleCondition(Compensation__c.Compensation_Form_Token__c + ' = :token')).endConditions();
        return (List<Compensation__c>) Database.query(qb.toSoqlString());
    }

    public virtual List<Compensation__c> getById(String Id, Set<Object> selectorOptions)
    {
        QueryBuilder qb = this.newQueryBuilder(selectorOptions).addConditions().add(new QueryBuilder.SimpleCondition(Compensation__c.Id + ' = :Id')).endConditions();
        return (List<Compensation__c>) Database.query(qb.toSoqlString());
    }
}