force-app/main/default/objects/Product2/fields/Product_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Product_Level_1__c</fullName>
    <label>Product Level 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Level_2__c</fullName>
    <label>Product Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AaE L2</fullName>
            </value>
            <value>
                <fullName>Addressed Mail</fullName>
            </value>
            <value>
                <fullName>AP Global Solutions</fullName>
            </value>
            <value>
                <fullName>Communication &amp; Insight Services</fullName>
            </value>
            <value>
                <fullName>Consumer Non Product</fullName>
            </value>
            <value>
                <fullName>Consumer Products</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Decipha &amp; Digital Mailbox</fullName>
            </value>
            <value>
                <fullName>Digital ID Services</fullName>
            </value>
            <value>
                <fullName>Digital Mailbox L2</fullName>
            </value>
            <value>
                <fullName>Domestic Express Post Envelopes</fullName>
            </value>
            <value>
                <fullName>Express Post</fullName>
            </value>
            <value>
                <fullName>Financial, Identity and Commercial Services</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Fulfilment &amp; Unaddressed</fullName>
            </value>
            <value>
                <fullName>Fulfilment L2</fullName>
            </value>
            <value>
                <fullName>Government Solutions Centre</fullName>
            </value>
            <value>
                <fullName>ID&amp;G and F&amp;CS</fullName>
            </value>
            <value>
                <fullName>Identity Services</fullName>
            </value>
            <value>
                <fullName>Industry Solutions</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Letters &amp; Mail Network - Domestic</fullName>
            </value>
            <value>
                <fullName>Letters &amp; Mail Network - International</fullName>
            </value>
            <value>
                <fullName>Mail Products</fullName>
            </value>
            <value>
                <fullName>Mailroom L2</fullName>
            </value>
            <value>
                <fullName>Mail Services</fullName>
            </value>
            <value>
                <fullName>Merchandise Services</fullName>
            </value>
            <value>
                <fullName>MRS &amp; Data Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Level_3__c</fullName>
    <label>Product Level 3</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AaE L3</fullName>
            </value>
            <value>
                <fullName>Addressed Mail</fullName>
            </value>
            <value>
                <fullName>AP Global Solutions</fullName>
            </value>
            <value>
                <fullName>AP Global Solutions L3</fullName>
            </value>
            <value>
                <fullName>Boxes &amp; Bags</fullName>
            </value>
            <value>
                <fullName>Business &amp; Payments Services</fullName>
            </value>
            <value>
                <fullName>Cash Services</fullName>
            </value>
            <value>
                <fullName>Consumer and Financial Products</fullName>
            </value>
            <value>
                <fullName>Consumer Products L3</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Courier L3</fullName>
            </value>
            <value>
                <fullName>Decipha</fullName>
            </value>
            <value>
                <fullName>Decipha L3</fullName>
            </value>
            <value>
                <fullName>Digital ID L3</fullName>
            </value>
            <value>
                <fullName>Digital ID Services L3</fullName>
            </value>
            <value>
                <fullName>Digital Mailbox L3</fullName>
            </value>
            <value>
                <fullName>Digital Services</fullName>
            </value>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>eMarketplaces</fullName>
            </value>
            <value>
                <fullName>Express Letters</fullName>
            </value>
            <value>
                <fullName>Express Parcels</fullName>
            </value>
            <value>
                <fullName>Express Post</fullName>
            </value>
            <value>
                <fullName>Federal Services</fullName>
            </value>
            <value>
                <fullName>Financial &amp; Commercial Services</fullName>
            </value>
            <value>
                <fullName>Financial Products</fullName>
            </value>
            <value>
                <fullName>Fulfilment</fullName>
            </value>
            <value>
                <fullName>Fulfilment L3</fullName>
            </value>
            <value>
                <fullName>Government &amp; Agency Services</fullName>
            </value>
            <value>
                <fullName>Identity &amp; Government Services</fullName>
            </value>
            <value>
                <fullName>Identity Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Level_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Level_4__c</fullName>
    <description>Phase 1</description>
    <label>Product Level 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_History__c/Product_History__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Stores history of updated products</description>
    <label>Product History</label>
    <nameField>
        <displayFormat>PH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_History__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Stores the updated field of product</description>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductUtil.cls
/**************************************************
Type:       Class for Product Trigger
Purpose:    Captures all the changes 
History:
--------------------------------------------------
05.23.2012   Joseph Barrameda (CloudSherpas.com)    Created

***************************************************/

public with sharing class ProductUtil { 
    
    public static void CaptureChanges(Map <Id, Product2> oldMap, Map <Id,Product2> newMap, List<Product2> listCtr ){

        List <Product_History__c> prodHistoryList = new List <Product_History__c> ();
            
        for (Product2 newProd: listCtr){
                                        
            if ( oldMap.get(newProd.ID).Name != newMap.get(newProd.Id).Name ) {         //Validate if there was a change on Name              
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Name';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Name;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Name;             
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).ProductCode != newMap.get(newProd.Id).ProductCode ) { //    Validate if there was a change on Product Code
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'ProductCode';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).ProductCode;
                prodHistory.New_Value__c = newMap.get(newProd.ID).ProductCode;              
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Description != newMap.get(newProd.Id).Description ) {   //  Validate if there was a change on Description
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Description';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Description;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Description;              
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Family != newMap.get(newProd.Id).Family ) {     //  Validate if there was a change on Family
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Family';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Family;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Family;               
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Product_Level_1__c != newMap.get(newProd.Id).Product_Level_1__c ) { //  Validate if there was a change on Product_Level_1__c
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Product_Level_1__c';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Product_Level_1__c;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Product_Level_1__c;               
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Product_Level_2__c != newMap.get(newProd.Id).Product_Level_2__c ) { //  Validate if there was a change on Product_Level_2__c
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Product_Level_2__c';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Product_Level_2__c;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Product_Level_2__c;               
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Product_Level_3__c != newMap.get(newProd.Id).Product_Level_3__c ) { //  Validate if there was a change on Product_Level_3__c
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Product_Level_3__c';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Product_Level_3__c;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Product_Level_3__c;
                prodHistoryList.add(prodHistory);
            }
            if ( oldMap.get(newProd.ID).Product_Level_4__c != newMap.get(newProd.Id).Product_Level_4__c ) { //  Validate if there was a change on Product_Level_4__c
                Product_History__c prodHistory = new Product_History__c();
                prodHistory.Field__c= 'Product_Level_4__c';
                prodHistory.Old_Value__c = oldMap.get(newProd.ID).Product_Level_4__c;
                prodHistory.New_Value__c = newMap.get(newProd.ID).Product_Level_4__c;
                prodHistoryList.add(prodHistory);
            }
        }        
        if (!prodHistoryList.isEmpty()){
        try     {
                insert prodHistoryList;
            }
            catch (Exception e) {}
        }
    }
        
    /******************** Test Coverage *****************************/
    
    public static testMethod void TestMe(){
        Test.startTest();
        List <Product2> prodList =new List <Product2>();
        Product2 prodTest = new Product2 ();                
        Product2 prod;        
        prodTest.Name = 'TesterXYZ';
        prodTest.ProductCode ='TST001';
        prodTest.Description = 'Tester 5 in 1';
        prodTest.Family = 'Electronics'; 
        prodTest.Product_Level_1__c = 'Email Services';
        prodTest.Product_Level_2__c = 'Mail';
        prodTest.Product_Level_3__c = 'International Service';
        prodTest.Product_Level_4__c = 'Local Service';
        insert ProdTest;
        
        for (Product2 tmp : [Select Name, ProductCode, Description, Family, Product_Level_1__c, Product_Level_2__c, Product_Level_3__c, Product_Level_4__c from Product2 where Name='TesterXYZ' LIMIT 1]){
            tmp.Name = 'Tester';
            tmp.ProductCode ='TST0001';
            tmp.Description = 'Tester 6 in 1';
            tmp.Family = 'Electronics Gadget'; 
            tmp.Product_Level_1__c = 'Mail Services';
            tmp.Product_Level_2__c = 'Email Services';
            tmp.Product_Level_3__c = 'Local Service';
            tmp.Product_Level_4__c = 'International Service';
            prodList.add(tmp);
        }
        update prodList;            
        System.assertEquals(prodTest.Name, 'TesterXYZ');
        System.assertEquals(prodTest.ProductCode, 'TST001');
        System.assertEquals(prodTest.Description, 'Tester 5 in 1' );
        System.assertEquals(prodTest.family ,'Electronics');
        System.assertEquals(prodTest.Product_Level_1__c,'Email Services' );
        System.assertEquals(prodTest.Product_Level_2__c,'Mail');            
        Test.stopTest();
    }
    
}