force-app/main/default/objects/Account/fields/APCN__c.field-meta.xml
<CustomField>
    <fullName>APCN__c</fullName>
    <description>SSSW - SAP Integration</description>
    <externalId>true</externalId>
    <label>APCN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Integration_Service_Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Integration_Service_Mod_Date__c</fullName>
    <description>SSSW - Used in SFDC - SAP CRM integration. This field is populated by TIBCO with the datetime that the record was modified in SAP CRM.</description>
    <label>Integration Service Mod Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/APCN__c.field-meta.xml
<CustomField>
    <fullName>APCN__c</fullName>
    <description>Australia Post Customer Number. Allocated by SAP-CRM Customer Master.</description>
    <externalId>true</externalId>
    <inlineHelpText>Australia Post Customer Number.</inlineHelpText>
    <label>APCN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/IsInactiveCustomer__c.field-meta.xml
<CustomField>
	<fullName>IsInactiveCustomer__c</fullName>
	<formula>ISPICKVAL(Status__c, "Inactive")</formula>
	<label>Is Inactive Customer</label>
	<description>Indiacates a closed or merged account, ready to be archived and deleted. Examples - customer request, deceased etc. Derived from the Status__c field value</description>
	<inlineHelpText>Closed or Merged account, soon to be archived and deleted. Examples include deceased, customer request etc.</inlineHelpText>
	<type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LegalFirstName__c.field-meta.xml
<CustomField>
    <fullName>LegalFirstName__c</fullName>
    <label>Legal First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LegalLastName__c.field-meta.xml
<CustomField>
    <fullName>LegalLastName__c</fullName>
    <label>Legal Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPointEmail/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The consumer contact record that this phone record is related to</description>
    <inlineHelpText>The consumer contact record that this phone record is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Point Emails</relationshipLabel>
    <relationshipName>Contact_Point_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPointEmail/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether or not the mobile phone number has been verified by the consumer.</description>
    <inlineHelpText>Indicates whether or not the mobile phone number has been verified by the consumer.</inlineHelpText>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContactPointPhone/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The consumer contact record that this phone record is related to</description>
    <inlineHelpText>The consumer contact record that this phone record is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Point Phones</relationshipLabel>
    <relationshipName>Contact_Point_Phones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/CustomerDataSync__e.object-meta.xml
<CustomObject>
    <description>This platform event will replace the SSSW inbound interface that synchs consumer data from SAP CRM to Salesforce</description>
    <label>Customer Data Sync</label>
    <pluralLabel>Customer Data Sync</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomerDataSync__e/fields/addresses__c.field-meta.xml
<CustomField>
    <fullName>addresses__c</fullName>
    <description>This field will store the JSON structure containing the one or more addresses that pertain to the consumer</description>
    <label>addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/apcn__c.field-meta.xml
<CustomField>
    <fullName>apcn__c</fullName>
    <description>Australia Post Customer Number. Allocated by SAP-CRM Customer Master.</description>
    <label>apcn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/birthDate__c.field-meta.xml
<CustomField>
    <fullName>birthDate__c</fullName>
    <description>Birth Date of the Consumer</description>
    <label>birthDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/emails__c.field-meta.xml
<CustomField>
    <fullName>emails__c</fullName>
    <description>This field will store the JSON structure containing the one or more emails that pertain to the consumer</description>
    <label>emails</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/integrationServiceModDate__c.field-meta.xml
<CustomField>
    <fullName>integrationServiceModDate__c</fullName>
    <description>The date and time this consumer was last updated in SAP CRM.</description>
    <label>integrationServiceModDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/isInactiveCustomer__c.field-meta.xml
<CustomField>
    <fullName>isInactiveCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be set to TRUE when SAP CRM has archived the consumer record.  When this record is set to TRUE, the consumer must go through the Salesforce Archive proces</description>
    <label>isInactiveCustomer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/legalFirstName__c.field-meta.xml
<CustomField>
    <fullName>legalFirstName__c</fullName>
    <description>First Name of the Consumer</description>
    <label>legalFirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/legalLastName__c.field-meta.xml
<CustomField>
    <fullName>legalLastName__c</fullName>
    <label>legalLastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/legalMarketingOptIn__c.field-meta.xml
<CustomField>
    <fullName>legalMarketingOptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Consumer Opt In for Legal Marketing</description>
    <label>legalMarketingOptIn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/loa__c.field-meta.xml
<CustomField>
    <fullName>loa__c</fullName>
    <description>Level of Assurance allocated to the Consumer</description>
    <label>loa</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/phones__c.field-meta.xml
<CustomField>
    <fullName>phones__c</fullName>
    <description>This field will store the JSON structure containing the one or more phone numbers that pertain to the consumer</description>
    <label>phones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/preferredName__c.field-meta.xml
<CustomField>
    <fullName>preferredName__c</fullName>
    <description>Preferred Name of the Consumer</description>
    <label>preferredName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/salesforceRecordID__c.field-meta.xml
<CustomField>
    <fullName>salesforceRecordID__c</fullName>
    <description>The Salesforce Account Record ID of the consumer as provided by SAP CRM</description>
    <label>salesforceRecordID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerDataSync__e/fields/winningMasterAPCN__c.field-meta.xml
<CustomField>
    <fullName>winningMasterAPCN__c</fullName>
    <description>This field will be used when the consumer record is to be merged with another consumer record.  This record is the losing consumer record and this field will specify the APCN of the winning consumer record</description>
    <label>winningMasterAPCN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Consumer allows the capture of information for Consumers</description>
    <label>Consumer</label>
</RecordType>

force-app/main/default/classes/CustomerDataSyncEventHandler_Test.cls
/**
 * @description       : This is a test class for Customer Data Sync Event handler
 * @author            : Sreenish Krishnan
 * @domain            : Connected Customer
 * @last modified on  : 07-22-2022
 * @last modified by  : Sreenish Krishnan
 **/
@isTest
private class CustomerDataSyncEventHandler_Test {
	@isTest
	static void testprocessCustomerDataEventNewCustomer() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '1242';
		personAccount.apcn__pc = '1242';

		//Prepare the Platform Events published from the ESB
		//Scenario #1: New Customer inserted from SAP
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '1243',
				salesforceRecordID__c = null,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = null,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		//Mock Responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });
		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testprocessCustomerDataEventExistingCustomerAPCNFoundNewIntegrationServiceModDate() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '1242';
		personAccount.apcn__pc = '1242';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 4, 5, 2, 2, 3);

		//Prepare the Platform Events published from the ESB
		//Scenario #2: Existing APCN found and so update the custmer information
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '1242',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 2',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		//Mock Responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });
		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLInserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testprocessCustomerDataEventExistingCustomerAPCNFoundOldIntegrationServiceModDate() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '1242';
		personAccount.apcn__pc = '1242';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 5, 5, 2, 2, 3);

		//Prepare the Platform Events published from the ESB
		//Scenario #2: Existing APCN found and so update the custmer information
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '1242',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 2',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		//Mock Responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });
		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testprocessCustomerDataEventSalesforceIDNotFound() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '1242';
		personAccount.apcn__pc = '1242';

		//Prepare the Platform Events published from the ESB
		//Scenario #2: Salesforce ID not found and the APCN is also not found
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '1243',
				salesforceRecordID__c = fflib_IDGenerator.generate(Account.SObjectType),
				legalFirstName__c = 'FName Scenario 2',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		//Mock Responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });
		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(0)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testprocessCustomerDataEventAPCNNotFoundSalesforceIDFound() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '1242';
		personAccount.apcn__pc = '1242';

		//Prepare the Platform Events published from the ESB
		//Scenario #2: Salesforce ID not found and the APCN is also not found
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '1243',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 2',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		//Mock Responses
		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });
		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	//cp email classes
	@isTest
	static void testsyncContactPointEmailCreateNewEmails() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337950';
		personAccount.apcn__pc = '873337950';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 5, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337950',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointEmailSelector mockCpEmailsSelector = (ContactPointEmailSelector) MockUtility.mockSelector(
			ContactPointEmailSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockAccountsSelector.selectById((Set<Id>) fflib_Match.anyObject()))
			.thenReturn(new Map<Id, Account>{ personAccount.id => personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			//	.thenReturn(new Map<Id, Account>{ personAccount.Id => personAccount });
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpEmailsSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new Map<Id, ContactPointEmail>{});

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testsyncContactPointEmailUpdateExistingEmail() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337950';
		personAccount.apcn__pc = '873337950';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 4, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		ContactPointEmail cpEmail = ApplicationTestDataFactory.getContactPointEmails(1, personAccount.id, true)[0];
		cpEmail.EmailAddress = 'Laurel_Mertz@hotmail.com';
		cpEmail.Contact__c = personContact.Id;
		cpEmail.Verified__c=true;

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337950',
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointEmailSelector mockCpEmailsSelector = (ContactPointEmailSelector) MockUtility.mockSelector(
			ContactPointEmailSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpEmailsSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointEmail>{ cpEmail });

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}


	@isTest
	static void testsyncContactPointEmailUpsertExistingEmail() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337950';
		personAccount.apcn__pc = '873337950';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 4, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		ContactPointEmail cpEmail = ApplicationTestDataFactory.getContactPointEmails(1, personAccount.id, true)[0];
		cpEmail.EmailAddress = 'Laurel_Mertz@hotmail.com';
		cpEmail.Contact__c = personContact.Id;

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337950',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"true\",\n \"isPrimary\":\"true\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointEmailSelector mockCpEmailsSelector = (ContactPointEmailSelector) MockUtility.mockSelector(
			ContactPointEmailSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpEmailsSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointEmail>{ cpEmail });

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testsyncContactPointEmailDeleteExistingEmail() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337950';
		personAccount.apcn__pc = '873337950';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 4, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		ContactPointEmail cpEmail = ApplicationTestDataFactory.getContactPointEmails(1, personAccount.id, true)[0];
		cpEmail.EmailAddress = 'emailtobedeleted@hotmail.com';
		cpEmail.Contact__c = personContact.Id;

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337950',
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointEmailSelector mockCpEmailsSelector = (ContactPointEmailSelector) MockUtility.mockSelector(
			ContactPointEmailSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(
				mockCpEmailsSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointEmail>{ cpEmail });

		MockUtility.Mocks.when(mockDatabase.dmlDelete((List<SObject>) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLDeleted());

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');

		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlDelete((List<SObject>) fflib_Match.anyObject());
	}

	//cp phone classes
	@isTest
	static void testsyncContactPointPhoneCreateNewPhones() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337951';
		personAccount.apcn__pc = '873337951';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 5, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337952',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointPhoneSelector mockCpPhonesSelector = (ContactPointPhoneSelector) MockUtility.mockSelector(
			ContactPointPhoneSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockAccountsSelector.selectById((Set<Id>) fflib_Match.anyObject()))
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			//	.thenReturn(new Map<Id, Account>{ personAccount.Id => personAccount });
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpPhonesSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointPhone>{});

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}

	@isTest
	static void testsyncContactPointPhoneUpdateExistingPhones() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337951';
		personAccount.apcn__pc = '873337951';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 5, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		ContactPointPhone cpPhone = ApplicationTestDataFactory.getContactPointPhones(1, personAccount.id, true)[0];
		cpPhone.TelephoneNumber = '+61491570156';
		cpPhone.Contact__c = personContact.Id;

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337952',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[ \n {\n \"phone\":\"0491570156\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"0491570159\",\n \"type\":\"MOBILE\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n },\n {\n \"phone\":\"08 8888 8888\",\n \"type\":\"HOME\",\n \"isVerified\":\"false\",\n \"isUnique\":\"false\",\n \"isPrimary\":\"false\"\n }\n ]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointPhoneSelector mockCpPhonesSelector = (ContactPointPhoneSelector) MockUtility.mockSelector(
			ContactPointPhoneSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockAccountsSelector.selectById((Set<Id>) fflib_Match.anyObject()))
			.thenReturn(new Map<Id, Account>{ personAccount.id => personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpPhonesSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointPhone>{ cpPhone });

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();

		System.assertEquals(true, srList[0].isSuccess(), 'event published');
		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject());
	}
	@isTest
	static void testsyncContactPointPhoneDeleteExistingPhones() {
		// =====================================
		// Data Preparation
		// =====================================
		//Prepare Person Account that exist in database and the a contact point email associated to the Account
		Account personAccount = ApplicationTestDataFactory.getPersonAccounts(1, true)[0];
		personAccount.apcn__c = '873337951';
		personAccount.apcn__pc = '873337951';
		personAccount.Integration_Service_Mod_Date__c = Datetime.newInstanceGmt(2021, 5, 5, 2, 2, 3);
		Contact personContact = ApplicationTestDataFactory.getContacts(1, personAccount.Id, true)[0];

		ContactPointPhone cpPhone = ApplicationTestDataFactory.getContactPointPhones(1, personAccount.id, true)[0];
		cpPhone.TelephoneNumber = '+61491570156';
		cpPhone.Contact__c = personContact.Id;

		//Prepare the Platform Events published from the ESB
		List<CustomerDataSync__e> events = new List<CustomerDataSync__e>();
		events.add(
			new CustomerDataSync__e(
				apcn__c = '873337952',
				salesforceRecordID__c = personAccount.Id,
				legalFirstName__c = 'FName Scenario 1',
				legalLastName__c = 'LName Scenario 1',
				preferredName__c = 'FNameLNameScenario1',
				birthDate__c = Date.newInstance(2022, 4, 5),
				loa__c = 100.23,
				legalMarketingOptIn__c = true,
				winningMasterAPCN__c = personAccount.Id,
				isInactiveCustomer__c = false,
				integrationServiceModDate__c = Datetime.newInstanceGmt(2022, 4, 5, 2, 2, 3),
				emails__c = '[ \n {\n \"emailAddress\":\"Laurel_Mertz@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n },\n {\n \"emailAddress\":\"Dina_Heller@hotmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"true\"\n }\n,\n{\n \"emailAddress\":\"mary.test.cust@yopmail.com\",\n \"isVerified\":\"false\",\n \"isPrimary\":\"false\",\n \"isCredentialEmail\":\"false\"\n } ]',
				phones__c = '[]',
				addresses__c = '[ \n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n },\n {\n \"type\":\"Other\",\n \"suburb\":\"CROYDON\",\n \"state\":\"NSW\",\n \"postCode\":\"3206\",\n \"country\":\"AU\"\n }\n ]'
			)
		);

		// =====================================
		// Stubbing (No stubbing required as its a platform event)
		// =====================================
		//Mock the Accounts Selector and Database
		AccountsSelector mockAccountsSelector = (AccountsSelector) MockUtility.mockSelector(AccountsSelector.class);
		ContactPointPhoneSelector mockCpPhonesSelector = (ContactPointPhoneSelector) MockUtility.mockSelector(
			ContactPointPhoneSelector.class
		);
		ApplicationDatabase mockDatabase = MockUtility.mockDatabase();

		MockUtility.Mocks.startStubbing();

		MockUtility.Mocks.when(
				mockAccountsSelector.selectByAPCNAndIdAndPersonAccount(
					(Map<String, Object>) fflib_Match.anyObject(),
					fflib_Match.anyString(),
					fflib_Match.anySObjectField()
				)
			)
			.thenReturn(new List<Account>{ personAccount });

		MockUtility.Mocks.when(mockAccountsSelector.selectById((Set<Id>) fflib_Match.anyObject()))
			.thenReturn(new Map<Id, Account>{ personAccount.id => personAccount });

		MockUtility.Mocks.when(mockDatabase.dmlUpsert((List<SObject>) fflib_Match.anyObject(), (SObjectField) fflib_Match.anyObject()))
			.thenAnswer(new MockUtility.AnswerGenericDMLUpserted());

		MockUtility.Mocks.when(
				mockCpPhonesSelector.selectByParentId((Set<Id>) fflib_Match.anyObject(), (Set<Object>) fflib_Match.anyObject())
			)
			.thenReturn(new List<ContactPointPhone>{ cpPhone });

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		List<Database.SaveResult> srList = EventBus.publish(events);

		Test.stopTest();
		System.assertEquals(true, srList[0].isSuccess(), 'event published');

		((ApplicationDatabase) MockUtility.Mocks.verify(mockDatabase, MockUtility.Mocks.times(1)))
			.dmlDelete((List<SObject>) fflib_Match.anyObject());
	}
}