force-app/main/default/objects/Account/fields/Assignment_Effective_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Effective_From_Date__c</fullName>
    <description>The date the licensee assignment is effective from.</description>
    <label>Assignment Effective From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Assignment_Effective_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Effective_To_Date__c</fullName>
    <description>The date the licensee assignment is effective to.</description>
    <label>Assignment Effective To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facility associated with this License</description>
    <inlineHelpText>Facility associated with this License</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3) AND 4</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility CMA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility CPA</value>
        </filterItems>
        <filterItems>
            <field>Account.Licence_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licence_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licence Assignment</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Licence_Status__c.field-meta.xml
<CustomField>
    <fullName>Licence_Status__c</fullName>
    <description>Status of the License</description>
    <label>Licence Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended Without Fees</fullName>
            </value>
            <value>
                <fullName>Suspended With Fees</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LicenceManualActivationDate__c.field-meta.xml
<CustomField>
    <fullName>LicenceManualActivationDate__c</fullName>
    <description>The date/time that the Licence was manually activated.</description>
    <inlineHelpText>The date/time that the Licence was manually activated.</inlineHelpText>
    <label>Licence Manual Activation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LicenceManualDeactivationDate__c.field-meta.xml
<CustomField>
    <fullName>LicenceManualDeactivationDate__c</fullName>
    <description>The date/time that the Licence was manually deactivated.</description>
    <inlineHelpText>The date/time that the Licence was manually deactivated.</inlineHelpText>
    <label>Licence Manual Deactivation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nominated_Partner_Contact_Incent_User__c.field-meta.xml
<CustomField>
    <fullName>Nominated_Partner_Contact_Incent_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact used to integrate with the Incent application, and as the primary point of contact for communications.</description>
    <inlineHelpText>Contact used to integrate with the Incent application, and as the primary point of contact for communications</inlineHelpText>
    <label>Nominated Partner Contact &amp; Incent User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Incent and Primary Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentABN__c.field-meta.xml
<CustomField>
    <fullName>ParentABN__c</fullName>
    <description>The Parent Organisation&apos;s ABN which is referenced in the outbound message for Licence Activation button on the Licence record type.</description>
    <formula>Parent.ABN__c</formula>
    <inlineHelpText>ABN of the Parent Organisation</inlineHelpText>
    <label>Parent ABN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Vendor_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Vendor_ID__c</fullName>
    <description>SAP Vendor ID for the Licensee</description>
    <externalId>true</externalId>
    <label>SAP Vendor ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/WCIS_Code__c.field-meta.xml
<CustomField>
    <fullName>WCIS_Code__c</fullName>
    <description>The WCIS Id for this facility, based on network data sourced from WCIS</description>
    <formula>Network_Facility__r.Org_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>WCIS Id for this facility</inlineHelpText>
    <label>WCIS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>Facility Organisation for LPO Partner</description>
    <label>Facility</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Licence.recordType-meta.xml
<RecordType>
    <fullName>Licence</fullName>
    <active>true</active>
    <description>Licence agreement with an LPO Partner</description>
    <label>Licence</label>
</RecordType>

force-app/main/default/objects/Contact/fields/IncentCredential__c.field-meta.xml
<CustomField>
    <fullName>IncentCredential__c</fullName>
    <description>This field will store the azure credential email address for the Retail users logging into exactly/incent.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field will store the azure credential email address for the Retail users logging into exactly/incent.</inlineHelpText>
    <label>Incent Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Premium &amp; Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Network__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PartnerInfoLicenceActivationController.cls
/**
 * @author Naveen Rajanna
 * @date 2023-03-17
 * @description Controller for Manual ABN/Licence Activation performed by Partner Info Users
 * @test PartnerInfoLicenceActivationCont_Test
 * @changelog
 * 2024-06-15	Snigdha Sahu : REQ3429628 : Add validation for Incent Cred to be populated for nominated contact on parent org
 */
public with sharing class PartnerInfoLicenceActivationController {
	private static final Set<SObjectField> ACCOUNT_FIELDS = new Set<SObjectField>{
		Account.Id, Account.Name, Account.WCIS_Code__c, Account.Licence_Status__c, Account.ParentABN__c, Account.SAP_Vendor_ID__c,
		Account.Assignment_Effective_From_Date__c, Account.Assignment_Effective_To_Date__c, Account.CreatedDate, Account.LastModifiedDate, Account.Nominated_Partner_Contact_Incent_User__c
	};
	private static final Set<SObjectField> NETWORK_FIELDS = new Set<SObjectField>{ Network__c.State__c };
	private static final Set<SObjectField> USER_FIELDS = new Set<SObjectField>{ User.Id, User.Name };
    private static final Set<SObjectField> CONTACT_FIELDS = new Set<SObjectField>{ Contact.IncentCredential__c };

	/**
	 * Return wrapper containing IncomingLicence, Facility and OutgoingLicence records for the passed IncomingLicence Id
	 * @param incomingLicenceId
	 * @return  `InitWrapper`
	 * @exception
	 */
	@AuraEnabled(cacheable=true)
	public static InitWrapper fetchInitDetails(String incomingLicenceId) {
		InitWrapper initWrapper = null;
		try {
			// Query to get FacilityId and OutgoingLicenceId from IncomingLicenceId
			List<Account> incomingLicence = AccountsSelector.newInstance(
					1,
					new Set<SObjectField>{ Account.Id, Account.Facility__c, Account.ParentId}
				)
				.selectById(new Set<Id>{ Id.valueOf(incomingLicenceId) }, new Set<Object>{ AccountsSelector.Options.WITH_FACILITY })
				.values();

			// Query to get IncomingLicence, Facility and OutgoingLicence records
			if (!incomingLicence.isEmpty()) {
				//added IncentCredential__c
				Set<Id> idSet = new Set<Id>{ incomingLicence[0].Id, incomingLicence[0].ParentId, incomingLicence[0].Facility__c, incomingLicence[0].Facility__r?.ParentId };
				idSet.remove(null);
				Map<SObjectType, Set<SObjectField>> fieldOverrides = new Map<SObjectType, Set<SObjectField>>{
					Account.SObjectType => ACCOUNT_FIELDS, Network__c.SObjectType =>  NETWORK_FIELDS, User.SObjectType => USER_FIELDS, Contact.SObjectType => CONTACT_FIELDS
				};

				Map<Id, Account> accountMap = AccountsSelector.newInstance(0, fieldOverrides)
					.selectById(
						idSet,
						new Set<Object>{ 
							AccountsSelector.Options.WITH_CREATEDBY_USER, AccountsSelector.Options.WITH_LASTMODIFIEDBY_USER, 
							AccountsSelector.Options.WITH_PARENT, AccountsSelector.Options.WITH_NETWORK,  AccountsSelector.Options.WITH_CONTACT
						}
					);				
					
				// Update the wrapper with the details to be return to lwc
				initWrapper = new InitWrapper();
				initWrapper.domainURL = String.valueof(URL.getOrgDomainUrl().toExternalForm());
				initWrapper.incomingLicence = accountMap.get(incomingLicence[0].Id);
				
				if (incomingLicence[0].Facility__c != null) {
					initWrapper.facility = accountMap.get(incomingLicence[0].Facility__c);
					initWrapper.outgoingLicence = (incomingLicence[0].Facility__r.ParentId != null &&
						accountMap.containsKey(incomingLicence[0].Facility__r.ParentId))
						? accountMap.get(incomingLicence[0].Facility__r.ParentId)
						: null;
				}

				if(accountMap.containsKey(incomingLicence[0].ParentId)){
					Account parentAccount = accountMap.get(incomingLicence[0].ParentId);
					initWrapper.incentCred = parentAccount.Nominated_Partner_Contact_Incent_User__r.IncentCredential__c;
					system.debug('IncentCredential value is ' + initWrapper.incentCred);
				}
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return initWrapper;
	}

	/**
	 * Perform DML to update the Incoming and Outgoing Licence fields and return Boolean to indicate outcome
	 * @param incomingLicenceId
	 * @param outgoingLicenceId
	 * @return  `Boolean`
	 * @exception
	 */
	@AuraEnabled
	public static Boolean updateLicences(String incomingLicenceId, String outgoingLicenceId) {
		try {
			List<Account> updateable = new List<Account>();
			// set the IncomingLicence Licence Status to Active and set the Licence Manual Activation Date to Today's Date
			updateable.add(
				new Account(
					Id = Id.valueOf(incomingLicenceId),
					Licence_Status__c = AccountUtil.LICENCE_STATUS_ACTIVE,
					LicenceManualActivationDate__c = Datetime.now()
				)
			);
			if (outgoingLicenceId != null) {
				// set the OutgoingLicence Licence Manual Deactivation Date to Today's Date
				updateable.add(new Account(Id = Id.valueOf(outgoingLicenceId), LicenceManualDeactivationDate__c = Datetime.now()));
			}
			if (!updateable.isEmpty()) {
				ApplicationDatabase.getInstance().dmlUpdate(updateable);
				return true;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return false;
	}

	/**
	 * Wrapper class for the request
	 */
	public class InitWrapper {
		@AuraEnabled
		public Account facility;
		@AuraEnabled
		public Account incomingLicence;
		@AuraEnabled
		public Account outgoingLicence;
		@AuraEnabled
		public String domainURL;
		@AuraEnabled
		public String incentCred;
	}
}