force-app/main/default/objects/Account/fields/Business_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>Business_at_Risk__c</fullName>
    <formula>IF( AtRiskBusinessCount__c &gt; 0, IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;),
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business at Risk</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>djk 20/10/11</description>
    <label>Opportunity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Charge_Account__c/APT_Charge_Account__c.object-meta.xml
<CustomObject>
    <label>Charge Account Request</label>
    <nameField>
        <displayFormat>ChargeAccount{0000000}</displayFormat>
        <label>Charge Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Account Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_Credit_Assessment__c/APT_Credit_Assessment__c.object-meta.xml
<CustomObject>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>Credit Assess - {0000}</displayFormat>
        <label>Credit Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_Credit_Assessment__c/fields/APT_Charge_Account__c.field-meta.xml
<CustomField>
    <fullName>APT_Charge_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Account</label>
    <referenceTo>APT_Charge_Account__c</referenceTo>
    <relationshipLabel>Credit Assessments</relationshipLabel>
    <relationshipName>Credit_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APT_Credit_Assessment__c/fields/APT_Proposal__c.field-meta.xml
<CustomField>
    <fullName>APT_Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Credit Assessments</relationshipLabel>
    <relationshipName>Credit_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The link to the account record to identify the external party to this agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N50000001Xl0UEAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Apttus__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Agreements (Primary Contact)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus_QPComply__RelatedProposalId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPComply__RelatedProposalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated quote/proposal</description>
    <label>Related Quote/Proposal</label>
    <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_Credit_Assessment__c.field-meta.xml
<CustomField>
    <fullName>APT_Credit_Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Account Assessment Outcome</label>
    <referenceTo>APT_Credit_Assessment__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/At_Risk_Business__c.object-meta.xml
<CustomObject>
    <label>At Risk Business</label>
    <nameField>
        <displayFormat>BAR-{0000}</displayFormat>
        <label>At Risk Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>At Risk Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMExternalOnboardingRequest__c/BAMExternalOnboardingRequest__c.object-meta.xml
<CustomObject>
    <description>This object stores a record of each Merchant Portal onboarding request sent to Camunda and its current status. This provides the ability to view the status of requests.  This data is also used to determine if there have been changes to a Contact Application Role or Linked Entity since the last successfully processed request.</description>
    <label>External Onboarding Request</label>
    <nameField>
        <displayFormat>BEOR-{000000}</displayFormat>
        <label>External Onboarding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Onboarding Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Support_Request__c/Deal_Support_Request__c.object-meta.xml
<CustomObject>
    <description>This Object is used for raising various types of support requests that may be related to a particular Opportunity or an Organisation.</description>
    <label>Deal Support Request</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Deal Support Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Support Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Support_Request__c/fields/APT_Contract__c.field-meta.xml
<CustomField>
    <fullName>APT_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
    <relationshipLabel>Deal Support Request</relationshipLabel>
    <relationshipName>Deal_Support_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Support_Request__c/fields/Business_At_Risk__c.field-meta.xml
<CustomField>
    <fullName>Business_At_Risk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link the Business At Risk record where there is one</description>
    <label>Business At Risk</label>
    <referenceTo>At_Risk_Business__c</referenceTo>
    <relationshipLabel>Deal Support Request</relationshipLabel>
    <relationshipName>Deal_Support_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Support_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is lookup to the Opportunity that DSR request is linked to</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Support Request</relationshipLabel>
    <relationshipName>Deal_Support_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Support_Request__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is field will store the Organisation details to which the DSR request is linked to</description>
    <label>Legal Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Support Request</relationshipLabel>
    <relationshipName>Deal_Support_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Support_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>What is the main product this opportunitiy is focused around</description>
    <inlineHelpText>What is the main product this opportunitiy is focused around?</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3PL</fullName>
            </value>
            <value>
                <fullName>AaE</fullName>
            </value>
            <value>
                <fullName>Address Post</fullName>
            </value>
            <value>
                <fullName>APGL Commercial Outbound</fullName>
            </value>
            <value>
                <fullName>Australia Post Parcel Contract</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Community Update</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Decipha</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital ID</fullName>
            </value>
            <value>
                <fullName>Digital Mailbox</fullName>
            </value>
            <value>
                <fullName>Direct Access</fullName>
            </value>
            <value>
                <fullName>eLetter</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>Express AP</fullName>
            </value>
            <value>
                <fullName>Express Courier International</fullName>
            </value>
            <value>
                <fullName>Express eParcel</fullName>
            </value>
            <value>
                <fullName>Express Post</fullName>
            </value>
            <value>
                <fullName>Financial &amp; Commercial Services</fullName>
            </value>
            <value>
                <fullName>First Direct Solutions</fullName>
            </value>
            <value>
                <fullName>Fulfilio</fullName>
            </value>
            <value>
                <fullName>Fulfilment &amp; Unaddressed</fullName>
            </value>
            <value>
                <fullName>ID&amp;G and F&amp;CS</fullName>
            </value>
            <value>
                <fullName>ID&amp;V</fullName>
            </value>
            <value>
                <fullName>Identity &amp; Government Services</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>International AP</fullName>
            </value>
            <value>
                <fullName>Letters/Trusted Services</fullName>
            </value>
            <value>
                <fullName>Local Pickup and Delivery Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Support_Request__c/fields/Returns__c.field-meta.xml
<CustomField>
    <fullName>Returns__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Returns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple.recordType-meta.xml
<RecordType>
    <fullName>Simple</fullName>
    <active>true</active>
    <businessProcess>BG Sales Process</businessProcess>
    <label>Simple</label>
</RecordType>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Startrack</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Parcel Services</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Trusted Services</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Mail Services</fullName>
    </customValue>
    <customValue>
        <fullName>MyPost Business</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DealSupportRequestsSelector_Test.cls
/**
* @author Nathan Franklin
* @date 2021-01-12
* @group Tests
* @tag Selector
* @tag Deal Support Request SObject
* @domain Core
* @description A very simple selector class that sits in the base domain
* @changelog
* 2020-04-10 - arjun.singh@auspost.com.au - Created
* 2022-04-08 - seth.heang@auspost.com.au - updated test method to test search method
* 2022-12-01 - Harry Wang - added test method for selectByAccountRelationshipQueryLocator
* 2024-02-02 - Mahesh Parvathaneni - updated test method to include dsrIds to test search method
* 2024-08-10 - Harry Wang - added tests for selectByAtRiskBusinessId and selectByAccountId
*/
@IsTest
public with sharing class DealSupportRequestsSelector_Test {
	/**
	 * Test:
	 *  Ensures that the selectors QueryBuilder is generating the correct output
	 */
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectString() {

		// =====================================
		// Data Preparation
		// =====================================
		// None!

		// =====================================
		// Stubbing
		// =====================================
		// None!

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		DealSupportRequestsSelector selector = DealSupportRequestsSelector.newInstance();
		QueryBuilder qb = selector.newQueryBuilder();
		String soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?ism)\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select from Deal Support Request');

		Test.stopTest();

	}

	/**
	* Test:
	*  Ensures that the selectors QueryBuilder is generating the correct output
	*/
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectStringForFieldOverride() {
		Test.startTest();

		DealSupportRequestsSelector selector = DealSupportRequestsSelector.newInstance();
		QueryBuilder qb = selector.newQueryBuilder();
		String soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select from Deal_Support_Request__c');

		selector = DealSupportRequestsSelector.newInstance(1, new Set<SObjectField>{
				Deal_Support_Request__c.Id
		});
		qb = selector.newQueryBuilder();
		soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select from Deal_Support_Request__c');

		selector = DealSupportRequestsSelector.newInstance(1, new Map<SObjectType, Set<SObjectField>>{
				Deal_Support_Request__c.SObjectType => new Set<SObjectField>{Deal_Support_Request__c.Id}
		});
		qb = selector.newQueryBuilder();
		soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select from Deal_Support_Request__c');

		selector = DealSupportRequestsSelector.newInstance(new Map<SObjectType, Set<SObjectField>>{
				Deal_Support_Request__c.SObjectType => new Set<SObjectField>{Deal_Support_Request__c.Id}
		});
		qb = selector.newQueryBuilder();
		soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select from Deal_Support_Request__c');
		Test.stopTest();
	}

	/**
	 * Test:
	 *  Ensures that the selectors QueryBuilder is generating the correct output
	 */
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectStringWithRelatedFields() {

		// =====================================
		// Data Preparation
		// =====================================
		// None!

		// =====================================
		// Stubbing
		// =====================================
		// None!

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		DealSupportRequestsSelector selector = DealSupportRequestsSelector.newInstance();
		QueryBuilder qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_RECORDTYPE});
		String soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?ism)RecordType\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select RecordType fields');

		qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_OWNER});
		soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?ism)Owner\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select Owner fields');

		qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_RECORDTYPE, DealSupportRequestsSelector.Options.WITH_OWNER});
		soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?ism)RecordType\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select RecordType fields');
		System.assertEquals(true, Pattern.compile('(?ism)Owner\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select Owner fields');
		
		qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_PRIMARYCONTACT});
		soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?is)APT_Contract__r.Apttus__Primary_Contact__r\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select Primary Contact fields');

		qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_CHARGE_ACCOUNT_REQUEST});
		soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?is)APT_Contract__r.Apttus_QPComply__RelatedProposalId__r.APT_Credit_Assessment__r.APT_Charge_Account__r\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select Charge Request fields');

		qb = selector.newQueryBuilder(new Set<Object>{DealSupportRequestsSelector.Options.WITH_CREDIT_ASSESSMENT});
		soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?is)APT_Contract__r.Apttus_QPComply__RelatedProposalId__r.APT_Credit_Assessment__r\\..*?\\bfrom Deal_Support_Request__c\\b').matcher(soql).find(), 'Resulting query does not select Credit Assessement  fields');

		Test.stopTest();

	}
	/**
	 * Executes a query to ensure it returns expected results with actual inserted data
	 */
	@IsTest
	public static void testSelectorIntegration() {

		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Account> accountList = ApplicationTestDataFactory.getAccounts(2, false);
		insert accountList;
		Account account = accountList[0];
		Account chargeAccount = accountList[1];

		Contact primaryContact = ApplicationTestDataFactory.getContacts(1, account.Id, false)[0];
		insert primaryContact;

		Opportunity opportunityRecord = ApplicationTestDataFactory.getOpportunities(1, account.Id, false)[0];
		insert opportunityRecord;

		At_Risk_Business__c atRiskBusiness = ApplicationTestDataFactory.getAtRiskBusiness(1, account.Id, false)[0];
		insert atRiskBusiness;

		/*APT_Charge_Account__c chargeAccountRequest = ApplicationTestDataFactory.getApttusChargeAccountRequest(1,false)[0];
		insert chargeAccountRequest;

		APT_Credit_Assessment__c apttusCreditAssessment = ApplicationTestDataFactory.getApttusCreditsAssessment(1, chargeAccountRequest.Id, false)[0];
		insert apttusCreditAssessment ;

		Apttus_Proposal__Proposal__c apttusProposals = ApplicationTestDataFactory.getApttusProposals(1, primaryContact.Id, false)[0];
		insert apttusProposals;

		Apttus__APTS_Agreement__c apttusContracts = ApplicationTestDataFactory.getApttusContracts(1, primaryContact.Id, opportunityRecord.Id, false)[0];
		insert apttusContracts;*/
		
		Deal_Support_Request__c dealSupportRequest = ApplicationTestDataFactory.getDealSupportRequests(1, opportunityRecord.Id, account.Id, false)[0];
		Id psrAPPCRecTypeId = RecordTypesSelector.newInstance().selectByDeveloperName('Deal_Support_Request__c', new Set<String>{APT_Constants.PSR_APPC_RECORD_TYPE_APINAME}).values()[0].Id;
		dealSupportRequest.recordTypeId = psrAPPCRecTypeId;
		dealSupportRequest.product__c = APT_Constants.PSR_APPC_PRODUCT_NAME;
		dealSupportRequest.Returns__c = true;
		dealSupportRequest.Business_At_Risk__c = atRiskBusiness.Id;
		insert dealSupportRequest;

		BAMExternalOnboardingRequest__c externalOnboardingRecord = ApplicationTestDataFactory.getBAMExternalOnboardingRequests(1,dealSupportRequest.Id, 'Deal_Support_Request__c', false)[0];
		insert externalOnboardingRecord;
		
		/* apttusCreditAssessment.APT_Proposal__c = apttusProposals.Id;
		apttusCreditAssessment.APT_Charge_Account__c = chargeAccountRequest.Id;
		apttusProposals.APT_Credit_Assessment__c = apttusCreditAssessment.Id;
		apttusContracts.Apttus_QPComply__RelatedProposalId__c = apttusProposals.Id;
		apttusContracts.Apttus__Account__c = account.Id;
		dealSupportRequest.APT_Contract__c = apttusContracts.Id;*/

		Map<Id, Deal_Support_Request__c> mappedDealSupports = new Map<Id, Deal_Support_Request__c>(new List<Deal_Support_Request__c>{dealSupportRequest});

		// =====================================
		// Stubbing
		// =====================================
		// None!

		// =====================================
		// Testing
		// =====================================
		Test.startTest();
		
		DealSupportRequestsSelector selector = DealSupportRequestsSelector.newInstance(1);
		Map<Id, Deal_Support_Request__c> results = selector.selectById(mappedDealSupports.keySet());
		System.assertEquals(1, results.size(), 'Result count was wrong');
		results = selector.selectById(mappedDealSupports.keySet(), new Set<Object>{DealSupportRequestsSelector.Options.WITH_RECORDTYPE, DealSupportRequestsSelector.Options.WITH_OWNER});
		
		System.assertEquals(1, results.size(), 'Result count was wrong');
		System.assertNotEquals(null, results.values()[0].RecordType, 'Expected RecordType object');
		System.assertNotEquals(null, results.values()[0].OwnerId, 'Expected Owner object');

		Map<Id, Deal_Support_Request__c> resultsforMultipleDSR = selector.selectByRecordList(new List<Deal_Support_Request__c>{dealSupportRequest});
		System.assertEquals(1, resultsforMultipleDSR.size(), 'Result count was wrong');

		DealSupportRequestsSelector selector2 = DealSupportRequestsSelector.newInstance(1, new Set<SObjectField>{
			Deal_Support_Request__c.Id,
			Deal_Support_Request__c.Name,
			Deal_Support_Request__c.Product__c,
			Deal_Support_Request__c.Opportunity__c,
			Deal_Support_Request__c.RecordTypeId
		});
		
		Map<String, Object> searchParams = new Map<String, Object>();
		searchParams.put('opportunityIds', new Set<Id>{opportunityRecord.Id});
		searchParams.put('recTypeIds', new Set<Id>{psrAPPCRecTypeId});
		searchParams.put('productNames', new Set<String>{APT_Constants.PSR_APPC_PRODUCT_NAME});
		searchParams.put('dsrIds', new Set<String>{results.values()[0].Name});
		List<Deal_Support_Request__c> resultsforAPPCPSRList = selector2.search(searchParams, new Set<Object>(), true);
		System.assertEquals(1, resultsforAPPCPSRList.size(), 'Result count was wrong');

		Set<Id> accountIds = new Set<Id>{account.Id};
		Database.QueryLocator queryLocator = DealSupportRequestsSelector.newInstance().selectByAccountOrderByAccountIdQueryLocator(accountIds, new Set<Object>{
				DealSupportRequestsSelector.Options.WITH_ORGANISATION
		});

		List<Deal_Support_Request__c> queryResults = (List<Deal_Support_Request__c>)Database.query(queryLocator.getQuery());

		System.assertEquals(1, queryResults.size(), 'Expected to return only the DSRs related to the supplied account');
		System.assertEquals(dealSupportRequest.Id, queryResults[0].Id, 'Expected to return only the DSRs related to the supplied account');

		queryResults = selector.selectByAtRiskBusinessId(new Set<Id>{atRiskBusiness.Id}, new Set<Object>());
		System.assertEquals(dealSupportRequest.Id, queryResults[0].Id, 'Id not matched');

		Set<SObjectField> fieldOverrides = new Set<SObjectField>{Deal_Support_Request__c.Id, Deal_Support_Request__c.Organisation__c};
		queryResults = DealSupportRequestsSelector.newInstance(1, fieldOverrides).selectByAccountId(accountIds, new Set<Object>{DealSupportRequestsSelector.Options.WITH_OPPORTUNITY});
		System.assertEquals(account.Id, queryResults[0].Organisation__c, 'Parent account not matched');
		System.assertEquals(opportunityRecord.Id, queryResults[0].Opportunity__r.Id, 'Opportunity not matched');
		Test.stopTest();

	}
}