force-app/main/default/objects/Account/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <description>djk 07/10/2011 rolls up customer number from Role object</description>
    <label>Customer Number</label>
    <summarizedField>Organisation_Role__c.Customer_Number_Rollup__c</summarizedField>
    <summaryFilterItems>
        <field>Organisation_Role__c.Role_Type__c</field>
        <operation>equals</operation>
        <value>Customer, Prospect, Partner, Known, Non Account Customer</value>
    </summaryFilterItems>
    <summaryForeignKey>Organisation_Role__c.Organisation__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <description>This field captures the unique identifier from the legacy application, eg SAP CRM. It is expected to be populated during the initial data load and also used for ongoing integration.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the SAP Customer ID.</inlineHelpText>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &apos;Accounts&apos; in SAP ERP, eg Charge Account, Cash Account, etc.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <description>DJK 07/10/2011 LOOKS UP CUSTOMER NUMBER FROM ROLE OBJECT VIA ACCOUNT</description>
    <formula>Organisation__r.AccountNumber</formula>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerNumber__c</fullName>
    <formula>text(Organisation__r.Customer_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerNumber</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <formula>Account.AccountNumber</formula>
    <label>Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_by_Billing_Account__c/Revenue_by_Billing_Account__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Revenue at the Billing Account level, with Credit and Rebate data.</description>
    <label>Revenue by Billing Account</label>
    <nameField>
        <label>Revenue by Billing Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue by Billing Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_by_Billing_Account__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Revenue</relationshipLabel>
    <relationshipName>Revenue_by_Billing_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_by_Billing_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Revenue by Billing Account</relationshipLabel>
    <relationshipName>Revenue_by_Billing_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_by_Billing_Account__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchDeleteDuplicateRevenueTest.cls
/**
* @description Test class for BatchDeleteDuplicateRevenue
* @date 2024-10-10
* @group Tests
* @group Selector
* @changelog
* 2024-10-10 - Swati Mogadala - Created
*/
@isTest
public class BatchDeleteDuplicateRevenueTest {

    @isTest
    static void testBatchDeleteDuplicateRevenue() {
        // // =====================================
        // Data Preparation
        // =====================================
        MockUtility.disableTriggerExecution();
		Account testAccount = ApplicationTestDataFactory.getAccounts(1, false)[0];
      	testAccount.LEGACY_ID__c='60000000';
		insert testAccount;
        
       	Billing_Account__c billingAcc = ApplicationTestDataFactory.getBillingAccounts(1, testAccount.Id, 'TEAM', false)[0];
		insert billingAcc;
        
        // Positive test case
		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAccount.Id, false)[0];
		revenue.Unique_Id__c=revenue.CustomerNumber__c + 'Test1';
		insert revenue;
		// Negative test case
		Budget_and_Revenue__c duplicate = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAccount.Id, false)[0];
        revenue.Unique_Id__c='60000008Test1';
		insert duplicate;

		
		// Positive test case
		Revenue_by_Billing_Account__c rev = ApplicationTestDataFactory.getRevByBillingAcc(1, testAccount.Id,billingAcc.Id, false)[0];
        rev.Customer__c=testAccount.id;
        rev.Billing_Account__c=billingAcc.Id;
		insert rev;
        rev.Unique_Id__c=rev.Customer__r.Customer_number__c +'Test1';
        update rev;
        // Negative test case
        Revenue_by_Billing_Account__c dup = ApplicationTestDataFactory.getRevByBillingAcc(1, testAccount.Id,billingAcc.Id, false)[0];
        dup.Customer__c=testAccount.id;
        dup.Billing_Account__c=billingAcc.Id;
        dup.Unique_Id__c='66000000Test2';
        insert dup;
        // =====================================
        // Testing
        // =====================================
        Test.startTest();

        // Step 2: Verify that records are created
        System.assertEquals(2, [SELECT COUNT() FROM Budget_and_Revenue__c]);
        System.assertEquals(2, [SELECT COUNT() FROM Revenue_by_Billing_Account__c]);

        // Step 3: Instantiate the batch class and execute it
        BatchDeleteDuplicateRevenue batch = new BatchDeleteDuplicateRevenue();
        Database.executeBatch(batch);
        Test.stopTest();

        // Step 4: Verify that the records have been deleted
        System.assertEquals(1, [SELECT COUNT() FROM Budget_and_Revenue__c]);
        System.assertEquals(1, [SELECT COUNT() FROM Revenue_by_Billing_Account__c]);
    }

    @isTest
    static void testBatchWithNoRecords() {
        // Step 1: Ensure no records exist
        Test.startTest();
        System.assertEquals(0, [SELECT COUNT() FROM Budget_and_Revenue__c]);
        System.assertEquals(0, [SELECT COUNT() FROM Revenue_by_Billing_Account__c]);

        // Step 2: Instantiate the batch class and execute it
       
        BatchDeleteDuplicateRevenue batch = new BatchDeleteDuplicateRevenue();
        Database.executeBatch(batch);
        Test.stopTest();

        // Step 3: Verify that no exceptions were thrown and that no records exist
        System.assertEquals(0, [SELECT COUNT() FROM Budget_and_Revenue__c]);
        System.assertEquals(0, [SELECT COUNT() FROM Revenue_by_Billing_Account__c]);
    }
}