force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Organisation’s main (generic) business email address. 
Users can edit this field (regardless of whether the organisation is a Prospect or Customer) without having to raise a case to the Data Quality team.</inlineHelpText>
    <label>Org Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/ArticleID__c.field-meta.xml
<CustomField>
    <fullName>ArticleID__c</fullName>
    <description>Tracking Number of Article</description>
    <externalId>true</externalId>
    <label>Article ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Article__c/fields/ArticleLodgementDate__c.field-meta.xml
<CustomField>
    <fullName>ArticleLodgementDate__c</fullName>
    <label>Article Lodgement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ArticleType__c.field-meta.xml
<CustomField>
    <fullName>ArticleType__c</fullName>
    <label>Article Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regular Parcel</fullName>
            </value>
            <value>
                <fullName>Courier Parcel</fullName>
            </value>
            <value>
                <fullName>Express Parcel</fullName>
            </value>
            <value>
                <fullName>Regular Letter</fullName>
            </value>
            <value>
                <fullName>Courier Letter</fullName>
            </value>
            <value>
                <fullName>Express Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture network information for an article</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Receiver_APCN__c.field-meta.xml
<CustomField>
    <fullName>Receiver_APCN__c</fullName>
    <label>Receiver APCN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/ReceiverPostcode__c.field-meta.xml
<CustomField>
    <fullName>ReceiverPostcode__c</fullName>
    <label>Receiver Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/SenderPostcode__c.field-meta.xml
<CustomField>
    <fullName>SenderPostcode__c</fullName>
    <label>Sender Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>true</active>
    <description>SSSW</description>
    <label>Article</label>
</RecordType>

force-app/main/default/objects/Case/fields/ArticleTest__c.field-meta.xml
<CustomField>
    <fullName>ArticleTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ArticleType__c.field-meta.xml
<CustomField>
    <fullName>ArticleType__c</fullName>
    <description>Used for Contact Us Form
2014-05 CCU - Changed from multi-picklist to picklist as per instructed</description>
    <label>Article Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Letter</fullName>
            </value>
            <value>
                <fullName>Parcel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CaseOriginator__c.field-meta.xml
<CustomField>
    <fullName>CaseOriginator__c</fullName>
    <description>SSSW</description>
    <label>Case Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Sender</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Addressee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/LastStatusUpdate__c.field-meta.xml
<CustomField>
    <fullName>LastStatusUpdate__c</fullName>
    <description>Provides the last time the status is updated</description>
    <label>Last Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SLATargetDate__c.field-meta.xml
<CustomField>
    <fullName>SLATargetDate__c</fullName>
    <description>This date is used to determine how long can a case remain in the queue before it gets assigned to users. This date is also used by the CAR team to determine the estimated SLA date/time.</description>
    <label>SLA Target Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Exact_Target_LogIn__c/Exact_Target_LogIn__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Exact Target LogIn</label>
</CustomObject>

force-app/main/default/objects/Exact_Target_LogIn__c/fields/BulkSSSWBatchSize__c.field-meta.xml
<CustomField>
    <fullName>BulkSSSWBatchSize__c</fullName>
    <label>Bulk SSSW Case Send Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exact_Target_LogIn__c/fields/Message_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Message_EndPoint__c</fullName>
    <label>Message EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exact_Target_LogIn__c/fields/RequestToken_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>RequestToken_EndPoint__c</fullName>
    <label>RequestToken EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Network__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Network__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <externalId>true</externalId>
    <label>Post Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Default_Taks.recordType-meta.xml
<RecordType>
    <fullName>Default_Taks</fullName>
    <active>true</active>
    <label>Default Task</label>
</RecordType>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSSW_SendBulkEmailContr_Test.cls
/**
  * @author       : kalpita.talwadekar@auspost.com.au
  * @date         : 20/05/2016
  * @description  : Test class for generating PM26 form
  */
/*******************************  History ************************************************
    Date                User                                        Comments
    20/12/2016          Dion Gunn        Modified to implement mock interface and correctly query ET Custom Settings.
                                        Ideally should be updated to do some actual testing, which it's not currently doing.
    13/02/2017          Dion Gunn       Modified to refer to new custom setting.
    14/05/2020          Swati Mogadala    Modified as per controller to make metods into getter setter methods #INC1579297
    22/10/2020          Neha Mehta        Modified as per controller #REQ2286193
*******************************  History ************************************************/
@isTest
private class SSSW_SendBulkEmailContr_Test{
    
    // Constants
    private static final String ADMIN_PROFILE = 'System Administrator';
    private static final String SSSW_MYNETWORK_PROFILE = 'SSSW - MyNetwork';
    private static final Profile prof = [SELECT Id,Name FROM profile where Name =: SSSW_MYNETWORK_PROFILE LIMIT 1];
    
    @testSetup static void testDataCreation() {
        //insert article with Account's APCN
        Article__c testArticle1 = new Article__c();
        testArticle1.Name = 'testArticle1';
        testArticle1.ArticleID__c = 'testArticle1';
        testArticle1.ArticleLodgementDate__c = Date.today();
        testArticle1.SenderPostcode__c = '3000';
        testArticle1.ReceiverPostcode__c = '3006';
        testArticle1.ArticleType__c = 'Regular Parcel';
        //testArticle1.Receiver_APCN__c = 'abcd1234';
        insert testArticle1;
        
        //insert network
        Network__c nw = TestDataProvider.createTestNetwork();
        nw.Email__c = 'top@top.com';
        nw.Name = 'test network';
        nw.Post_Code__c = '3000';
        nw.Geolocation__Latitude__s = 31;
        nw.Geolocation__Longitude__s = 121;
        insert nw;
        
        Map<String,Schema.RecordTypeInfo> accRecTypeMap = Schema.Sobjecttype.Account.getRecordTypeInfosByName();
        Account acc = TestUtility.createBusinessAccount('Wayne Enterprises',
                                                        accRecTypeMap.get('Organisation').getRecordTypeId());
        Database.insert(acc);

        Contact con = TestUtility.createContact('Bruce','Wayne','bruce@wayne.com',acc.id);
        con.Email = 'bruce@wayne.com';
        Database.insert(con);
        
        Map<String,Schema.RecordTypeInfo> caseRecTypeMap = Schema.Sobjecttype.Case.getRecordTypeInfosByName();
        Case csRec = TestUtility.createCase('Enquiry','In Progress','Investigation',acc.Id,con.Id,
                                            caseRecTypeMap.get('SSSW Delivery').getRecordTypeId());
        csRec.ArticleTest__c = testArticle1.Id;  
        csRec.Status = 'Awaiting Network Response';
        csRec.Network__c = nw.id;    
        csRec.EnquirySubType__c = 'Disputed Delivery';            
        //KPT 03-Nov-2017: Inactivated below since the clear-code mapping changed
        //csRec.ProductCategory__c = 'Domestic Parcels'; 
        csRec.ProductCategory__c = 'Web & Apps'; 
        csRec.caseOriginator__c ='Customer';//Added by Neha Mehta
        csRec.SLATargetDate__c = system.today()-2;    
        csRec.CreatedDate = system.today()-2;               
        Database.insert(csRec);
        String defaultRecTypeId = [Select Id from RecordType where developerName = 'Default_Taks'  limit 1].Id;
        Task tsk = new task(WhatId = csRec.Id,RecordTypeId = defaultRecTypeId,Type = 'Email', whoId = csRec.contact.Id,
                                Interaction_Type__c='Case Origin',Subject='task',
                               Status='Completed',CreatedDate = system.today()-2);
        insert tsk;
        
        Case csReec2 = csRec.clone();
        database.insert(csReec2);

        //ET Token Insert
        //13-02-2017 Dion Gunn: Modified the below to set batch size and refer to correct custom setting
        Exact_Target_LogIn__c etl = new Exact_Target_LogIn__c();
        etl.name = 'marketinglogin';
        etl.clientid__c = 'GdfGsdfsdfdsfHJ9a6lE9ukq';
        etl.clientsecret__c = 'secret stuff';
        etl.message_endpoint__c = 'http://messageendpoint.goes.here.com';
        etl.requestToken_endpoint__c = 'http://allaboutthattokenendpoint.com';
        etl.BulkSSSWBatchSize__c = 40;
        insert etl;
        
    }
    
    /**
      * @description       Method to test the send email functioanlity
      * @param             NA
      * @return            NA
      * @throws            NA
      */
    private static testMethod void testScn1() {
           Case cse = [Select Id from Case limit 1];
           //insert email template
           Folder fld = [Select Id from Folder where DeveloperName='SSSW_CCC_Bulk_Email_Template' limit 1];
           EmailTemplate em = new EmailTemplate(DeveloperName='TestTemplate',SUbject='Test',
                                            Body='here we are',Name='TestTemplate',
                                            FolderId=fld.Id,TemplateType='Text', isActive = true);
           insert em;           ApexPages.StandardController stdCon = new ApexPages.StandardController(cse);
           SSSW_SendBulkEmailContr contr = new SSSW_SendBulkEmailContr(stdCon);
           contr.initialize();          
          // contr.getType();
          // contr.getStatus();
          List<SelectOption> Type= contr.Type;
          List<SelectOption> Status= contr.Status;
          List<SelectOption> Queue= contr.QueueNames;
          // contr.getEmailTemplates();
           
           //Folder fld = new Folder(Name='SSSW_CCC_Bulk_Email_Template' , DeveloperName='SSSW_CCC_Bulk_Email_Template');
           //insert fld;
           
           List<SelectOption> ProdCat= contr.ProdCat;
           List<SelectOption> ProdSubCat= contr.ProdSubCat;
           List<SelectOption> EnqySubType= contr.EnqySubType;
           //contr.getProdCat();
           //contr.getProdSubCat();
          // contr.getEnqySubType();
           contr.cse.SLATargetDate__c = system.today()-4;
           contr.Rangecse.CreatedDate =  system.today()-4;
           contr.cse.LastStatusUpdate__c = system.today()-4;
           contr.Rangecse.LastStatusUpdate__c = system.today()+2;
           contr.fOpList[0].operator = '>';
           contr.fOpList[1].operator = '>';
           contr.fOpList[2].operator = '>';
           contr.fOpList[3].operator = '>';
           contr.fOpList[4].operator = '>';
           contr.fOpList[5].operator = '<';
           contr.showNoTask = false;
          Test.setMock(HttpCalloutMock.class, new ETIntegrationMock('SendEmail'));
           test.startTest();
               contr.getCases();
               contr.sendEmail();
               contr.templateId = em.Id;
               contr.sendEmail();
               contr.getEmailTemplates();
           test.stopTest();
    }
    
    /**
      * @description       Method to test the send email functioanlity
      * @param             NA
      * @return            NA
      * @throws            NA
      */
    private static testMethod void testScn2() {
           Case cse = [Select Id from Case limit 1];
           //insert email template
           Folder fld = [Select Id from Folder where DeveloperName='SSSW_CCC_Bulk_Email_Template' limit 1];
           EmailTemplate em = new EmailTemplate(DeveloperName='TestTemplate',SUbject='Test',
                                            Body='here we are',Name='TestTemplate',
                                            FolderId=fld.Id,TemplateType='Text', isActive = true);
           insert em;           ApexPages.StandardController stdCon = new ApexPages.StandardController(cse);
           SSSW_SendBulkEmailContr contr = new SSSW_SendBulkEmailContr(stdCon);
           contr.initialize();          
           //contr.getType();
           //contr.getStatus();
           //contr.getQueNames();
           List<SelectOption> Types= contr.Type;
           List<SelectOption> Status= contr.Status;
           List<SelectOption> Queue= contr.QueueNames;
           //contr.getEmailTemplates();
           
           //Folder fld = new Folder(Name='SSSW_CCC_Bulk_Email_Template' , DeveloperName='SSSW_CCC_Bulk_Email_Template');
           //insert fld;
          // contr.getEmailTemplates();
           List<SelectOption> ProdCat= contr.ProdCat;
           List<SelectOption> ProdSubCat= contr.ProdSubCat;
           List<SelectOption> EnqySubType= contr.EnqySubType;
           //contr.getProdCat();
           //contr.getProdSubCat();
           //contr.getEnqySubType();
           contr.cse.SLATargetDate__c = system.today()-4;
           contr.Rangecse.CreatedDate =  system.today()-4;
           contr.cse.LastStatusUpdate__c = system.today()-4;
           contr.Rangecse.LastStatusUpdate__c = system.today()+2;
           contr.fOpList[0].operator = '>';
           contr.fOpList[1].operator = '>';
           contr.fOpList[2].operator = '>';
           contr.fOpList[3].operator = '>';
           contr.fOpList[4].operator = '>';
           contr.fOpList[5].operator = '<';
           contr.showNoTask = true;
           Test.setMock(HttpCalloutMock.class, new ETIntegrationMock('SendEmail'));
           test.startTest();
               contr.getCases();
               contr.sendEmail();
               contr.templateId = em.Id;
               contr.sendEmail();
               contr.getEmailTemplates();
           test.stopTest();
    }

    public class ETIntegrationMock implements HttpCalloutMock {

        public String body;

        public ETIntegrationMock(String requestType) {
            if(requestType.equals('Token')) {
                this.body = '{"accessToken": "7RxKd99XIZuw7YhPKFHZ93Rd","expiresIn": 3479}';
            }
            if(requestType.equals('SendEmail')) {
                this.body = '{"requestId":"dd63978e-bca6-4eb8-b3ae-9e98949b8703","responses":[{"recipientSendId":"dd63978e-bca6-4eb8-b3ae-9e98949b8703","hasErrors":false,"messages":["Queued"]}]}';
            }
        }

        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody(body);
            response.setStatusCode(200);
            return response;
        }
    }
    
}