force-app/main/default/objects/Account/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <description>This field captures the unique identifier from the legacy application, eg SAP CRM. It is expected to be populated during the initial data load and also used for ongoing integration.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the SAP Customer ID.</inlineHelpText>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>MailingStreet2__c</fullName>
    <description>SSSW</description>
    <label>Mailing Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BAMApplication__c/BAMApplication__c.object-meta.xml
<CustomObject>
    <description>Object stores configuration information for applications that are exposed through Merchant Portal</description>
    <label>Merchant Portal Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Portal Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMApplication__c/fields/AppKey__c.field-meta.xml
<CustomField>
    <fullName>AppKey__c</fullName>
    <description>External Application Key for API Linking</description>
    <externalId>true</externalId>
    <inlineHelpText>External Application Key for API Linking</inlineHelpText>
    <label>App Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BAMApplication__c/recordTypes/BAM.recordType-meta.xml
<RecordType>
    <fullName>BAM</fullName>
    <active>true</active>
    <description>Applications relating to the BAM Framework</description>
    <label>BAM</label>
</RecordType>

force-app/main/default/objects/BAMApplicationRole__c/BAMApplicationRole__c.object-meta.xml
<CustomObject>
    <description>Configuration for all the roles that are connected to a Application exposed in Merchant Portal</description>
    <label>Merchant Portal Application Role</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Role Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Portal Application Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMApplicationRole__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The Parent application that this role belongs to</description>
    <inlineHelpText>The Parent application that this role belongs to</inlineHelpText>
    <label>Application</label>
    <referenceTo>BAMApplication__c</referenceTo>
    <relationshipName>ApplicationRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BAMApplicationRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>The name of the role that will be displayed in BAM</description>
    <inlineHelpText>The name of the role that will be displayed in BAM</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Super Admin</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Super User</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BAMApplicationRole__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Determines whether the role is active or not. Only Active roles are exposed in BAM</description>
    <inlineHelpText>Determines whether the role is active or not. Only Active roles are exposed in BAM</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BAMContactApplication__c/BAMContactApplication__c.object-meta.xml
<CustomObject>
    <description>Stores a relationship between Contact and Merchant Portal application. This determines which applications are available to a particular contact when using Merchant Portal</description>
    <label>Merchant Portal Contact Application</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Merchant Portal Contact Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Portal Contact Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMContactApplication__c/fields/AppKey__c.field-meta.xml
<CustomField>
    <fullName>AppKey__c</fullName>
    <description>Stores the value of the Application&apos;s key. This is necessary since sharing rules do not currently support formula fields and certain teams require edit access to their respective records.</description>
    <inlineHelpText>Stores the value of the Application&apos;s key. This is necessary since sharing rules do not currently support formula fields and certain teams require edit access to their respective records.</inlineHelpText>
    <label>App Key (For Sharing Rules)</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BAMContactApplication__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The application assigned to the contact</description>
    <label>Application</label>
    <referenceTo>BAMApplication__c</referenceTo>
    <relationshipName>ContactApplications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BAMContactApplication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact the application is associated to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ContactApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BAMContactRole__c/BAMContactRole__c.object-meta.xml
<CustomObject>
    <description>This is a junction object that links a contact to a particular Application in the BAM structure.</description>
    <label>Merchant Portal Contact Role</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Portal Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMContactRole__c/fields/ApplicationRole__c.field-meta.xml
<CustomField>
    <fullName>ApplicationRole__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Application Role of this context</description>
    <inlineHelpText>The Application Role of this context</inlineHelpText>
    <label>Application Role</label>
    <referenceTo>BAMApplicationRole__c</referenceTo>
    <relationshipName>ApplicationRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BAMContactRole__c/fields/ContactApplication__c.field-meta.xml
<CustomField>
    <fullName>ContactApplication__c</fullName>
    <description>The contact application the role relates to.</description>
    <label>Contact Application</label>
    <referenceTo>BAMContactApplication__c</referenceTo>
    <relationshipName>ContactRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &apos;Accounts&apos; in SAP ERP, eg Charge Account, Cash Account, etc.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>PeopleSoft
TEAM</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PeopleSoft</fullName>
            </value>
            <value>
                <fullName>SAP ERP</fullName>
                <default>true</default>
                <label>SAP ERP</label>
            </value>
            <value>
                <fullName>TEAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field is used to select the non-Salesforce contact&apos;s role.</description>
    <inlineHelpText>This field is used to select the non-Salesforce contact&apos;s role.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated By</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>SMEs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>StarTrack - Source System</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Peoplesoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCUSettings__c/CCUSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SSSW - The different BSP setting values used by any code that has a prefix BSP or CCU</description>
    <label>BSP Settings</label>
</CustomObject>

force-app/main/default/objects/CCUSettings__c/fields/AdminCaseSubject__c.field-meta.xml
<CustomField>
    <fullName>AdminCaseSubject__c</fullName>
    <label>Admin Case Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCUSettings__c/fields/CCUCommunityUserProfileId__c.field-meta.xml
<CustomField>
    <fullName>CCUCommunityUserProfileId__c</fullName>
    <description>2014-06 CCU - This ProfileId will determine whether the Case Comment is from the business user or AusPost Agent.</description>
    <inlineHelpText>Please specify ProfileId (18 char) for &quot;CCU Community User&quot;</inlineHelpText>
    <label>CCU Community User ProfileId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCUSettings__c/fields/GeneralRecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>GeneralRecordTypeId__c</fullName>
    <description>2014-06 CCU - For saving enquiry with enquiry type  equal to &apos;ask a question&apos;.</description>
    <inlineHelpText>Please specify RecordTypeId (18 char) for &quot;SSSW General Enquiry&quot;</inlineHelpText>
    <label>SSSW General Enquiry RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCUSettings__c/fields/UserNameExtension__c.field-meta.xml
<CustomField>
    <fullName>UserNameExtension__c</fullName>
    <description>2014-06 CCU - This field decides the extension added to end of the UserName. For Production, it should be blank.</description>
    <label>UserName Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSSW</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mailing_DPID__c.field-meta.xml
<CustomField>
    <fullName>Mailing_DPID__c</fullName>
    <description>SSSW</description>
    <label>Mailing DPID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>MailingStreet2__c</fullName>
    <label>Mailing Street 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/DPID__c.field-meta.xml
<CustomField>
    <fullName>DPID__c</fullName>
    <description>2014-06 CCU - CCU Portal QAS implementation - allows portal user to update their address</description>
    <label>DPID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/bspRegistration.cls
public class bspRegistration
{
    /**************************************************
    Type:         Controller for visualforce page bspRegistration
    History:
    --------------------------------------------------
    2014-06-26    Louis Wang (Bluewolf)        Updated.
    2016-11-22    David Catindoy               Updated line 70.
    2019-01-22    saiswetha.pingali@auspost.com.au - Corrected the phone number format as per REQ1610773
    2019-03-13    saiswetha.pingali@auspost.com.au - Fix for INC1308447 - Creating bsp users for existing contacts errored.
    2019-07-31    nathan.franklin@auspost.com.au - Uplift to create BAM Application rules
    **************************************************/

    public Contact c {get; set;}
    public String section {get; set;}
    public String businessName {get; set;}
    public String businessNumber {get; set;}

    public AddressExtension mailingAddress {get;set;}
    private string ccuProfileId {get;set;}
    private string generalRecordTypeId {get;set;}
    private string usernameExtension {get;set;}
    private string caseSubject {get; set;}

    public bspRegistration() {
        c = new Contact();
        // default to Australia
        c.MailingCountry = 'Australia';

        // initialise component variables
        mailingAddress = new AddressExtension(c.MailingStreet, c.MailingStreet2__c, c.MailingCity, c.MailingState, c.MailingPostalCode, c.Mailing_DPID__c,
                c.MailingCountry);

        getBSPSetting();
        setPageHeaders();
    }

    public pageReference redirect() {
        system.debug('INFO:'+Userinfo.getUserType());
        if(Userinfo.getUserType()<>'Guest') {
            PageReference p= new PageReference('/bsp/bspEnquiry');
            return p;
        }
        return null;
    }

    private void getBSPSetting()
    {
        // grab detail from Custom Setting
        CCUSettings__c configSetting = CCUSettings__c.getInstance();
        ccuProfileId = configSetting.CCUCommunityUserProfileId__c;
        generalRecordTypeId = configSetting.GeneralRecordTypeId__c;
        usernameExtension = configSetting.UsernameExtension__c;
        caseSubject = configSetting.AdminCaseSubject__c;
    }

    public PageReference save()
    {
        setPageHeaders();
        c.Phone = c.Phone.replaceAll('[^\\d]','');


        // When Create Account button is clicked,
        //    - create a Contact
        //    - create a User
        //    - Create a Case
        SavePoint sp = Database.setSavepoint();
        String myBusinessName;
        myBusinessName = string.escapeSingleQuotes(businessName.trim());
        system.debug('BUSINESS NAME:'+myBusinessName);
        myBusinessName = '\''+myBusinessName + '\'';
        system.debug('BUSINESS NAME:'+myBusinessName);
        //myBusinessName = string.escapeSingleQuotes(myBusinessName.trim());
        businessNumber = string.escapeSingleQuotes(businessNumber.trim());

        //Updated Nov. 22, 2016 - StarTrack update to not allow portal guest to create new account against StarTrack billing account (Australia Post account number) and StarTrack Account Name (Business Name)
        String query = 'SELECT Id, Organisation__r.Id, Organisation__r.Name FROM Billing_Account__c WHERE Organisation__r.Name = ' + myBusinessName + ' AND LEGACY_ID__c = \''+businessNumber+'\' AND Source_System__c = \'' + BspConstants.SOURCE_SYSTEM_SAP_ERP + '\' LIMIT 1';

        // Check if entered Business name and Australia Post account number exists
        List<Billing_Account__c> accts = Database.query(query);
        if(accts.size() == 0){
            string msgString = 'Your account is not created. Please provide the right Business Name and Australia Post account number.';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, msgString);
            ApexPages.addMessage(myMsg);
            return null;
        }
        // pick the first record from the list
        Billing_Account__c a = accts[0];

        // check if the contact already exists in CRM,
        //    based on FirstName, LastName and Email
        List<Contact> checkContacts = new List<Contact>();
        system.debug('*** details***');
        system.debug(c.FirstName);
        system.debug(c.LastName);
        system.debug(c.Email);
        system.debug(a.Organisation__r.Name);
        Boolean canICreateContact = true;
        Boolean canIUpdateContact = false;
        //Fix - INC1308447 Updated SOQL to include Phone
        checkContacts = [SELECT Id, Email, FirstName, LastName,Account.Name,Phone
        FROM Contact
        WHERE FirstName = : c.FirstName
        AND LastName = : c.LastName
        AND Email = : c.Email
        AND BillingAccount__c = :a.Id
        AND IsPersonAccount = false
        ORDER BY CreatedDate];
        if(checkContacts.size()==0) {
            checkContacts = [SELECT Id, Email,Phone
            FROM Contact
            WHERE FirstName = : c.FirstName
            AND LastName = : c.LastName
            AND Email = : c.Email
            AND BillingAccount__c = null
            AND IsPersonAccount = false
            ORDER BY CreatedDate];
            if(checkContacts.size()==0)
            {
                checkContacts = [SELECT Id, Email,Phone
                FROM Contact
                WHERE FirstName = : c.FirstName
                AND LastName = : c.LastName
                AND Email = : c.Email
                AND IsPersonAccount = false
                ORDER BY CreatedDate];
                if(checkContacts.size()>0) {
                    // if the Contact already exists, throw error
                    string msgString = 'You already have an existing account with Australia Post related to a different Billing Account. Please contact Australia Post to update your details.';
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, msgString);
                    ApexPages.addMessage(myMsg);
                    return null;
                }
            }
            else
            {
                canIUpdateContact = true;
                c = checkContacts[0];
            }
        } else {
            canICreateContact = false;
            c = checkContacts[0];
        }



        // check if the particular username already been taken
        List<User> checkUsers = [SELECT Id
        FROM User
        WHERE Username = : c.Email + usernameExtension];
        if(checkUsers.size()>0)
        {
            // if the User already exists, throw error
            string msgString = 'The Email Address/Login Name is already taken. Please contact us to enable your account. Or use forget password to receive your latest credentials via Email';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, msgString);
            ApexPages.addMessage(myMsg);
            return null;
        }


        //Set contact details
        c.accountId = a.Organisation__r.Id;
        // fetch info from component variable
        c.MailingStreet = mailingAddress.line1.split(',',2)[0];
        system.debug('c.mailingStreet:'+c.MailingStreet+mailingAddress.dpid);
        c.MailingStreet2__c = mailingAddress.line2;
        c.MailingCity = mailingAddress.city;
        c.MailingState = mailingAddress.state;
        c.MailingPostalCode = mailingAddress.postcode;
        c.MailingCountry = mailingAddress.countryName;
        c.Mailing_DPID__c = mailingAddress.dpid;
        // set billing account on contact
        c.BillingAccount__c = a.Id;

        try
        {
            If(CanIUpdateContact) {
                update c;
            }
            else If(CanICreateContact) {
                insert c;
            }

            // grab the bam application
            BAMApplication__c app = [Select Id From BAMApplication__c Where AppKey__c = 'BSP'];
            BAMApplicationRole__c role = [Select Id From BAMApplicationRole__c Where Application__r.AppKey__c = 'BSP' and Role__c = 'User'];

            // create BAM application and contact role for initial state
            BAMContactApplication__c contactApp = new BAMContactApplication__c(Application__c = app.Id, Contact__c = c.Id, Status__c = 'Active');
            insert contactApp;

            BAMContactRole__c contactRole = new BAMContactRole__c(ContactApplication__c = contactApp.Id, ApplicationRole__c = role.Id, Status__c = 'Active');
            insert contactRole;
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
            Database.rollback(sp);
            return null;
        }

        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.EmailHeader.triggerUserEmail = true;
        string aliasString = c.FirstName.substring(0,1) + c.LastName;
        if(c.LastName.Length()>4)
        {
            aliasString = c.FirstName.substring(0,1) + c.LastName.substring(0,4);
        }


        //PageReference p = site.login(u.username,password,'ssswdev1-auspostccu.cs5.force.com/ccu');
        User u = new User(  alias = aliasString,
                firstname = c.FirstName,
                Street = mailingAddress.line1,
                City = mailingAddress.city,
                State = mailingAddress.state,
                PostalCode = mailingAddress.postcode,
                Country = mailingAddress.countryName,
                DPID__c = mailingAddress.dpid,
                CompanyName = businessName,
                Phone = c.Phone,
                MobilePhone = c.MobilePhone,
                email=c.email,
                emailencodingkey='UTF-8',
                lastname=c.LastName,
                languagelocalekey='en_US',
                localesidkey='en_AU',
                profileid = ccuProfileId,
                contactId=c.Id,
                timezonesidkey='Australia/Sydney',
                username=c.email+usernameExtension);
        u.setOptions(dmo);

        try
        {
            insert u;
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
            Database.rollback(sp);
            return null;
        }

        Case myCase = new Case(RecordTypeId=generalRecordTypeId,
                Subject=caseSubject,
                Type='General Enquiry',
                Origin='BSP',
                ContactId=c.Id);
        try
        {
            insert myCase;
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
            Database.rollback(sp);
            return null;
        }

        // if reaches here, then everything are saved successfully. Move to next section.
        section = 'thankyou';
        return null;
    }

    private void setPageHeaders()
    {
        // the following code resolved IE8/9 mis-aligned rendering issue

        // Make sure IE9 will use edge (IE9) mode - without the insertion of the following header
        // <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        // comes too late and gives this error
        // HTML1115: X-UA-Compatible META tag ('IE=edge,chrome=1') ignored because document mode is already finalized.
        // Caused by Vf outputing tags and content prior to this meta tag
        Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=edge,chrome=1');

        // Add headers as advised by security review 2013-02-15
        Apexpages.currentPage().getHeaders().put('X-Frame-Options', 'SameOrigin'); // To prevent clickjacking
        Apexpages.currentPage().getHeaders().put('Cache-control', 'no-store'); // To prevent the browser to store personal information into its cache
        Apexpages.currentPage().getHeaders().put('Pragma', 'no-cache');
    }


}