force-app/main/default/objects/Account/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <description>This field captures the unique identifier from the legacy application, eg SAP CRM. It is expected to be populated during the initial data load and also used for ongoing integration.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the SAP Customer ID.</inlineHelpText>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APR__c/APR__c.object-meta.xml
<CustomObject>
    <description>Annual Price Review.</description>
    <label>APR</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>APR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/APR__c/fields/Legal_Entity_Name_LookUp__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_LookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>APRs</relationshipLabel>
    <relationshipName>APRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &apos;Accounts&apos; in SAP ERP, eg Charge Account, Cash Account, etc.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/APRsSelector_Test.cls
/**
 * @author Harry Wang
 * @group Tests
 * @tag Selector
 * @domain Sales
 * @description Test class for APRsSelector
 * @changelog
 * 2022-12-01 - Harry Wang - Created
 */
@IsTest
public with sharing class APRsSelector_Test {
	/**
	 * Test:
	 *  Ensures that the selectors QueryBuilder is generating the correct output
	 */
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectString() {
		// =====================================
		// Data Preparation
		// =====================================
		// None!

		// =====================================
		// Stubbing
		// =====================================
		// None!

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		APRsSelector selector = APRsSelector.newInstance();
		QueryBuilder qb = selector.newQueryBuilder();
		String soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select from APR__c');

		Test.stopTest();
	}

	/**
	* Test:
	*  Ensures that the selectors QueryBuilder is generating the correct output
	*/
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectStringForFieldOverride() {
		Test.startTest();

		APRsSelector selector = APRsSelector.newInstance(1, new Set<SObjectField>{
				APR__c.Id, APR__c.Legal_Entity_Name_LookUp__c
		});
		QueryBuilder qb = selector.newQueryBuilder();
		String soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select from APR__c');
		System.assertEquals(false, Pattern.compile('(?ism)RecordTypeId\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting selects RecordTypeId but it shouldn\'t: ' + soql);
		System.assertEquals(true, Pattern.compile('(?ism)Legal_Entity_Name_LookUp__c\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select Legal_Entity_Name_LookUp__c field: ' + soql);

		selector = APRsSelector.newInstance(1, new Map<SObjectType, Set<SObjectField>>{
				APR__c.SObjectType => new Set<SObjectField>{APR__c.Id}
		});
		qb = selector.newQueryBuilder();
		soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select from APR__c');
		System.assertEquals(false, Pattern.compile('(?ism)Legal_Entity_Name_LookUp__c\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting selects Legal_Entity_Name_LookUp__c but it shouldn\'t: ' + soql);
		System.assertEquals(true, Pattern.compile('(?ism)Id\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select Id field: ' + soql);

		selector = APRsSelector.newInstance(new Map<SObjectType, Set<SObjectField>>{
				APR__c.SObjectType => new Set<SObjectField>{APR__c.Id, APR__c.Legal_Entity_Name_LookUp__c}
		});
		qb = selector.newQueryBuilder();
		soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?is)\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select from APR__c');
		System.assertEquals(false, Pattern.compile('(?ism)RecordTypeId\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting selects RecordTypeId but it shouldn\'t: ' + soql);
		System.assertEquals(true, Pattern.compile('(?ism)Legal_Entity_Name_LookUp__c\\b.*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select Legal_Entity_Name_LookUp__c field: ' + soql);

		Test.stopTest();
	}

	/**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output with related fields
     */
	@IsTest
	public static void testEnsureQueryBuilderProducesCorrectStringWithRelatedFields() {

		// =====================================
		// Data Preparation
		// =====================================
		// None!

		// =====================================
		// Stubbing
		// =====================================
		// None!

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		APRsSelector selector = APRsSelector.newInstance(0);
		QueryBuilder qb = selector.newQueryBuilder(new Set<Object>{APRsSelector.Options.WITH_ORGANISATION});
		String soql = qb.toSoqlString();
		System.assertEquals(true, Pattern.compile('(?ism)Legal_Entity_Name_LookUp__r\\..*?\\bfrom APR__C\\b').matcher(soql).find(), 'Resulting query does not select Organisation fields');

		Test.stopTest();

	}

	/**
	* Test:
	*  Ensures that the selector methods return expected matching result
	*/
	@IsTest
	public static void testSelectorIntegration() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Account> parentAccounts = ApplicationTestDataFactory.getAccounts(2, false);
		parentAccounts[0].LEGACY_ID__c = '60000000';
		parentAccounts[1].LEGACY_ID__c = '60000001';
		insert(parentAccounts);

		List<Billing_Account__c> billingAccounts = new List<Billing_Account__c>();
		for (Account parentAccount: parentAccounts) {
			billingAccounts.add(ApplicationTestDataFactory.getBillingAccounts(1, parentAccount.Id, 'SAP ERP', false)[0]);
		}
		insert billingAccounts;

		List<APR__c> aprs = new List<APR__c>();
		for (Billing_Account__c billingAccount: billingAccounts) {
			APR__c apr = ApplicationTestDataFactory.getAPRs(1, billingAccount.Id, null, false)[0];
			apr.Legal_Entity_Name_LookUp__c = billingAccount.Organisation__c;
			aprs.add(apr);
		}
		insert(aprs);

		// =====================================
		// Stubbing
		// =====================================
		//None

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		Set<Id> accountIds = new Set<Id>{parentAccounts[0].Id};
		Database.QueryLocator queryLocator = APRsSelector.newInstance().selectByAccountOrderByAccountIdQueryLocator(accountIds, new Set<Object>{
				APRsSelector.Options.WITH_ORGANISATION
		});

		List<APR__c> queryResults = (List<APR__c>)Database.query(queryLocator.getQuery());

		System.assertEquals(1, queryResults.size(), 'Expected to return only the APRs related to the supplied account');
		System.assertEquals(aprs[0].Id, queryResults[0].Id, 'Expected to return only the APRs related to the supplied account');


		queryLocator = APRsSelector.newInstance().selectByAccountOrderByAccountIdQueryLocator(new Set<Id>(), new Set<Object>{
				APRsSelector.Options.WITH_ORGANISATION
		});
		queryResults = (List<APR__c>)Database.query(queryLocator.getQuery());
		System.assertEquals(2, queryResults.size(), 'Expected to return APRs related to any account when account id is not specified');
		Test.stopTest();
	}
}