force-app/main/default/objects/Account/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <description>This field captures the unique identifier from the legacy application, eg SAP CRM. It is expected to be populated during the initial data load and also used for ongoing integration.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the SAP Customer ID.</inlineHelpText>
    <label>LEGACY ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <description>SSSW - Object used to store detail for an Article. WARNING: This is utilised by Integration processes from SAP-EM via Tibco.</description>
    <label>Article</label>
    <nameField>
        <label>Article Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Billing Account field to capture billing account info</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &apos;Accounts&apos; in SAP ERP, eg Charge Account, Cash Account, etc.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/LEGACY_ID__c.field-meta.xml
<CustomField>
    <fullName>LEGACY_ID__c</fullName>
    <externalId>true</externalId>
    <label>Billing Account No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Callers_Data_Change__c.field-meta.xml
<CustomField>
    <fullName>Callers_Data_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <description>StarTrack Caller values changed (triggers the process builder to record a task asynchronously using the Caller Data Capture datetime field)</description>
    <label>Create Call Log</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Number_of_Callers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Callers__c</fullName>
    <defaultValue>0</defaultValue>
    <description>StarTrack Number of Callers iterative field to set using Publisher Action and trigger the Process Builder job which stores the Caller information as a Task record.</description>
    <label>Number of Callers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recent_Caller_Email__c.field-meta.xml
<CustomField>
    <fullName>Recent_Caller_Email__c</fullName>
    <description>Capture recent caller email information</description>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>StarTrack: Capture Related Billing Account Information</description>
    <label>Related Billing Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Billing_Account__c.Organisation__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StarTrack_Error_Messages__c/StarTrack_Error_Messages__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>StarTrack: All error messages on startrack messages are captured here</description>
    <label>StarTrack Error Messages</label>
</CustomObject>

force-app/main/default/classes/StarTrackPBUtility_Test.cls
/************************************
 * History
 * Sept-2015:  Paul Fayle  Created
 * **********************************/
//Test of the Invocable method to Update the Web Email for StarTrack cases called by Process Builder
@isTest
private class StarTrackPBUtility_Test{
    public static testmethod void testPBUtility(){
        List<sobject> ls = TestDataProvider.createStartrackErrorMessagesData();

        // Verify all custom settings are created
        System.assertEquals(ls.size(),[SELECT id FROM StarTrack_Error_Messages__c].size());

        List<Account> lst_account = TestDataProvider.createAccount('test', 1);
        INSERT lst_account;
        lst_account[0].Legacy_Id__c = '60000000';
        UPDATE lst_account;
        
        List<Billing_Account__c> lst_billingAccount = TestDataProvider.createBillingAccount('test', 1, lst_account);
        INSERT lst_billingAccount;
        
        List<Article__c> lst_article = TestDataProvider.createArticle('Subject', 1,lst_billingAccount);       
        INSERT lst_article;        
        
        Id CaseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('General Enquiry').getRecordTypeId();
        List<case> lst_cases = TestDataProvider.createCases('Subject', 1,lst_article);
        INSERT lst_cases;
        lst_cases[0].Accountid = lst_account[0].id;
        lst_cases[0].Related_Billing_Account__c = lst_billingAccount[0].id; 
        lst_cases[0].Recent_Caller_Email__c = 'test@test.com';
        lst_cases[0].Origin = 'Phone';
        lst_cases[0].RecordTypeId = CaseRecTypeId;
        lst_cases[0].Number_of_Callers__c = 1;
        lst_cases[0].Callers_Data_Change__c = true;
        
        test.startTest();

        UPDATE lst_cases;
         

        Test.stopTest();
        for (Case c : [SELECT SuppliedEmail FROM Case WHERE ID = :lst_cases[0].Id]) {
            //System.assertEquals('test@test.com', c.SuppliedEmail); PB dependent
        }        
     }        
}