force-app/main/default/objects/Account/fields/Licence_Type__c.field-meta.xml
<CustomField>
    <fullName>Licence_Type__c</fullName>
    <description>Partner Info - Type of Outlet</description>
    <inlineHelpText>What type of Outlet does this Facility or Licence relate to?</inlineHelpText>
    <label>Outlet Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LPO</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>RP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement_Document__c/Agreement_Document__c.object-meta.xml
<CustomObject>
    <description>A container to attach Agreement Document for Retail and Network Partners</description>
    <label>Partner Agreement Document</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Agreement Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Agreement Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement_Document__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <label>Licence</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Licence_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agreement_Document__c/fields/Licence_Type__c.field-meta.xml
<CustomField>
    <fullName>Licence_Type__c</fullName>
    <label>Licence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LPO</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement_Document__c/fields/Rate_List__c.field-meta.xml
<CustomField>
    <fullName>Rate_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate List</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Licence_Type__c</field>
            <operation>equals</operation>
            <valueField>Rate_List__c.Licence_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rate_List__c</referenceTo>
    <relationshipName>Licence_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Approval_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Located</fullName>
            </value>
            <value>
                <fullName>Pending Pre-Approval</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Signature</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
            <value>
                <fullName>Not Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate_List__c/Rate_List__c.object-meta.xml
<CustomObject>
    <description>Rates for Partner Agreement Documents</description>
    <label>Partner Rate List</label>
    <nameField>
        <label>Rate List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_List__c/fields/ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to bypass validation in Apex RateListTriggerHandler_Test</description>
    <label>ByPassValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate_List__c/fields/Licence_Type__c.field-meta.xml
<CustomField>
    <fullName>Licence_Type__c</fullName>
    <label>Licence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LPO</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>CMA</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>LCPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate_List__c/recordTypes/LPO.recordType-meta.xml
<RecordType>
    <fullName>LPO</fullName>
    <active>true</active>
    <description>Rates for LPO Licence Type Partner Agreement Documents</description>
    <label>LPO</label>
</RecordType>

force-app/main/default/classes/GenerateDocumentPageControllerTest.cls
/**
   * Created by: Shashwat Nath
   * Description: Test class for GenerateDocumentPage class
   * Date: 07/10/2019
   */
@IsTest
public class GenerateDocumentPageControllerTest {
    /* Test Method for bulk approvals */
    @testSetup static void setup() {
        Account Acc = new Account();
        Acc.name = 'Test';
        insert Acc;

        //data setup
        Rate_List__c rtList = new Rate_List__c();
        rtList.name = 'Test';
        rtList.Status__c = 'Active';
        rtList.Licence_Type__c = 'LPO';
        insert rtList;
        
        rtList.Status__c = 'Active';
        rtList.ByPassValidation__c=true;
        update rtList;
        
        
         system.debug('Rate List after insert'+rtList);

        Agreement_Document__c agreementRec = new Agreement_Document__c();
        agreementRec.Rate_List__c = NULL;
        agreementRec.Licence__c = Acc.id;
        agreementRec.Licence_Type__c='LPO';
        insert agreementRec;

    }
    
    public static testmethod void updateAgreementDocumentRecordTest() {

        Agreement_Document__c agreementRec = [Select ID FROM Agreement_Document__c LIMIT 1];

        Test.StartTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(agreementRec);
            GenerateDocumentPageController cont = new GenerateDocumentPageController(sc);
            GenerateDocumentPageController.updateAgreementDocumentRecord(agreementRec.id , 'LPO');
        Test.StopTest();
        List<Agreement_Document__c> rtlistUpdated = new List<Agreement_Document__c>();
        rtlistUpdated = [Select Id , Rate_List__c from Agreement_Document__c where ID=:agreementRec.id LIMIT 1];
        Rate_List__c rtList = [SELECT ID, Licence_Type__c , Status__c FROM Rate_List__c LIMIT 1];
        system.debug('Rate List'+rtList);
        System.AssertEquals(rtlistUpdated[0].Rate_List__c , rtList.id);

    }
}