force-app/main/default/objects/Account/fields/MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>MailingStreet2__c</fullName>
    <description>SSSW</description>
    <label>Mailing Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <description>Primary Address which consists of street, suburb, state, country</description>
    <label>Sender Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Line1__c.field-meta.xml
<CustomField>
    <fullName>Address1Line1__c</fullName>
    <label>Addressee Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1line2__c.field-meta.xml
<CustomField>
    <fullName>Address1line2__c</fullName>
    <description>Address line 2, SSSW</description>
    <label>Sender Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Postcode__c.field-meta.xml
<CustomField>
    <fullName>Address1Postcode__c</fullName>
    <description>SSSW</description>
    <label>Sender Address Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1State__c.field-meta.xml
<CustomField>
    <fullName>Address1State__c</fullName>
    <description>SSSW</description>
    <label>Sender Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address1Suburb__c.field-meta.xml
<CustomField>
    <fullName>Address1Suburb__c</fullName>
    <description>SSSW</description>
    <label>Sender Address Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <description>Secondary address which consists of street, suburb, state and country</description>
    <label>Addressee Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Line1__c.field-meta.xml
<CustomField>
    <fullName>Address2Line1__c</fullName>
    <label>Sender Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2line2__c.field-meta.xml
<CustomField>
    <fullName>Address2line2__c</fullName>
    <description>Line 2 of secondary Address, SSSW</description>
    <label>Addressee Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Postcode__c.field-meta.xml
<CustomField>
    <fullName>Address2Postcode__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2State__c.field-meta.xml
<CustomField>
    <fullName>Address2State__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address2Suburb__c.field-meta.xml
<CustomField>
    <fullName>Address2Suburb__c</fullName>
    <description>SSSW</description>
    <label>Addressee Address Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DatePosted__c.field-meta.xml
<CustomField>
    <fullName>DatePosted__c</fullName>
    <label>Date Posted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DescriptionofContents__c.field-meta.xml
<CustomField>
    <fullName>DescriptionofContents__c</fullName>
    <label>Description of Contents</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Name__c</fullName>
    <description>SSSW</description>
    <label>Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>SSSW - Clear View Codes - Controlling Picklist</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Parcels</fullName>
            </value>
            <value>
                <fullName>International Parcels</fullName>
            </value>
            <value>
                <fullName>Domestic Letters</fullName>
            </value>
            <value>
                <fullName>International Letters</fullName>
            </value>
            <value>
                <fullName>Money &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Post Office &amp; Business Hub Services</fullName>
            </value>
            <value>
                <fullName>Travel &amp; ID</fullName>
            </value>
            <value>
                <fullName>Web &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Card Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Accounting Service Helpdesk</fullName>
            </value>
            <value>
                <fullName>eParcel</fullName>
            </value>
            <value>
                <fullName>e-LMS</fullName>
            </value>
            <value>
                <fullName>S &amp; T APIs</fullName>
            </value>
            <value>
                <fullName>eParcel Unmanifested</fullName>
            </value>
            <value>
                <fullName>Parcel Send</fullName>
            </value>
            <value>
                <fullName>Contract/Account Issue</fullName>
            </value>
            <value>
                <fullName>Customer Account Issues</fullName>
            </value>
            <value>
                <fullName>Parcel Send Assistance/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProductSubCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductSubCategory__c</fullName>
    <description>SSSW - Clear View Codes - Dependant Picklist</description>
    <label>Product Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Access Maintenance</fullName>
            </value>
            <value>
                <fullName>Acc Non-urgent</fullName>
            </value>
            <value>
                <fullName>Acc Urgent</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Payable AP</fullName>
            </value>
            <value>
                <fullName>Accounts Payable ST</fullName>
            </value>
            <value>
                <fullName>Advice</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airmail over 2kg</fullName>
            </value>
            <value>
                <fullName>Airmail under 2kg</fullName>
            </value>
            <value>
                <fullName>All Other ID&amp;V services</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>API Key Issues</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>Armaguard</fullName>
            </value>
            <value>
                <fullName>Article Collection</fullName>
            </value>
            <value>
                <fullName>ATO</fullName>
            </value>
            <value>
                <fullName>Bank@Post</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Barcodes</fullName>
            </value>
            <value>
                <fullName>BCard</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Business Letters</fullName>
            </value>
            <value>
                <fullName>Car Insurance</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>CEPOS</fullName>
            </value>
            <value>
                <fullName>Change of Address Online</fullName>
            </value>
            <value>
                <fullName>Cheque Fraud</fullName>
            </value>
            <value>
                <fullName>Cheques</fullName>
            </value>
            <value>
                <fullName>China Union Pay - CUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceID__c.field-meta.xml
<CustomField>
    <fullName>ReferenceID__c</fullName>
    <description>SSSW Reference ID, and used for Contact Us Form</description>
    <externalId>true</externalId>
    <inlineHelpText>The Reference ID for this Case. i.e Article ID or MRS CRN.</inlineHelpText>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Secondary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact__c</fullName>
    <description>SSSW - Text field for page layouts</description>
    <label>Addressee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SecondaryContact__c.field-meta.xml
<CustomField>
    <fullName>SecondaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SSSW - This field is used to allow for Cases to have a dual relationship to the Contacts in the System, and also for the Contact Us Form</description>
    <label>Secondary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Secondary Cases</relationshipLabel>
    <relationshipName>SecondaryCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>MailingStreet2__c</fullName>
    <label>Mailing Street 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SSSWCN18FormContExt.cls
/**
  * @author       : kalpita.talwadekar@auspost.com.au
  * @date         : 03/12/2015
  * @description  : Controller class for CN18 form
  */
/*******************************  History ************************************************
    
*******************************  History ************************************************/
public with sharing class SSSWCN18FormContExt {
    
    public transient String htmlBody { get; set; }
    public Case relatedCase {get;set;}
    private String caseId ;
    private Boolean isCreate = false;
    public STring msgBody1 {get;set;}
    public STring msgBody2 {get;set;}
    public STring msgBody3 {get;set;}
    
    /** 
      * @name: SSSWCN18FormContExt()
      * @desciption: Controller method to get the case record 
      * @param: NA
      * @return: NA
      *
      */
    public SSSWCN18FormContExt(ApexPages.StandardController controller) {
        
        if (controller.getRecord() != null) {
            relatedCase = (Case)controller.getRecord(); 
            caseId = controller.getRecord().Id;
            isCreate = apexpages.currentpage().getparameters().get('create') == 'true' ? true : false;
        }
    }
    
    /** 
      * @name: getBody()
      * @desciption: method to create the body of the cn18 form and attach to case
      * @param: NA
      * @return: NA
      *
      */
    public void getBody() {
        try {

            if(!String.isBlank(caseId)) {
                relatedCase = [Select Id, CaseNumber, Secondary_Contact__c, SecondaryContact__r.FirstName, Address2Line1__c ,Address2State__c ,Address2Postcode__c, 
                                SecondaryContact__r.LastName, Address2line2__c,Address1Line1__c,Address1Suburb__c,Address1line2__c,
                                Address1State__c,Address1Postcode__c, Contact.MailingStreet, Contact.MailingStreet2__c, Address2Suburb__c ,
                                Contact.MailingCity,Contact.MailingState,Contact.MailingPostalCode,
                                Account.Name,ProductCategory__c,ReferenceID__c,Contact.Name,
                                DescriptionofContents__c,DatePosted__c,ProductSubCategory__c,
                                Contact.Firstname, Contact.LastName,Primary_Name__c,Address1__c,
                                Address2__c from Case where Id =: caseId limit 1];
                //creating message body
                String datePosted = relatedCase.DatePosted__c!=null   ? relatedCase.DatePosted__c.day()+'/'+
                                relatedCase.DatePosted__c.month() +'/'+relatedCase.DatePosted__c.year()  :''; 
                String addreseeFrstName = !STring.isblank(relatedCase.Secondary_Contact__c) ? 
                                                    relatedCase.Secondary_Contact__c.split(' ' , 2).get(0) : '';                                                      
               
                msgBody1 = Label.CL_CN18_Content.replaceAll('#addFName',addreseeFrstName).replaceAll('#contName',relatedCase.Contact.Name).replaceAll('#caseNumber',relatedCase.CaseNumber);
               
                String senderAdd = !String.isBlank(relatedCase.Primary_Name__c ) ? relatedCase.Primary_Name__c +', ' : '' ;
                senderAdd += !String.isBlank(relatedCase.Address1Line1__c ) ? relatedCase.Address1Line1__c +', ' : ''  ;
                senderAdd += !String.isBlank(relatedCase.Address1Line2__c) ? relatedCase.Address1Line2__c +', ' : ''  ;
                senderAdd += !String.isBlank(relatedCase.Address1Suburb__c ) ? relatedCase.Address1Suburb__c +', ' : ''  ;
                senderAdd += !String.isBlank(relatedCase.Address1State__c ) ? relatedCase.Address1State__c +', ' : ''  ;
                senderAdd += !String.isBlank(relatedCase.Address1Postcode__c ) ? relatedCase.Address1Postcode__c +', ' : ''  ;
                senderAdd += '<br/><br/>';                
                String refNumber = !String.isBlank(relatedCase.ReferenceID__c) ? relatedCase.ReferenceID__c : '';
                String descCont = !String.isBlank(relatedCase.DescriptionofContents__c) ? relatedCase.DescriptionofContents__c : '' ;
                  
                msgBody2 = Label.CL_CN18_ParcelDetails.replaceAll('#refNumber#',refNumber).replaceAll('#senderDetails#',senderAdd ).replaceAll('#descOfCOntent#',descCont ).replaceAll('#datePosted#',datePosted );
                
                msgBody3 = Label.CL_CN18_Signature.replaceAll('#usernameInitial#',userinfo.getFirstName() +' ' + userinfo.getLastName().substring(0,1));
                
                PageReference pdf = Page.SSSWCN18Form;
                // add parent id to the parameters for standardcontroller
                pdf.getParameters().put('id',caseId);
            
                // create the new attachment
                Attachment attach = new Attachment();
                // the contents of the attachment from the pdf
                Blob body;
                // returns the output of the page as a PDF
                body = !test.isRunningTest() ? body = pdf.getContent() : Blob.valueOf('Unit Test Attachment Body');
                attach.Body = body;
                // add the user entered name
                attach.Name = 'CN 18 Form'+ '.pdf';
                attach.IsPrivate = true;
                // attach the pdf to the account
                attach.ParentId = caseId;
                if(isCreate)  {
                    database.insert(attach);
                }
            }
            
        } 
        catch (Exception exp) {
            // Error Logged to Exception object for analysis
            UTIL_LoggingService.logHandledException(exp, UserInfo.getOrganizationId(), SSSWConstants.SSSW_APP, 
                                                    'SSSWCN18FormContExt', 'getBody', 
                                                    null, LoggingLevel.ERROR);
        }
    } 
    
}