force-app/main/default/objects/Account/fields/SalesTeamType__c.field-meta.xml
<CustomField>
    <fullName>SalesTeamType__c</fullName>
    <description>Dependent picklist field to segment Accounts based on Sales team picklist. This field is populated by automation on business accounts based on the controlling &quot;Sales Team&quot; (API Name - &quot;Sales_Segment__c&quot;) pick list value and not intended to be populated directly. The value of this field drives sharing behaviour that handles access segmentation for Sales Team.
- Criteria based sharing rules on Account (3 sharing rules)
- Apex managed sharing for sensitive child objects having a lookup relationship to Account</description>
    <inlineHelpText>Segment of the Account based on the assigned Sales Team.</inlineHelpText>
    <label>Sales Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holding</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Intermediary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APR__c/APR__c.object-meta.xml
<CustomObject>
    <description>Annual Price Review.</description>
    <label>APR</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>APR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/APR__c/fields/Legal_Entity_Name_LookUp__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_LookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>APRs</relationshipLabel>
    <relationshipName>APRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesRecordSharingBatchable_Test.cls
/**
 * @author Harry Wang
 * @group Tests
 * @tag Batch
 * @domain Sales
 * @description Test class for SalesRecordSharingBatchable
 * @changelog
 * 2022-12-05 - Harry Wang - Created
 */
@IsTest
private class SalesRecordSharingBatchable_Test {
	@IsTest
	static void testBatch() {
		// =====================================
		// Data Preparation
		// =====================================
		String soql = 'SELECT Legal_Entity_Name_LookUp__c, Legal_Entity_Name_LookUp__r.SalesTeamType__c FROM APR__c WHERE Legal_Entity_Name_LookUp__c != NULL';
		List<APR__c> aprs = new List<APR__c>{new APR__c()};

		// =====================================
		// Stubbing
		// =====================================
		SalesRecordSharingService mockSharingService = (SalesRecordSharingService) MockUtility.mockUtility(SalesRecordSharingService.class);
		SalesAPRSharingBatchable sharingBatchable = (SalesAPRSharingBatchable) MockUtility.mockUtility(SalesAPRSharingBatchable.class);
		ApplicationLogger mockLoggerService = (ApplicationLogger) MockUtility.mockUtility(ApplicationLogger.class);

		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockSharingService.getSharingConfiguration((SObjectType)fflib_Match.anyObject())).thenAnswer(new AnswerMapping());
		MockUtility.Mocks.when(sharingBatchable.getQueryLocator()).thenReturn(Database.getQueryLocator(soql));
		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		SalesAPRSharingBatchable batch = new SalesAPRSharingBatchable();
		Database.QueryLocator ql = batch.start(null);
		batch.execute(null, aprs);
		batch.finish(null);

		Test.stopTest();

		System.assertNotEquals(null, ql, 'Expect a valid query locator to be returned');
		((SalesRecordSharingService)MockUtility.Mocks.verify(mockSharingService, MockUtility.Mocks.times(0))).shareRecords((SObjectType)fflib_Match.anyObject(), (Map<Id, SObject>)fflib_Match.anyObject(), fflib_Match.anyBoolean());
		((ApplicationLogger)MockUtility.Mocks.verify(mockLoggerService, MockUtility.Mocks.times(1))).logException((ApplicationLogger.ExceptionWrapper)fflib_Match.anyObject(), fflib_Match.anyString(), fflib_Match.anyString(), fflib_Match.anyString(), fflib_Match.anyString(), (ApplicationLogger.LoggingLevel)fflib_Match.anyObject());
		((ApplicationLogger)MockUtility.Mocks.verify(mockLoggerService, MockUtility.Mocks.times(1))).logGenericMessage((List<String>)fflib_Match.anyList(), fflib_Match.anyString(), fflib_Match.anyString(), fflib_Match.anyString(), fflib_Match.anyString(), (ApplicationLogger.LoggingLevel)fflib_Match.anyObject());
	}

	public class AnswerMapping implements fflib_Answer {
		public Object answer(fflib_InvocationOnMock invocation) {
			SalesRecordSharingService.SalesSharingObjectMapping mapping = new SalesRecordSharingService.SalesSharingObjectMapping
					(APR__c.getSObjectType(), APR__c.Legal_Entity_Name_LookUp__c, 'Legal_Entity_Name_LookUp__r', 'reason');

			return mapping;
		}
	}

	private class MockException extends Exception{}
}