force-app/main/default/objects/BAMContactApplication__c/BAMContactApplication__c.object-meta.xml
<CustomObject>
    <description>Stores a relationship between Contact and Merchant Portal application. This determines which applications are available to a particular contact when using Merchant Portal</description>
    <label>Merchant Portal Contact Application</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Merchant Portal Contact Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Portal Contact Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BAMContactApplication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact the application is associated to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ContactApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BAMContactRole__c/BAMContactRole__c.object-meta.xml
<CustomObject>
    <description>This is a junction object that links a contact to a particular Application in the BAM structure.</description>
    <label>Merchant Portal Contact Role</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Portal Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BAMContactApplicationsSelector.cls
/**
 * @author Hasantha Liyanage
 * @date 2023-10-02
 * @group selector
 * @domain BAM
 * @description BAMContactRole__c selector
 * @changelog
 * 2023-10-02 - Hasantha Liyanage  - Created
 */
public virtual inherited sharing class BAMContactApplicationsSelector extends ApplicationSelector {
	public enum Options {
		WITH_CONTACT
	}
	public static BAMContactApplicationsSelector newInstance() {
		return (BAMContactApplicationsSelector)Application.Selectors.newInstance(BAMContactApplicationsSelector.class);
	}

	public virtual override SObjectType getSObjectType() {
		return BAMContactApplication__c.getSObjectType();
	}

	public virtual override Set<SObjectField> getSObjectFieldList() {
		return new Set<SObjectField> {
				BAMContactApplication__c.Id, BAMContactApplication__c.Name, BAMContactApplication__c.Contact__c
		};
	}

	public virtual override QueryBuilder newQueryBuilder() {
		return newQueryBuilder(new Set<Object>());
	}

	public virtual override QueryBuilder newQueryBuilder(Set<Object> selectorOptions) {
		QueryBuilder builder = super.newQueryBuilder(selectorOptions);
		if (selectorOptions.contains(Options.WITH_CONTACT)) {
			builder.addRelatedFields(ContactsSelector.newInstance().newQueryBuilder(), 'Contact__r');
		}
		return builder;
	}
}