force-app/main/default/objects/Entitlement_Rule__c/Entitlement_Rule__c.object-meta.xml
<CustomObject>
    <label>Entitlement Rule</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Entitlement Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlement Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement_Rule__c/fields/Entitlement_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Rule_Name__c</fullName>
    <label>Entitlement Rule Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entitlement_Rule__c/fields/Escalation_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Hierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escalation Hierarchy</label>
    <referenceTo>Escalation_Hierarchy__c</referenceTo>
    <relationshipLabel>Entitlement Rules</relationshipLabel>
    <relationshipName>Entitlement_Rules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement_Rule__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Escalation_Hierarchy__c/Escalation_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Escalation Hierarchy</label>
    <nameField>
        <label>SLA Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escalation Hierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EntitlementRulesSelector.cls
/**
 * @description
 * A very simple selector class that sits in the base domain
 *
 * @author Mahesh Parvathaneni
 * @date 2023-01-26
 * @group Selector
 * @tag Selector
 * @tag Name SObject
 * @domain Core
 * @changelog
 */

public virtual inherited sharing class EntitlementRulesSelector extends ApplicationSelector {

	public enum Options {
		WITH_ESCALATION_HIERARCHY
	}

	public static EntitlementRulesSelector newInstance() {
		return (EntitlementRulesSelector)Application.Selectors.newInstance(EntitlementRulesSelector.class);
	}

	public static EntitlementRulesSelector newInstance(Integer recordLimit) {
		return (EntitlementRulesSelector)Application.Selectors.newInstance(EntitlementRulesSelector.class).setLimit(recordLimit);
	}

	public virtual override SObjectType getSObjectType() {
		return Entitlement_Rule__c.getSObjectType();
	}

	public virtual override Set<SObjectField> getSObjectFieldList() {
		return new Set<SObjectField> {
			Entitlement_Rule__c.Id, Entitlement_Rule__c.Active__c, Entitlement_Rule__c.Escalation_Hierarchy__c,
			Entitlement_Rule__c.Rule__c, Entitlement_Rule__c.RecordTypeId, Entitlement_Rule__c.Entitlement_Rule_Name__c
		};
	}

	/**
	 * @description Run a simple query to get active entitlement records by record type dev names
	 */
	public virtual Map<Id, Entitlement_Rule__c> selectActiveRulesByRecordTypeDevNames(Set<String> recordTypeDevNames) {
		return selectActiveRulesByRecordTypeDevNames(recordTypeDevNames, new Set<Object>());
	}

    /**
	 * @description Run a simple query to get active entitlement records by record type dev names
	 */
	public virtual Map<Id, Entitlement_Rule__c> selectActiveRulesByRecordTypeDevNames(Set<String> recordTypeDevNames, Set<Object> selectorOptions) {
		QueryBuilder qb = newQueryBuilder(selectorOptions)
				.addConditions()
				.add((new QueryBuilder.InCondition('RecordType.DeveloperName')).inCollection(recordTypeDevNames))
				.endConditions();			
		return new Map<Id, Entitlement_Rule__c>((List<Entitlement_Rule__c>)Database.query(qb.toSoqlString()));
	}

	public virtual override QueryBuilder newQueryBuilder(Set<Object> selectorOptions) {
		QueryBuilder builder = super.newQueryBuilder(selectorOptions);

		if(selectorOptions.contains(Options.WITH_ESCALATION_HIERARCHY)) {
			builder.addRelatedFields(EscalationHierarchiesSelector.newInstance(recordLimit, fieldOverrides).newQueryBuilder(selectorOptions), 'Escalation_Hierarchy__r');
		}

		return builder;
	}
}