force-app/main/default/objects/APT_Charge_Account__c/APT_Charge_Account__c.object-meta.xml
<CustomObject>
    <label>Charge Account Request</label>
    <nameField>
        <displayFormat>ChargeAccount{0000000}</displayFormat>
        <label>Charge Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Account Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_Credit_Assessment__c/APT_Credit_Assessment__c.object-meta.xml
<CustomObject>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>Credit Assess - {0000}</displayFormat>
        <label>Credit Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_Credit_Assessment__c/fields/APT_Charge_Account__c.field-meta.xml
<CustomField>
    <fullName>APT_Charge_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Account</label>
    <referenceTo>APT_Charge_Account__c</referenceTo>
    <relationshipLabel>Credit Assessments</relationshipLabel>
    <relationshipName>Credit_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Assessment_Network__c/Credit_Assessment_Network__c.object-meta.xml
<CustomObject>
    <description>This object is the junction object for the lodgement points for credit assessment application. User will select preferred locations in BCA online application and it will be stored in this object.</description>
    <label>Credit Assessment Network</label>
    <nameField>
        <displayFormat>CAN-{0000000}</displayFormat>
        <label>Credit Assessment Network Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessment Networks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Assessment_Network__c/fields/Credit_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Credit_Assessment__c</fullName>
    <description>This field looks up to Credit Assessment object. This is primary relationship with Credit Assessment object.</description>
    <label>Credit Assessment</label>
    <referenceTo>APT_Credit_Assessment__c</referenceTo>
    <relationshipLabel>Credit Assessment Networks</relationshipLabel>
    <relationshipName>Credit_Assessment_Networks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Credit_Assessment_Network__c/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>This field is to capture the related network information for the credit assessment. This will be considered as lodgement points for the online application. This is the secondary relationship.</description>
    <label>Network</label>
    <referenceTo>Network__c</referenceTo>
    <relationshipLabel>Credit Assessment Networks</relationshipLabel>
    <relationshipName>Credit_Assessment_Networks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CreditsAssessmentNetworkSelector_Test.cls
/**
* @author avula.jansirani@auspost.com.au
* @date 2021-05-18
* @group Tests
* @tag Selector
* @tag Credit_Assessment_Network__c SObject
* @domain Core
* @description A very simple selector class that sits in the base domain
* @changelog
* 2021-05-18 - avula.jansirani@auspost.com.au - Created
*/
@IsTest
public class CreditsAssessmentNetworkSelector_Test {
    /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectString() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();

        CreditsAssessmentNetworkSelector selector = CreditsAssessmentNetworkSelector.newInstance();
        QueryBuilder qb = selector.newQueryBuilder();
        String soql = qb.toSoqlString();

        System.assertEquals(true, Pattern.compile('(?ism)\\bfrom Credit_Assessment_Network__c\\b').matcher(soql).find(), 'Resulting query does not select from Credit_Assessment_Network__c');

        Test.stopTest();

    }
    
       /**
     * Executes a query to ensure it returns expected results with actual inserted data
     */
    @IsTest
    public static void testSelectorIntegration() {
        
        // =====================================
        // Data Preparation
        // =====================================
        MockUtility.disableTriggerExecution();

        List<Account> accountList = ApplicationTestDataFactory.getAccounts(2, false);
        insert accountList;
        
        APT_Charge_Account__c chargeAccountRequest = ApplicationTestDataFactory.getApttusChargeAccountRequest(1,false)[0];
        insert chargeAccountRequest;
        
        APT_Credit_Assessment__c apttusCreditAssessment = ApplicationTestDataFactory.getApttusCreditsAssessment(1, chargeAccountRequest.Id, false)[0];
        insert apttusCreditAssessment ; 
        
        Network__c networkFacility = ApplicationTestDataFactory.getLPONetwork(1,false)[0];
        insert networkFacility;
        
        Credit_Assessment_Network__c can = new Credit_Assessment_Network__c(Network__c=networkFacility.Id, Credit_Assessment__c=apttusCreditAssessment.Id);
        insert can;
        
         // =====================================
        // Testing
        // =====================================
        Test.startTest();
        
        CreditsAssessmentNetworkSelector selector = CreditsAssessmentNetworkSelector.newInstance();
        Map<Id, Credit_Assessment_Network__c> results = selector.selectById(new Set<Id>{can.Id});
        System.assertEquals(1, results.size(), 'Result count is correct');

 
        Test.stopTest();
    }
}