force-app/main/default/objects/GroupedAccountProductRevenue__c/GroupedAccountProductRevenue__c.object-meta.xml
<CustomObject>
    <description>Consolidates monthly revenue figures for a given account and product for a specified financial year. It  includes values from child accounts and related products. Used to calculate retained and incremental revenue for opportunities and to track sales forecasts against actuals.</description>
    <label>Grouped Account Product Revenue</label>
    <nameField>
        <displayFormat>APR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GroupedAccountProductRevenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/AnchorOrganisation__c.field-meta.xml
<CustomField>
    <fullName>AnchorOrganisation__c</fullName>
    <description>This field identifies the &apos;Anchor&apos; account for the revenue summary. Sales revenue from all associated child accounts within the hierarchy will be aggregated.</description>
    <inlineHelpText>Select the &apos;Anchor&apos; account for this revenue summary. All revenue from linked child accounts in the hierarchy will be included in this aggregation.</inlineHelpText>
    <label>Anchor Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GroupedAccountProductRevenues</relationshipLabel>
    <relationshipName>GroupedAccountProductRevenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/FinancialYear__c.field-meta.xml
<CustomField>
    <fullName>FinancialYear__c</fullName>
    <description>Australian financial year as a numeric value, indicating the latter year of the financial period.</description>
    <inlineHelpText>Enter the ending year of the Australian financial year.</inlineHelpText>
    <label>Financial Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/PrimaryProduct__c.field-meta.xml
<CustomField>
    <fullName>PrimaryProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field identifies the &apos;Primary Product&apos; for the revenue summary. Sales revenue from all associated related products will be aggregated based on this primary product reference</description>
    <inlineHelpText>Select the primary Product for aggregation. Revenues from related products will be consolidated under this reference</inlineHelpText>
    <label>Primary Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>GroupedAccountProductRevenues</relationshipLabel>
    <relationshipName>GroupedAccountProductRevenues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev10__c.field-meta.xml
<CustomField>
    <fullName>Rev10__c</fullName>
    <description>This field captures the total revenue for the month of October.</description>
    <inlineHelpText>Enter the total revenue for October.</inlineHelpText>
    <label>Revenue October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev11__c.field-meta.xml
<CustomField>
    <fullName>Rev11__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of November.</description>
    <inlineHelpText>Enter the total revenue for November.</inlineHelpText>
    <label>Revenue November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev12__c.field-meta.xml
<CustomField>
    <fullName>Rev12__c</fullName>
    <description>This field captures the total revenue for the month of December.</description>
    <inlineHelpText>Enter the total revenue for December.</inlineHelpText>
    <label>Revenue December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev1__c.field-meta.xml
<CustomField>
    <fullName>Rev1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of January.</description>
    <inlineHelpText>Enter the total revenue for January.</inlineHelpText>
    <label>Revenue January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev2__c.field-meta.xml
<CustomField>
    <fullName>Rev2__c</fullName>
    <description>This field captures the total revenue for the month of February</description>
    <inlineHelpText>Enter the total revenue for February.</inlineHelpText>
    <label>Revenue February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev3__c.field-meta.xml
<CustomField>
    <fullName>Rev3__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of March.</description>
    <inlineHelpText>Enter the total revenue for March.</inlineHelpText>
    <label>Revenue March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev4__c.field-meta.xml
<CustomField>
    <fullName>Rev4__c</fullName>
    <description>This field captures the total revenue for the month of April.</description>
    <inlineHelpText>Enter the total revenue for April.</inlineHelpText>
    <label>Revenue April</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev5__c.field-meta.xml
<CustomField>
    <fullName>Rev5__c</fullName>
    <description>This field captures the total revenue for the month of May.</description>
    <inlineHelpText>Enter the total revenue for May.</inlineHelpText>
    <label>Revenue May</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev6__c.field-meta.xml
<CustomField>
    <fullName>Rev6__c</fullName>
    <description>This field captures the total revenue for the month of June.</description>
    <inlineHelpText>Enter the total revenue for June.</inlineHelpText>
    <label>Revenue June</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev7__c.field-meta.xml
<CustomField>
    <fullName>Rev7__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of July.</description>
    <inlineHelpText>Enter the total revenue for July.</inlineHelpText>
    <label>Revenue July</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev8__c.field-meta.xml
<CustomField>
    <fullName>Rev8__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of August</description>
    <inlineHelpText>Enter the total revenue for August</inlineHelpText>
    <label>Revenue August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev9__c.field-meta.xml
<CustomField>
    <fullName>Rev9__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of September.</description>
    <inlineHelpText>Enter the total revenue for September.</inlineHelpText>
    <label>Revenue September</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UID</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GroupedRevenueSchedule__c/GroupedRevenueSchedule__c.object-meta.xml
<CustomObject>
    <label>Grouped Revenue Schedule</label>
    <nameField>
        <displayFormat>GRS-{0000000000}</displayFormat>
        <label>Grouped Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grouped Revenue Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupedRevenueSchedule__c/fields/GroupedAccountProductRevenue__c.field-meta.xml
<CustomField>
    <fullName>GroupedAccountProductRevenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grouped Account Product Revenue</description>
    <inlineHelpText>Associated Revenue</inlineHelpText>
    <label>Grouped Account Product Revenue</label>
    <referenceTo>GroupedAccountProductRevenue__c</referenceTo>
    <relationshipName>Grouped_Account_Product_Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GroupedRevenueSchedule__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Forecast for December</description>
    <inlineHelpText>Sales Forecast for December</inlineHelpText>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipName>GroupedAccountProductForecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityRevenueScheduleModule_Test.cls
/***
 * @author Steve L.
 * @date 2024-02-12
 * @description Test Class covering OpportunityRevenueScheduleModule
 * @changelog
 * 2024-02-12- Steve L - Created
 */

@IsTest
private class OpportunityRevenueScheduleModule_Test {
	@IsTest
	private static void testAfterUpdateCreateUpdateRevenueSchedules() {
		// =====================================
		// Data Preparation
		// =====================================
		Account account = ApplicationTestDataFactory.getAccounts(1, true)[0];
		Opportunity oppRec = ApplicationTestDataFactory.getOpportunities(1, account.Id, true)[0];
		oppRec.AccountId = account.Id;

		Opportunity changedOppRec = oppRec.clone(true,true);
		changedOppRec.StageName = 'Closed Won';

		Product2 prod =  ApplicationTestDataFactory.getProducts(1,true)[0];

		PricebookEntry pbe = ApplicationTestDataFactorySales.getPriceBookEntries(1, Test.getStandardPricebookId(), prod.Id, true).get(0);

		OpportunityLineItem oppProd = ApplicationTestDataFactory.getOpportunityLineItems(1, oppRec.Id, pbe.Id, true).get(0);
		oppProd.Quantity = 1;
		oppProd = (OpportunityLineItem)ApplicationTestDataFactory.setUnwritableFields(oppProd, new Map<String, Object>{'Product2Id' => prod.Id, 'Opportunity' => oppRec});

		GroupedAccountProductRevenue__c groupedRev2023 = new GroupedAccountProductRevenue__c( AnchorOrganisation__c = account.Id, PrimaryProduct__c = prod.Id,
				FinancialYear__c = 2023, UID__c = ProductRevenueService.getUID(account.Id,prod.Id,'2023'),
				Rev1__c = 11,Rev2__c = 22,Rev3__c = 33,Rev4__c = 44,
				Rev5__c = 55,Rev6__c = 66,Rev7__c = 77,Rev8__c = 88,
				Rev9__c = 99,Rev10__c = 110,Rev11__c = 220,Rev12__c = 330);
		ApplicationTestDataFactory.generateRecordIds(new List<GroupedAccountProductRevenue__c> {groupedRev2023});
		GroupedRevenueSchedule__c revSch = new  GroupedRevenueSchedule__c(GroupedAccountProductRevenue__c = groupedRev2023.Id, OpportunityProduct__c = oppProd.Id);

		ApplicationUnitOfWork mockUow = MockUtility.mockUnitOfWork();

		OpportunityLineItemSelector oppProdSelector = (OpportunityLineItemSelector)MockUtility.mockSelector(OpportunityLineItemSelector.class);
		GroupedAccountProductRevenueSelector gapSelector = (GroupedAccountProductRevenueSelector) MockUtility.mockSelector(GroupedAccountProductRevenueSelector.class);
		GroupedRevenueScheduleSelector greSelector = (GroupedRevenueScheduleSelector) MockUtility.mockSelector(GroupedRevenueScheduleSelector.class);
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(oppProdSelector.selectByOpportunity((Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject())).thenReturn(new List<OpportunityLineItem>{oppProd});
		MockUtility.Mocks.when(oppProdSelector.selectByOPCCalculationOpportunityIds((Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject())).thenReturn(new List<OpportunityLineItem>{oppProd});
		MockUtility.Mocks.when(gapSelector.selectByUniqueIds((Set<String>)fflib_Match.anyObject())).thenReturn(new Map<Id, GroupedAccountProductRevenue__c>{groupedRev2023.Id=>groupedRev2023});
		MockUtility.Mocks.when(greSelector.selectByOpportunityProductIds((Set<String>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject())).thenReturn(new List<GroupedRevenueSchedule__c>{revSch});
		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();
		OpportunityRevenueScheduleModule module = OpportunityRevenueScheduleModule.newInstance();
		module.onAfterUpdate(new List<Opportunity>{changedOppRec}, new Map<Id,Opportunity>{oppRec.Id=>oppRec}, mockUow);
		Test.stopTest();

		((ApplicationUnitOfWork)MockUtility.Mocks.verify(mockUow, 2)).registerNew((List<SObject>)fflib_Match.anyObject());
	}

}