force-app/main/default/objects/Lead/fields/Lead_Seeker__c.field-meta.xml
<CustomField>
    <fullName>Lead_Seeker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to identify leads created using the Lead Seeker initiative</description>
    <inlineHelpText>Tick this checkbox if the lead was created as part of the Lead Seeker Initiative</inlineHelpText>
    <label>Lead Seeker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadSeekerConversionOverride__c.field-meta.xml
<CustomField>
    <fullName>LeadSeekerConversionOverride__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Seeker Conversion Override</label>
    <type>Checkbox</type>
	<description>Tick this to allow linking to an old Opportunity when converting a Lead Seeker record.</description>
	<inlineHelpText>Tick this to allow linking to an old Opportunity when converting a Lead Seeker record.</inlineHelpText>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>Master</businessProcess>
    <description>Record type for all standard leads</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Lead_Seeker__c.field-meta.xml
<CustomField>
    <fullName>Lead_Seeker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field will be auto updated when a lead is converted</description>
    <inlineHelpText>Pre-filled automatically if this Opportunity was created from a  Lead submitted through the Seeker program.</inlineHelpText>
    <label>Lead Seeker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BGStandardLeadModule_Test.cls
/**
 * @description
 * Test class for BGStandardLeadModule
 * @author Pratyush Chalasani
 * @date 2023-03-27
 * @group Tests
 * @domain BGStandardLead
 * @changelog
 */
@IsTest
private class BGStandardLeadModule_Test {
	/**
	 * Test:
	 *  When a Lead is converted, the before update will check the CreatedDates of the Lead and Opportunity records
	 *  and check that the Lead was created after the Opportunity
	 */
	@IsTest
	private static void testDontConvertLeadUsingExistingOpportunity() {

		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(LeadTriggerHandler.getUnitOfWorkSObjectTypes());
		Opportunity testOpp = ApplicationTestDataFactory.getOpportunities(1, fflib_IDGenerator.generate(Account.getSObjectType()), true)[0];

		testOpp = (Opportunity)ApplicationTestDataFactory.setUnwritableFields(testOpp, new Map<String, Object>{'CreatedDate' => System.Now().addDays(-1)});

		List<Lead> testLeads = ApplicationTestDataFactory.getLeads(5, true);

		// Lead 0: Positive test: BG Standard and Lead Seeker, and ConvertedOpportunityId will be changed (this should be blocked from linking to old opp)
		testLeads[0].RecordTypeId = ApplicationTestDataFactory.leadBGStandardRecordType;
		testLeads[0].Lead_Seeker__c = true;

		// Lead 1: Negative test: BG Standard and Lead Seeker, and ConvertedOpportunityId will be changed, but LeadSeekerConversionOverride__c will be ticked
		testLeads[1].RecordTypeId = ApplicationTestDataFactory.leadBGStandardRecordType;
		testLeads[1].Lead_Seeker__c = true;
		testLeads[1].LeadSeekerConversionOverride__c = true;

		// Lead 2: Negative test: BG Standard and Lead Seeker, but ConvertedOpportunityId has not changed
		testLeads[2].RecordTypeId = ApplicationTestDataFactory.leadBGStandardRecordType;
		testLeads[2].Lead_Seeker__c = true;
		testLeads[2] = (Lead)ApplicationTestDataFactory.setUnwritableFields(testLeads[2], new Map<String, Object>{'ConvertedOpportunityId' => testOpp.Id, 'CreatedDate' => System.Now()});

		// Lead 3: Negative test: BG Standard but not Lead Seaker
		testLeads[3].RecordTypeId = ApplicationTestDataFactory.leadBGStandardRecordType;

		// Lead 4: Negative test: not BG Standard and not Lead Seaker (do nothing here)

		Map<Id, Lead> oldMap = new Map<Id, Lead>(testLeads);

		// Lead 0 & 1: Ensure ConvertedOpportunityId value has changed (make sure to do this after creating the oldMap above)
		testLeads[0] = (Lead)ApplicationTestDataFactory.setUnwritableFields(testLeads[0], new Map<String, Object>{'ConvertedOpportunityId' => testOpp.Id, 'CreatedDate' => System.Now()});
		testLeads[1] = (Lead)ApplicationTestDataFactory.setUnwritableFields(testLeads[1], new Map<String, Object>{'ConvertedOpportunityId' => testOpp.Id, 'CreatedDate' => System.Now()});

		// =====================================
		// Stubbing
		// =====================================
		OpportunitiesSelector mockOpportunitiesSelector = (OpportunitiesSelector)MockUtility.mockSelector(OpportunitiesSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockOpportunitiesSelector.selectById(new Set<Id>{ testOpp.Id })).thenReturn(new Map<Id, Opportunity>{testOpp.Id => testOpp});
		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BGStandardLeadModule module = BGStandardLeadModule.newInstance();

		module.onBeforeUpdate(testLeads, oldMap, uow);

		// Positive
		Assert.isTrue(testLeads[0].hasErrors());
		Assert.areEqual(testLeads[0].getErrors()[0].message, Label.leadSeakerIntoExistingOpportunity);

		// Negative
		Assert.isFalse(testLeads[1].hasErrors());
		Assert.isFalse(testLeads[2].hasErrors());
		Assert.isFalse(testLeads[3].hasErrors());
		Assert.isFalse(testLeads[4].hasErrors());

		Test.stopTest();
	}
}