force-app/main/default/objects/Lead/fields/Lead_Seeker__c.field-meta.xml
<CustomField>
    <fullName>Lead_Seeker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to identify leads created using the Lead Seeker initiative</description>
    <inlineHelpText>Tick this checkbox if the lead was created as part of the Lead Seeker Initiative</inlineHelpText>
    <label>Lead Seeker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Network__c/Network__c.object-meta.xml
<CustomObject>
    <description>SSSW - Used to store the Facility Details from WICIS and Mapping of Bypasses</description>
    <label>Network</label>
    <nameField>
        <label>Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Network</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Lead_Seeker__c.field-meta.xml
<CustomField>
    <fullName>Lead_Seeker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field will be auto updated when a lead is converted</description>
    <inlineHelpText>Pre-filled automatically if this Opportunity was created from a  Lead submitted through the Seeker program.</inlineHelpText>
    <label>Lead Seeker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/APSNumber__c.field-meta.xml
<CustomField>
    <fullName>APSNumber__c</fullName>
    <description>APS Number used for Lead Seeker point allocation</description>
    <inlineHelpText>APS Number used for Lead Seeker point allocation</inlineHelpText>
    <label>APS Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Network__c.field-meta.xml
<CustomField>
    <fullName>Network__c</fullName>
    <description>Field used to store the  users network. Used to display information in list views</description>
    <label>Network</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityLeadSeekerModule_Test.cls
/***
 * @description Test class for OpportunityLeadSeekerModule
 * @author Boris Bachovski
 * @date 2023-06-21
 * @changelog
 */
@IsTest
private class OpportunityLeadSeekerModule_Test {
	/**
	 * 
	 */
	@isTest
	static void testLeadSeeker() {
		
		// =====================================
		// Data Preparation
		// =====================================
		ApplicationUnitOfWork uow = ApplicationUnitOfWork.newInstance(OpportunityAutomationTriggerHandler.getUnitOfWorkSObjectTypes());
		
		Network__c network = ApplicationTestDataFactory.getLPONetwork(1, true)[0];
		Account account = ApplicationTestDataFactory.getFacilityAccounts(1, network.Id, true)[0];
		Contact contact = ApplicationTestDataFactory.getContacts(1, account.Id, true)[0];
		contact.account = account; // set explicitly to prevent issues with traversal in the actual code
		User user = ApplicationTestDataFactory.getCommunityUsers(1, new List <Id> { contact.Id }, true)[0];
		user.contact = contact; // set explicitly to prevent issues with traversal in the actual code
		user.APSNumber__c = '1234';
		List <Opportunity> oppties = ApplicationTestDataFactory.getOpportunities(2, account.Id, false);

		// =====================================
		// Stubbing
		// =====================================
		UsersSelector mockUsersSelector = (UsersSelector)MockUtility.mockSelector(UsersSelector.class);

		// set up our responses
		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(mockUsersSelector.selectById(new Set<Id> { user.Id }, 
															new Set <Object> { UsersSelector.Options.WITH_CONTACT, 
																				ContactsSelector.Options.WITH_ACCOUNT, 
																				AccountsSelector.Options.WITH_RECORDTYPE }))
						.thenReturn(new Map <Id, User> { user.Id => user });

		MockUtility.Mocks.stopStubbing();

		// =====================================
		// Testing
		// =====================================
		Test.startTest();
		
		OpportunityLeadSeekerModule module = new OpportunityLeadSeekerModule();
		module.currentUserId = user.Id;
		module.onBeforeInsert((List <SObject>)oppties, uow);
		
		Test.stopTest();

		System.Assert(oppties[0].LeadSource == OpportunityLeadSeekerModule.LEAD_SEEKER_OPPORTUNITY_LEAD_SOURCE, 'Expected opportunity record Lead Source to be ' + OpportunityLeadSeekerModule.LEAD_SEEKER_OPPORTUNITY_LEAD_SOURCE + '. Received ' + oppties[0].LeadSource);
		System.Assert(oppties[0].Lead_Seeker__c == true, 'Expected opportunity record Lead Seeker to be true.');
	}
}