force-app/main/default/objects/AusPostSettings__c/AusPostSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are the settings required in order to use AusPost web services. The values for different settings are used by various components in the solution.</description>
    <label>AusPost Settings</label>
</CustomObject>

force-app/main/default/objects/CacheSettings__c/CacheSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Defines the specific settings for platform cache when used with CacheManager</description>
    <label>Cache Settings</label>
</CustomObject>

force-app/main/default/objects/CacheSettings__c/fields/CacheEnabled__c.field-meta.xml
<CustomField>
    <fullName>CacheEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Where platform cache should be enabled when using the CacheManager class</description>
    <inlineHelpText>Where platform cache should be enabled when using the CacheManager class</inlineHelpText>
    <label>Cache Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LightningUtilityController_Test.cls
/**************************************************
Type:       Lightning Utility Controller Test class (LightningUtilityController)
History:
--------------------------------------------------
28-May-2018: Hasantha.Liyanage@auspost.com.au created
2023-08-28	Naveen Rajanna	REQ3286437 - Changed api version and removed hard coded URL to use apex methods to generate URL
**************************************************/
@isTest
public class LightningUtilityController_Test {

	@testSetup
	static void setupTest(){
		//inserting custom settings for url retrival
		AusPostSettings__c auSetting = new AusPostSettings__c(Name = 'VF_Iframe_Instance_URL', URL__c = System.URL.getSalesforceBaseUrl().toExternalForm());
		insert auSetting;
		//inserting custom settings for enable cache
		CacheSettings__c setting = new CacheSettings__c (CacheEnabled__c = true);
		insert setting;
	}

	/**
	 * These tests are just to get the coverage
	 */
	public static testMethod void LightningUtilityController_Test() {
		LightningUtilityController ctrl = new LightningUtilityController();
		// tests for retrieve field labels
		LightningUtilityController.getSObjectFieldLabels(new List<String>{'Account.Type'});
		// test for retrieve picklist values
		LightningUtilityController.getSObjectFieldPicklistValues(new List<String>{'Account.Type'});
		// test for retrieve custom setting values by name
		LightningUtilityController.getSystemCustomSettingListByName('AusPostSettings__c','VF_Iframe_Instance_URL');
	}

}