force-app/main/default/objects/AusPostSettings__c/AusPostSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are the settings required in order to use AusPost web services. The values for different settings are used by various components in the solution.</description>
    <label>AusPost Settings</label>
</CustomObject>

force-app/main/default/objects/AusPostSettings__c/fields/URL2__c.field-meta.xml
<CustomField>
    <fullName>URL2__c</fullName>
    <description>Additional URL if required</description>
    <label>URL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BAMRegistrationSuccessfulController_Test.cls
/**************************************************
Description:    Tests BAMRegistrationSuccessfulController
History:
--------------------------------------------------
2019-08-10  nathan.franklin@auspost.com.au  Created
**************************************************/
@isTest
public class BAMRegistrationSuccessfulController_Test {
	public class SuccessfulResponseMock implements HttpCalloutMock {
		public HttpResponse respond(HttpRequest req) {
			HttpResponse response = new HttpResponse();
			response.setStatusCode(204);
			return response;
		}
	}
	public class FailureResponseMock implements HttpCalloutMock {
		public HttpResponse respond(HttpRequest req) {
			HttpResponse response = new HttpResponse();
			response.setStatusCode(500);
			return response;
		}
	}

	@testSetup
	public static void testSetup() {
		AusPostSettings__c testSetting = new AusPostSettings__c(Name = 'BAM-CSSO-Completion', URL2__c = 'callout:nothing');
		insert testSetting;
	}

	/**
	 * Scenario:
	 * Very simple test for code coverage since we do not need to process the result of the callout
	 */
	public static testMethod void testCalloutCodeSuccess() {
		Test.setMock(HttpCalloutMock.class, new SuccessfulResponseMock());
		Test.startTest();
		BAMRegistrationSuccessfulController.triggerRegistrationCompleteIntegration('{}');
		Test.stopTest();
	}

	/**
	 * Scenario:
	 * Very simple test for code coverage since we do not need to process the result of the callout
	 */
	public static testMethod void testCalloutCodeFailure() {
		Test.setMock(HttpCalloutMock.class, new FailureResponseMock());
		Test.startTest();
		BAMRegistrationSuccessfulController.triggerRegistrationCompleteIntegration('{}');
		Test.stopTest();
	}

}