force-app/main/default/objects/AusPostSettings__c/AusPostSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are the settings required in order to use AusPost web services. The values for different settings are used by various components in the solution.</description>
    <label>AusPost Settings</label>
</CustomObject>

force-app/main/default/objects/AusPostSettings__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Testing if token expiry is equal to 1 day</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AusPostSettings__c/fields/URL2__c.field-meta.xml
<CustomField>
    <fullName>URL2__c</fullName>
    <description>Additional URL if required</description>
    <label>URL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AusPostSettings__c/fields/URL3__c.field-meta.xml
<CustomField>
    <fullName>URL3__c</fullName>
    <label>URL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressValidationController.cls
/**************************************************
Type:       AddressValidation's controller 
Purpose:    Used by AddressValidation VF component to show the autocomplete address from AusPost  
History:
--------------------------------------------------
Dec-2013:  george.nguyen@bluewolf.com  Created                                            
**************************************************/
global with sharing class AddressValidationController {
    
    public string token {get;set;}
    public string addressSearchURL {get;set;}
    public string addressDetailsURL {get;set;}
    
    public AddressValidationController(){
        token = '';
        addressSearchURL = '';
        addressDetailsURL = '';
        
        AusPostSettings__c setting = AusPostSettings__c.getValues('AddressValidation');
        if(setting != null){
            token = setting.Token__c;
            addressSearchURL = setting.URL2__c;
            addressDetailsURL = setting.URL3__c;
        }
    }
    
    
}