force-app/main/default/objects/Opportunity/fields/Commit_to_close_by__c.field-meta.xml
<CustomField>
    <fullName>Commit_to_close_by__c</fullName>
    <label>Commit to close by</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <inlineHelpText>This is the end date on the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <inlineHelpText>This is the commencement date on the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Offering_Type__c.field-meta.xml
<CustomField>
    <fullName>Offering_Type__c</fullName>
    <description>Used to indicate if this opportunity belongs to the product or solutions offering. Workflow is used to populate this field but can be overwritten.</description>
    <inlineHelpText>Indicate whether this opportunity is a singular product or multi product solution.</inlineHelpText>
    <label>Offering Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Annualised_Value__c.field-meta.xml
<CustomField>
    <fullName>Annualised_Value__c</fullName>
    <formula>If(AND(NOT(ISNULL( Contract_Start_Date__c )),NOT(ISNULL( Contract_End_Date__c))), IF(Contract_End_Date__c - Contract_Start_Date__c &lt; 367, TotalPrice, ( TotalPrice / Revenue_Duration__c ) * (CASE(MOD(Opportunity.Start_of_CFY__c - DATE(1985,6,24),7), 
0 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c )/7)*5))),0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annualised Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <inlineHelpText>Revenue end date should be the contract end date, or earlier if that is what is expected. The revenue end date should not be beyond the contract end date.</inlineHelpText>
    <label>Revenue End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <inlineHelpText>The ‘revenue start date’ is the date the customer is first invoiced for services provided to them. Please factor into the ‘start date’ any on-boarding and implementation time required for the product or service.</inlineHelpText>
    <label>Revenue Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OppCloneTest.cls
/****************************************************************************************
Author:         Unknown
History:
-----------------------------------------------------------------------------------------
25-11-2016        Unknown              Test class created 
09-03-2021        Seth Heang           Remove (seeAllData=true) and remove hard-coded PricebookEntryId reference to use locally created PricebookEntry test data
*****************************************************************************************/
@isTest
private class OppCloneTest{
    static testMethod void testcloneWithoutItems() {        
        test.startTest();
        
        
        Account a=new Account();
        a.name='ttestt';
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name='testtest';
        o.Account=a;
        o.Offering_Type__c='Product';
        o.StageName='Identify';
        o.Probability=3;
        o.CloseDate=Date.today();
        o.Commit_to_close_by__c=Date.today();
        o.Type='Existing Customer';
        insert o;
        
        // Create Product2
        Product2 testProduct = new Product2();
        testProduct.Name = 'Test Product';
        testProduct.IsActive = TRUE;
        insert testProduct;
        // Get Standard Pricebook2
        Id standardPBId = Test.getStandardPricebookId();
        // Create PricebookEntry
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = standardPBId;
        pbe.Product2Id = testProduct.Id;
        pbe.UnitPrice = 1.00;
        pbe.IsActive = TRUE;
        pbe.UseStandardPrice = FALSE;
        insert pbe;
        
        OpportunityLineItem li = new OpportunityLineItem(OpportunityId = o.Id,Quantity = 5,PricebookEntryId = pbe.Id,
                TotalPrice = 5,Contract_Start_Date__c = system.today(),Contract_End_Date__c = system.today().addDays(3));
		li = (OpportunityLineItem)ApplicationTestDataFactory.setUnwritableFields(li, new Map<String, Object>{
				'Annualised_Value__c' => 5000,
				'Product2Id' => testProduct.Id
		});
		li.Opportunity = o;
        
        OpportunityCloneWithItemsController oc=new OpportunityCloneWithItemsController();
        oc.cloneWithoutItems();
        
        oc.cloneWithItems();
        
        ApexPages.StandardController sc = new ApexPages.standardController(o);
        // create an instance of the controller
        OpportunityCloneWithItemsController myPageCon = new OpportunityCloneWithItemsController (sc);
        
        //try calling methods/properties of the controller in all possible scenarios
        // to get the best coverage.
        
        myPageCon.cloneWithoutItems();
        myPageCon.cloneWithItems();
        
        test.stopTest();    
    }    
}