force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerNumber__c</fullName>
    <formula>text(Organisation__r.Customer_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerNumber</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <inlineHelpText>Current Financial Year</inlineHelpText>
    <label>Financial Year</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/uid__c.field-meta.xml
<CustomField>
    <fullName>uid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>An unique identifier field that is used in Apex to help uniquely identify a record.</description>
    <externalId>true</externalId>
    <inlineHelpText>An unique identifier field that is used in Apex to help uniquely identify a record.</inlineHelpText>
    <label>uid</label>
    <length>34</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BudgetAndRevenueSelector_Test.cls
/**
 * @changelog
 * 2024-10-10 - Swati Mogadala - New method added test_selectByDups()
 */
@isTest
public class BudgetAndRevenueSelector_Test {
	@isTest
	static void testSelectByOrganisationId() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		Account testAcc = new Account(Name = 'test');

		insert testAcc;

		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];

		insert revenue;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		List<Budget_and_Revenue__c> results = selector.selectByOrganisationId(testAcc.Id);
		
		Assert.areEqual(1, results.size(), 'Expected result size of 1');

		Test.stopTest();
	}
	@isTest
	static void testSelectByOrganisationIdWithFY() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		Account testAcc = new Account(Name = 'test');

		insert testAcc;

		// Positive test case
		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];
		revenue.Financial_Year__c = '2023';
		insert revenue;

		// Negative test case
		Budget_and_Revenue__c invalid = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];
		revenue.Financial_Year__c = '2024';
		insert invalid;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		List<Budget_and_Revenue__c> results = selector.selectByOrganisationId(new Set<Id>{testAcc.Id}, new Set<String>{'2023'});
		
		// Make sure we only get back the positive test record
		Assert.areEqual(1, results.size(), 'Expected result size of 1');
		Assert.areEqual(revenue.Id, results[0].Id, 'Expected 2023 revenue record');

		Test.stopTest();
	}
	@isTest
	static void testSelectByUniqueIds() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		Account testAcc = new Account(Name = 'test');

		insert testAcc;

		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];
		revenue.uid__c = 'testuid';
		insert revenue;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		Map<Id,Budget_and_Revenue__c> results = selector.selectByUniqueIds(new Set<String>{revenue.uid__c});
		
		Assert.areEqual(1, results.size(), 'Expected result size of 1');

		Test.stopTest();
	}
	
	@isTest
	static void testSelectByOrganisationAndProduct() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		Account testAcc = new Account(Name = 'test');

		insert testAcc;

		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];
		revenue.uid__c = 'testuid';
		revenue.Financial_Year__c ='2024';
		insert revenue;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		LIst<Budget_and_Revenue__c> results = selector.selectByOrganisationAndProduct(new Set<Id>{testAcc.Id}, new Set<Id>(), new Set<String>{revenue.Financial_Year__c}, new Set<Id>());
		
		Assert.areEqual(1, results.size(), 'Expected result size of 1');

		Test.stopTest();
	}
	
	@isTest
	static void testSelectByOrganisationAndProduct2() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		Account testAcc = new Account(Name = 'test');

		insert testAcc;

		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc.Id, false)[0];
		revenue.uid__c = 'testuid';
		revenue.Financial_Year__c ='2024';
		insert revenue;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		LIst<Budget_and_Revenue__c> results = selector.selectByOrganisationAndProduct(new Set<Id>{testAcc.Id}, new Set<Id>(), new Set<Integer>{2024}, new Set<Id>());
		
		Assert.areEqual(1, results.size(), 'Expected result size of 1');

		Test.stopTest();
	}
		@isTest
	static void testSelectByDups() {
		// =====================================
		// Data Preparation
		// =====================================
		MockUtility.disableTriggerExecution();

		List<Account> testAcc = ApplicationTestDataFactory.getAccounts(1,false);

		insert testAcc;

		// Positive test case
		Budget_and_Revenue__c revenue = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc[0].Id, false)[0];
		revenue.Unique_Id__c=revenue.CustomerNumber__c + 'Test1';
		insert revenue;
		// Negative test case
		Budget_and_Revenue__c duplicate = ApplicationTestDataFactory.getBudgetAndRevenue(1, testAcc[0].Id, false)[0];
		revenue.Financial_Year__c = '2024';
		revenue.Unique_Id__c='6000000Test1';
		insert duplicate;

		// =====================================
		// Testing
		// =====================================
		Test.startTest();

		BudgetAndRevenueSelector selector = BudgetAndRevenueSelector.newInstance();
		List<Budget_and_Revenue__c> results = selector.selectByDups();
		
		// Make sure we only get back the positive test record
		Assert.areEqual(1, results.size(), 'Expected result size of 1');
		Assert.areEqual(duplicate.Id, results[0].Id, 'Expected duplicate revenue record');

		Test.stopTest();
	}
}