force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <inlineHelpText>Current Financial Year</inlineHelpText>
    <label>Financial Year</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product (Level 5)</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Budget_and_Revenue_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>Sales implementation case</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/Opp_Product_Classification__c.object-meta.xml
<CustomObject>
    <description>Phase 2 Opportunity Product Classification object</description>
    <label>Opportunity Product Classification</label>
    <nameField>
        <displayFormat>OPC-{0000000000}</displayFormat>
        <label>Opp Product Classifcation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Classification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Hidden_1st_of_Multi_Year__c.field-meta.xml
<CustomField>
    <fullName>Hidden_1st_of_Multi_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Phase 2 - Field to indicate that the OPC record is the first in a multi-year contract.</description>
    <label>Hidden 1st of Multi-Year</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Hidden_Renewal_Missing_Growth__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Renewal_Missing_Growth__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hidden Renewal Missing Growth</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Hidden_Under_Review__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Under_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hidden Under Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Jan_NRT_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Jan_NRT_Adjustment__c</fullName>
    <label>Jan NRT Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opp_Product_Classification</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Opp_Product_Classification</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opp_Product_Classification__c/fields/Under_Review_by_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Under_Review_by_Sales_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that can be checked by the sales manager for OPC to be under review</description>
    <label>Under Review by Sales Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <inlineHelpText>This is the end date on the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <inlineHelpText>This is the commencement date on the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Phase 2 - Used for data mapping requirements</description>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object used to display billed revenue</description>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS{00000000}</displayFormat>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Schedule__c/fields/Apr_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Apr_Claimed_Revenue__c</fullName>
    <label>April Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Aug_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Aug_Claimed_Revenue__c</fullName>
    <label>August Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/CalendarYear__c.field-meta.xml
<CustomField>
    <fullName>CalendarYear__c</fullName>
    <description>Phase 2 - This field it used to identify the Calendar Year of the Revenue schedule record. This field also populates the Unique Key formula used for the SAP Integration</description>
    <label>CalendarYear</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Classification_c__c.field-meta.xml
<CustomField>
    <fullName>Classification_c__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Cross Sell</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>New Business - One Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Dec_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Dec_Claimed_Revenue__c</fullName>
    <label>December Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Exception_Override__c.field-meta.xml
<CustomField>
    <fullName>Exception_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The field can only be changed by system admin and sales operation users.</inlineHelpText>
    <label>Exception Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Feb_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Feb_Claimed_Revenue__c</fullName>
    <label>February Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Hidden_1st_of_Multi_Year__c.field-meta.xml
<CustomField>
    <fullName>Hidden_1st_of_Multi_Year__c</fullName>
    <formula>IF( Hidden_Contract_Start_FY__c =  Financial_Year__c &amp;&amp;  Multi_Year__c = &apos;YES&apos;, &apos;YES&apos;, &apos;NO&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hidden 1st of Multi-Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Jan_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Jan_Claimed_Revenue__c</fullName>
    <label>January Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Jul_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Jul_Claimed_Revenue__c</fullName>
    <description>Phase 2 - This field captures the Billed Opportunity Revenue for July</description>
    <label>July Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Jun_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Jun_Claimed_Revenue__c</fullName>
    <label>June Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Mar_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Mar_Claimed_Revenue__c</fullName>
    <label>March Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/May_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>May_Claimed_Revenue__c</fullName>
    <label>May Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Multi_Year__c.field-meta.xml
<CustomField>
    <fullName>Multi_Year__c</fullName>
    <description>Return YES if Contract End - Contract Start &gt; June 30 - Contract Start
Return NO otherwise</description>
    <formula>IF(NOT(ISNULL(Contract_Start_Date__c)) &amp;&amp; NOT(ISNULL(Contract_End_Date__c)) &amp;&amp; Contract_Length__c &gt; Days_to_End_of_FY__c, &apos;YES&apos;, &apos;NO&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hidden Multi-Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Nov_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Nov_Claimed_Revenue__c</fullName>
    <label>November Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Oct_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Oct_Claimed_Revenue__c</fullName>
    <label>October Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Phase 2 - This field is the relationship between the Opportunity and the Revenue Schedule</description>
    <inlineHelpText>Related Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Schedule</relationshipLabel>
    <relationshipName>Opportunity_Billings_Revenue_del</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Opportunity_Product_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product Classification</label>
    <referenceTo>Opp_Product_Classification__c</referenceTo>
    <relationshipLabel>Related Revenue Schedule</relationshipLabel>
    <relationshipName>Related_Revenue_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Opportunity_Billings_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Reclassified__c.field-meta.xml
<CustomField>
    <fullName>Reclassified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reclassified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Schedule__c/fields/Sep_Claimed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Sep_Claimed_Revenue__c</fullName>
    <label>September Scheduled Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Startrack</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Parcel Services</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Trusted Services</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Post - Mail Services</fullName>
    </customValue>
    <customValue>
        <fullName>MyPost Business</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateOPCBatchable.cls
/**************************************************
Type:       Apex Batchable Job Class for Generation of Opportunity Product Classification (OPC)
Purpose:    Generates the Opportunity Product Classification (OPC) record from their source revenue schedule(s) and 
            finds any matching actual revenue against it from the current financial year and last financial year
Used By:    
History:
--------------------------------------------------
10.08.2012  M. Isidro (Cloud Sherpas)   Created
15.08.2012  M. Isidro (Cloud Sherpas)   Consolidation of logic flow and OPCUtility Class
28.08.2012  M. isidro (Cloud Sherpas)   Fixed null error exception on Revenue Schedule
30.08.2012  M. Isidro (Cloud Sherpas)   Added Revenue Schedule that are reclassified but previously flagged as under review
04.09.2012  M. Isidro (Cloud Sherpas)   Added test coverage
11.09.2012  M. Isidro (Cloud Sherpas)   Fixed heap size too large error
04.10.2012  M. Isidro (Cloud Sherpas)   Added code to exclude Revenue Schedule where Opportunity Stage is not equal to Closed Won 
11.10.2012  M. Isidro (Cloud Sherpas)   Added filter to exclude OPC records under review by Sales Manager
15.10.2012  R. Enojas (Salesforce)      Added code to clear OPCs whose Revenue Schedules have been deleted due to 'Product Error' (CR 27)
19.12.2012	R. Enojas (Salesforce)		Changed date criteria on batch scope to start from July 1st of the CFY
**************************************************/

global class GenerateOPCBatchable implements Database.Batchable<SObject> {
    
    public Boolean testRun = false;

    global String query;
    
/*  
    global Map<String, Opp_Product_Classification__c> idOPCMap = new Map<String, Opp_Product_Classification__c>();
    global Map<String, Budget_and_Revenue__c> idBARMap = new Map<String, Budget_and_Revenue__c>();
    global Map<String, Revenue_Schedule__c> idRSMap = new Map<String, Revenue_Schedule__c>();
    global Map<String, Id> uniqueIdopcIdMap = new Map<String, Id>();
    global Map<String, String> renewalUpsellMap = new Map<String, String>();
    global Map<String, Revenue_Schedule__c> opcIdRSMap = new Map<String, Revenue_Schedule__c>();
    global List<Opp_Product_Classification__c> opcList = new List<Opp_Product_Classification__c>();
    global List<Case> caseList = new List<Case>();  
    
    global Map<String, Opp_Product_Classification__c> idOPCExistingMap = new Map<String, Opp_Product_Classification__c>();
    global List<Opp_Product_Classification__c> insertOPCList = new List<Opp_Product_Classification__c>();
    global List<Opp_Product_Classification__c> updateOPCList = new List<Opp_Product_Classification__c>();    
    global List<Opp_Product_Classification__c> requeryOPCList = new List<Opp_Product_Classification__c>();
    
    global String rtId = [SELECT Id FROM RecordType WHERE IsActive = true AND SobjectType='Case' AND Name='OPC Exception' Limit 1].Id;  
*/    
    
    global GenerateOPCBatchable() {
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        system.debug('### START:');
        system.debug('***getHeapSize: ' + Limits.getHeapSize());
        
        Date dateToday = Date.today();
        Integer currYear = dateToday.year();
        Integer currMonth = dateToday.month();
        Integer finalYear;
        
        //Logic to derive the start of the FY based on today's date
        system.debug('Current Year: ' + currYear);
        system.debug('Current Month: ' + currMonth);
        
        if (currMonth >= 7 && currMonth <= 12)
        	finalYear = currYear;
        else if (currMonth >= 1 && currMonth <= 6)
        	finalYear = currYear-1;  
		
		system.debug('Final Year: ' + finalYear);
		
		Date finalDate = date.newInstance(finalYear, 7, 1);
		
		system.debug('Final Date: ' + finalDate);
		
		
        query = 'Select Id '
        + ' From Revenue_Schedule__c'
        + ' Where'
        + ' ( Opportunity__r.AccountId <> null' 

        + ' And Opportunity__r.StageName = \'Closed Won\' '

        + ' And Product__c <> null'
        + ' And Classification_c__c <> null'
        + ' And CalendarYear__c <> null'
        + ' And Financial_Year__c <> null'
        + ' And Opportunity__c <> null )'
//        + ' And ( (Opportunity_Product_Classification__r.Hidden_Under_Review__c = false) Or (Opportunity_Product_Classification__r.Hidden_Renewal_Missing_Growth__c = true) )'
        + ' And ( ' 
        + ' (((Opportunity_Product_Classification__r.Hidden_Under_Review__c = false) Or' 
        + ' (Opportunity_Product_Classification__r.Hidden_Renewal_Missing_Growth__c = true) Or' 
        + ' (Opportunity_Product_Classification__r.Hidden_Under_Review__c = true AND (Reclassified__c = true)))'
        + ' AND (Opportunity_Product_Classification__r.Under_Review_by_Sales_Manager__c = false))'
        + ' )'
        + ' And ' 
        + ' ( (Contract_End_Date__c >= :finalDate) Or (Exception_Override__c = true) )'
        + ' Order By Opportunity__r.AccountId, Product__c, Classification_c__c, Financial_Year__c';            
        
        //append 200 query limit for testing
        if(testRun)
            query = query + ' limit 200';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        system.debug('### EXECUTE:');
        system.debug('***getLimitHeapSize: ' + Limits.getLimitHeapSize());
        system.debug('***getHeapSize: ' + Limits.getHeapSize());        

        Map<String, Opp_Product_Classification__c> idOPCMap = new Map<String, Opp_Product_Classification__c>();
        Map<String, Budget_and_Revenue__c> idBARMap = new Map<String, Budget_and_Revenue__c>();
        Map<String, Revenue_Schedule__c> idRSMap = new Map<String, Revenue_Schedule__c>();
        Map<String, Id> uniqueIdopcIdMap = new Map<String, Id>();
        Map<String, String> renewalUpsellMap = new Map<String, String>();
        Map<String, Revenue_Schedule__c> opcIdRSMap = new Map<String, Revenue_Schedule__c>();
        List<Opp_Product_Classification__c> opcList = new List<Opp_Product_Classification__c>();
        List<Case> caseList = new List<Case>(); 
        
        Map<String, Opp_Product_Classification__c> idOPCExistingMap = new Map<String, Opp_Product_Classification__c>();
        List<Opp_Product_Classification__c> insertOPCList = new List<Opp_Product_Classification__c>();
        List<Opp_Product_Classification__c> updateOPCList = new List<Opp_Product_Classification__c>();    
        List<Opp_Product_Classification__c> requeryOPCList = new List<Opp_Product_Classification__c>();
        
        List<String> rsIdList = new List<String>();
        List<Revenue_Schedule__c> rsList = new List<Revenue_Schedule__c>();
        List<String> acctIdList = new List<String>();
        List<String> prodIdList = new List<String>();
        
        List<String> opcIdList = new List<String>();        
        
        String rtId = [SELECT Id FROM RecordType WHERE IsActive = true AND SobjectType='Case' AND Name='OPC Exception' Limit 1].Id;  
/*      
        Map<String, Opp_Product_Classification__c> idOPCMap = new Map<String, Opp_Product_Classification__c>();
        Map<String, Budget_and_Revenue__c> idBARMap = new Map<String, Budget_and_Revenue__c>();
        Map<String, Revenue_Schedule__c> idRSMap = new Map<String, Revenue_Schedule__c>();
        Map<String, Id> uniqueIdopcIdMap = new Map<String, Id>();
        Map<String, String> renewalUpsellMap = new Map<String, String>();
        Map<String, Revenue_Schedule__c> opcIdRSMap = new Map<String, Revenue_Schedule__c>();
        List<Opp_Product_Classification__c> opcList = new List<Opp_Product_Classification__c>();
        List<Case> caseList = new List<Case>(); 
*/

        // Get OPC Id to be deleted from Revenue Schedule records   
        system.debug('### scope: ' + scope);
        
        if (!scope.isEmpty()) {
            for (SObject rs : scope) {
                rsIdList.add( String.valueOf(rs.get('Id')) );   
            }
            
            system.debug('### rsIdList: ' + rsIdList);
            
            rsList =
            [Select Id, Opportunity__r.AccountId, Product__c, Classification_c__c, CalendarYear__c, 
            Opportunity__c, Financial_Year__c, Opportunity_Product_Classification__c,
            Product__r.Name, Opportunity__r.Customer_Name__c, Contract_Start_Date__c, Contract_End_Date__c,
            Multi_Year__c, Exception_Override__c, Hidden_1st_of_Multi_Year__c,
            Jan_Claimed_Revenue__c, Feb_Claimed_Revenue__c, Mar_Claimed_Revenue__c,  
            Apr_Claimed_Revenue__c, May_Claimed_Revenue__c, Jun_Claimed_Revenue__c,
            Jul_Claimed_Revenue__c, Aug_Claimed_Revenue__c, Sep_Claimed_Revenue__c,
            Oct_Claimed_Revenue__c, Nov_Claimed_Revenue__c, Dec_Claimed_Revenue__c,
            
            Jan_NRT_Adjustment__c, Feb_NRT_Adjustment__c, Mar_NRT_Adjustment__c,  
            Apr_NRT_Adjustment__c, May_NRT_Adjustment__c, Jun_NRT_Adjustment__c,
            Jul_NRT_Adjustment__c, Aug_NRT_Adjustment__c, Sep_NRT_Adjustment__c,
            Oct_NRT_Adjustment__c, Nov_NRT_Adjustment__c, Dec_NRT_Adjustment__c
            
            From Revenue_Schedule__c
            Where Id in : rsIdList
            Order By Opportunity__r.AccountId, Product__c, Classification_c__c, Financial_Year__c];
        }       
        
        system.debug('### rsList: ' + rsList);
        system.debug('***getHeapSize: After rsList: ' + Limits.getHeapSize());
        
        for (Revenue_Schedule__c rs : rsList) {
            String opcId = rs.Opportunity_Product_Classification__c;
            system.debug('***opcId: ' + opcId);
            if (opcId != '' && opcId != null) {
                opcIdList.add( opcId );
            }
            
            String accountId = rs.Opportunity__r.AccountId;
            system.debug('***accountId: ' + accountId);
            if (accountId != '' && accountId != null) {
                acctIdList.add( accountId );
            }   
            
            String prodId = rs.Product__c;
            system.debug('***prodId: ' + prodId);
            if (prodId != '' && prodId != null) {
                prodIdList.add( prodId );
            }                       
        } 
        
        // Delete all OPC records related to the Revenue Schedule records in scope
        if (!opcIdList.isEmpty()) {
            system.debug('*** opcIdList Not Empty: ' + opcIdList);
            OPCUtility.deleteOPCList(opcIdList);
        }
        system.debug('***getHeapSize: After deleteOPCList: ' + Limits.getHeapSize());
        
        // For CR 27, delete all OPC records related to Revenue Schedule records that have been deleted due to 'Product Error'
        // Only delete OPCs in the context of the Organisations within scope and those that do not have any Revenue Schedules 
        List<Id> addlOPCList = new List<Id>(); 
        
        for (Opp_Product_Classification__c addlOPC : [SELECT Id, Account__c, Under_Review_by_Sales_Manager__c 
        												FROM Opp_Product_Classification__c 
        												WHERE Account__c in :acctIdList
        												AND Id NOT IN (SELECT Opportunity_Product_Classification__c FROM Revenue_Schedule__c)])
            if (addlOPC.Under_Review_by_Sales_Manager__c <> true)
                addlOPCList.add(addlOPC.Id);
        
        if (!addlOPCList.isEmpty()) {
            system.debug('*** addlOPCList Not Empty: ' + addlOPCList);
            OPCUtility.deleteOPCList(addlOPCList);
        }
        system.debug('***getHeapSize: After deleteOPCList for addlOPCList: ' + Limits.getHeapSize()); 
        
        
        OPCUtility.createMapGrowthClassification(rsList, renewalUpsellMap);
        system.debug('***getHeapSize: After createMapGrowthClassification: ' + Limits.getHeapSize());       
        
        // Create OPC from Revenue Schedule/s
        OPCUtility.createOPCMap(rsList, idOPCMap, idRSMap, renewalUpsellMap);
        system.debug('***getHeapSize: After createOPCMap: ' + Limits.getHeapSize());        
        // After this method is executed, input parameters should be updated
        
        // Check if OPC records already exist
        // New OPCs will be inserted and existing OPCs will be aggregated
        OPCUtility.checkIfOPCExist(idOPCMap, idOPCExistingMap, insertOPCList, updateOPCList);
        system.debug('***getHeapSize: After checkIfOPCExist: ' + Limits.getHeapSize()); 
        
        // After this method is executed, input parameters should be updated 
        
        // Relate the related Revenue Schedule to the new OPC records
        OPCUtility.relateRevenueScheduleToOPC(insertOPCList, rsList, uniqueIdopcIdMap, opcIdRSMap);
        system.debug('***getHeapSize: After relateRevenueScheduleToOPC:' + Limits.getHeapSize());   
        
        // Create Budget and Revenue Map
        OPCUtility.createBARMap(idBARMap, acctIdList, prodIdList);
        system.debug('***getHeapSize: After createBARMap: ' + Limits.getHeapSize());    

        // Check for exceptions
        if (!insertOPCList.isEmpty()) {
            requeryOPCList = OPCUtility.requeryOPCList(insertOPCList, requeryOPCList);
            system.debug('***requeryOPCList: ' + requeryOPCList);
            system.debug('***getHeapSize: After requeryOPCList: ' + Limits.getHeapSize());  
            
            OPCUtility.checkForException(requeryOPCList, idBARMap, opcIdRSMap, caseList, rtId, rsList);
            system.debug('***getHeapSize: After checkForException: ' + Limits.getHeapSize());       
            
            
            system.debug('@@@ Size of idOPCMap: ' + idOPCMap.size());   
            system.debug('@@@ Size of idBARMap: ' + idBARMap.size());
            system.debug('@@@ Size of idRSMap: ' + idRSMap.size());
            system.debug('@@@ Size of uniqueIdopcIdMap: ' + uniqueIdopcIdMap.size());
            system.debug('@@@ Size of renewalUpsellMap: ' + renewalUpsellMap.size());
            system.debug('@@@ Size of opcIdRSMap: ' + opcIdRSMap.size());
            system.debug('@@@ Size of opcList: ' + opcList.size());
            system.debug('@@@ Size of caseList: ' + caseList.size());
            system.debug('@@@ Size of idOPCExistingMap: ' + idOPCExistingMap.size());
            system.debug('@@@ Size of insertOPCList: ' + insertOPCList.size());
            system.debug('@@@ Size of updateOPCList: ' + updateOPCList.size());
            system.debug('@@@ Size of requeryOPCList: ' + requeryOPCList.size());
            system.debug('@@@ Size of rsIdList: ' + rsIdList.size());
            system.debug('@@@ Size of rsList: ' + rsList.size());
            system.debug('@@@ Size of acctIdList: ' + acctIdList.size());
            system.debug('@@@ Size of prodIdList: ' + prodIdList.size());
            system.debug('@@@ Size of opcIdList: ' + opcIdList.size());
            
        
            idOPCMap.clear();
            idBARMap.clear();
            idRSMap.clear();
            uniqueIdopcIdMap.clear();   
            renewalUpsellMap.clear();   
            opcIdRSMap.clear(); 
            opcList.clear();
            caseList.clear();
            idOPCExistingMap.clear();
            insertOPCList.clear();
            updateOPCList.clear();
            requeryOPCList.clear();
            rsIdList.clear();
            rsList.clear();
            acctIdList.clear();
            prodIdList.clear();
            opcIdList.clear();
            
            system.debug('***getHeapSize: After checkForException: REDUCED: ' + Limits.getHeapSize());  

            idOPCMap = null;
            idBARMap = null;
            idRSMap = null;
            uniqueIdopcIdMap = null;    
            renewalUpsellMap = null;    
            opcIdRSMap = null;  
            opcList = null;
            caseList = null;
            idOPCExistingMap = null;
            insertOPCList = null;
            updateOPCList = null;
            requeryOPCList = null;
            rsIdList = null;
            rsList = null;
            acctIdList = null;
            prodIdList = null;
            opcIdList = null;
            addlOPCList = null;

            system.debug('***getHeapSize: After NULLING: REDUCED: ' + Limits.getHeapSize());    
        }
    
        
/*      
        caseList.clear();
        if (!updateOPCList.isEmpty()) {
            requeryOPCList = OPCUtility.requeryOPCList(updateOPCList, requeryOPCList);
            system.debug('***requeryOPCList: ' + requeryOPCList);
            OPCUtility.checkForException(requeryOPCList, idBARMap, opcIdRSMap, caseList, rtId, rsList);         
        }
*/                      
    }

    
    global void finish(Database.BatchableContext BC) {
        system.debug('*** FINISH:');    
    }   
    
/*
    @isTest(seeAllData=true)
    private static void testGenerateOPCBatchable() {
        test.startTest();
        GenerateOPCBatchable gob = new GenerateOPCBatchable();
        Database.executeBatch(gob, 1000);
        test.stopTest();
    }   
*/
}