force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Apr_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Apr_Revenue_Amount__c</fullName>
    <label>Apr Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Aug_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Aug_Revenue_Amount__c</fullName>
    <label>Aug Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Dec_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Dec_Revenue_Amount__c</fullName>
    <label>Dec Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Feb_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Feb_Revenue_Amount__c</fullName>
    <label>Feb Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <inlineHelpText>Current Financial Year</inlineHelpText>
    <label>Financial Year</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Jan_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Jan_Revenue_Amount__c</fullName>
    <label>Jan Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Jul_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Jul_Revenue_Amount__c</fullName>
    <label>Jul Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Jun_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Jun_Revenue_Amount__c</fullName>
    <label>Jun Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Mar_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mar_Revenue_Amount__c</fullName>
    <label>Mar Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/May_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>May_Revenue_Amount__c</fullName>
    <label>May Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Nov_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Nov_Revenue_Amount__c</fullName>
    <label>Nov Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Oct_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Oct_Revenue_Amount__c</fullName>
    <label>Oct Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <inlineHelpText>Name of Customer</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Budget_and_Revenue_2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product (Level 5)</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Budget_and_Revenue_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Sep_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sep_Revenue_Amount__c</fullName>
    <label>Sep Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/uid__c.field-meta.xml
<CustomField>
    <fullName>uid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>An unique identifier field that is used in Apex to help uniquely identify a record.</description>
    <externalId>true</externalId>
    <inlineHelpText>An unique identifier field that is used in Apex to help uniquely identify a record.</inlineHelpText>
    <label>uid</label>
    <length>34</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BudgetAndRevenueSelector.cls
/**
* @author Pratyush Chalasani
* @date 2023-04-21
* @group Selector
* @tag Selector
* @tag Profile SObject
* @domain Core
* @description A very simple selector class that sits in the base domain
* @changelog
* 2023-04-21 - Pratyush Chalasani - Created
*/
public virtual inherited sharing class BudgetAndRevenueSelector extends ApplicationSelector {
	public static BudgetAndRevenueSelector newInstance() {
		return (BudgetAndRevenueSelector)Application.Selectors.newInstance(BudgetAndRevenueSelector.class);
	}
	
	public virtual override SObjectType getSObjectType() {
		return Budget_and_Revenue__c.getSObjectType();
	}

	public virtual override Set<SObjectField> getSObjectFieldList() {
		return new Set<SObjectField> {
			Budget_and_Revenue__c.Id, Budget_and_Revenue__c.Organisation__c, Budget_and_Revenue__c.Product__c, Budget_and_Revenue__c.Financial_Year__c,Budget_and_Revenue__c.uid__c,
			Budget_and_Revenue__c.Jan_Revenue_Amount__c, Budget_and_Revenue__c.Feb_Revenue_Amount__c, Budget_and_Revenue__c.Mar_Revenue_Amount__c, Budget_and_Revenue__c.Apr_Revenue_Amount__c, Budget_and_Revenue__c.May_Revenue_Amount__c, Budget_and_Revenue__c.Jun_Revenue_Amount__c,
			Budget_and_Revenue__c.Jul_Revenue_Amount__c, Budget_and_Revenue__c.Aug_Revenue_Amount__c, Budget_and_Revenue__c.Sep_Revenue_Amount__c, Budget_and_Revenue__c.Oct_Revenue_Amount__c, Budget_and_Revenue__c.Nov_Revenue_Amount__c, Budget_and_Revenue__c.Dec_Revenue_Amount__c 
		};
	}

	/**
	 * @description Query revenues by specific account
	 */
	public List<Budget_and_Revenue__c> selectByOrganisationId(Id organisationId) {
		QueryBuilder qb = newQueryBuilder().addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Organisation__c + ' = :organisationId')).endConditions();

		return (List<Budget_and_Revenue__c>)Database.query(qb.toSoqlString());
	}

    public Map<Id, Budget_and_Revenue__c> selectByUniqueIds(Set<String> uniqueIds) {
		QueryBuilder qb = newQueryBuilder().addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.uid__c + ' in :uniqueIds')).endConditions();
		System.debug('SOQL');
		System.debug(qb.toSoqlString());

		return new Map<Id, Budget_and_Revenue__c>((List<Budget_and_Revenue__c>)Database.query(qb.toSoqlString()));
	}

	/**
	 * @description Query revenues by accounts and financial years
	 */
	public List<Budget_and_Revenue__c> selectByOrganisationId(Set<Id> organisationIds, Set<String> financialYears) {
		QueryBuilder qb = newQueryBuilder().addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Organisation__c + ' in :organisationIds')).endConditions();

		if (!financialYears.isEmpty()) {
			qb.addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Financial_Year__c + ' in :financialYears')).endConditions();
		}

		System.debug('SOQL');
		System.debug(qb.toSoqlString());

		return (List<Budget_and_Revenue__c>)Database.query(qb.toSoqlString());
	}
    
    public List<Budget_and_Revenue__c> selectByOrganisationAndProduct(Set<Id> organisationIds, Set<Id> productIds, Set<Integer> financialYears, set<Id> recordsToExclude) {
        Set<String> fy = new Set<String>();
        for (integer currentY : financialYears) {
            fy.add(String.ValueOf(currentY));
        }
        return selectByOrganisationAndProduct(organisationIds, productIds, fy,recordsToExclude);
    }
    
	/**
	 * @description Query revenues by accounts and products and financial years
	 */
	public List<Budget_and_Revenue__c> selectByOrganisationAndProduct(Set<Id> organisationIds, Set<Id> productIds, Set<String> financialYears, set<Id> recordsToExclude) {
		QueryBuilder qb = newQueryBuilder().addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Organisation__c + ' in :organisationIds')).endConditions();

        if (!productIds.isEmpty()) {
			qb.addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Product__c + ' in :productIds')).endConditions();
		}
        
        if (!financialYears.isEmpty()) {
			qb.addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.Financial_Year__c + ' in :financialYears')).endConditions();
		}
        
		if (!recordsToExclude.isEmpty()) {
			qb.addConditions().add(new QueryBuilder.SimpleCondition(Budget_and_Revenue__c.uid__c + 'not in :recordsToExclude')).endConditions();
		}

		System.debug('SOQL');
		System.debug(qb.toSoqlString());

		return (List<Budget_and_Revenue__c>)Database.query(qb.toSoqlString());
	}

}