force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APT_Competitors__c.field-meta.xml
<CustomField>
    <fullName>APT_Competitors__c</fullName>
    <label>Competitors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>DHL Global</fullName>
            </value>
            <value>
                <fullName>DHL Express</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>Toll</fullName>
            </value>
            <value>
                <fullName>Quantium</fullName>
            </value>
            <value>
                <fullName>Australia Post</fullName>
            </value>
            <value>
                <fullName>Toll IPEC</fullName>
            </value>
            <value>
                <fullName>Fastways</fullName>
            </value>
            <value>
                <fullName>TNT</fullName>
            </value>
            <value>
                <fullName>Couriers Please</fullName>
            </value>
            <value>
                <fullName>Hunters Express</fullName>
            </value>
            <value>
                <fullName>Direct Freight</fullName>
            </value>
            <value>
                <fullName>Allied Express</fullName>
            </value>
            <value>
                <fullName>Border Express</fullName>
            </value>
            <value>
                <fullName>Other / Local Couriers</fullName>
            </value>
            <value>
                <fullName>Salmat</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>Walker Network</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APT_Pricing_Reason__c.field-meta.xml
<CustomField>
    <fullName>APT_Pricing_Reason__c</fullName>
    <label>Pricing Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>International Renewal</fullName>
            </value>
            <value>
                <fullName>International Customised Rates</fullName>
            </value>
            <value>
                <fullName>Standard Cat 5 &amp; 6 Domestic Rates</fullName>
            </value>
            <value>
                <fullName>Customised Domestic Rates Renewal / New</fullName>
            </value>
            <value>
                <fullName>Domestic Express Satchel Rates (flat rates)</fullName>
            </value>
            <value>
                <fullName>Competitor Threat/Competitor Pricing</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Lost Business</fullName>
            </value>
            <value>
                <fullName>Cubic Profile</fullName>
            </value>
            <value>
                <fullName>Future Date and Time (DCE)</fullName>
            </value>
            <value>
                <fullName>Oversize</fullName>
            </value>
            <value>
                <fullName>Features &amp; Charges i.e. Returns</fullName>
            </value>
            <value>
                <fullName>Customised Wine pricing</fullName>
            </value>
            <value>
                <fullName>Growth opportunity</fullName>
            </value>
            <value>
                <fullName>Strategic Business Opportunity</fullName>
            </value>
            <value>
                <fullName>Overweight</fullName>
            </value>
            <value>
                <fullName>Out of Specification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AdjustmentAmount__c</fullName>
    <description>The manual price adjustment amount.</description>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__AdjustmentType__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AdjustmentType__c</fullName>
    <description>The manual price adjustment type</description>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>Price Override</fullName>
            </value>
            <value>
                <fullName>Customised Pricing</fullName>
            </value>
            <value>
                <fullName>Offer Higher Band</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ConfigurationId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ConfigurationId__c</fullName>
    <description>ID of the associated configuration</description>
    <label>Configuration</label>
    <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ContractNumbers__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ContractNumbers__c</fullName>
    <description>A comma separated list of contract numbers associated with the line item</description>
    <label>Contract Numbers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__OptionId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__OptionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected option</description>
    <label>Option</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Option Line Items</relationshipLabel>
    <relationshipName>OptionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__PricingStatus__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PricingStatus__c</fullName>
    <description>The pricing status</description>
    <label>Pricing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the selected product or service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_CQApprov__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_CQApprov__Approval_Status__c</fullName>
    <description>The approval status of the cart line item</description>
    <inlineHelpText>The approval status of the cart line item</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Approval Triggered</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APT_RefreshPricingController.cls
/**
 * This apex class is controller for visual force page - APT_RefreshPricing
 * Created By - Mausam Padhiyar
 * Created Date - 21st Sept, 2016
 
 * Last Modified By - Mausam Padhiyar
 * Last Modified Date - 23rd Nov, 2016 | Defect 1791 | reset adjustment amount and adjustment type fields
 */
public with sharing class APT_RefreshPricingController {
    
    public String quoteId;
    public String configId;
    public String configRequestId;
    public String flow;
    
    public boolean haserrorMessages {get; set;}
    public map<string,string> mapUrlParam = new map<string,string>();
    
    /**
     * constructor
     */
    public APT_RefreshPricingController() {
        init();
    }
    
    /**
     * init method
     */
    public void init() {
        haserrorMessages = false;
        quoteId = Apexpages.currentpage().getparameters().get(APT_Constants.URL_BUSINESS_OBJECT_ID);
        configId = Apexpages.currentpage().getparameters().get(APT_Constants.URL_ID);
        configRequestId = Apexpages.currentpage().getparameters().get(APT_Constants.URL_CONFIG_REQUEST_ID);
        flow = Apexpages.currentpage().getparameters().get(APT_Constants.LABEL_FLOW);
        
        URL u = new URL(ApexPages.currentPage().getHeaders().get(APT_Constants.URL_REFERER));
        getCartParameters(u);
    }
    
    /**
     * get cart parameters
     */
    public void getCartParameters(URL u) {
        String parentPageURL = u.getQuery(); 
        if(String.isNotBlank(parentPageURL)){
            for(string s:parentPageURL.split(APT_Constants.SEPERATOR_AND)){
                List<string> lstParam = s.split(APT_Constants.SEPERATOR_EQUAL);
                if(lstParam.size()==2){
                  mapUrlParam.put(lstParam[0],lstParam[1]);
                }     
            }
        }
    }
    
    /**
     * Refresh Pricing
     */
    public PageReference refreshPrice() {
        try {
            if(configId != null) {
                list<Apttus_Config2__LineItem__c> listLineItem = new list<Apttus_Config2__LineItem__c>();
                for(Apttus_Config2__LineItem__c li : [SELECT Id, Apttus_Config2__ProductId__r.APT_Contract_Pricing__c,
                                                    Apttus_Config2__OptionId__r.APT_Contract_Pricing__c,
                                                    Apttus_CQApprov__Approval_Status__c, Apttus_Config2__ContractNumbers__c,
                                                    Apttus_Config2__PricingStatus__c,
                                                    Apttus_Config2__AdjustmentType__c, Apttus_Config2__AdjustmentAmount__c
                                                    FROM Apttus_Config2__LineItem__c
                                                    WHERE Apttus_Config2__ConfigurationId__c = :configId
                                                    AND Apttus_Config2__ContractNumbers__c != null
                                                    AND (Apttus_Config2__ProductId__r.APT_Contract_Pricing__c = true
                                                    OR Apttus_Config2__OptionId__r.APT_Contract_Pricing__c = true)]) {
                    
                    li.Apttus_Config2__PricingStatus__c = APT_Constants.LABEL_LINE_STATUS;
                    li.Apttus_Config2__ContractNumbers__c = null;
                    
                    //1791
                    li.Apttus_Config2__AdjustmentAmount__c = null;
                    li.Apttus_Config2__AdjustmentType__c = null;
                    li.APT_Pricing_Reason__c = null;
                    li.APT_Competitors__c = null;
                    //1791
                    
                    listLineItem.add(li);
                }
                
                if(listLineItem.size() > 0) {
                    update listLineItem;
                }
            }
            
            PageReference cartPage = Page.Apttus_Config2__Cart;
            cartPage.getParameters().put(APT_Constants.LABEL_FLOW, flow);
            cartPage.getParameters().put(APT_Constants.URL_ID, configId);
            cartPage.getParameters().put(APT_Constants.URL_CONFIG_REQUEST_ID, configRequestId);
            cartPage.getParameters().put(APT_Constants.URL_LAUNCH_STATE, mapUrlParam.get(APT_Constants.URL_LAUNCH_STATE));
            
            return cartPage;
        } catch(system.exception ex) {
            haserrorMessages = true;
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
        
        return null;
    }
}