force-app/main/default/objects/Customer_Scoping_Questionnaire__c/Customer_Scoping_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Customer Scoping Questionnaire (CSQ)</label>
    <nameField>
        <displayFormat>CSQ-{0000}</displayFormat>
        <label>Customer Scoping Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Scoping Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/fields/CSQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CSQ_Status__c</fullName>
    <label>CSQ Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for approval</fullName>
            </value>
            <value>
                <fullName>Approved_by_SM</fullName>
                <label>Approved by SM</label>
            </value>
            <value>
                <fullName>Rejected by SM</fullName>
            </value>
            <value>
                <fullName>Pick-Up Locations Approved</fullName>
            </value>
            <value>
                <fullName>Pending National Operations Manager Approval</fullName>
            </value>
            <value>
                <fullName>Fully_Approved</fullName>
                <label>Fully Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CSQ</relationshipLabel>
    <relationshipName>Customer_Scoping_Questionnaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/recordTypes/CSQ.recordType-meta.xml
<RecordType>
    <fullName>CSQ</fullName>
    <active>true</active>
    <label>CSQ</label>
</RecordType>

force-app/main/default/objects/Freight_Offering__c/Freight_Offering__c.object-meta.xml
<CustomObject>
    <label>Freight Offering</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Freight Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Offering__c/fields/B2BBBP__c.field-meta.xml
<CustomField>
    <fullName>B2BBBP__c</fullName>
    <description>Break Bulk Palets</description>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2B%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/B2BCartons__c.field-meta.xml
<CustomField>
    <fullName>B2BCartons__c</fullName>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2B%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/B2BSatchels__c.field-meta.xml
<CustomField>
    <fullName>B2BSatchels__c</fullName>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2B%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/B2CBBP__c.field-meta.xml
<CustomField>
    <fullName>B2CBBP__c</fullName>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2C%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/B2CCartons__c.field-meta.xml
<CustomField>
    <fullName>B2CCartons__c</fullName>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2C%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/B2CSatchels__c.field-meta.xml
<CustomField>
    <fullName>B2CSatchels__c</fullName>
    <inlineHelpText>B2B% and B2C% must add up to 100%</inlineHelpText>
    <label>B2C%</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/Cartons__c.field-meta.xml
<CustomField>
    <fullName>Cartons__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cartons</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/Customer_Scoping_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Customer_Scoping_Questionnaire__c</fullName>
    <label>Customer Scoping Questionnaire</label>
    <referenceTo>Customer_Scoping_Questionnaire__c</referenceTo>
    <relationshipLabel>Freight Offerings</relationshipLabel>
    <relationshipName>Freight_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/Freight_Offering__c.field-meta.xml
<CustomField>
    <fullName>Freight_Offering__c</fullName>
    <label>Freight Offering</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cartons</fullName>
            </value>
            <value>
                <fullName>Break Bulk Pallets</fullName>
            </value>
            <value>
                <fullName>Bulk Pallets</fullName>
            </value>
            <value>
                <fullName>Satchels</fullName>
            </value>
            <value>
                <fullName>Incompatible Freight</fullName>
            </value>
            <value>
                <fullName>Dangerous Goods</fullName>
            </value>
            <value>
                <fullName>Additional Freight Presentation</fullName>
            </value>
            <value>
                <fullName>Service Requirements</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/Qty_ConnotesCartons__c.field-meta.xml
<CustomField>
    <fullName>Qty_ConnotesCartons__c</fullName>
    <label>Qty Connotes (Monthly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Offering__c/fields/Qty_Items_cartons__c.field-meta.xml
<CustomField>
    <fullName>Qty_Items_cartons__c</fullName>
    <label>Cartons Qty Items (Monthly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Pick_Up_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Pick_Up_Location__c</fullName>
    <label>Primary Pick-Up Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple.recordType-meta.xml
<RecordType>
    <fullName>Simple</fullName>
    <active>true</active>
    <businessProcess>BG Sales Process</businessProcess>
    <label>Simple</label>
</RecordType>

force-app/main/default/objects/Pick_Up_Location__c/Pick_Up_Location__c.object-meta.xml
<CustomObject>
    <label>Pick-Up Location</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Pick-Up Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pick-Up Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pick_Up_Location__c/fields/CSQ__c.field-meta.xml
<CustomField>
    <fullName>CSQ__c</fullName>
    <label>CSQ</label>
    <referenceTo>Customer_Scoping_Questionnaire__c</referenceTo>
    <relationshipLabel>Pick-Up Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/CSQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CSQ_Status__c</fullName>
    <formula>text(CSQ__r.CSQ_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CSQ Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/Freight_Offering__c.field-meta.xml
<CustomField>
    <fullName>Freight_Offering__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Testing relationship between FO &amp; Location</description>
    <label>Freight Offering</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CSQ__c</field>
            <operation>equals</operation>
            <valueField>Freight_Offering__c.Customer_Scoping_Questionnaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Freight_Offering__c</referenceTo>
    <relationshipLabel>Pick-Up Locations</relationshipLabel>
    <relationshipName>Pick_Up_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <inlineHelpText>QLD 
Region 1 = Gold Coast-Lismore-Sunshine Coast-Toowoomba
Region 2 = Mackay-Townsville- Rockhampton 

NSW/ACT
Region 1 = Canberra-Wollongong-Albury
Region 2 = Orange-Tamworth-Wagga Wagga
Region 3 = Coffs Harbour-Newcastle-Port Macquarie-Tuggerah</inlineHelpText>
    <label>Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Regional 1 (GLD, LSS, SSC, TWB)</fullName>
            </value>
            <value>
                <fullName>Regional 2 (MAC, TVL, ROC)</fullName>
            </value>
            <value>
                <fullName>Regional 1 (CBR,WOL,ALB,WAG)</fullName>
            </value>
            <value>
                <fullName>Regional 2 (ORG,TAM)</fullName>
            </value>
            <value>
                <fullName>Regional 3 (COF,NCL,PTM,TUG)</fullName>
            </value>
            <value>
                <fullName>Regional (Bendigo-Geelong-Hobart-Shepparton-Traralgon-Launceston)</fullName>
            </value>
            <value>
                <fullName>Melbourne South East</fullName>
            </value>
            <value>
                <fullName>Regional 1 (WOL)</fullName>
            </value>
            <value>
                <fullName>Regional 1 (CBR, WOL, ALB, WAG, ORG)</fullName>
            </value>
            <value>
                <fullName>Regional 2 (CBR, ALB, WAG, ORG)</fullName>
            </value>
            <value>
                <fullName>Regional 3 (TAM)</fullName>
            </value>
            <value>
                <fullName>Regional 4 (COF, NCL, PTM, TUG)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/Pick_up_Location_Status__c.field-meta.xml
<CustomField>
    <fullName>Pick_up_Location_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Received Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/Primary_Pick_Up_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Pick_Up_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Pick Up Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pick_Up_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PickUpLocationSelector_Test.cls
/**
* @author Nathan Franklin
* @date 2021-01-12
* @group Tests
* @tag Selector
* @tag Pick Up Location
* @domain Core
* @description A very simple selector class that sits in the base domain
* @changelog
* 2021-05-12 - Shashwat.Nath@auspost.com.au - Created
* 2023-10-10 - paul.perry5@auspost.com.au - Added test coverage for selecting related tasks and filtering status pending information options
*/
@IsTest
public with sharing class PickUpLocationSelector_Test{
    /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectString() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();

        PickUpLocationSelector selector = PickUpLocationSelector.newInstance();
        QueryBuilder qb = selector.newQueryBuilder(new Set<Object>{PickUpLocationSelector.Options.FILTER_PRIMARY_PICKUP_LOCATION});
        String soql = qb.toSoqlString();

		System.assertEquals(true, Pattern.compile('(?ism)\\bfrom Pick_Up_Location__c\\b').matcher(soql).find(), 'Resulting query does not select from Pick Up Location');

		qb = selector.newQueryBuilder(new Set<Object>{
			PickUpLocationSelector.Options.FILTER_STATUS_PENDING_INFORMATION,
			PickUpLocationSelector.Options.WITH_PENDING_TASKS
		});

		soql = qb.toSoqlString();

		System.assertEquals(true, soql.contains('FROM Tasks'), 'Resulting query does not select from Pick Up Location with Tasks');

        Test.stopTest();

    }

    /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectStringWithRelatedFields() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();

        PickUpLocationSelector selector = PickUpLocationSelector.newInstance();
        QueryBuilder qb = selector.newQueryBuilder(new Set<Object>{PickUpLocationSelector.Options.FILTER_PRIMARY_PICKUP_LOCATION});
        String soql = qb.toSoqlString();
        System.assertEquals(false, Pattern.compile('(?is)Primary_Pick_Up_Location__c\\..*?\\bfrom Pick_Up_Location__c\\b').matcher(soql).find(), 'Resulting query does not select pick up location');
        Test.stopTest();

    }
    /**
     * Executes a query to ensure it returns expected results with actual inserted data
     */
    @IsTest
    public static void testSelectorIntegration() {

        // =====================================
        // Data Preparation
        // =====================================
        MockUtility.disableTriggerExecution();

        Opportunity opp = new Opportunity(Name = 'Test Optty', StageName = 'Identify', CloseDate = system.today());
        Insert opp;
        Customer_Scoping_Questionnaire__c CSQ = new Customer_Scoping_Questionnaire__c(CSQ_Status__c = 'Approved_by_SM', Opportunity__c = opp.Id);
        Insert CSQ;
        Freight_Offering__c freightOffering = new Freight_Offering__c(Customer_Scoping_Questionnaire__c = CSQ.Id, Cartons__c = true, 
                                                                      B2BCartons__c = 50, B2CCartons__c  = 50, Qty_ConnotesCartons__c = 100, 
                                                                      Qty_Items_cartons__c = 100, B2CBBP__c = 50, B2BBBP__c = 50, 
                                                                      B2BSatchels__c = 50, B2CSatchels__c = 50);
        Insert freightOffering;
        
        Pick_Up_Location__c pickUpLoc = new Pick_Up_Location__c(pick_up_location_status__c = 'Rejected', CSQ__c = CSQ.Id, Location_Type__c='Metro' , Primary_Pick_Up_Location__c = false , State__c='NSW' , Freight_Offering__c = freightOffering.id);
        Insert pickUpLoc; 
            
        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();
        
        PickUpLocationSelector selector = PickUpLocationSelector.newInstance(1);
        Map<Id, Pick_Up_Location__c > results = selector.selectById(new Set<Id>{pickUpLoc.id});
        System.assertEquals(1, results.size(), 'Result count was wrong');

        results = selector.selectById(new Set<Id>{pickUpLoc.id}, new Set<Object>{PickUpLocationSelector.Options.FILTER_PRIMARY_PICKUP_LOCATION});
        System.assertEquals(1, results.size(), 'Result count was wrong');

        List<Pick_Up_Location__c> resultList = selector.selectByParentId(new Set<Id>{CSQ.Id}, new Set<Object>{PickUpLocationSelector.Options.FILTER_PRIMARY_PICKUP_LOCATION});
        System.assertEquals(1, resultList.size(), 'Result count was wrong');
        Test.stopTest();
    }
    
      /**
     * Test:
     *  Ensures that the selectors QueryBuilder is generating the correct output
     */
    @IsTest
    public static void testEnsureQueryBuilderProducesCorrectStringWithFieldOverrides() {

        // =====================================
        // Data Preparation
        // =====================================
        // None!

        // =====================================
        // Stubbing
        // =====================================
        // None!

        // =====================================
        // Testing
        // =====================================
        Test.startTest();
        PickUpLocationSelector selector1 = PickUpLocationSelector.newInstance(0, new Set<SObjectField>{Pick_Up_Location__c.Name});

        PickUpLocationSelector selector = PickUpLocationSelector.newInstance(0, new Map<SObjectType, Set<SObjectField>>{
                Pick_Up_Location__c.SObjectType => new Set<SObjectField>{Pick_Up_Location__c.Name}
        });
        QueryBuilder qb = selector.newQueryBuilder(new Set<Object>{PickUpLocationSelector.Options.FILTER_PRIMARY_PICKUP_LOCATION});
        String soql = qb.toSoqlString();
        System.assertEquals(true, Pattern.compile('(?ism)Name.*?\\bfrom Pick_Up_Location__c\\b').matcher(soql).find(), 'Resulting query does not select Name field: ' + soql);

        Test.stopTest();

    }
}