force-app/main/default/objects/Customer_Scoping_Questionnaire__c/Customer_Scoping_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Customer Scoping Questionnaire (CSQ)</label>
    <nameField>
        <displayFormat>CSQ-{0000}</displayFormat>
        <label>Customer Scoping Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Scoping Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/fields/PreApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>PreApprovalStatus__c</fullName>
    <description>Indicates the Pre-Approval status value that works in conjunction with CSQ Approval Process 1.</description>
    <inlineHelpText>Indicates the Pre-Approval status value that works in conjunction with CSQ Approval Process 1.</inlineHelpText>
    <label>Pre-Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Onboarding Approval</fullName>
            </value>
            <value>
                <fullName>Under Onboarding Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/fields/PreApprover__c.field-meta.xml
<CustomField>
    <fullName>PreApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who is responsible for the onboarding review, and the decider of the CSQ Pre-Approval Process. This field is auto populated to the user Id who changed Pre-Approval status to &apos;Under Onboarding Review&apos;.</description>
    <inlineHelpText>The user who is responsible for the onboarding review, and the decider of the CSQ Pre-Approval Process. This field is auto populated to the user Id who changed Pre-Approval status to &apos;Under Onboarding Review&apos;.</inlineHelpText>
    <label>Pre-Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Scoping_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Scoping_Questionnaire__c/recordTypes/CSQ.recordType-meta.xml
<RecordType>
    <fullName>CSQ</fullName>
    <active>true</active>
    <label>CSQ</label>
</RecordType>

force-app/main/default/classes/CSQPreApprovalUnderReviewModule.cls
/***
 * @author SteveL
 * @date 2024-03-14
 * @description Logic related to CSQ records.
 * @changelog
 */

public inherited sharing class CSQPreApprovalUnderReviewModule extends ApplicationModule {
	public CSQPreApprovalUnderReviewModule() {
		getTriggerEvents().enableBeforeUpdate();
	}

	public static CSQPreApprovalUnderReviewModule newInstance() {
		return (CSQPreApprovalUnderReviewModule) Application.Utilities.newInstance(CSQPreApprovalUnderReviewModule.class);
	}

	/**
	 * Called when a CSQ is being updated.
	 * @param records list of CSQ records
	 * @param existingRecords map of existing CSQ records
	 * @param uow instance of UnitOfWork
	 */
	public override void onBeforeUpdate(List<SObject> records, Map<Id, SObject> existingRecords, ApplicationUnitOfWork uow) {
		try {
			setUnderReviewPreApprover(records, existingRecords);
		} catch (Exception ex) {
			// Error Logged to Exception object for analysis
			ApplicationLogger.getInstance().logException(ApplicationLogger.wrapException(ex), 'CSQ', CSQPreApprovalUnderReviewModule.class.getName(), 'onBeforeUpdate', 'Customer_Scoping_Questionnaire__c', ApplicationLogger.LoggingLevel.ERROR);
		}
	}

	/**
	 * @description set the PreApprover__c field to the current user if the pre approval status is changed to Under Onboarding Review
	 * @param records List<SObject>
	 * @param existingRecords Map<Id, SObject>
	 */
	private static void setUnderReviewPreApprover(List<SObject> records, Map<Id, SObject> existingRecords) {
		Customer_Scoping_Questionnaire__c oldCsq;
		for (Customer_Scoping_Questionnaire__c csq : (List<Customer_Scoping_Questionnaire__c>) records) {
			oldCsq = (Customer_Scoping_Questionnaire__c) existingRecords.get(csq.Id);
			if (csq.PreApprovalStatus__c == CSQAutomationTriggerHandler.PRE_APPROVAL_STATUS_UNDER_ONBOARDING_REVIEW && oldCsq.PreApprovalStatus__c != CSQAutomationTriggerHandler.PRE_APPROVAL_STATUS_UNDER_ONBOARDING_REVIEW) {
				csq.PreApprover__c = UserInfo.getUserId();
			}
		}
	}
}