force-app/main/default/objects/APT_ApprovalCommentsFieldMapping__c/APT_ApprovalCommentsFieldMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in Approval trigger to parse and Approval comments and copy to Line Item</description>
    <label>Approval Comments Field Mapping</label>
</CustomObject>

force-app/main/default/objects/APT_ApprovalCommentsFieldMapping__c/fields/APT_Field_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_Field_Data_Type__c</fullName>
    <label>Field Data Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_ApprovalCommentsFieldMapping__c/fields/APT_Line_Item_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>APT_Line_Item_Field_Name__c</fullName>
    <label>Line Item Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus__APTS_Agreement__c/Apttus__APTS_Agreement__c.object-meta.xml
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus__APTS_Agreement__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/Apttus_Approval__Approval_Request__c.object-meta.xml
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Notified</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reassigned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/fields/Apttus_Approval__Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approver_Comments__c</fullName>
    <label>Approver Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/fields/Apttus_Approval__ChildObjectId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__ChildObjectId__c</fullName>
    <description>ID of the child object</description>
    <inlineHelpText>ID of the child object</inlineHelpText>
    <label>Child Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Approval__Approval_Request__c/fields/Apttus_Approval__StepLabel__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__StepLabel__c</fullName>
    <description>The step label</description>
    <inlineHelpText>The step label</inlineHelpText>
    <label>Step Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/Apttus_Config2__LineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product or service line item</description>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/APT_Tier_Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_Tier_Adjustment_Type__c</fullName>
    <description>for startrack delegation</description>
    <formula>TEXT(Apttus_Config2__ConfigurationId__r.Apttus_QPConfig__Proposald__r.APT_Tier_Adjustment_Type__c)</formula>
    <label>Requested Adjustment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__LineItem__c/fields/Apttus_Config2__AllowManualAdjustment__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AllowManualAdjustment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether manual price adjustments are allowed for the line item</description>
    <label>Allow Manual Adjustment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/Apttus_Config2__PriceListItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__AllowManualAdjustment__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__AllowManualAdjustment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether manual price adjustments are allowed for the product</description>
    <label>Allow Manual Adjustment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/Apttus_Proposal__Proposal__c.object-meta.xml
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_Domestic_Overweight_Flag__c.field-meta.xml
<CustomField>
    <fullName>APT_Domestic_Overweight_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please click on Submit for Approval button at top of the page to submit Oversize Approval</inlineHelpText>
    <label>Domestic Oversize Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_International_Overweight_Flag__c.field-meta.xml
<CustomField>
    <fullName>APT_International_Overweight_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>International Overweight Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_Overweight_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>APT_Overweight_Approval_Status__c</fullName>
    <label>Oversize Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/APT_Tier_Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_Tier_Adjustment_Type__c</fullName>
    <description>Tier Adjustment for Approval</description>
    <label>(depr) Requested Adjustment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Tier Up</fullName>
            </value>
            <value>
                <fullName>2 Tier Up</fullName>
            </value>
            <value>
                <fullName>3 Tier Up</fullName>
                <isActive>false</isActive>
                <label>3 Tier Up</label>
            </value>
            <value>
                <fullName>4 Tier Up</fullName>
                <isActive>false</isActive>
                <label>4 Tier Up</label>
            </value>
            <value>
                <fullName>5 Tier Up</fullName>
                <isActive>false</isActive>
                <label>5 Tier Up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Proposal__Proposal__c/fields/Expected_Revenue_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Revenue_Start_Date__c</fullName>
    <defaultValue>Today()+ 30 + 30</defaultValue>
    <inlineHelpText>Please provide estimated revenue start date, this value will be populated across Opportunity Products</inlineHelpText>
    <label>Expected Revenue Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apttus_Approval__Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Approval__Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_International_Pricing__c.field-meta.xml
<CustomField>
    <fullName>APT_International_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Calculate International Pricing using Batch</description>
    <inlineHelpText>if true then product pricing will be handled using international pricing batch</inlineHelpText>
    <label>International Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Is_Cash_Account_Product__c.field-meta.xml
<CustomField>
    <fullName>APT_Is_Cash_Account_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if the Billing Account associated to the product is of Cash Type</description>
    <label>Is Cash Account Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Is_Charge_Account_Product__c.field-meta.xml
<CustomField>
    <fullName>APT_Is_Charge_Account_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if the Billing Account associate to the product is of Charge Type</description>
    <label>Is Charge Account Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Sync_with_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>APT_Sync_with_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set Sync with Opportunity as true if you want to sync the product while sync with opportunity action otherwise false.</description>
    <inlineHelpText>Set Sync with Opportunity as true if you want to sync the product while sync with opportunity action otherwise false.</inlineHelpText>
    <label>Sync with Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Apttus_Config2__ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ConfigurationType__c</fullName>
    <description>The product configuration type</description>
    <label>Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standalone</fullName>
                <default>true</default>
                <label>Standalone</label>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APT_ApprovalRequestTriggerHelper_Test.cls
@isTest
public with sharing class APT_ApprovalRequestTriggerHelper_Test {
    private static testMethod void testMethod1() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testuser = new User(Alias = APT_Constants.ALIAS_TEST_USER, Email=APT_Constants.EMAIL_TEST_USER,
                                 EmailEncodingKey=APT_Constants.EMAILENCODINGKEY_TEST_USER, LastName=APT_Constants.LASTNAME_TEST_USER, LanguageLocaleKey=APT_Constants.LANGUAGELOCALEKEY_TEST_USER,
                                 LocaleSidKey=APT_Constants.LOCALESIDKEY_TEST_USER, ProfileId = p.Id,
                                 TimeZoneSidKey=APT_Constants.TIMEZONESIDKEY_TEST_USER,
                                 UserName=APT_Constants.EMAIL_TEST_USER);
        System.runAs(testuser) {
            //Create Account
            Account acc = APT_TestUtils.createOrganisation();
            insert acc;
            //Create Opportunity
            Opportunity opty = APT_TestUtils.createOpportunity(acc.Id);
            insert opty;
            //Create PriceList
            Apttus_Config2__PriceList__c priceList = APT_TestUtils.createPriceList();
            insert priceList;
            //create international product
            Product2 bundle1 = APT_TestUtils.createDomesticProduct('International Bundle','eParcelStandard','Postal Services','CAT1', 'Standard');
            bundle1.APT_Sync_with_Opportunity__c=true;
            bundle1.APT_Is_Charge_Account_Product__c = true;
            bundle1.APT_Is_Cash_Account_Product__c = false;
            insert bundle1;
            //Create Option product
            Product2 option = APT_TestUtils.createDomesticProduct('International Bundle','eParcelStandard','Postal Services','CAT1', 'Standard');
            option.Apttus_Config2__ConfigurationType__c='Option';
            option.APT_Sync_with_Opportunity__c=true;
            option.APT_International_Pricing__c = false;
            insert option;
            //Create PriceBookEntry
            Id pricebookId = Test.getStandardPricebookId();
            PricebookEntry standardPrice = APT_TestUtils.getPricebookEntry(Test.getStandardPricebookId(),option.ID);
            insert standardPrice;
            //Create Price list Item
            Apttus_Config2__PriceListItem__c pli= APT_TestUtils.createPriceListItem(priceList.ID,bundle1.ID,'C Manufacturing','BAND 2');
            insert pli;
            //Create Proposal
            Apttus_Proposal__Proposal__c Proposal= APT_TestUtils.getQuoteProposal(acc.ID,opty.ID,'Proposal','Quote', priceList.ID);
            proposal.Expected_Revenue_Start_Date__c = System.Today() - 20;
            proposal.APT_Domestic_Overweight_Flag__c = true;
            proposal.APT_International_Overweight_Flag__c = true;
            proposal.APT_Overweight_Approval_Status__c = 'Approved';
            proposal.APT_Tier_Adjustment_Type__c = '1 Tier Up';
            insert Proposal;
            Apttus_Config2__ProductConfiguration__c prodconfig = APT_TestUtils.getProductConfiguration('Product Configuration', 1,
                                                                                                       Proposal.id, 'Proposal',
                                                                                                       'Ad Hoc',priceList.id, null,
                                                                                                       'New',
                                                                                                       null, null, true);
            insert prodconfig;
            Apttus_Config2__LineItem__c bundleLine = APT_TestUtils.getConfigLineItem(prodconfig.id, null, 1, true,//Config id, grpid, LineNum, isPrimary
                                                                                     1, 'Product/Service', bundle1.id, true, null,//ItemSeq, lineType, bundleid, customizable, productOptionid
                                                                                     null, null, null, 1, true,//optionid, class id, class hierarchy, qty, qty Modifiable
                                                                                     'Each', 1, priceList.id, pli.id,//Uom, term, priceList, Pli,
                                                                                     'One Time', 'Per Unit', 'Standard Price', 'One Time',//priceType, priceMethod, chargeType, frequency
                                                                                     true, true, 5500, 5500, 'Per Unit',//allowManualAdj, allocateGroupAdj, listPrice, basePrice, basePriceMethod,
                                                                                     5225, 0, 5225, 'TestaPTTUS');//baseExtPrice, optionPrice, extendedPrice, lineDesc
            bundleLine.Apttus_Config2__AllowManualAdjustment__c = true;
            bundleLine.Apttus_Config2__NetPrice__c = 5225;
            insert bundleLine;
            APT_ApprovalCommentsFieldMapping__c appfieldmap = new APT_ApprovalCommentsFieldMapping__c();
            appfieldmap.Name = 'RK Code';
            appfieldmap.APT_Field_Data_Type__c = 'Text';
            appfieldmap.APT_Line_Item_Field_Name__c = 'APT_Rate_Card_Key__c';
            insert appfieldmap;
            Test.StartTest();
            // create approval request
            Apttus_Approval__Approval_Request__c approvalReq = new Apttus_Approval__Approval_Request__c();
            approvalReq.Apttus_Approval__Approval_Status__c = 'Not Submitted';
            approvalReq.Apttus_Approval__ChildObjectId__c = bundleLine.Id;
            approvalReq.Apttus_Approval__Object_Type__c = APT_Constants.PRODUCT_CONFIGURATION_OBJECT;
            insert approvalReq;
            approvalReq.Apttus_Approval__Approval_Status__c = 'Rejected';
            approvalReq.Apttus_Approval__Approver_Comments__c = 'RK Code - 678 ';
            approvalReq.Apttus_Approval__StepLabel__c = 'Dangerous Goods';
            approvalReq.Apttus_QPApprov__ProposalId__c = proposal.Id;
            update approvalReq;
            /*
            try{
                approvalReq.Apttus_Approval__Approval_Status__c = 'Rejected';
                approvalReq.Apttus_Approval__Approver_Comments__c = 'Rejected - test';
                update approvalReq;
            }catch(Exception e) {
                System.debug('e.getMessage():'+ e.getMessage());
            }
			*/
            Apttus_Approval__Approval_Request__c approvalReq2 = new Apttus_Approval__Approval_Request__c();
            approvalReq2.Apttus_Approval__Approval_Status__c = 'Not Submitted';
            approvalReq2.Apttus_Approval__Object_Type__c = APT_Constants.PRODUCT_CONFIGURATION_OBJECT;
            insert approvalReq2;
            approvalReq2.Apttus_Approval__Approval_Status__c = 'Rejected';
            approvalReq2.Apttus_Approval__Approver_Comments__c = 'Rejected test';
            approvalReq2.Apttus_Approval__StepLabel__c = 'Overweight items';
            approvalReq2.Apttus_QPApprov__ProposalId__c = proposal.Id;
            update approvalReq2;
            Apttus_Approval__Approval_Request__c approvalReq3 = new Apttus_Approval__Approval_Request__c();
            approvalReq3.Apttus_Approval__Approval_Status__c = 'Not Submitted';
            approvalReq3.Apttus_Approval__Object_Type__c = APT_Constants.PRODUCT_CONFIGURATION_OBJECT;
            insert approvalReq3;
            approvalReq3.Apttus_Approval__Approval_Status__c = 'Approved';
            approvalReq3.Apttus_Approval__Approver_Comments__c = 'Rejected test';
            approvalReq3.Apttus_Approval__StepLabel__c = 'International Items';
            approvalReq3.Apttus_QPApprov__ProposalId__c = proposal.Id;
            update approvalReq3;
            Contact con= APT_TestUtils.createContact();
            insert con;
            Apttus__APTS_Agreement__c agreement = APT_TestUtils.createAgreement(con.Id);
            agreement.Apttus_QPComply__RelatedProposalId__c=proposal.Id;
            insert agreement;
            Apttus_Config2__ConfigSystemProperties__c objSett = new Apttus_Config2__ConfigSystemProperties__c(Name= 'System Properties');
            insert objSett;
            APT_TermAndConditionController tempObj = new APT_TermAndConditionController();
            tempObj.setcontractID(agreement.ID);
            ID testVar = tempObj.getcontractID();
            tempObj.approvalRequestSO = approvalReq3;
            tempObj.agreementSO = agreement;
            tempObj.getContractURL();
            Test.StopTest();
            system.assert(approvalReq!=null);
            system.assert(approvalReq2!=null);
            system.assert(approvalReq3!=null);
        }
    }
}