force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Phase 1 - Created Competitors object from Opportunity to Account</description>
    <label>Competitor and Incumbent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Competitors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors and Incumbents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <description>New competitor name requested by sales optimisation</description>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AaE</fullName>
            </value>
            <value>
                <fullName>Access Prepaid</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ARK Express</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>ATO Clearing house</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Bpay</fullName>
            </value>
            <value>
                <fullName>Bpoint</fullName>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cash Passport</fullName>
            </value>
            <value>
                <fullName>CBA</fullName>
            </value>
            <value>
                <fullName>Couriers Please</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>DHL International</fullName>
            </value>
            <value>
                <fullName>Digital Delivery</fullName>
            </value>
            <value>
                <fullName>Edentiti</fullName>
            </value>
            <value>
                <fullName>Experion</fullName>
            </value>
            <value>
                <fullName>Fastway</fullName>
            </value>
            <value>
                <fullName>FedEx</fullName>
            </value>
            <value>
                <fullName>FedEx International</fullName>
            </value>
            <value>
                <fullName>Green ID</fullName>
            </value>
            <value>
                <fullName>Internal Fulfillment</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>NAB</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Bank</fullName>
            </value>
            <value>
                <fullName>Other Clearing House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/Competitor_Type__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Type__c</fullName>
    <inlineHelpText>What type of competition are we up against? (4%)</inlineHelpText>
    <label>Competitor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Incumbent</fullName>
            </value>
            <value>
                <fullName>No Competitor Identified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>Phase 1 - Holds Opportunity Id for the Competitors related list in Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitors and Incumbents</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/DealSupportRequestMilestone__c/DealSupportRequestMilestone__c.object-meta.xml
<CustomObject>
    <description>Object used to track how long it took for deal support request to move across implementation stages.</description>
    <label>Deal Support Request Milestone</label>
    <nameField>
        <displayFormat>DSRM-{00000}</displayFormat>
        <label>Deal Support Request Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Support Request Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DealSupportRequestMilestone__c/fields/DealSupportRequest__c.field-meta.xml
<CustomField>
    <fullName>DealSupportRequest__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Id of deal support request related to this deal support request milestone record.</description>
    <inlineHelpText>Id of deal support request related to this deal support request milestone record.</inlineHelpText>
    <label>Deal Support Request</label>
    <referenceTo>Deal_Support_Request__c</referenceTo>
    <relationshipLabel>Deal Support Request Milestones</relationshipLabel>
    <relationshipName>DealSupportRequestMilestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Segment_Reference__c/Sales_Segment_Reference__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - This object contains reference data for Sales Segment to be derived from Tier/Segment/Post codes.</description>
    <label>Sales Team Reference</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Customer Segment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Team Reference</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicationTestDataFactorySales.cls
/**
 * @description 
 * @author Dattaraj Deshmukh
 * @date 2020-06-15
 * @group Tests
 * @tags mocking, apex mocks, tests, data factory, test data
 * @changelog
 * 2022-06-04 - Dattaraj Deshmukh - Created - getDealSupportRequestMilestones method for User story, SM-604
 * 2023-04-14 - Harry Wang - Created - added getOpportunityLineItems method
 * 2023-07-13 - Pratyush Chalasani - Added getSalesSegmentReferences
 * 2023-08-18 - Ranjeewa Silva - Added new method to return Competitors (Competitor__c)
 */
@IsTest
public with sharing class ApplicationTestDataFactorySales {


	/**
	* @desc: Called from DealSupportRequstMilestoneSelector_Test, DealSpprtReqsMilestonesTrackModule_Test.
	* Creates Deal Support Request milestone record for a DSR
	*/
	public static List<DealSupportRequestMilestone__c> getDealSupportRequestMilestones(integer count, Id dealSupportRequestId, Boolean generateIds) {
		return (List<DealSupportRequestMilestone__c>) ApplicationTestDataFactory.maybeGenerateIds(ApplicationTestDataFactory.populateSObjects(DealSupportRequestMilestone__c.SObjectType, new Map<SObjectField, Object>{
				DealSupportRequestMilestone__c.DealSupportRequest__c => dealSupportRequestId
		}, count), generateIds);
	}

	/**
	 * @desc: Called from OpportunityLineItemSelector_Test
	 * Creates OpportunityLineItems
	 */
	public static List<OpportunityLineItem> getOpportunityLineItems(Integer count, Id opportunityId, Id priceBookEntryId, Boolean generateIds) {
		return (List<OpportunityLineItem>) ApplicationTestDataFactory.maybeGenerateIds(ApplicationTestDataFactory.populateSObjects(OpportunityLineItem.SObjectType, new Map<SObjectField, Object>{
				OpportunityLineItem.opportunityId => opportunityId,
				OpportunityLineItem.Quantity => 1,
				OpportunityLineItem.UnitPrice => 2,
				OpportunityLineItem.PricebookEntryId => priceBookEntryId
		}, count), generateIds);
	}

	public static List<Sales_Segment_Reference__c> getSalesSegmentReferences(Integer count, Boolean generateIds) {
		return (List<Sales_Segment_Reference__c>) ApplicationTestDataFactory.maybeGenerateIds(ApplicationTestDataFactory.populateSObjects(Sales_Segment_Reference__c.SObjectType, new Map<SObjectField, Object>(), count), generateIds);
	}

	public static List<Competitor__c> getCompetitors(Integer count, Id opportunityId, Boolean generateIds) {
		return (List<Competitor__c>) ApplicationTestDataFactory.maybeGenerateIds(ApplicationTestDataFactory.populateSObjects(Competitor__c.SObjectType, new Map<SObjectField, Object>{
				Competitor__c.OpportunityId__c => opportunityId,
				Competitor__c.Competitor_Name__c => 'Other',
				Competitor__c.Competitor_Type__c => 'Competitor'
		}, count), generateIds);
	}
}