force-app/main/default/objects/Route_Assignment__c/Route_Assignment__c.object-meta.xml
<CustomObject>
    <description>The assignment of a Service Resource to a Duty</description>
    <label>Duty Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000}</displayFormat>
        <label>Duty Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Duty Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Assignment__c/fields/Duty_Board__c.field-meta.xml
<CustomField>
    <fullName>Duty_Board__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duty</label>
    <referenceTo>Route_Template__c</referenceTo>
    <relationshipLabel>Duty Assignments</relationshipLabel>
    <relationshipName>Assigned_Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Template__c/Route_Template__c.object-meta.xml
<CustomObject>
    <label>Duty Template</label>
    <nameField>
        <label>Duty Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duty Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/Duty_Board__c.field-meta.xml
<CustomField>
    <fullName>Duty_Board__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duty Template</label>
    <referenceTo>Route_Template__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Other record types - Delivery, Collection, Rest Break, etc</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/TDF_DeleteWorkOrderFromDBTCtrl_Test.cls
@isTest
public class TDF_DeleteWorkOrderFromDBTCtrl_Test{

    static testmethod void testDeleteWorkOrderFromDBTCtrl(){

        TDF_TestDataFactory objTestDataFactory = new TDF_TestDataFactory();

        OperatingHours objOperatingHours = objTestDataFactory.getOperatingHours('Afternoon Shift');
        insert objOperatingHours;

        ServiceTerritory objServiceTerritory = objTestDataFactory.getServiceTerritory('Dendanong', objOperatingHours.Id);
        insert objServiceTerritory;

        Route_Template__c objRouteTemplate = objTestDataFactory.getDutyTemplate('Test Template', objServiceTerritory.Id);
        insert objRouteTemplate;

        Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User objAdminUser = objTestDataFactory.getUser(sysAdmin.Id, 'tdf@australiaPost.com');
        insert objAdminUser;

        ServiceResource objServiceResource = objTestDataFactory.getServiceResource('TDF Test', objAdminUser);
        insert objServiceResource;

        Route_Assignment__c objRouteAssignment = objTestDataFactory.getRouteAssignment(objServiceResource.Id, objRouteTemplate.Id);
        insert objRouteAssignment;

        List<WorkOrder> workOrderList = new List<WorkOrder>();
        String standardWORecordType = objTestDataFactory.getWorkOrderRTId('Standard');

        for(Integer i=0; i<10; i++){
            WorkOrder objWorkOrder = objTestDataFactory.getWorkOrder(standardWORecordType);
            objWorkOrder.Duty_Board__c = objRouteTemplate.Id;
            workOrderList.add(objWorkOrder);
        }
        insert workOrderList;

        PageReference pageRef = Page.TDF_DeleteWorkOrderFromDBT;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', objRouteTemplate.Id);

        TDF_DeleteWorkOrderFromDBT_ControllerX objDeleteFromDBTController = new TDF_DeleteWorkOrderFromDBT_ControllerX(new ApexPages.StandardController(objRouteTemplate));

        objDeleteFromDBTController.confirmDeletion();

        objDeleteFromDBTController.startDate = System.today();
        objDeleteFromDBTController.endDate = System.today().addDays(1);

        objDeleteFromDBTController.confirmDeletion();

        System.assertEquals(10, workOrderList.size());

        objDeleteFromDBTController.deleteWorkOrders();

        workOrderList = [SELECT Id FROM WorkOrder WHERE Duty_Board__c =: objRouteTemplate.Id];

        System.assertEquals(0, workOrderList.size());

        objDeleteFromDBTController.cancel();        
    }
}