force-app/main/default/objects/AccountRelationship__c/AccountRelationship__c.object-meta.xml
<CustomObject>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>ACR-{00000000}</displayFormat>
        <label>Account Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountRelationship__c/fields/ParentAccount__c.field-meta.xml
<CustomField>
    <fullName>ParentAccount__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent account in the Parent-Related account relationship.</description>
    <inlineHelpText>Choose the primary (main) Parent account for this relationship.</inlineHelpText>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Accounts</relationshipLabel>
    <relationshipName>ParentAccountRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountRelationship__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account which is related to the Parent Account.</description>
    <inlineHelpText>Choose the Account which is related to the Parent Account.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>ChildAccountRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountRelationship__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APR__c/APR__c.object-meta.xml
<CustomObject>
    <description>Annual Price Review.</description>
    <label>APR</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>APR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/APR__c/fields/Legal_Entity_Name_LookUp__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_LookUp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>APRs</relationshipLabel>
    <relationshipName>APRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APR__c/fields/MHS_Confirmed_Rate__c.field-meta.xml
<CustomField>
    <fullName>MHS_Confirmed_Rate__c</fullName>
    <label>MHS Confirmed Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/uid__c.field-meta.xml
<CustomField>
    <fullName>uid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>An unique identifier field that is used in Apex to help uniquely identify a record.</description>
    <externalId>true</externalId>
    <inlineHelpText>An unique identifier field that is used in Apex to help uniquely identify a record.</inlineHelpText>
    <label>uid</label>
    <length>34</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <formula>Organisation__c +  Product__c +  Financial_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UniqueId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/GroupedAccountProductRevenue__c.object-meta.xml
<CustomObject>
    <description>Consolidates monthly revenue figures for a given account and product for a specified financial year. It  includes values from child accounts and related products. Used to calculate retained and incremental revenue for opportunities and to track sales forecasts against actuals.</description>
    <label>Grouped Account Product Revenue</label>
    <nameField>
        <displayFormat>APR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GroupedAccountProductRevenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/AnchorOrganisation__c.field-meta.xml
<CustomField>
    <fullName>AnchorOrganisation__c</fullName>
    <description>This field identifies the &apos;Anchor&apos; account for the revenue summary. Sales revenue from all associated child accounts within the hierarchy will be aggregated.</description>
    <inlineHelpText>Select the &apos;Anchor&apos; account for this revenue summary. All revenue from linked child accounts in the hierarchy will be included in this aggregation.</inlineHelpText>
    <label>Anchor Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GroupedAccountProductRevenues</relationshipLabel>
    <relationshipName>GroupedAccountProductRevenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/FinancialYear__c.field-meta.xml
<CustomField>
    <fullName>FinancialYear__c</fullName>
    <description>Australian financial year as a numeric value, indicating the latter year of the financial period.</description>
    <inlineHelpText>Enter the ending year of the Australian financial year.</inlineHelpText>
    <label>Financial Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/PrimaryProduct__c.field-meta.xml
<CustomField>
    <fullName>PrimaryProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field identifies the &apos;Primary Product&apos; for the revenue summary. Sales revenue from all associated related products will be aggregated based on this primary product reference</description>
    <inlineHelpText>Select the primary Product for aggregation. Revenues from related products will be consolidated under this reference</inlineHelpText>
    <label>Primary Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>GroupedAccountProductRevenues</relationshipLabel>
    <relationshipName>GroupedAccountProductRevenues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev1__c.field-meta.xml
<CustomField>
    <fullName>Rev1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of January.</description>
    <inlineHelpText>Enter the total revenue for January.</inlineHelpText>
    <label>Revenue January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev2__c.field-meta.xml
<CustomField>
    <fullName>Rev2__c</fullName>
    <description>This field captures the total revenue for the month of February</description>
    <inlineHelpText>Enter the total revenue for February.</inlineHelpText>
    <label>Revenue February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev3__c.field-meta.xml
<CustomField>
    <fullName>Rev3__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field captures the total revenue for the month of March.</description>
    <inlineHelpText>Enter the total revenue for March.</inlineHelpText>
    <label>Revenue March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev4__c.field-meta.xml
<CustomField>
    <fullName>Rev4__c</fullName>
    <description>This field captures the total revenue for the month of April.</description>
    <inlineHelpText>Enter the total revenue for April.</inlineHelpText>
    <label>Revenue April</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev5__c.field-meta.xml
<CustomField>
    <fullName>Rev5__c</fullName>
    <description>This field captures the total revenue for the month of May.</description>
    <inlineHelpText>Enter the total revenue for May.</inlineHelpText>
    <label>Revenue May</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/Rev6__c.field-meta.xml
<CustomField>
    <fullName>Rev6__c</fullName>
    <description>This field captures the total revenue for the month of June.</description>
    <inlineHelpText>Enter the total revenue for June.</inlineHelpText>
    <label>Revenue June</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UID</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GroupedAccountProductRevenue__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <description>A formula field used by Apex to construct maps to identify records.</description>
    <formula>AnchorOrganisation__c +  PrimaryProduct__c +  TEXT(FinancialYear__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>A formula field used by Apex to construct maps to identify records.</inlineHelpText>
    <label>UniqueId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupedRevenueSchedule__c/GroupedRevenueSchedule__c.object-meta.xml
<CustomObject>
    <label>Grouped Revenue Schedule</label>
    <nameField>
        <displayFormat>GRS-{0000000000}</displayFormat>
        <label>Grouped Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grouped Revenue Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupedRevenueSchedule__c/fields/GroupedAccountProductRevenue__c.field-meta.xml
<CustomField>
    <fullName>GroupedAccountProductRevenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grouped Account Product Revenue</description>
    <inlineHelpText>Associated Revenue</inlineHelpText>
    <label>Grouped Account Product Revenue</label>
    <referenceTo>GroupedAccountProductRevenue__c</referenceTo>
    <relationshipName>Grouped_Account_Product_Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <inlineHelpText>This is the end date on the contract</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <inlineHelpText>This is the commencement date on the contract</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DoNotUseAccountHierarchy__c.field-meta.xml
<CustomField>
    <fullName>DoNotUseAccountHierarchy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to exclude the account records within the Account Hierarchy from the OPC calculation. Note any manually linked child accounts will still be included</description>
    <inlineHelpText>Check this field to exclude the account records within the Account Hierarchy from the OPC calculation. Note any manually linked child accounts will still be included</inlineHelpText>
    <label>Do not use account hierarchy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Annualised_Value__c.field-meta.xml
<CustomField>
    <fullName>Annualised_Value__c</fullName>
    <formula>If(AND(NOT(ISNULL( Contract_Start_Date__c )),NOT(ISNULL( Contract_End_Date__c))), IF(Contract_End_Date__c - Contract_Start_Date__c &lt; 367, TotalPrice, ( TotalPrice / Revenue_Duration__c ) * (CASE(MOD(Opportunity.Start_of_CFY__c - DATE(1985,6,24),7), 
0 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( Opportunity.End_of_CFY__c -Opportunity.Start_of_CFY__c )/7)*5))),0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annualised Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <inlineHelpText>Revenue end date should be the contract end date, or earlier if that is what is expected. The revenue end date should not be beyond the contract end date.</inlineHelpText>
    <label>Revenue End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <inlineHelpText>The ‘revenue start date’ is the date the customer is first invoiced for services provided to them. Please factor into the ‘start date’ any on-boarding and implementation time required for the product or service.</inlineHelpText>
    <label>Revenue Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductScheduleService_Test.cls
/**
 * @description test class fro the product schedule service
 * @author Ken McGuire
 * @date 2024-01-17
 * @changelog
*/
@isTest
public class ProductScheduleService_Test {
	@isTest 
	public static void testCreateRevenueSchedules() {
		// =====================================
		// Data Preparation
		// =====================================
		Date dateOfTest = Date.newInstance(2024, 4, 1);
		Account account = ApplicationTestDataFactory.getAccounts(1, true)[0];
		Account parentAcc = ApplicationTestDataFactory.getAccounts(1, true)[0];
		AccountRelationship__c accRelation = new AccountRelationship__c(ParentAccount__c = parentAcc.Id, RelatedAccount__c = account.Id, Relationship__c='OPC');

		Opportunity oppRec = ApplicationTestDataFactory.getOpportunities(1, account.Id, true)[0];
		oppRec.AccountId = account.Id;
		oppRec.DoNotUseAccountHierarchy__c = false;
		Product2 prod = ApplicationTestDataFactory.getProducts(1,true)[0];

		Budget_and_Revenue__c budgrev = ApplicationTestDataFactory.getBudgetAndRevenue(1,account.Id,prod.Id,dateOfTest.year(),true)[0];
		budgrev.uid__c = ProductRevenueService.getUID(budgrev);
		budgrev = (Budget_and_Revenue__c)ApplicationTestDataFactory.setUnwritableFields(budgrev, new Map<String, Object>{
		'UniqueId__c' => ProductRevenueService.getUID(budgrev)
		});
		Budget_and_Revenue__c budgrevp = ApplicationTestDataFactory.getBudgetAndRevenue(1,account.Id,prod.Id,dateOfTest.year()-1,true)[0];
		budgrevp.uid__c = ProductRevenueService.getUID(budgrevp);
		budgrevp = (Budget_and_Revenue__c)ApplicationTestDataFactory.setUnwritableFields(budgrevp, new Map<String, Object>{
		'UniqueId__c' => ProductRevenueService.getUID(budgrevp)
		});

		Id priceBookId = Test.getStandardPricebookId();
		PricebookEntry pbEntry = ApplicationTestDataFactorySales.getPriceBookEntries(1, priceBookId, prod.Id, true)[0];

		OpportunityLineItem oli1 = new OpportunityLineItem(OpportunityId = oppRec.Id,Quantity = 5,PricebookEntryId = pbEntry.Id,
		TotalPrice = 5 * pbEntry.UnitPrice,Contract_Start_Date__c = dateOfTest,Contract_End_Date__c = dateOfTest.addDays(3));
		oli1 = (OpportunityLineItem)ApplicationTestDataFactory.setUnwritableFields(oli1, new Map<String, Object>{
		'Annualised_Value__c' => 5000,
		'Product2Id' => prod.Id
		});
		oli1.Product2 = prod;
		oli1.Opportunity = oppRec;
		APR__c apr = new APR__c(Legal_Entity_Name_LookUp__c = account.Id,MHS_Confirmed_Rate__c=0.10);
		ProductRevenueService revenueServiceUnderTest = ProductRevenueService.newInstance();
		revenueServiceUnderTest.revenueCalculationContextDate = dateOfTest;

		GroupedAccountProductRevenue__c groupedRev2023 = new GroupedAccountProductRevenue__c( AnchorOrganisation__c = account.Id, PrimaryProduct__c = prod.Id,
		FinancialYear__c = 2023, UID__c = ProductRevenueService.getUID(account.Id,prod.Id,'2023'), Id = fflib_IDGenerator.generate(GroupedAccountProductRevenue__c.getSObjectType()),
		Rev1__c = 11,Rev2__c = 22,Rev3__c = 33,Rev4__c = 44,
		Rev5__c = 55,Rev6__c = 66,Rev7__c = 77,Rev8__c = 88,
		Rev9__c = 99,Rev10__c = 110,Rev11__c = 220,Rev12__c = 330);

		GroupedAccountProductRevenue__c groupedRev2024 = new GroupedAccountProductRevenue__c( AnchorOrganisation__c = account.Id, PrimaryProduct__c = prod.Id,
		FinancialYear__c = 2024, UID__c = ProductRevenueService.getUID(account.Id,prod.Id,'2024'), Id = fflib_IDGenerator.generate(GroupedAccountProductRevenue__c.getSObjectType()),
		Rev1__c = 440,Rev2__c = 550,Rev3__c = 660,Rev4__c = 770,
		Rev5__c = 880,Rev6__c = 990,Rev7__c = 1100,Rev8__c = 2200,
		Rev9__c = 3300,Rev10__c = 4400,Rev11__c = 5500,Rev12__c = 6600);

		// =====================================
		// Stubbing
		// =====================================
		GroupedRevenueScheduleSelector scheduleSelector = (GroupedRevenueScheduleSelector)MockUtility.mockSelector(GroupedRevenueScheduleSelector.class);
		GroupedAccountProductRevenueSelector revenueSelector = (GroupedAccountProductRevenueSelector)MockUtility.mockSelector(GroupedAccountProductRevenueSelector.class);
		OpportunityLineItemSelector lineItemSelector = (OpportunityLineItemSelector)MockUtility.mockSelector(OpportunityLineItemSelector.class);

		MockUtility.Mocks.startStubbing();
		MockUtility.Mocks.when(revenueSelector.selectByUniqueIds((Set<String>)fflib_Match.anyObject())).thenReturn(new Map<Id, GroupedAccountProductRevenue__c>{groupedRev2023.Id=>groupedRev2023,groupedRev2024.Id=>groupedRev2024});
		MockUtility.Mocks.when(scheduleSelector.selectByOpportunityProductIds((Set<String>)fflib_Match.anyObject(),(Set<Object>)fflib_Match.anyObject())).thenReturn(new List<GroupedRevenueSchedule__c>()); 
		MockUtility.Mocks.when(lineItemSelector.selectByOPCCalculationOpportunityIds((Set<Id>)fflib_Match.anyObject(), (Set<Object>)fflib_Match.anyObject())).thenReturn(new List<OpportunityLineItem>{oli1});
		MockUtility.Mocks.stopStubbing();
		ProductScheduleService scheduleServiceUnderTest = ProductScheduleService.newInstance();
		scheduleServiceUnderTest.productRevenueServiceInstance = revenueServiceUnderTest;

		Test.startTest();
		List<GroupedRevenueSchedule__c> revenueSchedules = scheduleServiceUnderTest.createUpdateRevenueSchedules(new Set<Id>{oppRec.id});
		System.assertEquals(1, revenueSchedules.size(), 'createUpdateRevenueSchedules did not generate correct number of schedules');
		Double totalSchedules = 0;
		for (GroupedRevenueSchedule__c schedule : revenueSchedules) {
			for (Integer month=1; month<=12; month++) {
				Double value = (Double)schedule.get('For'+String.valueOf(month)+'__c');
				totalSchedules = totalSchedules + value;
			}
		}
		System.assertEquals(88, Math.round(totalSchedules), 'total schedule did not add up to 88');
		Test.stopTest();
	}

	@isTest
	public static void testRevenueScheduleCalculator() {
		Date contractStart = Date.newInstance(2023, 3, 15);
		Date contractEnd = Date.newInstance(2024,1,15);

		ProductScheduleService.RevenueScheduleCalculator calculator = new ProductScheduleService.RevenueScheduleCalculator(contractStart,contractEnd, ProductScheduleService.newInstance().defaultRevenueAllocation );

		Boolean insideTestAtStart = calculator.isYearMonthInRange(2023, 3);
		Boolean insideTestAtEnd = calculator.isYearMonthInRange(2024, 1);
		Boolean insideTestMiddle = calculator.isYearMonthInRange(2023, 6);
		Boolean outsideBefore = calculator.isYearMonthInRange(2023, 2);
		Boolean outsideAfter = calculator.isYearMonthInRange(2024, 2);
		System.assertEquals(insideTestAtStart,true);
		System.assertEquals(insideTestAtEnd,true);
		System.assertEquals(insideTestMiddle,true);
		System.assertEquals(outsideBefore,false);
		System.assertEquals(outsideAfter,false);
	}

}