force-app/main/default/objects/BillingAccountCreationEvent__e/BillingAccountCreationEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event for Billing Account Creation , these events are generated by Camunda</description>
    <label>Billing Account Creation</label>
    <pluralLabel>Billing Account Creation</pluralLabel>
</CustomObject>

force-app/main/default/objects/BillingAccountCreationEvent__e/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>Additional Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingAccountCreationEvent__e/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BillingAccountCreationEventHandler_Test.cls
/***
 * @description Test class for BillingAccountCreationEventHandler
 * @author Ranjeewa Silva
 * @date 2023-11-27
 * @changelog
 * 2023-11-07 - Ranjeewa Silva - created
 */
@IsTest
private class BillingAccountCreationEventHandler_Test {

	/**
	 * This class does not do much so we just need a single test for coverage
	 */
	@IsTest
	private static void testForCoverage() {

		BillingAccountCreationEventHandler handler = new BillingAccountCreationEventHandler();

		handler.registerModules();

		System.assert(BillingAccountCreationEvent__e.SObjectType == handler.getSObjectType());
		System.assert(handler.newUnitOfWork() != null, 'Expected a valid unit of work instance, but got null');

		List<BillingAccountCreationEvent__e> events = new List<BillingAccountCreationEvent__e>();
		events.add(new BillingAccountCreationEvent__e(Source_System__c='SAP', Additional_Info__c=APT_Constants.RATING_PLAN_ACTIVATION_LABEL));
		events.add(new BillingAccountCreationEvent__e(Source_System__c='SAP'));
		events.add(new BillingAccountCreationEvent__e(Source_System__c='TEAM'));

		Map<String, List<SObject>> filteredGroupRecords = handler.primeRecordFilters(events);
		Assert.areEqual(3, filteredGroupRecords.size(), 'Expected the event records to be filtered into 3 groups, SAP rating plans, SAP billing accounts and TEAM billing accounts');

		Assert.areEqual(1, filteredGroupRecords.get('filterNewAusPostRatingPlans').size());
		Assert.areEqual(events[0].Id, filteredGroupRecords.get('filterNewAusPostRatingPlans')[0].Id);

		Assert.areEqual(1, filteredGroupRecords.get('filterNewAusPostBillingAccounts').size());
		Assert.areEqual(events[1].Id, filteredGroupRecords.get('filterNewAusPostBillingAccounts')[0].Id);

		Assert.areEqual(1, filteredGroupRecords.get('filterNewStarTrackBillingAccounts').size());
		Assert.areEqual(events[2].Id, filteredGroupRecords.get('filterNewStarTrackBillingAccounts')[0].Id);
	}
}