force-app/main/default/objects/At_Risk_Business__c/At_Risk_Business__c.object-meta.xml
<CustomObject>
    <label>At Risk Business</label>
    <nameField>
        <displayFormat>BAR-{0000}</displayFormat>
        <label>At Risk Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>At Risk Business</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/At_Risk_Business__c/fields/Date_of_Revenue_Calculation__c.field-meta.xml
<CustomField>
	<fullName>Date_of_Revenue_Calculation__c</fullName>
	<inlineHelpText>Revenue calculations may become inconsistent when BaR records span multiple months</inlineHelpText>
	<descrition>Date when revenue was automatically calculated.</descrition>
	<label>Date of Revenue Calculation</label>
	<type>Date</type>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Look up on the &quot;Organisation&quot; record. Will auto populate if created from the Organisation record</description>
    <inlineHelpText>The customer to who the Risk/Lost Business is linked to.</inlineHelpText>
    <label>Legal Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>At Risk Business</relationshipLabel>
    <relationshipName>Business_At_Risks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Products__c.field-meta.xml
<CustomField>
	<fullName>Products__c</fullName>
	<label>Products</label>
	<type>MultiselectPicklist</type>
	<description>Selected products for revenue at risk</description>
	<inlineHelpText>Selected products for revenue at risk</inlineHelpText>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>placeholder</fullName>
				<label>(placeholder)</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Products_IDs__c.field-meta.xml
<CustomField>
    <fullName>Products_IDs__c</fullName>
    <description>IDs for selected products</description>
    <inlineHelpText>IDs for selected products</inlineHelpText>
    <label>Products IDs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Recalculate_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If ticked, will force a recalculation of annual revenue at risk, even if product selection has not changed.</description>
    <inlineHelpText>If ticked, will force a recalculation of annual revenue at risk, even if product selection has not changed.</inlineHelpText>
    <label>Recalculate Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Scale__c.field-meta.xml
<CustomField>
    <fullName>Scale__c</fullName>
    <description>Identify the scale of the risk/lost business.</description>
    <inlineHelpText>Identify the scale of the risk/lost business.</inlineHelpText>
    <label>Scale</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product Specific (Please Specify)</fullName>
            </value>
            <value>
                <fullName>Whole of Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/At_Risk_Business__c/fields/Value_of_Business_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>Value_of_Business_at_Risk__c</fullName>
    <description>Currency Field - User Input</description>
    <inlineHelpText>Enter estimated value. This will be system calculated after saving when you select specific product(s) or whole of business.</inlineHelpText>
    <label>Annual Value of Business at Risk</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/Budget_and_Revenue__c.object-meta.xml
<CustomObject>
    <description>Phase 2 - Object that contains Budget and Billed Revenue data. Previous name was &quot;Target and Revenue&quot; (MW0003520).</description>
    <label>Customer Revenue</label>
    <nameField>
        <label>Customer Revenue ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Revenue</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <inlineHelpText>Current Financial Year</inlineHelpText>
    <label>Financial Year</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <inlineHelpText>Name of Customer</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Budget_and_Revenue_2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_and_Revenue__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product (Level 5)</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Budget_and_Revenue_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AtRiskBusinessRevenueModule.cls
/**
 * @description Domain Module to handle At_Risk_Business__c object functionality
 * Domain Modules should NEVER be called directly. Domain modules should be exposed and called via the corresponding TriggerHandler class
 * @author Pratyush Chalasani
 * @group Domain
 * @domain AtRiskBusiness
 * @changelog
 * 2023-04-21 - Pratyush Chalasani - Created
 *
 */
public inherited sharing class AtRiskBusinessRevenueModule extends ApplicationModule {
	@testVisible
	private static Date calculationDate = System.today();
	
	public static AtRiskBusinessRevenueModule newInstance() {
		return (AtRiskBusinessRevenueModule) Application.Utilities.newInstance(AtRiskBusinessRevenueModule.class);
	}

	// Setup which trigger events this module should respond to
	public AtRiskBusinessRevenueModule() {
		getTriggerEvents().enableBeforeUpdate();
	}

	public override void onBeforeUpdate(List<SObject> records, Map<Id, SObject> existingRecords, ApplicationUnitOfWork uow) {
		calculateRevenueAtRisk((List<At_Risk_Business__c>) records, (Map<Id, At_Risk_Business__c>) existingRecords);
	}
	
	private void calculateRevenueAtRisk(List<At_Risk_Business__c> records, Map<Id, At_Risk_Business__c> existingRecords){
		Map<String, List<String>> financialYearMonths = AtRiskBusinessUtility.getFinancialYearsAndMonths(calculationDate);

		List<At_Risk_Business__c> filteredRecords = new List<At_Risk_Business__c>();

		Set<Id> organisationIDs = new Set<Id>();

		Map<Id, List<String>> revenueProductMap = new Map<Id, List<String>>();

		// Filter records which have changed Scale or Product ID fields,
		// and collect account IDs
		for (At_Risk_Business__c arb: records) {
			At_Risk_Business__c oldARB = existingRecords.get(arb.Id);

			if ((arb.Scale__c != oldARB.Scale__c) || (arb.Products_IDs__c != oldARB.Products_IDs__c) || (arb.Recalculate_Revenue__c == true)) {
				// Reset recalculation flag
				arb.Recalculate_Revenue__c = false;

				if (arb.Scale__c == 'Whole of Business') {
					arb.Products_IDs__c = null;
					arb.Products__c = null;
				}

				if (String.isNotBlank(arb.Products_IDs__c)) {
					revenueProductMap.put(arb.Id, arb.Products_IDs__c.split(';'));
				}
				
				organisationIDs.add(arb.Legal_Entity_Name__c);

				filteredRecords.add(arb);
			}
		}

		if (!filteredRecords.isEmpty()) {
			List<Budget_and_Revenue__c> revenueList = BudgetAndRevenueSelector.newInstance().selectByOrganisationId(organisationIDs, financialYearMonths.keySet());

			Map<Id, List<Budget_and_Revenue__c>> orgRevenueMap = new Map<Id, List<Budget_and_Revenue__c>>();

			for (Budget_and_Revenue__c revenue: revenueList) {
				List<Budget_and_Revenue__c> orgRevenues = orgRevenueMap.get(revenue.Organisation__c);

				if (orgRevenues == null || orgRevenues.isEmpty()) {
					orgRevenues = new List<Budget_and_Revenue__c>();

					orgRevenueMap.put(revenue.Organisation__c, orgRevenues);
				}

				orgRevenues.add(revenue);
			}

			// Here is where we calculate the total revenue in the 12 months to date for each ARB record
			for (At_Risk_Business__c arb: records) {
				// Revenue total for each financial year record
				Map<String, Decimal> fyRevenue = new Map<String, Decimal>();

				// first set everything to zero
				for (String fy: financialYearMonths.keySet()) {
					fyRevenue.put(fy, 0);
				}

				// Get the revenue records for the linked account
				List<Budget_and_Revenue__c> revenues = orgRevenueMap.get(arb.Legal_Entity_Name__c);

				// Get the list of products selected for this ARB record
				List<Id> productIDs = revenueProductMap.get(arb.Id);

				Decimal totalRevenue = 0;
				
				if (revenues != null) {
					for (Budget_and_Revenue__c rev: revenues) {
						if ((arb.Scale__c == 'Whole of Business') || (productIDs != null && productIDs.contains(String.valueOf(rev.Product__c)))) {
							Decimal revenue = fyRevenue.get(rev.Financial_Year__c);
				
							List<String> months = financialYearMonths.get(rev.Financial_Year__c);
				
							for (String m: months) {
								Decimal r = (Decimal)(rev.get(m + '_Revenue_Amount__c'));
				
								if (r != null) {
									revenue += r;
								}
							}
				
							fyRevenue.put(rev.Financial_Year__c, revenue);
						}
					}

					for (String year: fyRevenue.keySet()) {
						totalRevenue += fyRevenue.get(year);
					}
				}

				arb.Date_of_Revenue_Calculation__c = calculationDate;
				arb.Value_of_Business_at_Risk__c = totalRevenue;
			}
		}
	}
}