force-app/main/default/objects/APT_Post_Code_Mapping__c/APT_Post_Code_Mapping__c.object-meta.xml
<CustomObject>
    <description>Master data to store postcode, suburb, zones and tier zone for startrack</description>
    <label>Post Code Mapping</label>
    <nameField>
        <label>Post Code Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Post Code Mapping</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_Direct_Zone__c.field-meta.xml
<CustomField>
    <fullName>APT_Direct_Zone__c</fullName>
    <label>Direct Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_EXP_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_EXP_Zone_Type__c</fullName>
    <label>EXP Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_NXF_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_NXF_Zone_Type__c</fullName>
    <label>NXF Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_Onforwarding_Alternate_Zone__c.field-meta.xml
<CustomField>
    <fullName>APT_Onforwarding_Alternate_Zone__c</fullName>
    <label>Onforwarding Alternate Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_Onforwarding_Zone__c.field-meta.xml
<CustomField>
    <fullName>APT_Onforwarding_Zone__c</fullName>
    <label>Onforwarding Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_PRM_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_PRM_Zone_Type__c</fullName>
    <label>PRM Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_RE2_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_RE2_Zone_Type__c</fullName>
    <label>RE2 Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_RET_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_RET_Zone_Type__c</fullName>
    <label>RET Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_SE2_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_SE2_Zone_Type__c</fullName>
    <label>SE2 Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APT_Post_Code_Mapping__c/fields/APT_SE3_Zone_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_SE3_Zone_Type__c</fullName>
    <label>SE3 Zone Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/Apttus_Config2__PriceListItem__c.object-meta.xml
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/APT_Price_Structure__c.field-meta.xml
<CustomField>
    <fullName>APT_Price_Structure__c</fullName>
    <label>Price Structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WINE {Z20}</fullName>
            </value>
            <value>
                <fullName>WINE {Z30}</fullName>
            </value>
            <value>
                <fullName>BANDED {Z30}</fullName>
            </value>
            <value>
                <fullName>BANDED {Z40}</fullName>
            </value>
            <value>
                <fullName>BASE+PER_KG {Z20}</fullName>
            </value>
            <value>
                <fullName>BASE+PER_KG {Z30}</fullName>
            </value>
            <value>
                <fullName>BASE+PER_KG {Z40}</fullName>
            </value>
            <value>
                <fullName>BANDED SPECIAL EXPRESS {Z40}</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceListItem__c/fields/Apttus_Config2__ProductId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the product associated with the price list</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>PriceLists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceMatrix__c/Apttus_Config2__PriceMatrix__c.object-meta.xml
<CustomObject>
    <description>Represents a price matrix associated with a price list entry</description>
    <label>Price Matrix</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Matrix Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Matrices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceMatrix__c/fields/Apttus_Config2__PriceListItemId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PriceListItemId__c</fullName>
    <description>ID of the associated price list item</description>
    <label>Price List Item</label>
    <referenceTo>Apttus_Config2__PriceListItem__c</referenceTo>
    <relationshipLabel>Matrix Pricing</relationshipLabel>
    <relationshipName>PriceMatrices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apttus_Config2__PriceMatrixEntry__c/Apttus_Config2__PriceMatrixEntry__c.object-meta.xml
<CustomObject>
    <description>Represents a single entry in a price matrix</description>
    <label>Price Matrix Entry</label>
    <nameField>
        <displayFormat>ME-{0000000000}</displayFormat>
        <label>Matrix Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Matrix Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apttus_Config2__PriceMatrixEntry__c/fields/Apttus_Config2__PriceMatrixId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PriceMatrixId__c</fullName>
    <description>ID of the associated matrix</description>
    <label>Price Matrix</label>
    <referenceTo>Apttus_Config2__PriceMatrix__c</referenceTo>
    <relationshipLabel>Entries</relationshipLabel>
    <relationshipName>MatrixEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/APT_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_Type__c</fullName>
    <description>Created for Ariba mapping purposes. Reused for future records with Sellers input</description>
    <inlineHelpText>Ariba migrated field</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mail, Letters or Parcel</fullName>
            </value>
            <value>
                <fullName>Agency Services</fullName>
            </value>
            <value>
                <fullName>APMS</fullName>
            </value>
            <value>
                <fullName>PostConnect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Domestic_Pricing__c.field-meta.xml
<CustomField>
    <fullName>APT_Domestic_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if true then product pricing will be handled using domestic pricing batch</description>
    <inlineHelpText>if true then product pricing will be handled using domestic pricing batch</inlineHelpText>
    <label>Domestic Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_International_Pricing__c.field-meta.xml
<CustomField>
    <fullName>APT_International_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Calculate International Pricing using Batch</description>
    <inlineHelpText>if true then product pricing will be handled using international pricing batch</inlineHelpText>
    <label>International Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/APT_Product_type__c.field-meta.xml
<CustomField>
    <fullName>APT_Product_type__c</fullName>
    <label>Product type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>eParcels Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>UMS</fullName>
            </value>
            <value>
                <fullName>Post Billpay</fullName>
            </value>
            <value>
                <fullName>Print Post</fullName>
            </value>
            <value>
                <fullName>Community Update</fullName>
            </value>
            <value>
                <fullName>Securepay</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
            <value>
                <fullName>Legacy Products</fullName>
            </value>
            <value>
                <fullName>StarTrack</fullName>
            </value>
            <value>
                <fullName>On Demand</fullName>
            </value>
            <value>
                <fullName>Decipha</fullName>
            </value>
            <value>
                <fullName>Workforce Verification</fullName>
            </value>
            <value>
                <fullName>Priority Product</fullName>
            </value>
            <value>
                <fullName>Local Pickup and Delivery Services</fullName>
            </value>
            <value>
                <fullName>Track Mail</fullName>
            </value>
            <value>
                <fullName>Parcel Contract</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Feature</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Surcharge</fullName>
            </value>
            <value>
                <fullName>Parcel Contract-Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APT_DeleteExistingPMEBatch.cls
/***
 * @author Mahesh Patel
 * @date 2021-05-01
 * @group 
 * @description Apex batch class which deletes all the existing PME's associated with product type for which the job is triggered for.
 * Subsequent batches are chained to this batch job and varies between ST and other product types.
 * @changelog
 * 2021-05-01 - Mahesh Patel - Created
 * 2021-09-14 - Mathew Jose - Updated to incorporate chages require for Parcel Contract products.
*/
global class APT_DeleteExistingPMEBatch implements Database.Batchable<sObject>, Database.Stateful 
{    
    global set<String> setErrorMessage {get;set;} 
    global List<APT_Post_Code_Mapping__c> listPostCodeMapping;
    global String productType {get;set;} 
    global String priceStructure {get;set;}  
    public static final String CLASSNAME = 'APT_DeleteExistingPMEBatch';
    public static final String ORGID = UserInfo.getOrganizationId();     
    /**
        Constructor
    **/    
    global APT_DeleteExistingPMEBatch(String productType, String priceStructure) 
    {
        setErrorMessage = new set<String>();
        this.productType = productType;
        this.priceStructure = priceStructure;
    }

    /**
        Start Method
    **/        
    global Database.QueryLocator start(Database.BatchableContext bc) 
    {        
        String stProductType = APT_Constants.PRODUCTTYPE_STARTRACK;
        String parSimProductType = 'Parcel Contract';
        list<string> parSimFSRProductTypeList= new list<string>{'Parcel Contract-Feature','Parcel Contract-Surcharge','Parcel Contract-Return'};
        String queryStr = 'SELECT Id FROM Apttus_Config2__PriceListItem__c WHERE';
        if(productType == 'Domestic_Non_Startrack')
        {
            queryStr += ' Apttus_Config2__ProductId__r.APT_Domestic_Pricing__c = true AND Apttus_Config2__ProductId__r.APT_Product_type__c !=: stProductType AND Apttus_Config2__ProductId__r.APT_Product_type__c !=: parSimProductType';
            if(!String.isBlank(priceStructure)){
                queryStr += ' AND APT_Price_Structure__c =: priceStructure';
            }
        }
        else if(productType == 'Startrack')
        {
            queryStr += ' Apttus_Config2__ProductId__r.APT_Domestic_Pricing__c = true AND Apttus_Config2__ProductId__r.APT_Product_type__c =: stProductType';
        }
        else if(productType == 'International')
        {
            queryStr += ' Apttus_Config2__ProductId__r.APT_International_Pricing__c = true';
        }        
        else if(productType == 'Domestic_Simplified_Parcel_Contract')
        {
            queryStr += ' Apttus_Config2__ProductId__r.APT_Domestic_Pricing__c = true AND Apttus_Config2__ProductId__r.APT_Product_type__c =: parSimProductType';
            if(!String.isBlank(priceStructure)){
                queryStr += ' AND APT_Price_Structure__c =: priceStructure';
            }    
        }
        else if(productType == 'Domestic_Simplified_Features_Surcharges'){
            queryStr += ' Apttus_Config2__ProductId__r.APT_Product_type__c IN : parSimFSRProductTypeList';
        }    
        return Database.getQueryLocator(queryStr);
    }
    /**
        Execute Method
    **/        
    global void execute(Database.BatchableContext bc, list<Apttus_Config2__PriceListItem__c> listPriceListItem)
    {
        try 
        { 
            //delete price matrix entry
            Set<Id> setPriceListItemId = new Set<Id>();
            for(Apttus_Config2__PriceListItem__c priceListItem : listPriceListItem) 
            {
                setPriceListItemId.add(priceListItem.Id);
            }
            
            Set<Id> setPriceMatrixId = new Set<Id>();
            for(Apttus_Config2__PriceMatrix__c priceMatrix : [SELECT Id FROM Apttus_Config2__PriceMatrix__c WHERE Apttus_Config2__PriceListItemId__c IN :setPriceListItemId]) 
            {
                setPriceMatrixId.add(priceMatrix.Id);
            }
            
            List<Apttus_Config2__PriceMatrixEntry__c> listPriceMatrixEntry = [SELECT Id FROM Apttus_Config2__PriceMatrixEntry__c WHERE Apttus_Config2__PriceMatrixId__c IN :setPriceMatrixId];
            if(listPriceMatrixEntry != null && listPriceMatrixEntry.size() > 0) 
            {
                delete listPriceMatrixEntry;
            }
            
        } 
        catch(System.Exception ex) 
        {
            setErrorMessage.add(ex.getMessage() + ex.getStackTraceString());             
            system.debug('APT_DeleteExistingPMEBatch Exception: ' + ex.getMessage() + ex.getStackTraceString().substringBefore('\n'));
            UTIL_LoggingService.logHandledException(ex, ORGID, 'Apttus Pricing Batch Job', CLASSNAME, 'execute', null, LoggingLevel.ERROR);

        }
    }

    /**
        Finish Method
    **/    
    global void finish(Database.BatchableContext bc) 
    {
        //Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob asyncApexJob = [SELECT Id, Status, NumberOfErrors, TotalJobItems, CreatedBy.Email, ExtendedStatus  
                                    FROM AsyncApexJob 
                                    WHERE Id = :bc.getJobId()];

        system.debug('No. of errors: ' + asyncApexJob.NumberOfErrors);
                        
        if(asyncApexJob.NumberOfErrors > 0) 
        {
            setErrorMessage.add(asyncApexJob.ExtendedStatus);
        }
        
        if(setErrorMessage.size() > 0) 
        {
            APT_PricingBatchUtility.sendEmailNotification('DeleteExistingPMEBatch', asyncApexJob, setErrorMessage, null);
        } 
        else 
        {
            if(productType == 'Startrack')
            {
                //Get Post Code Mapping
                List<APT_Post_Code_Mapping__c> listPostCodeMapping = [SELECT Id, APT_Direct_Zone__c, APT_Onforwarding_Zone__c, APT_Onforwarding_Alternate_Zone__c,
                                                                        APT_EXP_Zone_Type__c, APT_PRM_Zone_Type__c, APT_NXF_Zone_Type__c, APT_SE2_Zone_Type__c, 
                                                                        APT_SE3_Zone_Type__c, APT_RET_Zone_Type__c, APT_RE2_Zone_Type__c 
                                                                        FROM APT_Post_Code_Mapping__c];

                //Determine Zone Type for ST Products
                APT_DetermineZoneTypesBatch determineZoneTypesBatch = new APT_DetermineZoneTypesBatch(listPostCodeMapping, productType);
                if(!Test.isRunningTest()){
                    database.executeBatch(determineZoneTypesBatch, 1);
                }
            }
            else
            {
                //call price list item and price matrix batch
                APT_PricingDataBatch createPLIBatch = new APT_PricingDataBatch(productType, priceStructure);
                if(!Test.isRunningTest()){
                    database.executeBatch(createPLIBatch, 1);
                } 
            }
            
        }
    }
}