force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Queue Management Settings for SSSW</description>
    <label>SSSW Queue Management</label>
</CustomObject>

force-app/main/default/objects/QM__c/fields/UnifiedDefaultMonitoringQueueId__c.field-meta.xml
<CustomField>
	<fullName>UnifiedDefaultMonitoringQueueId__c</fullName>
	<description>The ID of an Omni queue for Unified Cases. This is a holding queue used for Proactive Monitoring and related automations.</description>
	<inlineHelpText>The ID of an Omni queue for Unified Cases. This is a holding queue used for Proactive Monitoring and related automations.</inlineHelpText>
	<label>Unified Default Monitoring Queue Id</label>
	<length>18</length>
	<type>Text</type>
</CustomField>

force-app/main/default/classes/UnifiedPushToMonitoringQueueController.cls
/**
 * @description Controller Class for unifiedPushToMonitoringQueue LWC.
 *			This LWC is a Modal Popup on Quick Action that will push the Case to Unified Customer Service Monitoring Queue.
 * @author Seth Heang
 * @date 2024-07-10
@changelog
2024-07-10 - Seth Heang - Created
 */
public with sharing class UnifiedPushToMonitoringQueueController {

	/**
	 * @description Fetch unified customer service monitoring queue Id from custom setting
	 * @return Id
	 */
	@AuraEnabled(Cacheable=true)
	public static Id getUnifiedCustomerServiceMonitoringQueueId() {
		return QM__c.getInstance()?.UnifiedDefaultMonitoringQueueId__c;
	}
}