force-app/main/default/objects/ExternalURL__c/ExternalURL__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SSSW - External URLs used in apex/ VF code are managed in here.</description>
    <label>ExternalURL</label>
</CustomObject>

force-app/main/default/objects/ExternalURL__c/fields/myURL__c.field-meta.xml
<CustomField>
    <fullName>myURL__c</fullName>
    <label>myURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAQ__kav/FAQ__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>FAQPreview</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>SSSW - FAQ Articles.</description>
    <label>FAQ</label>
    <pluralLabel>FAQs</pluralLabel>
</CustomObject>

force-app/main/default/objects/FAQ__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/internalArticlePreview_Test.cls
/**
*  This test class is for CaseUtility.
*
@author Yuanyuan Zhang
@created 2014-07-16
@version 1.0
@since 30.0
*
@changelog
* 2014-07-16 Yuanyuan Zhang <yuanyuan.zhang@bluewolf.com>
* - Created
* - Test coverage  100%
* 2021-08-11 - Seth Heang - Uplift API version to 52
*/
@isTest
private class internalArticlePreview_Test {
    
    static testmethod void test1 () {
        test.startTest();
        
        
        FAQ__kav fk = new FAQ__kav();
        fk.Answer__c = 'testxxx';
        //fk.PublishStatus = 'Draft';
        fk.Title = 'testxxx';
        fk.UrlName = 'testxx';
        insert fk;
        
        try {
            ApexPages.StandardController stdCtl = new ApexPages.StandardController(fk);   
            internalArticlePreview ext = new internalArticlePreview(stdCtl);
            ext.previewRedirect();
        } catch (Exception e) {
            ExternalURL__c ex = new ExternalURL__c(Name = 'ArticlePreview', myURL__c = 'https://test.my.url.com');
            insert ex;
            ApexPages.StandardController stdCtl = new ApexPages.StandardController(fk);   
            internalArticlePreview ext = new internalArticlePreview(stdCtl);
            ext.previewRedirect();
        }
        test.stopTest();
    }
}